### ISSUE TITLE
Why does stateWhileRevalidate make two network calls?

### ISSUE THREAD

**Issue by iKarthik** [GoogleChrome/workbox#1040]
Am using workbox-sw to help me cache my API responses. Below is an excerpt of my code. When I make the service worker intercepts my first call to /myapiendpoint/1/details, it goes to the network to get the response. On a subsequent call to the same endpoint, service-worker retrieves the response and cache and serves it to the app. I also expect it to make a request to the network to update the cache, if it is stale. But it ends up making two requests. Can anyone explain why?

```
const workboxSW = new self.WorkboxSW();
workboxSW.precache(fileManifest);

workboxSW.router.registerRoute('/myapiendpoint/:userid/details', workboxSW.strategies.staleWhileRevalidate({
"cacheName" : "User-Details",
"cacheExpiration" : { "maxEntries" : 10 }
}), 'GET');

```

**Comment by jeffposnick** [comment]
How are you determining that it makes two requests? If you're looking at the Network panel in Chrome's DevTools, you should know that there are going to be two entries (one with a "gear" icon and one without) displayed there, even though there is only one network request made.

(see https://stackoverflow.com/questions/33590378/status-code200-ok-from-serviceworker-in-chrome-network-devtools/33655173#33655173)

**Comment by iKarthik** [comment]
In Chrome Dev Tools I see two requests with the gear icon and one without. I assumed the ones with gear icons are the network requests. (I have attached a pic)

![service-workers-call](https://user-images.githubusercontent.com/3451786/32739960-069879ce-c867-11e7-80bb-18a9ad223b37.png)

(I should also note that am working locally on my sandbox, not sure if this has anything to do with multiple requests)

**Comment by jeffposnick** [comment]
The ones with the "gear" icons represent `fetch()`s that were made from inside your service worker. I'm puzzled by why there would be two, rather than one, `fetch()`s made from the service worker, given the configuration and usage you describe.

Is there any way that you could temporarily host your project somewhere publicly accessible, or put a simplified reproduction somewhere accessible? I have not seen this particular behavior before—for instance, if you visit [this page](https://ifixit-pwa.appspot.com/guide/98093) in a sample application multiple times, you'll see requests made for `https://www.ifixit.com/api/2.0/guides/98093` handled by a similar stale-while-revalidate policy, but there is no "phantom" extra request made from the service worker in this case.

**Comment by gauntface** [comment]
This is different in v3 which only shows two entries.

![screenshot from 2017-11-22 09-25-18](https://user-images.githubusercontent.com/139760/33141144-17bb9e0a-cf67-11e7-864c-c188a9092f74.png)

**Comment by gauntface** [comment]
@iKarthik please reopen if you can provide a demo page or more info.
