### ISSUE TITLE
Workbox CLI has an Awkward Start

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1052]
Using the Workbox CLI there are two big wrinkles:

1. The workbox config **must** be defined in the workbox commands even thought it's using the default file in the default location
1. You can't inject a manifest with the provided config. It would be good to ask this during the configuration rather than leave the developer go in and manually edit the config.json

**Comment by jeffposnick** [comment]
> The workbox config must be defined in the workbox commands even thought it's using the default file in the default location

I did that intentionally—if there's sentiment in favor of going in the other direction and inferring a default config file name, I could add it in, but my preference is to keep it explicit.

> You can't inject a manifest with the provided config. It would be good to ask this during the configuration rather than leave the developer go in and manually edit the config.json

By "provided config" do you mean the output of `wizard`?

If so, that's also intentional—I wanted `wizard` to focus on getting beginners up and running, and doing it by creating a config file that works with `generateSW` made the most sense. In order to get the `wizard` to produce a config file that works with `injectManifest` we'd need to assume that there's already a base service worker file somewhere on disk with most of the code already written, and my gut is that developers who have gotten that far don't need the `wizard` experience.

Again, I can be overridden here if folks disagree, but that was my thinking.

**Comment by gauntface** [comment]
Regarding the default config, I personally think it would be good to use a default - every CLI I've used that makes use of a config file has always had a default file that it uses if nothing is defined, its surprisingly jarring having to type it in (albeit a small problem).

Regarding the wizard and inject manifest, the reason I raised this issue is that I hit it when writing the "getting started" to "precache files" guides. The getting started guide (whether we keep it or not) has a nice story of "add the CDN file and now you can use workbox and write some routing logic", then next step is to then inject a precache manifest. The CLI then has the two wrinkles above that require explaining to the user.

Could we add a flag to the wizard that would ask for the service worker source file and add it to the config? Something like `workbox wizard --injectManifest` ?

**Comment by jeffposnick** [comment]
I filed https://github.com/GoogleChrome/workbox/issues/1078 to track using a default config file location when none is specified.

I'd like to think more about what `workbox wizard --injectManifest` would mean, and whether that's something we should support, though. In my mind, v3's `workbox wizard` was something you do once, to get started with a basic config that could be passed in to `generateSW` or edited by hand to add in functionality that would be overwhelming to expose in the wizard.

In the use case you describe, for that getting stared guide, you'd do `workbox wizard` and then edit the  newly created `workbox-config.js` to add in `swSrc` (and runtime caching, and anything else that folks might end up needing to configure).

**Comment by gauntface** [comment]
In the getting started flow - it's I have a service worker and it took no time, now I want to add precaching, the CLI is arguably the fastest path to that but manually editing the config after generation just smells slightly.

The flag or a question would be helpful. The nice thing with the flag is that it keeps the default flow very focused and fast.

Question could be, "Do you want Workbox to generate your service worker for you?" (Default to yes), if no, ask where the service worker file is.

**Comment by DavidScales** [comment]
I've recently started looking into updating Codelabs and some other training materials with v3, and have to say that I'm facing the same issue as @gauntface - I think it's awkward to generate a file & then modify it. 

I understand @jeffposnick thought process of streamlining the wizard for the beginner dev use case, but I think that the wizard flow could support either case without too much impact/confusion for devs. 

Some potential considerations:

1. If you go the flag route, you could just specify the path directly and forgo an additional prompt, e.g., `workbox wizard --src PATH/TO/SRC/SW` is clear to non-workbox-beginners that you are initializing a config file with a source service worker specified. 

2. You could potentially simply have a final prompt, like @gauntface suggests. The answer would determine if a file path is requested for `srcSW`. I think "Do you want Workbox to generate your service worker for you?" might not necessarily be ideal, because Workbox is generating the service worker regardless of whether or not there is a source file, but I don't know what the clearest wording would be. In any case, I'm not sure this option would even need a flag - it could be a default prompt if it was clear enough.

**Comment by nasearle** [comment]
I'm in the same boat and would appreciate being able to inject a manifest from the command line without having to edit the config.

If you do end up making this change, I'd like to throw in a vote for using a flag instead of a prompt.
1. It's unambiguous. In order to inject a manifest, developers have to already know that's what they want. That way there's no confusion.
2. If developers already know they want to inject a manifest, they can start from there so they don't have to answer an extra prompt. Also with David's suggestion of being able to specify the path to the source sw in the initial command, a flag becomes super convenient.

But if it does end up being a prompt, to respond to David's concern of clarity, maybe simply calling it a **new** service worker would be clear enough. So the wording could be something like "Do you want Workbox to generate a new service worker for you?"

**Comment by jeffposnick** [comment]
Given popular demand, I can add in support for

```sh
workbox wizard --swSrc PATH/TO/SRC/SW`
```

(I'd like to use `--swSrc|sw-src` as the flag name to reflect that that's also the config name.)

One other thing that I'd like to do with that approach is to validate the file that you pass in to ensure that it contains a match for the default `injectionPointRegExp` value, and refuse the start the wizard otherwise:

https://github.com/GoogleChrome/workbox/blob/36e99bd5f99b2ed869421715ebd735a67a20ee5c/packages/workbox-build/src/entry-points/options/defaults.js#L27

Does that sound good?

**Comment by DavidScales** [comment]
ah yeah that makes more sense as a flag name

that seems like a good idea to me 👍  that way devs can catch it during set up

**Comment by DavidScales** [comment]
Related question

Currently, completing `workbox wizard` produces this log:

> To build your service worker, run
> 
>   workbox generateSW workbox-config.js
> 
> as part of a build process. See https://goo.gl/fdTQBf for details.
> You can further customize your service worker by making changes to workbox-config.js. See https://goo.gl/YYPcyY for details.

Would it be possible also to modify this log if the user supplies the `swSrc` flag? Since the suggested `workbox generateSW workbox-config.js` command make less sense in this context. Perhaps the log could be changed to `workbox injectManifest workbox-config.js`?

**Comment by gauntface** [comment]
+1 from me. Feels like a simple enough tweak.
