### ISSUE TITLE
registerRoute() options object instead of method type string

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1070]
This was a comment raised by @surma during workbox-routing review.

Instead of:
```js
workbox.routing.registerRoute(match, handler, 'POST');
```

We should use an options object:
```js
workbox.routing.registerRoute(match, handler, {method: 'POST'});
```

This would actually make the API flexible in the future and would match the fetch API, so I'm in favor of this.

@jeffposnick @philipwalton @addyosmani for thoughts.

**Comment by jeffposnick** [comment]
I'm mostly indifferent here—it's not common to use Workbox with non-`GET` methods, and being able to override using that optional string value was effectively an afterthought. If folks like `{method: 'POST'}` better, that's cool.

Though I am curious about scenarios in which we'd ever want to support additional options—regarding matching the Fetch API, I don't see anything obvious in the [`RequestInit` dictionary](https://fetch.spec.whatwg.org/#requestinit) other than `method` that seem like they'd be a good fit for adding in later. If we were to start supporting, e.g., filtering on the `headers` fields via something like

```js
workbox.routing.registerRoute(match, handler, {
  method: 'POST',
  headers: {
    'x-something': 'true',
  }
});
```

then you run into questions of whether that logic makes more sense inside of the `match` callback.

**Comment by surma** [comment]
> Though I am curious about scenarios in which we'd ever want to support additional options

Well that’s the thing, isn’t it? We do not know yet what we might want to add as an option. Once we *do* know, the options dictionary will allow us to do so. At the very least it feels more descriptive to me.

**Comment by gauntface** [comment]
This has come up a few times in various forms:

1. routing.get(match, handler) and routing.post(match, handler) and routing.all()
1. routing.registerRoute(match, handler) <- enabling match to handle and support multiple types
1. routing.registerRoute(match, handler, {method: '...'})

I'm starting to think that the first option provides the most flexibility while being the least likely to provide a footgun. Pretty much all our demo's would be for get requests and for the analytics use case, `all()` would allow for the analytics case where both GET and POST was provided.

The problem with option two is that it'll be hard to make a safe default API for developers. For example `routing.registerRoute(new RegExp(....), handler)` We can default that to GET but how does a developer handle a POST request?

The third and fourth option is where we are today and it just feels awkward. I agree with both @surma's and @jeffposnick's point of view. If it's optional, then it should probably be in an object, but also agree that beyond the method, everything should be handled in the match callback, so if this is the case, why not option 1?

**Comment by jeffposnick** [comment]
I'm against anything that includes `routing.all()`, since there are very few scenarios in which you'd want a one-handler-fits-all for `GET`, `POST`, `PUT`, etc. You [can't](https://w3c.github.io/ServiceWorker/#cache-put) directly use `POST` and `PUT` `Request` objects as key when working with the Cache Storage API, for one thing, and cache interactions are the most common thing to do inside of a handler. For the Google Analytics use case, are you sure that the exact same `handler` could be used for both verbs? (If the same handler could be used, it's the exception rather than the rule.)

Switching from an optional third parameter being a string to being an object is a toss-up for me. If there's support for switching from others, now's the time to do it while we're still introducing breaking changes.

The argument for switching to `routing.get()`/`routing.put()` would have been stronger if we still supported Express-style routes, but since we've dropped support, moving closer to Express's interface seems like sending a mixed signal.

**Comment by gauntface** [comment]
I understand that there aren't many scenarios - but there *ARE* scenarios where it's useful - it's the point of a good API - it steers users, doesn't dictate.

I get the cache API argument, but it assumes developers are only only doing stuff with the cache API, which the minute any use other than GET is considered, it will likely get way out of the realm of what Workbox is geared towards.

I'm not convinced that developers will think that this is the same as express, they'll see a similarity, but the terminology we use in docs will be very different, and the warnings we've added will make it clear that we aren't express.

**Comment by gauntface** [comment]
I'm going to close this in favor of continuing discussion in: #778
