### ISSUE TITLE
workbox-build copyWorkboxLibraries - return full path instead of dirname

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1077]
Would it make sense for copyWorkboxLibraries to return the full path? 

It seems more useful than the dirname especially given path.dirname(...) would provide this if developers wanted it.

**Comment by jeffposnick** [comment]
The base directory name, without the full path, is [used](https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-build/src/entry-points/generate-sw.js#L71-L73) when constructing the appropriate `importScripts` URLs, e.g.:

```js
options.importScripts = [
  `${workboxDirectoryName}/${workboxSWFilename}`,
].concat(options.importScripts || []);
```

Given that it's straightforward to print out the full filesystem path when needed, I'd like to just stick with returning the base directory name instead of optimizing for the other usage.

**Comment by gauntface** [comment]
I'm not sure what this has to do with the method for copying the libraries.

I the developer write a function to copy the path of the workbox libraries to a specific path, when I get the returned value,

**Comment by jeffposnick** [comment]
If you're a developer who calls `workbox-build.copyWorkboxLibraries()` explicitly, then yes, there's a chance you'd want to make use of the file system path because you'd do something like logging it to `STDOUT`. But there's also a chance you'd want just the directory name, because you're going to construct a URL to use with `importScripts` configuration.

Both are valid things to do with the return value, and in either case, it's straightforward to use the `path` module to derive the value that isn't returned. I just made a judgment call to optimize for using the bare directory name.
