### ISSUE TITLE
Service worker cache network requests canceled, "Too many transactions queued"

### ISSUE THREAD

**Issue by rjsteinert** [GoogleChrome/workbox#1115]
**Library Affected**:
workbox-sw

**Browser & Platform**:
Does not work on Chromium v49, does work on Chrome v63.

**Issue or Feature Request Description**:
When registering service worker, all resources to cache are listed as "canceled". 

![screen shot 2017-12-11 at 12 31 19 pm](https://user-images.githubusercontent.com/156575/33844906-bd221d30-de6f-11e7-805d-9bcc98425ada.png)

![screen shot 2017-12-11 at 12 36 26 pm](https://user-images.githubusercontent.com/156575/33845035-240b5afc-de70-11e7-9b4d-732d88529c39.png)

**Comment by jeffposnick** [comment]
The published copies of Workbox do not support Chromium v49.

Our official support matrix is at https://github.com/GoogleChrome/workbox/wiki/V3-:-Browser-Support

If you'd like to use Workbox v2 with Chromium v49, you can check out the project's `#master` branch, modify the relevant Babel transpilation to use a different minimum supported browser version:

https://github.com/GoogleChrome/workbox/blob/60d90262077c18e34240921fe0d36b876f5ca3b0/utils/build.js#L159-L167

and run `npm install && gulp build`.

Support versions of Chromium prior to v51 impose a large additional runtime cost due to the need to polyfill generators for `async`/`await` support.
