### ISSUE TITLE
Question: how to cache an entire site to be used in an iframe offline

### ISSUE THREAD

**Issue by robertop87** [GoogleChrome/workbox#1142]
Sorry if it is not the best place to ask it.

I have a Polymer site working in offline mode, it's working perfectly, but in some points I need to show an iframe (same domain), but the playout is "No internet conecction"; I already cached all files included in the iframe and its own index.html, but the problem persists.

Any suggestion or idea?

**Comment by gauntface** [comment]
Can you provide the following information:

1.) Where is your service worker file on your website?
2.) What URL is the page being loaded in the browser?
3.) What URL is the page being loaded in the iframe?

**Comment by robertop87** [comment]
@gauntface 
1. https://mydomain.com/player/sw.js
2. https://mydomain.com/player/index.html
3. https://mydomain.com/pages/new/333ddd.html

Thanks in advance

**Comment by gauntface** [comment]
@robertop87 the location of the service worker file 'sw.js' means the **scope of the service worker** is `/player/`, this means it will control only pages that start with `/player/`. For the iframe, the service worker will not control that page since it starts with `/pages/`.

If you want to support offline of the service worker file you can do one of the following things:

1.) Move the service worker file to `/sw.js`, this means all pages on mydomain.com will be controller by your service worker.
2.) Add a second service worker that can be used to control the iframe url (i.e. a service worker at `/pages/sw.js` or `/pages/new/sw.js`. This will only control pages that start with `/pages/` or `/pages/new/`.

Does that make sense? I know we discussed this in the slack channel a little while a go.

**Comment by gauntface** [comment]
Going to close this and roll it into #1211
