### ISSUE TITLE
cacheFirst always hitting the network

### ISSUE THREAD

**Issue by chrstntdd** [GoogleChrome/workbox#1158]
**Library Affected**:
*workbox-sw and workbox-build...?*

**Browser & Platform**:
*all browsers.*

**Issue or Feature Request Description**:

This may be a mistake in my config, but I have tried just about everything and can't seem to get precaching to work at all. The overarching issue is that despite the installation of my service worker succeeding and the assets being precached on the same installation event, repeat visits still hit the network - never the cache. Even using the dev build, I couldn't get any helpful logs that would explain this behavior. I have been testing this using my own server and on a fresh install, I get these logs on my server, presumably due to the precaching:

```bash
GET / 200 19.341 ms - 4732
GET /dist/images/landing-bg.jpg 200 9.935 ms - 102106
GET /dist/css/pure.css 200 22.742 ms - -
GET /dist/js/1b1a3d3-app.js 200 21.433 ms - -
GET /dist/sw.js 200 1.825 ms - -
GET /dist/workbox-sw.prod.v2.1.2.js 200 2.117 ms - -
GET /dist/workbox-sw.prod.v2.1.2.js.map 200 4.824 ms - -
GET /dist/index.html?_workbox-precaching=c4e75fee53162c1aae3198b8c4b9fc16 200 7.823 ms - -
GET /dist/css/pure.css?_workbox-precaching=71f55ed2e98695e0e365deae05e60c3f 200 5.575 ms - -
GET /dist/js/3636819d-a0447f84.js?_workbox-precaching=1da4d9983f51e8a9fb04a9579f02e3cb 200 10.920 ms - -
GET /dist/js/b39025ba-3f198544.js?_workbox-precaching=e228f8ddf7ebfe4ea1479bcadbda7f66 200 161.298 ms - -
GET /dist/js/1b1a3d3-app.js?_workbox-precaching=480102f23cd101a60195614246e3ad74 200 7.594 ms - -
GET /dist/workbox-sw.prod.v2.1.2.js.map 200 48.540 ms - -
GET /dist/js/741cd244-8ed73404.js?_workbox-precaching=d7ed99a67df08c0e2fd5e3061c1194ad 200 164.007 ms - -
```

My `workbox-build` config:

```js
const outDir = join(__dirname, '/dist');

task('sw', async () => {
  try {
    await workbox.injectManifest({
      globDirectory: `${outDir}`,
      staticFileGlobs: ['**/*.{html,js,css}'],
      globIgnores: ['**/sw.js'],
      swSrc: 'client/sw.js',
      swDest: `${outDir}/sw.js`
    });
    info('  ⚙️ Service worker generated 🛠');
  } catch (error) {
    info(
      red('  😒 There was an error generating the service worker 😒', error)
    );
  }
});
```

My generated sw.js file:

```js
importScripts('workbox-sw.prod.v2.1.2.js');

const workbox = new WorkboxSW({
  skipWaiting: true,
  clientsClaim: true
});

workbox.precache([{
    "url": "css/pure.css",
    "revision": "71f55ed2e98695e0e365deae05e60c3f"
  },
  {
    "url": "index.html",
    "revision": "c4e75fee53162c1aae3198b8c4b9fc16"
  },
  {
    "url": "js/1b1a3d3-app.js",
    "revision": "480102f23cd101a60195614246e3ad74"
  },
  {
    "url": "js/3636819d-a0447f84.js",
    "revision": "1da4d9983f51e8a9fb04a9579f02e3cb"
  },
  {
    "url": "js/741cd244-8ed73404.js",
    "revision": "d7ed99a67df08c0e2fd5e3061c1194ad"
  },
  {
    "url": "js/b39025ba-3f198544.js",
    "revision": "e228f8ddf7ebfe4ea1479bcadbda7f66"
  }]);

workbox.router.registerNavigationRoute('/index.html');

workbox.router.registerRoute(
  /\.js|\.css|\.html$/,
  workbox.strategies.cacheFirst({
    cacheName: 'asdf',
    cacheExpiration: {
      maxEntries: 2,
      maxAgeSeconds: 7 * 24 * 60 * 60
    },
    cacheableResponse: { statuses: [0, 200] }
  })
);

```
Screen shots:

Cache
<img width="1224" alt="screen shot 2018-01-04 at 8 29 49 pm" src="https://user-images.githubusercontent.com/17863654/34591854-512dc93a-f18e-11e7-95c4-329683b9316f.png">

First visit network
<img width="884" alt="screen shot 2018-01-04 at 8 31 00 pm" src="https://user-images.githubusercontent.com/17863654/34591862-5e78a5ec-f18e-11e7-99b8-7577e366240f.png">

Second visit network
<img width="885" alt="screen shot 2018-01-04 at 8 31 17 pm" src="https://user-images.githubusercontent.com/17863654/34591867-6c70648c-f18e-11e7-95de-18e9410139a1.png">

**Comment by DavidScales** [comment]
It looks like the precaching stage is working, since you can see the files in the cache with dev tools, which makes me think it must be an issue with route matching. Is it possible that the regex in your `registerRoute` call is off? Currently it looks like you have `/\.js|\.css|\.html$/`, which only matches the end of a URL. I think you have to match the entire URL. 

Tools like https://regexr.com/ are useful for testing that stuff (I'm not great at regex so I use this a bit). 

I don't really understand the behavior shown in the network tab though, so that might not be the issue and I could be way off. 

Another thing I'm not familiar with is the `_workbox-precaching=...` parameter thats getting appending to URL's. I don't think Workbox ignores query params by default so that could cause issues as well, since the Cache API uses direct string comparison (e.g., `"index.html" !== "index.html?hello=world"`).

**Comment by gauntface** [comment]
Is there an example project or site we can see? It's normally easier to diagnose.

Things will be getting better for debugging and understanding what is happening in V3, checkout the precaching demo: https://workbox-demos.firebaseapp.com/demo/workbox-precaching/

**Comment by jeffposnick** [comment]
Based on your HTTP server logs, your service worker file is being served from `/dist/sw.js`.

Because it's being served from the `/dist/` subdirectory, an HTML page accessed from the top-level `/` page won't be under its scope, and the service worker won't be able to control that page. That's why you never see it intercepting any traffic.

If you start serving your service worker file from `/sw.js` instead of `/dist/sw.js`, I'd imagine that things should start working as expected.

Background on how service worker scopes work can be found at https://developers.google.com/web/fundamentals/primers/service-workers/#register_a_service_worker

**Comment by DavidScales** [comment]
Ah yeah that makes way more sense than my answer ;) I was mistaken about the regex thing. From testing, it looks like you don't need to match the entire URL with the regex in `registerRoute`.

**Comment by chrstntdd** [comment]
@jeffposnick - you're absolutely right! I adjusted things just like you said and now I serve the service worker from `/sw.js`. I knew it was just a minor config problem outside of this library specifically. Thank you for your help.
