### ISSUE TITLE
[Question] Custom the path of service worker file in index.js

### ISSUE THREAD

**Issue by robertop87** [GoogleChrome/workbox#1161]
Hi Everyone.

Currently I have a sw.js out of my app, and I need to use for my app.

After a build i got the index.js file with the next line:
   `navigator.serviceWorker.register('sw.js')`

And I need to set it to:
   `navigator.serviceWorker.register('../sw.js')`

Any suggestion?

Thanks in advaced

**Comment by gauntface** [comment]
From the slack channel:

The main scenario is the next:


[7:03] 
- I have an wesite here: mydomain.com
- I have my application using context here: mydomain.com/context
- Into my app I am loading iframes that use: mydoamin.com/sf/new/index.html
- My SW is located here: mydomain.com/context/sw.js
* As you told me before it should be located here: mydomain.com/sw.js
- But it's not possible with my current IT, then I asked them to redirect any request of mydomain.com/context/sw.js to mydomain.com/sw.js

Of course this is not working because in my built index.js I got the next line:
_navigator.serviceWorker.register('sw.js')_
and I need to configure workbox to have the next:
_ navigator.serviceWorker.register('../sw.js')_

**Comment by gauntface** [comment]
I don't think your redirects will help.

The best bet if you can't put sw.js in at /sw.js then you should probably look at adding the `Service-Worker-Allowed` header more info: https://www.w3.org/TR/service-workers-1/

I think Stackoverflow my be a better place for your questions as it's a service worker question instead of Workbox.
