### ISSUE TITLE
Turn off a service worker in parts of the website

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#1164]
Hi,

Service Workers are great and I love them, but they are very annoying when trying to work in the backend of a website like an admincp.

In Google Chrome there is a feature that you can turn off a service worker for a website - works great!

I just wondered if its possible to write a small JavaScript and add it to all the admincp pages that tells the browser to turn off the service worker automatically.

Because in a real life situation we only need to cache the front-end and not the back-end of a website.

Thanks.

(Feature Request if it's possible?)

**Comment by jeffposnick** [comment]
Hello @ayumihamsaki—Are those AdminCP pages purely server-rendered? (I'm not familiar with it, but I think it's a PHP script?)

I think what you're describing is just making sure that there aren't any service worker runtime caching routes that match the URLs you're using for your AdminCP pages. If all of your AdminCP pages share a common URL path prefix, that would make it much cleaner to keep things separate.

If you could share the URL prefix used for your AdminCP pages along with the runtime caching routes that you're currently using, we should be able to offer some advice.

**Comment by ayumihamsaki** [comment]
Hi Jeff,

Thanks for reply, Jake gave me a good answer will post his code here and also the link. I think this code should work for Workbox, maybe you guys want to add it to the doc's.

Code:

```
addEventListener('fetch', event => {
  const url = new URL(event.request.url);

  if (url.origin === location.origin && url.pathname.startsWith('/admin/') {
    // just let the browser do the normal thing:
    return;
  }

  // rest of your service worker logic
});
```

Linked from: https://github.com/w3c/ServiceWorker/issues/1257

**Comment by jeffposnick** [comment]
Hello @ayumihamsaki—I'm glad things are working for you!

I think the main thing is that, by default, Workbox won't intercept any `fetch` requests. Once you add in precaching, it will start intercepting requests for precached resources, but presumably your AdminCP URLs aren't precached (that's why I asked about server rendering).

So if Workbox was intercepting those URLs, it's likely because you had an overly broad runtime caching route defined. If you wanted to share your current Workbox routing configuration, we could get your routing logic adjusted so that it wouldn't match your `/admin/` URLs.

**Comment by ayumihamsaki** [comment]
@jeffposnick Thanks for the offer, I am waiting for Workbox V3 to come out of alpha and into beta, so I will sort this issue out later.
