### ISSUE TITLE
Handle cache-misses by falling back to network (by default?)

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#1188]
**Library Affected**:
`workbox-strategies`, `workbox-precaching`, `workbox-routing`

There are three places where cached responses would normally be used, but, in the case of a cache miss, falling back to the network might be preferable to a hard failure.

- [x] One is in the [`NetworkFirst` strategy](https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-strategies/NetworkFirst.mjs#L115) when `networkFirstTimeout` is set. You could imagine that strategy being applied with an empty cache, and the timeout being reached, but there not being any cached response to end up using. In the current codebase, we'd end up resolving with `null` as soon as the timeout hits rather than waiting for an eventual network response.

- [x] Another is in [`workbox.precaching`'s `default` export](https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-precaching/_default.mjs#L213), where a user who somehow ends up with a missing precached entry, that will result in the request failing immediately, instead of falling back to the network. (FWIW, `sw-precache` [automatically fell back](https://github.com/GoogleChromeLabs/sw-precache/blob/master/service-worker.tmpl#L171) to the network in this scenario.)

- [x] And finally, [`workbox.routing`'s `default` export](https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-routing/_default.mjs#L164) has a `registerNavigationRoute()` method that only does a `caches.match()` without a fallback.

In v2, you could accomplish something similar `workboxSW.router.setCatchHandler()`, but in v3, `workbox.precaching` doesn't end up using `Router` under the hood.

What are folks' thoughts on adding in network fallbacks by default in v3? I don't know if we'd need to allow developers to opt-out of the automatic fallbacks, but if we did, it might get a little messy figuring out how to do that, since it would need to be a setting that both `workbox.precaching` and `workbox.routing` could read. I guess it could be in `workbox.core`?

**Comment by gauntface** [comment]
1. We could definitely be smarter here.
1. I'm lost as to when this could be the case unless we aren't throwing an error (resulting in an aborted sw install). But still I'm ok with adding it in as a last resort.
1. Again agree we should change this behavior, although we should probably throw a warning in dev when caches.match is a miss and we fall back to the network - just to encourage precaching.

**Comment by DavidScales** [comment]
I think this is an interesting direction. I like this particularly for precache stuff, where the routing is implicit (though like Matt I'm not sure in which scenarios this would happen).

For runtime caching though, one consideration I'd like to propose is that the current pattern supports 

network first --> cache fallback --> custom logic fallback 

pretty readily, and the dev could implement a network-retry themselves in the custom logic fallback (this could maybe even be added to your common recipes).

It may still be nicer as a default like you're suggesting. However I would advocate for the opt-out or something similar, because the dev might want to do something besides a network retry in the custom logic fallback, such as serving an offline page (particularly in lie-fi situations). I haven't used `router.setCatchHandler()` in v2 but it sounds like the kind of thing that could work here.

**Comment by gauntface** [comment]
This and some of the comments in the streaming proposal doc makes me consider Jake's proposal a little more about the ability to change functions together.

router.registerRoute(matchCb, handler1Cb, handler2Cb, handler3Cb).

**Comment by sorin-davidoi** [comment]
> I'm lost as to when this could be the case unless we aren't throwing an error (resulting in an aborted sw install). But still I'm ok with adding it in as a last resort.

I think I'm bumping into this. Instead of generating the cache list server-side, I'm scraping the links from the DOM and sending them to the service worker. I expected this would work, but the links are added to `_entriesToCacheMap` without being cached. After further reading, I see that this is the expected behavior, but it might be worth being highlighted in the documentation.

```js
addEventListener('message', function(event) {
    const { data: { chapters } } = event;

    workbox.precaching.precacheAndRoute(
        chapters.map(chapter => ({ url: chapter, revision: chapter }))
    );
});
```

**Comment by gauntface** [comment]
@sorin-davidoi can you provide an example?

I think the reason it's not working for you is because precaching expects to run synchronously in the service worker (this is async due to the messaging).

You could just use the PrecacheController for your use case: https://developers.google.com/web/tools/workbox/modules/workbox-precaching#advanced_usage

**Comment by sorin-davidoi** [comment]
> @sorin-davidoi can you provide an example?

Refactored the code to generate the caching list at compile-time, and I don't have the original at hand anymore.

> I think the reason it's not working for you is because precaching expects to run synchronously in the service worker (this is async due to the messaging).

Yes, but I think it would be nice if that was more explicitly states in the docs, or `precacheAndRoute` could throw an error if it is run asynchronously.

**Comment by gauntface** [comment]
Removing from v3 - we've implemented the two biggest blocked IMO and I feel like the navigation route is something that we need to discuss further based on the PR that is currently open (i.e. why not just have a catch handler that defaults to network - this should a pretty big last change to work instead of various little places to try and handle this).

**Comment by muziyu1203** [comment]
hello，I met a problem when I use workbox-strategies to fetch a combo request like "https://xxx.xx.x/??a.css,b.css,c.css" in chrome 58, it showed error message "the FetchEvent for https://xxx.xx.x/??a.css,b.css,c.css" resulted in a network error response, the promise was rejected.", so I cannot fetch the combo request in chrome 58, while it works well in chrome 66.  So I wonder do you have any ideas for this situation?
