### ISSUE TITLE
Workbox CLI - add a note about "root" of webapp being build directory

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1237]
I just noticed that when we ask for the root of a web app, it's clear that it's the build directory that users should be pointing the config too.

Output for my selection
> ? What is the root of your web app? (choices include: src/ and build/)

Should we change the request to:

> ? What is the root of your web app (i.e. what directory do you deploy)?

**Comment by ChildLearningClub** [comment]
I'm using the PWA Studio extension for VSCode to convert a phaser3 web app over to PWA. I honestly didn't know what

 `? What is the root of your web app (i.e. what directory do you deploy)?` 

meant.  In the wizard I was selecting the root folder. At least in my case seeing

 `? What is the root of your web app? (choices include: src/ and build/)` 

or something similar directing me to the src/ folder would have saved me a couple of hours :)

**Comment by ChildLearningClub** [comment]
so it looks like

`? What is the root of your web app (i.e. what directory do you deploy)?`

is more applicable, I was using PWA Studio incorrectly. There is not much documentation as to how to use it, so it was more a matter of fiddling around until I got it to work correctly. At least in PWA Studio you first have to go into the directly you will be deploying, create a web manifest there.  
  Before creating the service worker change the folder you are in. I went back one folder so that I was no longer in the directory that I would deploy, but in the folder that contained it. PWA Studios github page is probably a better place to put this, but when trying to solve this issue myself I came to this page, so I figured I would leave a comment here.

**Comment by jeffposnick** [comment]
I'm sorry about that frustration. I just wanted to make sure that it's also been brought to the attention of the PWA Studio team (CC: @jgw96) as it might help to have this information in that context.
