### ISSUE TITLE
v3 bgSync queueDidReplay fires even when offline

### ISSUE THREAD

**Issue by DavidScales** [GoogleChrome/workbox#1249]
**Library Affected**:
*workbox-backgroundSync*

**Browser & Platform**:
*Google Chrome v63.0.3*

Still working on background sync, I've got the basic example working from #1222, and now I'm trying to use the `queueDidReplay` callback:

```javascript
const showNotification = () => {
  self.registration.showNotification('Background sync success!', {
    body: '🎉`🎉`🎉`'
  });
};

const bgSyncPlugin = new workbox.backgroundSync.Plugin(
  'dashboardr-queue',
  {
    callbacks: {
      queueDidReplay: showNotification
    }
  }
);

const networkWithBackgroundSync = new workbox.strategies.NetworkOnly({
  plugins: [bgSyncPlugin],
});

const addEventRoute = new workbox.routing.Route(
  ({url}) => url.pathname === '/api/add',
  networkWithBackgroundSync,
  'POST'
);

workbox.routing.registerRoute(addEventRoute);
```

This mostly works as expected, except it fires even when I'm offline. These are the steps I'm taking:

1. While online, make POST request to endpoint (api/add) - this works
2. Shut off server to go offline, make POST again - failed request is queued in IndexedDB as expected, but the notification still fires, signaling that `queueDidReplay` is executing even though my requests are not being successfully replayed. I also get an error log:

```
workbox-background-sync.dev.js:377 Uncaught (in promise) WorkboxError: 1 requests failed, while trying to replay Queue: dashboardr-queue.
    at https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.6/workbox-background-sync.dev.js:377:15
    at Generator.next (<anonymous>)
    at step (https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.6/workbox-core.dev.js:14:32)
    at https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.6/workbox-core.dev.js:25:15
    at <anonymous>
```

Any ideas?

Related but separate issue: 
#1247

**Comment by prateekbh** [comment]
Working with `sync` event on local can be tricky. To emulate proper offline behavior 

a.) You need to shut down the server
b.) Shut down your actual network(disconnect WIFI, pull of LAN etc)

Only then browser will know you are offline, because browser takes actual network as  the single source of truth.
Hence if you do `a.` but not `b.` browser will think its a server error, or if you do `b.` but not `a.` browser is happy as your API is still working.

P.S. Devtools offline does not help in this case because apparently for `sync` event it still looks for actual network.

**Comment by DavidScales** [comment]
Yes! that super fixed it. 

It also solves the issue of the bg sync taking 5 minutes to occur on Chrome, because it looks like turning the wifi back on triggers the event 😄  

Thanks!
