### ISSUE TITLE
GenerateSW vs InjectManifest - importWorkboxFrom

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1260]
I'm little confused by the differences in the GenerateSW and InjectManifest allowed values for `importWorkboxFrom`.

Why does inject manifest not allow 'local'?

**Comment by jeffposnick** [comment]
`injectManifest` is premised on the idea that there is a single point in the service worker file that we're going to modify (defined by `injectionPointRegexp`), and the only modification we're going to make is injecting the manifest.

Since the only thing we're modifying is the manifest, there's no provisions for modifying `importScripts()` and modifying the workbox module loader's base directory.

The assumption is that developers have control over their `swSrc` file, and are responsible for putting in the correct `importScripts()` and module path config statements. Developers might use `wokrbox copyLibraries <path/to/dest>`, download the `.zip` archive we make available, or using the CDN URL.

Given that, are there any changes to the implementation or the docs you'd like to see?

**Comment by jeffposnick** [comment]
And I'll also put in a caveat that the webpack plugin's `InjectManifest` mode has a different implementation than the `workbox-build`/`workbox-cli` mode, in that the injection is done by generating an external `precache-manifest.[hash].js` file that's then pulled in via `importScripts()` into `swSrc`.

So in the webpack case, we are modifying `importScripts()` already rather than relying on a single injection point RegExp, and we have more flexibility to support `importWorkboxFrom` set to `'cdn'` or `'chunk'`. Setting `importWorkboxFrom: 'local'` still isn't possible in that mode, because we'd also have to inject the workbox module loader configuration to point to the correct base directory.

**Comment by gauntface** [comment]
@jeffposnick Does the webpack `InjectManifest` use importWorkboxFrom? If so - it should support all options, or not support the command at all.

I'm fine with developers using workbox-build's `copyLibraries()` in conjunction with `injectManifest()` because they are using `workbox-build`. For the webpack injectManifest plugin, it feels like we are forcing the developer to figure out an extra step outside of their webpack config to get the files.

**Comment by raejin** [comment]
Is it possible to consider supporting `copyLibraries()` implicitly by configuring `importWorkboxFrom` option? I would love to explore this possibility but would like to know if this will be considered a path forward.

Currently, `InjectManifest` supports the option of `importWorkboxFrom` to be pointing at a valid chunk. However, after experimenting with this option, I believe that it is not the most realistic use case. The reason I came up with being:

1. Webpack will bundle its chunks, meaning, certain Webpack context will need to be exposed to service worker script. (such as webpackJsonp) --- Not ideal for our use case.
2. The only reasonable set up for this config is to copy & paste workbox-sw build to a source file, which will later be bundled by Webpack. (it will potentially go through multiple loaders, with transforms etc.) --- I think the extra loader steps are redundant, since we would simply refer to a workbox-sw build.

**Comment by jeffposnick** [comment]
> Does the webpack InjectManifest use importWorkboxFrom? If so - it should support all options, or not support the command at all.

Yup, the webpack plugin's `InjectManifest` uses `importWorkboxFrom`.

Adding support for `importWorkboxFrom: 'local'` to the webpack plugin means that in addition to modifying `importScripts()`, we'd also have to insert

```js
workbox.setConfig({modulePathPrefix});
```

somewhere into the `swSrc` file, which is *possible*, but I've been hesitant to mess too much with the source service worker file when in `InjectManifest` mode.

I think the webpack use case is also a bit special in that a user who wants a local copy of Workbox has the option of using webpack to bundle it up for them, and then specify `importWorkboxFrom: <chunkname>` to use that local copy.

**Comment by jeffposnick** [comment]
@raejin—We heard feedback with the previous release of Workbox that developers wanted the option of using webpack to create their own custom bundle, based on the individual modules, instead of of using our prepackaged bundles. I *think* we've met that use case in v3, though it might not be the use case that's right for your project.

When using webpack's `InjectManifest`, `importWorkboxFrom` supports 'none', '<chunkname>'`, or 'cdn'. If you use `importWorkboxFrom: 'none'` then you can maintain your own copy of the libraries in the location you'd like, and add

```js
importScripts('path/to/my/workbox-sw.js');
workbox.setConfig({modulePathPrefix: 'path/to/my/'});
```

to your `swSrc` file.

As mentioned above, we *could* add in support for `importWorkboxFrom: 'local'` and make those modifications to `swSrc` for you, but if we're going to go that route, maybe we need to rethink why we don't also allow that in `workbox-build`/`workbox-cli`.

**Comment by gauntface** [comment]
I would love `importWorkboxFrom: 'local'` to work in the inject manifest plugin. I would also be fine with either forcing the developer to set `modulePathPrefix` manually or injecting it - the tricky part we are solving is getting the files.

Regarding why not add to workbox-build or CLI is because the places where you'd use these (i.e. a node script of a terminal) to inject your manifest is also the same place you'd get the files - for build it's a function call, for CLI it's a comment.
