### ISSUE TITLE
InjectManifest Plugin – Set manifest dest

### ISSUE THREAD

**Issue by garviand** [GoogleChrome/workbox#1285]
**Library Affected**:
*workbox-webpack-plugin* (v3.0.0-alpha-5)

**Issue or Feature Request Description**:
*Add option to set the `manifestDest` when using InjectManifest Plugin with Webpack*

Since it is important to put the service worker file at the root of the files you want to cache (for scoping reasons), it is possible that the `precache-manifest.js` file could be in a different directory. It seems that the generated import call forces you to have both the service worker and precache manifest in the same directory.

Although this will usually be the case, it would be convenient to have the ability to choose.

**Comment by jeffposnick** [comment]
Thanks for the feature suggestion. As of the current implementation, the precache manifest will end up served from whatever your `publicPath` is configured to be:

https://github.com/GoogleChrome/workbox/blob/50fab168140067c213f97fea58bdc0657dd60b89/packages/workbox-webpack-plugin/src/inject-manifest.js#L100-L103

I can't say that I'm familiar with all the different ways that folks have webpack set up, but is setting `publicPath` in your webpack config sufficient here? Or do you really need to explicitly set your own prefix?

**Comment by gauntface** [comment]
cc @garviand as you weren't mentioned in the previous comment

**Comment by Schlesiger** [comment]
Not only adding a new destination, but the ability to rename the file would be preferred as well. Also, this should be an option for both `GenerateSW` and`InjectManifest`.

**Comment by MyNameReallySux** [comment]
I am also looking for this functionality. Basically want to have this manifest (and other manifest like files) put in a subfolder in order to keep the root directory more organized. If your not planning on adding this anytime soon I will probably do this myself and make a pull request, no ETA on when though.

It's not required to have this functionality, but implementing this is fairly simple and also gives developers 100% control over what this plugin outputs. This option should be available for both `GenerateSW` and `InjectManifest` as stated by @Schlesiger, and allow renaming.

**Comment by jeffposnick** [comment]
There are a few related issues that I'd like to address holistically:

1. Folks would like to name the precache manifest file something other than `precache-manifest.[manifestHash].js`.
1. Folks would like some control over where the precache manifest file and the local copy of the Workbox libraries wind up being written to. Currently they're always written to the top-level output directory for your `webpack` build, with `publicPath` prepended to the URL when they're referenced. This is not so much a matter of functionality as it is a matter of wanting more control over how your web server's files are structured.
1. Folks have run into issues due to setting `publicPath` in their webpack config, but *not* actually using a hosting environment where their service worker file is accessed with a URL that's prefixed with `publicPath`. This primarily comes up with developers who need to host their service worker file from a top-level `/service-worker.js` location, to ensure that it could control the full scope of their origin. (This was tracked in https://github.com/GoogleChrome/workbox/issues/1366 but I'm moving the discussion here.)

Regarding 1., my inclination is to leave things as-is for now. We need to ensure that there's always a correct hash included in the precache manifest's filename, because otherwise, changes to the manifest won't properly trigger the service worker update flow. Opening things up to allow a developer to use any arbitrary filename that they want would make it harder to ensure that the filename will always contain the appropriate hash. (We can revisit this later if needed.)

Regarding 2., this should be doable, but I am looking for some precedent as to whether there's a standard way to configure this sort of thing for `webpack` plugins. `html-webpack-plugin`, for one, has a [`filename` option](https://github.com/jantimon/html-webpack-plugin#options) that allows you to include a path prefix as well. But given that we don't want to support arbitrary filenames (see point 1.), calling it `filename` wouldn't work. We could call it `importsDirectory` or something along those lines, to indicate that it's a directory that's only used as a prefix when writing the imported files (precache manifest + local Workbox libraries).

Regarding 3., my inclination is to just start including the `publicPath` value as part of the configured `modulePathPrefix`. I'm a little worried about edge cases (if there were legitimate scenarios that relied on the previous behavior, for instance), but I gather that would end up with things being less-broken for the common use cases that it is right now.

Any feedback about those proposals are welcome, especially from folks using diverse `webpack` configurations. I'll look to put the changes for 2. and 3. into a single PR that folks could try out locally and offer feedback on.

**Comment by jeffposnick** [comment]
Also CC:ing in @raejin and @goldhand for their input, if they'd like to weigh in.

**Comment by raejin** [comment]
@jeffposnick 

Chiming in on your concern for point 1, could the hash be appended to the file name as part of the plugin cycle? I think offering customized name for precache manifest and controlling the content hash are not mutually exclusive. 

As for point 3, I'm all for making the implementation more Webpack setup agnostic. If moving `publicPath` to `modulePathPrefix` works with Webpack asset being served from a separate domain, that sounds good. I'm happy to help testing this out more rigorously.

**Comment by Schlesiger** [comment]
For point #1, this isn't a major issue, but I mostly wanted control over the manifest file name generation so I could append the hash as a query parameter. For example, `precache-manifest.js?[manifestHash]` instead of `precache-manifest.[manifestHash].js`.

**Comment by jeffposnick** [comment]
> For point 1, this isn't a major issue, but I mostly wanted control over the manifest file name generation so I could append the hash as a query parameter. For example, precache-manifest.js?[manifestHash] instead of precache-manifest.[manifestHash].js.

My concern is that someone would leave out the `[manifestHash]` when they defined their custom name, but I guess we could just throw an error and fail the compilation if it's configured without `[manifestHash]`.

**Comment by jeffposnick** [comment]
Those who have a vested interest in these changes, please take a look at https://github.com/GoogleChrome/workbox/pull/1403
