### ISSUE TITLE
Improve Testing for Windows

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#1320]
At the moment our tests are passing on AppVeyor, but after trying to run the same tests on a Window machines, the size and reivision of precached assets are different meaning we can't run our tests on Windows.

This doesn't need addressing immediately, but as Edge draws closer to stable SW support, we'll want a more reliable consistent set of tests.

**Comment by josephliccini** [comment]
Hi @gauntface !

From a rough estimate perspective, what would it take to run your various testing suites in Edge?

I am hooking up Workbox for an Edge specific project and keep uncovering small issues that I think might be caught by a lot of your existing tests.

Maybe I can help hook this up?  Or at the least, get some Edge specific test cases prepared.

Edge SW support has shipped in RS4 early last month.

This probably would include the fix for the AppVeyor size / revision differences as a side effect on Windows too.

Thanks!

**Comment by jeffposnick** [comment]
This is no longer a priority, as moving forward, Edge's service worker implementation should be (mostly?) identical to Chrome's.
