### ISSUE TITLE
[workbox-webpack-plugin] manifestTransforms not compatible with webpack 4?

### ISSUE THREAD

**Issue by Guymestef** [GoogleChrome/workbox#1341]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*Webpack 4*

**Issue or Feature Request Description**:
*The option "manifestTransforms" shouldn't crash webpack build when using webpack v4.*

Webpack stack trace:
[0] emittingTypeError: Cannot read property 'length' of undefined
    at module.exports (E:\Projects\SeatingPlan\SeatingPlanAdmin\node_modules\workbox-build\build\lib\filter-files.js:149:35)
    at _callee$ (E:\Projects\SeatingPlan\SeatingPlanAdmin\node_modules\workbox-build\build\lib\get-file-manifest-entries.js:191:29)

Hello,
Obviously, it crashes in [filter-files.js](https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-build/src/lib/filter-files.js) at line 118:
```javascript
const count = transformedManifest.length;
```
But I don't know what changes in webpack 4 to make transformedManifest undefined. With v3, everything was fine.

**Comment by jeffposnick** [comment]
Can you share some details about how you're configuring the Workbox webpack plugin? Are you using the `globPatterns` option to pick up additional files to precache that don't exist in the webpack asset pipeline?

Also, can you confirm which version of `workbox-webpack-plugin` you have installed? (The latest is `v3.0.0-beta.1`.)

**Comment by Guymestef** [comment]
I'm using the version 3.0.0-beta.1
Here my config:
```javascript
new GenerateSW({
                swDest: 'service-worker.js',
                manifestTransforms: [
                    (manifestEntries) => manifestEntries.map((entry) => {
                        if (entry.url.startsWith('dist/')) {
                            entry.url = entry.url.replace(/^dist\//i, '');
                        }
                        return entry;
                    })
                ],
                cacheId: 'sp-admin',
                importWorkboxFrom: 'local',
                maximumFileSizeToCacheInBytes: 10 * 1024 * 1024,
                globDirectory: './wwwroot',
                globPatterns: ['**/*.{js,png,jpg,gif,ico,html,css,eot,svg,ttf,json}'],
                globIgnores: [
                    '**/vendor-manifest.json',
                    '**/workbox*.js',
                    '**/*.hot-update.js',
                    '**/*.hot-update.json',
                    '**/precache-manifest.*.js'
                ],
                clientsClaim: true,
                skipWaiting: true
            })
```

**Comment by josephliccini** [comment]
same problem here.  I think this is because in `file-filters` it runs the file through the manifest transforms functions. 

For custom manifest transforms, documentation says to take the list of `ManifestEntries`, and return an array of `ManifestEntries`, but what is expected is this:
![image](https://user-images.githubusercontent.com/7726025/37005035-5febeed4-2087-11e8-81f1-b6af5c7128cb.png)

Workaround is to have `manifestTransform` functions return this:
```js
{ 
    manifest: manifestEntries
}
```

**Comment by josephliccini** [comment]
Note, I am not using the `webpack` plugin, but `workbox-build`.  

Yours @Guymestef (temporarily) will be:
```js
                manifestTransforms: [
                    (manifestEntries) => { manifest: manifestEntries.map((entry) => {
                        if (entry.url.startsWith('dist/')) {
                            entry.url = entry.url.replace(/^dist\//i, '');
                        }
                        return entry;
                    }) }
                ],
```

**Comment by jeffposnick** [comment]
The definition of `ManifestTransform` [changed recently](https://github.com/GoogleChrome/workbox/pull/1325), and is now

https://github.com/GoogleChrome/workbox/blob/f5792fd9c130fbd7916c7b3763752cf795d9b8a5/packages/workbox-build/src/lib/filter-files.js#L62-L67

The main difference is that you need to return a `{manifest, warnings}` object now, instead of just a `manifest`. We'll be sure to cover that in the migration guide. Apologies for the confusion during our beta period while we finalize the interface.

The change that @josephliccini suggested should work.

And if you're already using `webpack`, you'll find that v3 of `workbox-webpack-plugin` already knows about all of your assets in your compilation by default, and you may be able to get away without having to configure anything `glob`-related at all.

**Comment by Guymestef** [comment]
@josephliccini and @jeffposnick thanks for your replies

@jeffposnick I used ManifestTransform and glob* because I'm generated a vendors bundle with the DllPlugin of webpack in a separate build, in order to speed up the build of my app during development.
Is it planned or already done for workbox v3 to deal with the use of DllPlugin/DllReferencePlugin?

**Comment by jeffposnick** [comment]
@Guymestef—Sorry, I'm not familiar with `DllPlugin`/`DllReferencePlugin`.

We're learning a lot about how developers use webpack "in the real world" and would like to make as many common scenarios work with minimal Workbox configuration.

I'll open a new issue to track this and ask for some more information there.
