### ISSUE TITLE
One of the glob patterns doesn't match any files

### ISSUE THREAD

**Issue by moimael** [GoogleChrome/workbox#1356]
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
Workbox throws a warning 

```
WARNING in One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "/home/mlavault/Development/galaxy/public/dist",
  "globPattern": "**/manifest.*.js",
  "globIgnores": [
    "**/node_modules/**/*"
  ]
}
```

But the file is present at the right path and it is included in the precache-manifest. Other files are in the same directory and do not trigger this warning.

![screenshot from 2018-03-12 11-35-54](https://user-images.githubusercontent.com/1479859/37279018-c506d556-25e9-11e8-825e-538570cae9f0.png)

**Comment by gauntface** [comment]
@moimael what version are you using?

**Comment by moimael** [comment]
3.0 beta 2

**Comment by moimael** [comment]
Any idea why this happens ?

**Comment by jeffposnick** [comment]
In general, you don't want to use `globPatterns` to pick up assets that are part of the webpack build pipeline in v3 of the plugin. This is a departure from v2, and we're trying to improve the documentation around this (https://github.com/google/WebFundamentals/pull/5941) so that developers don't get caught up when migrating.

My guess would be that the file which matches `"**/manifest.*.js"` doesn't exist in the output filesystem *at the time that the Workbox plugin is run*. 

It's still being included in the precache manifest because in v3, assets that webpack knows about (independent of the filesystem) are picked up in the precache manifest by default.

I'd recommend dropping the `globPatterns` config value entirely, unless you specifically need to precache files which are *not* webpack assets.

**Comment by moimael** [comment]
The thing is i don't want all my assets in one service worker. We have a huge frontend app, that is organized into sub apps (landing pages, admin, ...) and each sub app has its own service worker (so we don't cache 10th of MB of assets for something the user will never visit).

So currently in my webpack conf I create one instance of the workbox plugin per app, hence the fact that I need to use globPatterns.

Unless there is a better way to achieve this ?

As for the manifest not being there when workbox is run, I don't see why that would be the case, it works perfectly fine with sw-precache plugin and all other bundles that are generated at the same time as the manifest are picked by the plugin.

**Comment by moimael** [comment]
Seems to work fine with the chunks option ! Thanks :)
