### ISSUE TITLE
Missing webpack publicPath on workbox.setConfig modulePathPrefix

### ISSUE THREAD

**Issue by djeeg** [GoogleChrome/workbox#1366]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
workbox 3.0.0

**Issue Description**:

Using this webpack config

```
    output: {
        publicPath: "/bundle/",
    },    
    plugins: [
		new InjectManifest({
                 importWorkboxFrom: 'local',
```

Generates this output

```
importScripts("/bundle/precache-manifest.<hash>.js", "/bundle/workbox-v3.0.0/workbox-sw.js");
workbox.setConfig({modulePathPrefix: "workbox-v3.0.0"});
```

If I start to use some plugins

`workbox.precaching.precacheAndRoute(files, {`

The plugins dont load in the browser (urls are missing /bundle/ prefix)

Workaround I have found, is to override modulePathPrefix

`workbox.setConfig({modulePathPrefix: "bundle/workbox-v3.0.0"});`

I see workboxSWImport adds `compilation.options.output.publicPath` 

https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-webpack-plugin/src/lib/get-workbox-sw-imports.js#L44

However setConfigString does not seem to
https://github.com/GoogleChrome/workbox/blob/1302a8400e452dcbdd6feb8570de24fa4d1a9c22/packages/workbox-webpack-plugin/src/inject-manifest.js#L119-L122

Not sure if i am supposed to override this on webpack options, cant see any properties
modifyUrlPrefix seems to only work on manifest

Maybe follow on from https://github.com/GoogleChrome/workbox/issues/1172
Or this comment https://github.com/GoogleChrome/workbox/issues/1260#issuecomment-362104124
> but I've been hesitant to mess too much with the source service worker file when in InjectManifest mode.

**Comment by jeffposnick** [comment]
(Bear with me, as I know that there are a lot of different ways that folks configure and use webpack.)

My understanding of `publicPath` is that developers configure it to indicate that all assets will be served from a URL that has `publicPath` as the prefix, including the generated service worker file.

So in your example (if we assume you're using `sw.js` as the service worker file's name), the assumption is that your web server will serve the service worker via `/bundle/sw.js`.

Assuming that's the case, the `workbox.setConfig({modulePathPrefix: "workbox-v3.0.0"});` statements would be correct, since the prefix `"workbox-v3.0.0"` is interpreted as being relative to the location of the service worker script, and equivalent to `"/bundle/workbox-v3.0.0"`.

The fact that you're running into issues indicates that some of those assumptions are not valid, at least for the way you're using webpack.

Could you clarify where, for instance, you're serving the your service worker file from?

**Comment by jeffposnick** [comment]
(Also, CC: @raejin who worked on https://github.com/GoogleChrome/workbox/pull/1265, which is related. I'd love to confirm that if there are changes that come out of this issue, they won't break assumptions that were made for other, related configurations.)

**Comment by djeeg** [comment]
Ahh yes that makes sense now, more of my situation below.

Upgrading from sw-precache-webpack-plugin (awesome job on the migration documents btw!)

My workbox-webpack-plugin output ends up like this:

- output\webpack\int\sw.js
- output\webpack\int\workbox-v3.0.0\workbox-sw.js
- output\webpack\int\workbox-v3.0.0\workbox-precaching.prod.js

However I forgot my carry over from sw-precache-webpack-plugin, repathing sw.js to the root path.

    app.use(
        "/sw.js",
        express.static(
            path.join(__dirname, "./../../../output/webpack/int/sw.js")
        ),
    );

Which I must have done to let the service worker access the root scope
Maybe it came from a suggestion like this
https://github.com/GoogleChromeLabs/sw-toolbox/issues/158#issuecomment-269622788

I will instead have to use **Service-Worker-Allowed**
https://github.com/GoogleChrome/workbox/issues/1161#issuecomment-356061501

**Comment by jeffposnick** [comment]
See See https://github.com/GoogleChrome/workbox/issues/1285#issuecomment-376653175 for follow-up.
