### ISSUE TITLE
Possible to set expire for precacheAndRoute

### ISSUE THREAD

**Issue by thangman22** [GoogleChrome/workbox#1387]
**Library Affected**:
workbox-precaching

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
I though best solution of this case is put hash on name or put revision of file but in some case we have to change it manually it would be great if we can setup expiration time for cache for precacheAndRoute

**Comment by thangman22** [comment]
@jeffposnick my fault. sorry

**Comment by thangman22** [comment]
@jeffposnick I'm not using build tool for this case. I try to integrate workbox with Wordpress. I created one page to display when cache not found and use as offline fallback. my problem is when pre-cache do first cache it not update again even my offline page is update.

**Comment by jeffposnick** [comment]
If you're not using a build tool, then `workbox.precaching.precacheAndRoute()` isn't a good choice.

I'd recommend using a runtime caching strategy instead, i.e. something from https://developers.google.com/web/tools/workbox/guides/route-requests#handling_a_route_with_a_workbox_strategy

**Comment by thangman22** [comment]
Please correct if wrong. Runtime caching will cache only after user request or browse this page right? Because my case is I want Wordpress immediately cache offline page i.e `/offline` when user visit any page of my website. I think one of good solution is fetch `/offline` when first visit for trigger ServiceWorker to cache. Do you has any good solution?

**Comment by jeffposnick** [comment]
I think the suggestion in https://github.com/GoogleChrome/workbox/issues/1377#issuecomment-374234943 covers that scenario.

**Comment by thangman22** [comment]
Oh actually I asked that question for another scenario but I it can use same solution thank you I will close this issue.

**Comment by jeffposnick** [comment]
No problem!

**Comment by Domiii** [comment]
I am using the `workbox-webpack-plugin`, and I learned that the `glob` configuration translates to `precacheAndRoute` (which is not documented anywhere).

@jeffposnick, you are saying:

> When integrating with a build tool, and using precacheAndRoute(), previously precached entries are expired and updated only when the build tool detects that there was a change. This happens whether or not you include hashes in the filenames, since Workbox can generate its own revision information independent of the filename, by looking at the file's contents.

However, I do not see that happening. What am I supposed to do in the following scenario:

## My problem
My `index.html` is static, in some `www` folder, outside of webpack's control. I want it to be reloaded every time it is changed, however it is stale and sitting in the cache forever. Restarting `webpack` and deleting the generated service-worker file both do not work. Chrome's "Hard reload + Empty cache" works.

In Chrome, when looking at `Application` -> `Cache Storage`, there is only a single `workbox-precache-someIdHere`, and for my `index.html`, it contains:

> Request URL: http://localhost:3000/index.html?__WB_REVISION__=0dc617f0075a2fdb48beb105a565c68b


## My `webpack` config:

```js
const workboxConfig = {
  swDest: "sw.js",

  // add non-webpack asset files (most importantly webflow files)
  globDirectory: root + '/www',
  globPatterns: ['**.*'],

  // see: https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#generateSW-runtimeCaching
  runtimeCaching: [{
    // custom rules for files that we want to fully control (especially index.html)
    urlPattern: /\/?index\.html.*/,
    // Apply a network-first strategy.
    handler: 'NetworkFirst',
    options: {
      // Fall back to the cache after 1 second.
      networkTimeoutSeconds: 1,
      // Use a custom cache name for this route.
      cacheName: 'index-cache',
      // Configure custom cache expiration.
      expiration: {
        maxAgeSeconds: 60
      }
    }
  }]
};

// ...

webpackConfig.plugins = [
    new GenerateSW(workboxConfig)
];
```

**NOTES**

1. I am using `webpack-dev-server`, which serves everything, including the static assets.
1. I use the `glob*` configuration options since those were the only options that I could use to actually get `index.html` cached in the first place. However, as of right now, it's cached forever.
1. `runtimeCaching` does not do anything.

Any help would be appreciated.

**Comment by apiel51** [comment]
> previously precached entries are expired and updated only when the build tool detects that there was a change

@jeffposnick are there any plans to reevaluate this? We rely on precaching but want to protect against users who haven't visited our site in a long time running a _very old_ bundle – instead we would love to set a TTL on the cached assets to force a network call and prevent this from happening. Curious if other folks have experienced the same use case.
