### ISSUE TITLE
Webpack plugin causes massive prolonged spike in CPU and Memory

### ISSUE THREAD

**Issue by jshado1** [GoogleChrome/workbox#1475]
## Library Affected

`workbox-webpack-plugin`

## Browser & Platform

OSX `10.9.5`
nodejs `10.0.0`
npm `6.0.0`
webpack `4.6.0`
workbox-webpack-plugin `3.2.0`
typescript `2.8.3` (probably not relevant)
ts-loader `4.2.0` (probably not relevant)

## Issue

When this is added to webpack for a fairly small app (73KB of source code and ~300KB of static/binary assets), it causes the `webpack-serve` process to exceed 100% CPU utilisation for several minutes during build/compilation until I manually kill the process; memory utilisation also increases _**significantly**_—memory utilisation is usually around 300MB, but with this plugin, it exceeds 1.2GB for the same duration.

This bad performance makes it literally unusable.

## Webpack plugins configuration

```js
plugins: [
    new webpack.DefinePlugin({
        // …
    }),
    new WorkboxPlugin.GenerateSW({
        swDest: 'sw.js',
        clientsClaim: true,
        skipWaiting: true,
    }),
    new ExtractTextPlugin({
        // …
    }),
    new HtmlWebpackPlugin({
        // …
    }),
],
```

**Comment by jeffposnick** [comment]
Apologies that you're running into this issue!

While we spend some time trying to reproduce it locally, could you provide a few more details?

- Do you see the same behavior when just running the `webpack` CLI to trigger a one-off build? Or is it limited to when you use `webpack-serve`?

- Does moving `GenerateSW` to last in the `plugins` array lead to any differences? (I'm not sure that it would w.r.t. the issue you're describing, but in general, if you wanted your HTML and/or the output of `ExtractTextPlugin` precached, you'd want to list `GenerateSW` after them.)

**Comment by jshado1** [comment]
I'm on vacation for a week starting today. I can try to put together a simplified example next weekend if you need.

**Comment by jeffposnick** [comment]
I don't have the exact same environment to test as you have (I'm on OS X 10.13, for instance), but I can't reproduce the issue when using the latest `webpack` 4.x release, `workbox-webpack-plugin` 3.2.0, and node 10 (w/`npm` 5.6.0).

I've also moved over (https://github.com/GoogleChrome/workbox/pull/1492) the existing `workbox-webpack-plugin` test suite to go against `webpack` 4.x instead of `webpack` 3.x, and those tests—which run `webpack` builds via the node API—complete  quickly and without issue.

That being said, you mention that your *normal* build time is around a minute, which makes me think that you've got a much more complicated build process than what I've been able to experiment with. (A minute sounds high for ~73kb of source code?) So it's entirely possible that you're just hitting some inefficiencies in the plugin that only become issues as the build gets more complex.

Any help you have putting together an example that we can run to reproduce the issues would be ideal, when you get the chance. And obviously if there's anyone from the community running into similar issues, we'd love to hear from you as well.

**Comment by jshado1** [comment]
A large part of the build time is from TypeScript converting to JavaScript, and (Semantic-UI) LESS converting to CSS. When I checked yesterday (without this plugin), the parts operating on the JavaScript itself took about 14 seconds on initial compile (and then about 4 seconds to re-compile a change with watch enabled).

I'll start ripping pieces out to see to what I can widdle it down.

**Comment by jeffposnick** [comment]
Can you give things a try using `workbox-webpack-plugin@next`?
