### ISSUE TITLE
Know the progression of files being cached

### ISSUE THREAD

**Issue by AdrienKourga** [GoogleChrome/workbox#1483]
**Library Affected**:
*workbox-sw*

**Browser & Platform**:
*"all browsers".*

**Issue or Feature Request Description**:
I made a webpage where the user can click on a button to cache videos with workbox. 
I need to display a progress-bar, but I didn't manage to be aware of the progression of the video being cached. 
With the custom plugins i can only be aware of the state before and after the caching but nothing concerning the advancement of the download.

Is there any way to be aware of this progression ?

Thanks,
Adrien

**Comment by hbl-huongdv** [comment]
> **Library Affected**:
> _workbox-sw_
> 
> **Browser & Platform**:
> _"all browsers"._
> 
> **Issue or Feature Request Description**:
> I made a webpage where the user can click on a button to cache videos with workbox.
> I need to display a progress-bar, but I didn't manage to be aware of the progression of the video being cached.
> With the custom plugins i can only be aware of the state before and after the caching but nothing concerning the advancement of the download.
> 
> Is there any way to be aware of this progression ?
> 
> Thanks,
> Adrien

Did you resolve this issue?

**Comment by chrislim** [comment]
Just wanted to add some of my learnings for reference in case it will help others. 

If you are hosting video on a separate domain from your web app, one challenge with the fetch-progress-indicators approach is that it wraps the stream with a new ReadableStream, which unfortunately does not have the {type: "cors"}. In Safari, this causes loading videos through the serviceWorker to break because it makes byte-range requests to progressively load the video and the non-cors request that is saved in the cache is opaque, meaning that these byte range requests fail. 

I'm still working out a solution to this issue, but it's something to be aware of when trying to solve the problem in the original ticket.
