### ISSUE TITLE
Workbox templatedUrls bug

### ISSUE THREAD

**Issue by Jamiewarb** [GoogleChrome/workbox#1487]
**Library Affected**:
*workbox-webpack-plugin* v3.2.0

**Platform**:
Mac High Sierra
node v9.11.1
webpack v3.5.0

**Issue or Feature Request Description**:
While writing a Stack Overflow ticket for support, I realised it may well be a bug, or an undocumented requirement.

I was using v2 of Workbox, and am now upgrading to v3. I generate it using Webpack.

I've begun using GenerateSW, and moving parts of the old config into the new one, changing where required for v3.

I'm running into a bug with templatedUrls not seeming to work the same way it did in v2.

Webpack config:

```javascript
plugins: [
    new WorkboxPlugin.GenerateSW({
        include: [/\.css$/, /\.js$/],
        importsDirectory: path.join(__dirname, 'public/precache'),
        'templatedUrls': {
            '/': ['header.php', 'footer.php']
        }
    })
]
```

Error:

```bash
There was an issue using one of the provided 'templatedUrls'. 'header.php' from '{"/":["header.php","footer.php"]}':
Error: An error occurred when globbing for files. 'The "path" argument must be of type string'
    at .../node_modules/workbox-build/build/lib/get-file-manifest-entries.js:138:27
```

If I use a string instead of an array, it works fine, but this is obviously for manual versioning rather than an array of file paths, which is what I am attempting to do here.

Finally, if I add `globDirectory: 'public'`, just before it, it seems to work, and expects my URLs to be based on that public directory (`../header.php`). However, it gives me this warning:

```bash
WARNING in You're using the following Workbox configuration 
option: [globDirectory]. In Workbox v3 and later, this is usually not needed.
```

While the docs do say the array of paths will be treated as a glob, so could be affected by globDirectory, it doesn't say a globDirectory must be defined to use it. Furthermore the warning is a surprise, telling me not to use it.

Any advice would be thoroughly appreciated!

**Comment by jeffposnick** [comment]
Sorry for the delayed response—this boils down to the same issue as https://github.com/GoogleChrome/workbox/issues/1384 (which I also need to follow up on...).

If you're happy to move the discussion there, I'll close this. And actually follow-up there 😄

**Comment by Jamiewarb** [comment]
Yep, absolutely fine! Thanks very much mate

**Comment by Jamiewarb** [comment]
Actually @jeffposnick, I'm not entirely sure it is a similar issue -- #1384 seems to refer to files that are generated by Webpack, but the header and footer files are already on the disk and are not generated by Webpack.

It's possible I've misunderstood, so if I'm wrong, feel free to close and we'll move discussion there as you say. Thanks!

**Comment by jeffposnick** [comment]
Ah, okay. If you really are dealing with files that exist on disk, outside of the webpack asset pipeline, then using `globDirectory` + `templatedUrls` is actually the correct approach—you can safely ignore that

```sh
WARNING in You're using the following Workbox configuration option: [globDirectory]
```

message. (Make sure that the entire contents of `/` really are uniquely determined by those two PHP files, though.)

So I think things are working as expected—you're one of the folks who actually do need to use that option while also using the webpack plugin.

#1384 is still relevant because we need to think about the exposed API surface for folks who are using the webpack plugin and want to be able to set options for files on disk, set options for files in the webpack asset pipeline, and keep those different settings straight. (Once we have an explicit way of setting the options for files on disk, we can remove that warning message.)

**Comment by Jamiewarb** [comment]
Okay, thanks for that confirmation Jeff! :+1:
