### ISSUE TITLE
Issue with lots of files

### ISSUE THREAD

**Issue by mick-feller** [GoogleChrome/workbox#1491]
Hi,

So i don't think this is specifically a workbox issue but not sure. What i've noticed is that when i try to precache lots of files (150+) the service worker starts failing requests.

After that it will cache "empty" or "failed" files which will then cause non of my css / js to load on page and leave a broken experience.

I'm running a huge monolithic app that uses webpack for it's builds and the code has been growing so the number of files / bundles have been growing. 

So for now i forced only certain files in precache but not sure if this is something you want to look at.

And if it's a limitation of the service worker itself maybe force a limit on the files? I don't know just thinking out loud how to prevent it.

When this was happening i got the same behavior as this bug:

https://github.com/GoogleChrome/workbox/issues/1441

So the service worker kind of got in an unknown state, that's also how i reproduced this bug. Even after updating to the latest version it was still failing to respond with a network request.

**Comment by jeffposnick** [comment]
Do you see any messages logged in the DevTools Console when this happens?

What does the Applications panel of Chrome's DevTools show—both the Service Workers and the Clear Storage tabs?

**Comment by Hoten** [comment]
I'm not getting the errors @mick-feller is, but I am noticing detrimental load times on initial install. I am still working on reducing the size of the precache, but at the moment it is:

```
1748 files will be precached, totaling 79.3 MB.
```

Other than reducing the precache size, what could be done to prevent degradation of load times? I would prefer the installation process to take much longer, and allow normal user requests to load without a huge delay.

**Comment by jeffposnick** [comment]
There are some best practices for service worker registration that you can follow: https://developers.google.com/web/fundamentals/primers/service-workers/registration

In general, though, asking users to download ~79mb prior to the service worker's installation completing is likely to be problematic, unless you know that all your users are on a fast, low-latency, highly-available Internet connection.

(Here's a related feature request for allowing developers to create separate required and optional precache payloads: https://github.com/GoogleChrome/workbox/issues/155)

**Comment by IanBellomy** [comment]
I'm pretty new to all this, but it sees like it'd be nice if there was a mechanism by which users could consent to such a download if they opt to add the page to the home screen / 'install' the 'PWA'. I'm sure I'm missing much dialog around service workers, but dipping my toe in, it seems a little odd that a service worker is, on one hand, meant to allow a site to cache files so that a user can use the site like a native off-line app, but on the other hand, the native-app-like need for installing numerous resources is too much to ask from the service worker. (Games / game-like activities would probably provide the best cases of an (off-line) user needing to access who-knows-what of a substantial asset catalog. )
