### ISSUE TITLE
Wordbox and updateViaCache

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#1519]
The link can be found here about them: https://developers.google.com/web/updates/2018/06/fresher-sw

From my understanding the following three outcomes are as follows:

- `all` = Will check the update of the Service Worker main script and the imported script via the browser cache. 
- `imports` = Only checks the update of the imported script via the browser cache and checks the main script update directly for the server.
- `none` = Either script will query the server directly.

Also:

- `all` was used prior to Chrome 68.
- `imports` will be used starting in Chrome 68.

Browser support:

Chrome and Firefox are using it right now, but others to add soon.

I am thinking that for most people the following would apply to Workbox:

Create a Service Worker Code once and update few times and the Workbox code gets updated all the time via importScripts tags.

So my logic would be this:

Service Worker main script from the browser cache and imported scripts via a server.

But there is no option for that. So just wondering what would be the best option for `Workbox` and `updateViaCache`.

p.s. I'm using a `Cache-Control: max-age=0, private, must-revalidate` for Workbox.

**Comment by jeffposnick** [comment]
Workbox takes care to include versioning information in the URLs for its runtime libraries, which get pulled in via `importScripts()`.

We include version numbers in both the CDN URLs, and when using our tools to create a local copy of the same runtime libraries, we place them all under a `workbox-vX.Y.Z` directory, which will presumably be part of the URLs you use on your own server.

The expectation, since these URLs are properly versioned, is that after they're downloaded once, there should be no need to download them again, since they won't change.

On the other hand, the top-level service worker that Workbox generates will include precache revisioning info, but always has the same URL (usually `/service-worker.js`, depending on what you choose for `swDest`). So this URL always should be checked for updates from the network to ensure your precached assets are kept up to date.

The ideal scenario (honor the browser cache for `importScripts()`, ignore the browser cache for `/service-worker.js`) is the new default fore Chrome 68 and later, and is also the default for Safari, Edge, and recent versions of Firefox.

As mentioned in that post you link to, it's still a good idea to serve `/service-worker.js` with `Cache-Control: max-age=0` to account for the fact that older Chromium-based browsers won't have the new behavior, but it's not strictly necessary for new browsers.

**Comment by ayumihamsaki** [comment]
@jeffposnick Thank you for your explanation.
