### ISSUE TITLE
Hard to read doc's on a tablet or other mobile devices

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#1526]
Very hard to read the doc's on an ipad there is oversized whitespace either side and the text column squeezed up, see two screenshots:

![35077829_224011064870305_490304468554874880_n](https://user-images.githubusercontent.com/17784082/41283152-c272bb84-6e2d-11e8-8189-88c3a3241a4c.jpg)

![35147107_224011078203637_2294402131165184000_n](https://user-images.githubusercontent.com/17784082/41283153-c2928e5a-6e2d-11e8-80ea-5f802994fe3e.jpg)

Request to remove the huge whitespace columns either side and fill up the whole space to make reading easier.

**Comment by jeffposnick** [comment]
I just tried things out on an (emulated) 12.9" iPad, and layout appeared okay. What specific device are you using? And are you just seeing the issue with the Reference Docs pages (i.e. the pages that are auto-generated from our JSDoc info)?

<img width="948" alt="untitled" src="https://user-images.githubusercontent.com/1749548/41299348-3fd9e3b0-6e31-11e8-8f43-cf231a99d209.png">

**Comment by ayumihamsaki** [comment]
@jeffposnick I was using an ipad 2 and a Safari browser running Version 9.3.5 IOS. I just released that is not whitespace - the whole menu is missing!

I can't repeat the error on an emulated device either but on the real device, the ipad, is displaying the error ever time. Sorry to pass on bad news.

**Comment by jeffposnick** [comment]
I think what's happening is that we have an old version of the docs live at URLs which contain `/prerelease/` instead of `/latest/`, e.g.  https://developers.google.com/web/tools/workbox/reference-docs/prerelease/workbox.strategies.StaleWhileRevalidate

That old version doesn't have proper formatting, but does show up in Google search results.

I'm going to update the underlying site structure to remove the old docs and just have `/prerelease/` redirect to `/latest/`. (We'll keep the explicitly versioned doc URLs for those who need them.)
