### ISSUE TITLE
Add ability to exclude some modules from local build

### ISSUE THREAD

**Issue by fresk-nc** [GoogleChrome/workbox#1527]
I use workbox-webpack-plugin with option `importWorkboxFrom: local` and I want to exclude modules that I don't use, for example `workbox.googleAnalytics`.

**Comment by jeffposnick** [comment]
There's no runtime cost incurred by having a local copy of `workbox.googleAnalytics` saved in your output directory, since it will never be loaded via `importScripts()` by `workbox-sw` if you're not using it.

The upside of automatically copying everything over is that if you *do* decide to start using additional functionality, you don't have to remember to opt-in to including the dependency libraries as part of your build.

If you're concerned about something like the cost of storing the actual, unused bytes on your web hosting server, then I think something like https://www.npmjs.com/package/webpack-cleanup-plugin could be dropped in to your build to remove files that you're really sure you won't use.

Alternatively, if you want more control over exactly which Workbox code you deploy, you could create your own bundle by consuming Workbox's ES2015 module exports, and then use `importWorkboxFrom: <your-workbox-chunk-name>`.

Given all that, my inclination is to keep `importWorkboxFrom: local` as-is. If there's an argument for changing the behavior that I'm overlooking, please let us know and we can reconsider.

**Comment by fresk-nc** [comment]
Okay,  `importWorkboxFrom: <your-workbox-chunk-name>` is better for me. Let's close this issue.
