### ISSUE TITLE
Question - default handler / strategy for workbox-webpack-plugin

### ISSUE THREAD

**Issue by ethan-ho** [GoogleChrome/workbox#1540]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
N/A

**Issue or Feature Request Description**:
There is a runtimeCaching option in GenerateSW plugin from workbox webpack module, but the doc itself doesn't tell which handler / strategy will be adopted if none provided.

Also, if I passed a runtimeCaching to match again JS assets with a strategy, e.g. networkFirst strategy for *\*.js* files, which strategy will be used for those requests aren't matching my runtimeCaching?

Thank you!

**Comment by ethan-ho** [comment]
@jeffposnick thank you for clarification, I realized my question is more about precaching handling.
If the request is precached, are they always serving from cache first?

**Comment by jeffposnick** [comment]
If you're using [`workbox.precaching.precacheAndRoute()`](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.precaching#.precacheAndRoute) within your service worker (which is what `GenerateSW` will put into the service worker it creates) then all requests for URLs which Workbox believes it can fulfill via a precached asset will be served cache-first.

There is some logic in place to automatically fall back to the network if, due to unforeseen circumstances, the cached entry was deleted, but that's an exception rather than the expected behavior.
