### ISSUE TITLE
Link to workbox.setConfig() docs after copyLibraries finishes

### ISSUE THREAD

**Issue by schorfES** [GoogleChrome/workbox#1541]
**Library Affected**:
workbox-build, workbox-cli

**Browser & Platform**:
CLI

**Versions**:

* workbox-sw@3.2.0
* workbox-cli@3.3.0
* workbox-build@3.3.0

**Issue or Feature Request Description**:
When using the workbox-cli with *copyLibraries* mode, all workbox files (*.dev.js and *.prod.js) are copied as expected into the given directory. But when import the _workbox-sw.js_ from that directory into the serviceworker, all dependencies like _workbox-core_, _workbox-strategies_ etc. are imported using the _storage.googleapis.com_ CDN. The reason is that the _workbox-sw.js_ contains this line: `const t="https://storage.googleapis.com/workbox-cdn/releases/3.3.0"` with the value from the `WORKBOX_CDN_ROOT_URL` setting, which results in loading from an incorrect origin. Is there a way to overwrite the `WORKBOX_CDN_ROOT_URL` while copying the library files to a local directory? Otherwise using all library files hosted my own origin instead of using the CDN won't work correctly.

**Comment by jeffposnick** [comment]
Apologies as this isn't made clear by the current `workbox copyLibraries` workflow.

You need to make a call to workbox.setConfig({modulePathPrefix: 'path/to/local/workbox'}) at the very start of your service worker file, after importing your local `workbox-sw.js`, to ensure that all the other dependent libraries are loaded locally as well.

There are some docs on this at https://developers.google.com/web/tools/workbox/reference-docs/prerelease/workbox#.setConfig

I'll leave this issue open to track making a change to `workbox copyLibraries` so that we explicitly log something to the console about this, pointing them to the docs.

**Comment by schorfES** [comment]
Hi @jeffposnick,

thanks for your helpful response and I think a logging to the console would be great. Maybe there is also the possibility to use the given path or to pass an extra config file into the process to rewrite the `WORKBOX_CDN_ROOT_URL` in the future...?

**Comment by jeffposnick** [comment]
If you use the `generateSW` mode along with `importWorkboxFrom: 'local'`, or `InjectManifest` with the `worbox-webpack-plugin`, the resulting service worker will automatically include the proper call to `workbox.setConfig()` pointing to the local copies of the library.

We can't count on folks who are doing `workbox copyLibraries` using one of those build tools, though, so I think the best we can do is pointing them to the docs.
