### ISSUE TITLE
POST Request cache using webpack

### ISSUE THREAD

**Issue by jay-shah-rushiinfotech** [GoogleChrome/workbox#1547]
- I use laravel.mix to generate sw.js and other things.
- Can workbox cache ajax "POST" response for which no parameter have been passed ? yes, then HOW ?
- For example, "POST" Request to get datatable response can be cacheable ?
- Can I cache by filtering POST DATA passed to POST Request ?

**Comment by jeffposnick** [comment]
The underling Cache Storage API [doesn't support](https://w3c.github.io/ServiceWorker/#cache-put) using `POST` requests as the key when storing a response. This is not a limitation specific to Workbox.

In general, since `POST` requests are meant to mutate server-side state, caching them locally and replaying the response tends not to be a great idea.

You can either write something by hand to process the incoming `POST` request and convert it into a `GET` prior to storing it, or, better yet, work with the API you're using to ensure that they also support `GET` requests.

**Comment by jeffposnick** [comment]
[`workbox-background-sync`](https://developers.google.com/web/tools/workbox/modules/workbox-background-sync) is a generic solution if you want to retry `POST` requests that fail due to network connectivity.

If you want to intercept `POST` requests and do something else with them, then one approach would be to do something like:

```js
workbox.routing.registerRoute(
  /api/, // Change to match your endpoint URL.
  async ({event, url}) => {
    // See https://developers.google.com/web/tools/workbox/guides/route-requests#handling_a_route_with_a_custom_callback
    // Do something here. What it is up to you.
    // Eventually, return a Response object, or else your request will fail.
    return response;
  },
  'POST' // Opt-in to matching POST requests. Only GET is matched by default.
);
```

**Comment by mihanizm56** [comment]
https://www.jsonrpc.org/
we actually can simply fetch data using POST method according to standard
 
> The underling Cache Storage API [doesn't support](https://w3c.github.io/ServiceWorker/#cache-put) using `POST` requests as the key when storing a response. This is not a limitation specific to Workbox.
> 
> In general, since `POST` requests are meant to mutate server-side state, caching them locally and replaying the response tends not to be a great idea.
> 
> You can either write something by hand to process the incoming `POST` request and convert it into a `GET` prior to storing it, or, better yet, work with the API you're using to ensure that they also support `GET` requests.
