### ISSUE TITLE
networkFirst and networkOnly behave inconsistently when extending

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/workbox#1551]
**Library Affected**:
workbox-sw

**Browser & Platform**:
Google Chrome v67

**Issue or Feature Request Description**:

I'm not sure if I'm doing it right, but when I try to extend a workbox strategy, networkFirst and networkOnly behave inconsistently. E.g.:

```
const customHandler = workbox.strategies.networkOnly();
// const customHandler = workbox.strategies.networkOnly();

function fallbackStrategy({event, url}) {
  return customHandler.handle({event})
    .then((response) => {
      return response || new Response('This gets called if networkFirst, no response in cache and offline');
    })
    .catch(() => {
      return new Response('This gets called if networkOnly, no response in cache and offline');
    })
}
workbox.routing.registerRoute(
  'my-route',
  fallbackStrategy
);
```

With NetworkFirst, if no network nor cache, I get an empty response in "then". With NetworkOnly, I get an error and handle it in catch. 

Is it intentional?

**Comment by jeffposnick** [comment]
Hey @devnook!

It's sort-of intentional. Mostly a side effect of how the two strategies differ.

`networkFirst` does not end up throwing in that scenario because the underlying network exception triggers a `cache.match()` lookup, and `cache.match()` doesn't throw/`reject` when there's a cache miss. Instead, it resolves with `undefined`. That resolution is used as the final resolution of the strategy.

I could see the argument both ways for propagating the initial network exception vs. resolving with `undefined` in `networkFirst`. Given that we have an established behavior that other folks might be relying on, it's definitely not something we'd change outside of a major semver bump.

That being said, if it's preventing you from doing something that you're trying to do, we'd like to help. What's the underlying behavior that you're trying to achieve? Is it something we could address by [expanding the section of our docs](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#provide_a_fallback_response_to_a_route) that covers providing a fallback response when a strategy fails, showing how to properly handle fallbacks for more types of strategies?

**Comment by sorendam** [comment]
Hi @jeffposnick

It is not really clear in the documentation where you [provide a fallback response to a route](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#provide_a_fallback_response_to_a_route) that networkFirst doesn't throw a reject. You could maybe add it to this so it reads something like this:
```
const FALLBACK_IMAGE_URL = '/images/fallback.png';
const imagesHandler = workbox.strategies.networkFirst();
workbox.routing.registerRoute(new RegExp('/images/'), ({event}) => {
        return imagesHandler.handle({event})
            .then((response) => {
                return response || caches.match(FALLBACK_IMAGE_URL);
            })
            .catch(() => caches.match(FALLBACK_IMAGE_URL));
    }); 
```

**Comment by jeffposnick** [comment]
I'd like to get this change in for v4.

My thought is that the most useful behavior to standardize on would be to have all of the built-in `workbox-strategies` throw an instance of a specific `Error` subclass when they are unable to provide a valid `Response` object. That should make it much easier to provide fallback content in a standardized, global manner via `workbox.routing.registerCatchHandler()`, or alternatively, via a `.catch()` attached to a specific strategy instance.

**Comment by jeffposnick** [comment]
Using `workbox-build@alpha` on `npm` should pick up our 4.0.0 alpha releases now, which contain a fix.

Feel free to [read the release notes](https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0-alpha.0) and confirm that it's working for you now.
