### ISSUE TITLE
Support for a new additionalManifestEntries build tool option

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/workbox#1571]
**Library Affected**:
workbox-build

**Browser & Platform**:
Node JS

**Issue or Feature Request Description**:
I might be the only customer for this, but I'd love it if I could provide my own set of ManifestEntries to `injectManifest` (or an equivlent function) so that I don't have to munge files to do what injectManifest does.

My use-case is that I have a product that has a pre-defined set of files in one directory, and they can be overriden by the user of the product in another. I need to create a manifest that contains the union of both directories and overwriting the configuration with the developer defined files taking precedence.

`/node_modules/topicdeck/dist/server/public` < everything in the package
`/public/` < files that the user has defined that take precedence over shipped files. 
 
Example of gymnastics I have to do: https://github.com/PaulKinlan/webgde-deck/blob/master/tools/producemanifest.js < I have to `getManifest()` for both directories, merge them (which is fine, I don't expect workbox to do this bit), and then I have to do the work of injectManifest manually (i.e, find the place to replace contents).  It feels like as a developer getManifest is interesting, but I can't do much with the data ;)

**Comment by jeffposnick** [comment]
Hey @PaulKinlan!

So the relevant code in the current `injectManifest` implementation is https://github.com/GoogleChrome/workbox/blob/d95348b930cce11c400e236adf3ca5c0727d9815/packages/workbox-build/src/entry-points/inject-manifest.js#L57-L58

It sounds like what you're proposing is to allow developers to pass in an additional option when calling `injectManifest`, called `manifestEntries`, and if that was set, to skip the step that calls `getFileManifestEntries()` and instead just use what we're passed. The rest of the code could stay the same.

It would look something like:

```js
let effectiveManifestEntries;
if (options.manifestEntries) {
  effectiveManifestEntries = options.manifestEntries;
} else {
  const {count, size, manifestEntries, warnings} = await getFileManifestEntries(options);
  effectiveManifestEntries = manifestEntries;
}

// Use effectiveManifestEntries later on in the replacement.
```

And then we'd need to add in some validation to throw an error if you try to set the `manifestEntries` option while also specifying the various `glob` options, since those won't end up being used.

Does that sound about right?

**Comment by jeffposnick** [comment]
I'm going to repurpose this as a proposal for a new build tool option supported in both `injectManifest` and `generateSW` called `additionalManifestEntries`, which takes in an array of [precache manifest entries](https://developers.google.com/web/tools/workbox/modules/workbox-precaching#explanation_of_the_precache_list).

The additional entries will be compared to the URLs found in the list of manifest entries that the build tool generates, and if there's a duplicate, it will be treated as a fatal error.

I could imagine folks finding this useful for precaching a list of known URLs from a CDN, or for the scenario that @PaulKinlan describes upthread.

My main concern is that this makes it easier than ever to end up precaching an unrevisioned URL in a way that will lead to it never getting updated; i.e. you could imagine a developer naively passing in:

```
additionalManifestEntries: [
  'https://example.org/api',
],
```

in order to populate the cache with the result of that API call in advance, but due to the way precaching works, that cached entry will never end up updated once cached.

The "safe" usage would be to pass in versioned URLs, or manifest entries that contain out-of-band revision info, like:

```
additionalManifestEntries: [
  'https://example.org/path/to/v1.0.0/app.js',
  {url: 'some-page.html', revision: '<hash-of-file>'}
],
```

`additionalManifestEntries` is not the only way that developers can shoot themselves in the foot like this, and I think the benefits outweigh the potential downside in this case. We might want to get more aggressive about logging when we see a potentially unversioned URL in a manifest in the `development` builds, though.
