### ISSUE TITLE
Workbox Wizard breaks

### ISSUE THREAD

**Issue by damianwojcik** [GoogleChrome/workbox#1574]
**Library Affected**:
workbox-cli

**Browser & Platform**:
Windows, Node 

**Issue**:
`workbox wizard` breaks at the 3rd prompt  > Where would you like your service worker file to be saved?

![code_2018-07-12_16-29-16](https://user-images.githubusercontent.com/18085193/42639634-c3115444-85f0-11e8-9709-209c8ca4fe6a.jpg)

**Comment by kryptonian41** [comment]
yupp m facing the same bug

**Comment by jeffposnick** [comment]
Apologies that you both are running into this.

I tried to reproduce and I was not able to. I'm using PowerShell with node v8.11.3 installed, and the latest `workbox-cli` v3.4.1. Are you using those versions, or perhaps an older version?

Also, can you reproduce it if you try running the wizard in a different directory?

**Comment by jeffposnick** [comment]
Okay, so this is pretty strange.

I've installed `node` v10.9.0 and have been able to reproduce some of the freezing when using PowerShell and the Node.js command prompt on Windows (I'm testing on a Windows Server installation, actually).

I can't reproduce the issue when using the Git Bash shell on Windows, so I think this is particular to shells that use Windows-style paths.

What seems to help is changing a few instances of asynchronous calls to their synchronous version. This gets a bit tricky, since the original source is transpiled with the [regenerator runtime](https://www.npmjs.com/package/regenerator-runtime), to ensure that we support `node` v6.

https://github.com/GoogleChrome/workbox/blob/ea88b6819c628f9fa726a0daf10999f8afa9610e/packages/workbox-cli/src/lib/questions/ask-root-of-web-app.js#L85

is an example of one spot that causes hangs, and it progresses past that if I change the code locally to `fse.statSync()`.

I'm going to debug more, and thanks for everyone's patience.

**Comment by jeffposnick** [comment]
Quick update—bumping the dependency versions for the various libraries used by `workbox-cli` seems to fix it in my local testing. I'll file a PR, and this should make it into the next minor release.

**Comment by yashints** [comment]
@jeffposnick  Any news on this? Facing the same issue and I see the PR is pending.
BTW: when I use Git Bash the wizard works fine, but the menu selection on it is horrible 😢

**Comment by jeffposnick** [comment]
Using `workbox-cli@alpha` on `npm` should pick up our 4.0.0 alpha releases now, which contain a fix.

Feel free to [read the release notes](https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0-alpha.0) and confirm that it's working for you know.

**Comment by rhroyston** [comment]
Neither of these fixed the issue for me. I'm using Cloud9 IDE - so it should be a linux environment that is running the package. I am using a Win10 machine running new Chrome browser to access Cloud9...?

```
npm install workbox-cli@4.0.0-beta.0 --global
npm install workbox-cli@4.0.0-alpha.0 --global
```

**Comment by seangwright** [comment]
I'm using
- Gitbash 2.19.1.windows.1
- Windows 10
- node v10.9.0

I experienced the same issue listed by the OP but switching to `4.0.0-beta.0` of workbox-cli fixed everything.
