### ISSUE TITLE
Add Master (latest) version to CDN

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/workbox#1604]
Over time life has got easier and better with this project and we now can load the files directly from Google CDN, see example:

`importScripts('https://storage.googleapis.com/workbox-cdn/releases/3.4.1/workbox-sw.js');`

However, this is a bit of a pain to keep checking and updating the version number - due to these Googler's working too hard and keep updating this project!

In Laravel they use a 'master' for the latest verision in their doc's. I would like to ask the Team to create a master version that is always the latest version and therefore doesn't need the developer to check and update the code. Of course we would fully understand that this may cause minor bugs, but accept any risk.

For example:

Master - Latest (Current) Version
v3.4.1
v3.3.1
v3.3.0

etc.

So all I need to do is add this to my service worker:

`importScripts('https://storage.googleapis.com/workbox-cdn/releases/master/workbox-sw.js');`

Thanks.

**Comment by jeffposnick** [comment]
What you describe is slightly problematic from the point of view of being able to ship breaking changes, and goes against the general best-practices related to [semantic versioning](https://semver.org/) that we try to follow.

But... even if you wanted to opt-out of semver and attempt to always pull in the `master` release, it's not something that's possible due to the way caching of imported scripts works. As of right now, Chrome (and potentially other browsers) [never checks](https://bugs.chromium.org/p/chromium/issues/detail?id=648295) for an update to a given script after its been imported during the initial execution of a given version of a service worker.

So `https://storage.googleapis.com/workbox-cdn/releases/master/workbox-sw.js` and all the files that get pulled in alongside it would get imported once, and continue to be reused indefinitely for a given version of the service worker, without any checks being made to see if `https://storage.googleapis.com/workbox-cdn/releases/master/workbox-sw.js` has been updated. Your users would end up being locked in to a given Workbox version, and you wouldn't really know *which* version each user was locked into, which is really the opposite of the frequent updates you're asking for.

**Comment by ayumihamsaki** [comment]
Thanks @jeffposnick  I wasn't aware of Semantic Versioning interesting read. That explains CDN's like cdnjs doing this issue as well.
