### ISSUE TITLE
Enable use of runtimeCaching in InjectManifest mode

### ISSUE THREAD

**Issue by RehanSaeed** [GoogleChrome/workbox#1614]
**Issue or Feature Request Description**:

I only want `InjectManifest` to add a web push ability. It would be very useful if I could use the `runtimeCaching` option with `InjectManifest`. This would also make switching from `GenerateSW` mode to `InjectManifest` easier.

One workaround I can use is to enable `GenerateSW` with `runtimeCaching` once and then copy and paste the code into a `service-worker.js` file. However, now I have to maintain code when it could be generated for me.

**Comment by jeffposnick** [comment]
Please see https://github.com/GoogleChrome/workbox/issues/708#issuecomment-415846786

If you're not content with running `GenerateSW` once, you can just put your `push` handler code into a separate `.js` file and reference it in `importScripts`.

**Comment by jeffposnick** [comment]
It's not on the roadmap. Better compilation/transpilation of the service worker when using webpack is on the radar, though: https://github.com/GoogleChrome/workbox/issues/1513

**Comment by YaoKaiLun** [comment]
> Please see [#708 (comment)](https://github.com/GoogleChrome/workbox/issues/708#issuecomment-415846786)
> 
> If you're not content with running `GenerateSW` once, you can just put your `push` handler code into a separate `.js` file and reference it in `importScripts`.

But the separate `.js` is hard to be managed by webpack especially when you want to hash its filename.

**Comment by cansin** [comment]
~~I would like to re-raise this issue. Using a separate .js through importScripts requires additional build steps in order to import necessary code (If I am not missing sth). And trying to use the generated code by `GenerateSW` is not feasible given hashed filenames. (I am also having a problem with `matchPrecache` not able to match precached routes by GenerateSW on my separate importScripts'ed script, but that might be on my part.)~~

I am dumb nevermind. I think I don't need to worry about hashes on what I am trying to do.
