### ISSUE TITLE
workbox-range-requests & failed cache.put()s of HTTP 206 responses

### ISSUE THREAD

**Issue by conzett** [GoogleChrome/workbox#1644]
**Library Affected**:
*workbox.rangeRequests*

**Browser & Platform**:
*Google Chrome v69*

**Issue or Feature Request Description**:
Using the new workbox.rangeRequests plugin with a cache first strategy we still seem to be running into the `TypeError: Partial response (status code 206) is unsupported` exception.

```javascript
importScripts('https://storage.googleapis.com/workbox-cdn/releases/3.5.0/workbox-sw.js'); 

workbox.setConfig({ debug: true });
workbox.skipWaiting();             
workbox.clientsClaim();            

workbox.routing.registerRoute(                   
  /\/active_storage\//,                          
  workbox.strategies.cacheFirst({                
    cacheName: 'active-storage-cache',       
    plugins: [new workbox.rangeRequests.Plugin()]
  })                                             
);
```

The Workbox debug log shows the following:

```
workbox Using CacheFirst to respond to '/rails/active_storage/blobs/sha/video.mp4'
workbox-core.dev.js:132 workbox No response found in the 'active-storage-cache' cache. Will respond with a network request.
workbox-core.dev.js:132 workbox Got response from network.
workbox-core.dev.js:132 workbox View the final response here.
workbox-core.dev.js:127 
Response {type: "cors", url: "https://redacted.amazonaws...", redirected: true, status: 206, ok: true, …}
body: (...)
bodyUsed: true
headers: Headers {}
ok: true
redirected: true
status: 206
statusText: "Partial Content"
type: "cors"
url: "https://redated.amazonaws.com/sha/video.mp4"
```

**Comment by jeffposnick** [comment]
Can you provide some additional info about what code is throwing the `TypeError: Partial response (status code 206) is unsupported` exception? Is there a stack trace associated with it?

I don't see an error string originating from Workbox that matches that pattern, so I'm curious as to whether it's something that's reading (what might be a valid partial `Response` object created by Workbox) that's unhappy.

**Comment by conzett** [comment]
Screenshot of the stack-trace from the chrome dev tools, not very long:

<img width="891" alt="screen shot 2018-09-18 at 12 31 27 pm" src="https://user-images.githubusercontent.com/142183/45702056-ce66a500-bb3e-11e8-9655-c1bb761104a2.png">

The request is originating from a video element:

```html
<video crossorigin="anonymous" autoplay loop src="(url)"></video>
```

Thanks for taking a look!

**Comment by jeffposnick** [comment]
Thanks for the additional info!

The error turns out to be triggered by the browser whenever you try to do a `cache.put()` using a `Response` object with a status of `206`. I guess that does make sense from the context of the Cache Storage API—you need a complete response, not a partial one, to be stored in the cache in order to be useful later on.

In terms of what you're trying to do, I don't believe you have any control over whether the initial `Response` used to populate that cache is going to be a `206` or a full `200`. I'm going to leave this open to think about what we could do to make this less of a gotcha. One possibility would be to hook into Workbox's cache management lifecycle callbacks and fire off a separate request to download the full resource when trying to populate the cache—perhaps making that an opt-in behavior.

I think the way most folks have ended up using `workbox.rangeRequests.Plugin` up until now is to explicitly precache a media asset ahead of time, which ensures that it's the full `200` response that's read from. In that scenario, the cache-first strategy effectively behaves like a cache-only. I understand that it would be nice to have the flexibility of using runtime caching with this approach, though.

**Comment by conzett** [comment]
> I guess that does make sense from the context of the Cache Storage API—you need a complete response, not a partial one, to be stored in the cache in order to be useful later on.

Good call, that makes total sense.

> In terms of what you're trying to do, I don't believe you have any control over whether the initial Response used to populate that cache is going to be a 206 or a full 200. I'm going to leave this open to think about what we could do to make this less of a gotcha. 

This seems to be the case when using the video element. Chrome will always send the request with a `Range` header and that will cause the server (in this case S3) to respond with the `206`.

> explicitly precache a media asset ahead of time, which ensures that it's the full 200 response that's read from. In that scenario, the cache-first strategy effectively behaves like a cache-only.

This is pretty much what we ended up doing as a work-around for the time being. Although we aren't able to precache the media as the URL is dynamic (albeit long-lived), we are able to fire off a basic `fetch` request for the mp4 prior to the video loading. This will be sent without the `Range` header and result in S3 sending the entire response and a 200. The video element will then be able to use the warm cache.

Thanks again for your help!

**Comment by jeffposnick** [comment]
I'm closing this in favor of #1804 (to address the default checks for cacheability) and #1663 (to discuss the "recipe" for dealing with video files across various browsers).

**Comment by Ajaxy** [comment]
> I guess that does make sense from the context of the Cache Storage API—you need a complete response, not a partial one, to be stored in the cache in order to be useful later on.

Why? Browsers will likely request the same ranges next time for the same media. And if a user just started watching a video and left, he could come back later and continue from the same point.

**Comment by micahjon** [comment]
I've run into this error in cases where the 206 response actually contains the full file (probably more relevant to audio files than video files due to size, but I guess it's ultimately up to the backend implementation), e.g.

```py
Content-Length: 43081890
Content-Range: bytes 0-43081889/43081890
```

You can write a [plugin](https://developer.chrome.com/docs/workbox/using-plugins/#methods-for-custom-plugins) to detect whether a 206 contains the full response and cache it as a 200 if it does.

```ts
// In plugin...
cacheWillUpdate: async ({ response }) => {
  if (response.status === 200) return response;

  // Content encoding shouldn't be set, or content-type will be inaccurate
  if (response.status === 206 && !response.headers.get('content-encoding')) {
    const contentLength = parseInt(response.headers.get('content-length'));
    if (
      `bytes 0-${contentLength - 1}/${contentLength}` ===
      response.headers.get('content-range')
    ) {
      // Convert response from 206 -> 200 to make it cacheable
      return new Response(response.body, { status: 200, headers: response.headers });
    }
  }

  return null;
}
```

Keep in mind that for cross-origin requests, that the server will need to expose the `content-range` header by setting `Access-Control-Expose-Headers: content-range` or the service worker won't be able to read it.

I suppose it'd also be possible to cache 206 partial responses in a separate cache, and then upon getting a final response, stitch them all together, but I haven't explored that at this point.

**Comment by jeffposnick** [comment]
Thanks for sharing that, @micahjon! It's definitely been our intention with the plugin system to allow folks to customize these behaviors to suit the specific serving infrastructure that they use.
