### ISSUE TITLE
why we have a temp cache in cache list?

### ISSUE THREAD

**Issue by lynnic26** [GoogleChrome/workbox#1687]
**Library Affected**:
*workbox*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
It will always contains a **temp** cache in cache list
I don't know what does it mean 
![image](https://user-images.githubusercontent.com/7609558/46580355-b5725500-ca55-11e8-946c-84dd440809a6.png)

**Comment by philipwalton** [comment]
`workbox-precaching` creates a temporary cache during the [install](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#install) phase of the service worker lifecycle, and then it clears it out and moves the cached assets to the regular precache cache during the [activate](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#activate) phase.

It does this to account for situations where you've deployed a new version of your service worker to your site, and some users may be running the new version in one tab and the old version in another tab. In order to have assets for *both* versions of the precache manifest cached at the same time, a temp cache is used.

I did a search through our `workbox-precaching` documentation and didn't see any mention of this temp cache, so we should definitely add something. I'll keep this issue open to track that.

**Comment by jadjoubran** [comment]
Related to #1735

**Comment by jeffposnick** [comment]
Right—The `-temp` cache shouldn't be (as) noticeable once #1736 is in place, so I'm closing this issue.

**Comment by jeffposnick** [comment]
Workbox v4 doesn't use `-temp` caches anymore.
