### ISSUE TITLE
cdnjs hosting

### ISSUE THREAD

**Issue by sashberd** [GoogleChrome/workbox#1723]
Hi,

As you already know we would like to host your lib on cdnjs. 
There are [some questions](https://github.com/cdnjs/cdnjs/pull/12619/files/92815e4739e4e7697cb07b2a47ddb9916581b471#r183958110) that we would like to get answers from you
Could you help us with them? 
Thanks

**Comment by jeffposnick** [comment]
Due to the way the Workbox service worker libraries are loaded, with `workbox-sw` being referenced via `importScripts()`, which in turn will (by default) load in all the other dependencies via the Google Storage CDN URL, I don't think this is going to work out as intended just by ingesting Workbox's packages.

You'd need to instruct all users to follow [this method](https://developers.google.com/web/tools/workbox/modules/workbox-sw#using_local_workbox_files_instead_of_cdn) of loading the dependencies via an alternate URL, or alternatively, hardcode a different default URL in a custom `workbox-sw` bundle.
