### ISSUE TITLE
Workbox Routing and Caching and service worker registration?

### ISSUE THREAD

**Issue by tatasaikumar** [GoogleChrome/workbox#1725]
(This issue was moved over from 
https://stackoverflow.com/questions/52620240/workbox-routing-caching-deletion-updation-and-service-worker-registration)

**Library Affected**:
*workbox-sw, workbox-build, workbox-webpack-plugin etc.*

**Issue or Feature Request Description**:
My Configuration goes like this
 new workboxPlugin.InjectManifest({
      swSrc: `public/sw.js`,
      swDest: './sw.js',
      exclude: [/\.jpg$/, /\.png$/,/\.js$/,/\.css$/,/\.gz$/,/\.svg$/,/\.jpeg$/,/\.html$/
                ,/\.json$/,/\.map$/,/\.gif$/]
    })
As I don't want any precache files, as I register my service simultaneously not on dom load.
And In my service worker file I have registered route like this
 workbox.routing.registerRoute(
    /\.(?:js|css|gzip|html|svg|gif)$/,
    workbox.strategies.cacheFirst(),
  ); 
 So all js,css mentioned files will be cached from this route.

![multiple js files1](https://user-images.githubusercontent.com/6897086/47293865-032bb780-d629-11e8-94ad-f3b4cb5ae8c7.jpeg)

**Comment by jeffposnick** [comment]
If you don't plan on precaching anything, you don't need to use the build tools, like `workbox-webpack-plugin`. You can just write your own service worker file that imports Workbox and sets up your runtime caching route, like https://developers.google.com/web/tools/workbox/guides/get-started#importing_workbox

Since you're using a mix of versioned (with hashes) and unversioned URLs, I'd recommend using two different runtime caching routes.

One should be a regular expression that detects URLs with hashes in them, and uses a cache-first strategy, along with cache expiration (depending on how many different responses you want to keep in the cache at a given time). The other route should match URLs without hashes in them, and use something like a stale-while-revalidate (or network-first) strategy to ensure that you get updates. You could also use cache expiration here.

The final service worker file might look something like:

```js
importScripts('https://storage.googleapis.com/workbox-cdn/releases/3.6.3/workbox-sw.js');

workbox.routing.registerRoute(
  new RegExp('\\.[a-f0-9]{8}\\.'),
  workbox.strategies.cacheFirst({
    cacheName: 'versioned-assets',
    plugins: [
      new workbox.expiration.Plugin({
        maxEntries: 50,
        purgeOnQuotaError: true,
      }),
    ],
  })
);

workbox.routing.registerRoute(
  new RegExp('\\.(?:gif|svg|jpg)'),
  workbox.strategies.staleWhileRevalidate({
    cacheName: 'unversioned-assets',
    plugins: [
      new workbox.expiration.Plugin({
        maxEntries: 50,
        purgeOnQuotaError: true,
      }),
    ],
  })
);
```
