### ISSUE TITLE
waitUntil function throwing error in Firefox

### ISSUE THREAD

**Issue by Sturgelose** [GoogleChrome/workbox#1758]
Welcome! Please use this template for reporting bugs or requesting features. For questions about using Workbox, the best place to ask is Stack Overflow, tagged with `[workbox]`: https://stackoverflow.com/questions/ask?tags=workbox

**Library Affected**:
workbox-precaching

**Browser & Platform**:
Works in:
* Chrome 70.0 in MacOS
* Safari 12.0

Fails in:
* Firefox 63.0.1 (64-bit) in MacOS
* Firefox Developer Edition (latest actual version)  in MacOS

**Issue or Feature Request Description**:
When registering a service worker in Firefox, it fails with error `InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable`.

It seems to fail in line 1018 in workbox-precaching.dev.js, in the waitUntil method:
```
self.addEventListener('activate', event => {
      event.waitUntil(precacheController.activate({
        event,
        plugins
      }));
    });
```

I thought that the issue would be the local testing env, but in a production ready system with https and everything setup fails in the same place.

Seems to be some kind of different logic with the waitUntil function in Firefox. I also tried to do some research on this kind of issue but I haven't been able to find anything.

I was able to reproduce with just these lines of code (even though my real logic is a bit more complex):
```
self.addEventListener('activate', event => {
  const test = async () => {
    return true;
  }
  event.waitUntil(test());
});
```

Also, I thought it could had been related to the piece of code I added in my service worker to handle updates, and some other custom logic, but I commented it out and seems to keep on failing just with the previous lines. However, it runs in all browsers but Firefox for some reason... I'm not sure though if this is an error in Firefox or it's just in workbox.

My guess is that there is a conflict is triggering the waitUntil in different parts of the code at the same time (though not sure).

Note that this code is inspired in the example given by Mozilla in their documentation about the waitUntil function: https://developer.mozilla.org/en-US/docs/Web/API/ExtendableEvent/waitUntil

Also, this bug can be reproduced in https://dashboardv2.bitphy.es (in this public reproduction, note that there is some extra code, but, I was able to reproduce it just with the lines given before)

**Comment by jeffposnick** [comment]
Apologies that you're running into this issue.

I can reproduce it when visiting https://dashboardv2.bitphy.es using the current Firefox Nightly 65.0a1, but I have not been able to reproduce the same error when visiting other web apps that also use Workbox's precaching (e.g. https://so-pwa.firebaseapp.com, https://jeffy.info).

I also have not been able to reproduce the issue when using your simple reproduction steps:

```js 
self.addEventListener('activate', event => {
  const test = async () => {
    return true;
  }
  event.waitUntil(test());
});
```

(Deployed live at https://glamorous-snowflake.glitch.me/)

So... I understand that the issue is real, but it is not clear that is a widespread issue, vs.  a smaller issue in Firefox due to something particular about your service worker's logic.

I really do want to get as close to a simplified reproduction step as possible, and I'm curious whether you can modify your initial reproduction example by "remix"ing https://glitch.com/edit/#!/glamorous-snowflake?path=public/sw.js:6:3 and get something that exhibits the error deployed.

**Comment by jeffposnick** [comment]
I'm closing this given the lack of updates.

If this remains a problem for you, could you please follow the suggestions mentioned in the previous response and let us know?
