### ISSUE TITLE
Workbox documentation: bgsync - Let users know how the sync process works

### ISSUE THREAD

**Issue by andrralv** [GoogleChrome/workbox#1798]
Right now on this page: https://developers.google.com/web/tools/workbox/modules/workbox-background-sync it explains how to use the background sync helper from Workbox, but it tells the user to press the "Sync" button on the Chrome Dev Tools in order to force a sync and test if background sync is working. 

This works but it's very confusing as the developer never really knows when the sync automatically happens if you don't press the button. I assumed the browser synced as soon as the user regained connection, but it turns out (after exhaustive searching and finding this issue: https://github.com/GoogleChrome/workbox/issues/1249 and this blog post: https://golb.hplar.ch/2018/06/background-sync.html) that the browser first tries to sync after 5 minutes, then it does a second try after 15 minutes, and a third try (when ???) until it fails. It would be very helpful to have this information explained on the workbox documentation.

**Comment by jadjoubran** [comment]
Hey @andrralv 
The behavior you're describing is called `exponential backoff`
While it's not mentioned in the documentation page you linked to, it is mentioned in [Jake's post about background-sync](https://developers.google.com/web/updates/2015/12/background-sync).

Would you like to send a PR to add this piece of information to the docs? It's in a different repo and here's the file you need to edit: [workbox-background-sync](https://github.com/google/WebFundamentals/blob/master/src/content/en/tools/workbox/modules/workbox-background-sync.md)

**Comment by jadjoubran** [comment]
It's never really explained because I think it's assumed that people know it.. I couldn't find a place that explains it on the internet other than this [wikipedia page](https://en.wikipedia.org/wiki/Exponential_backoff)
I think it would be enough to at least mention that the delay is an exponential backoff, and if you feel like adding more info that would be cool

I personally know exponential backoff from telegram and other apps that try to reconnect when I lose internet connectivity

**Comment by jeffposnick** [comment]
I've added info about this to the Workbox v4 docs in https://github.com/google/WebFundamentals/commit/2e6915b571bd8390cc3c59b148036a77b502887e

Thanks for bringing it to our attention!
