### ISSUE TITLE
'useless-glob-pattern' should be a warning, not a fatal error

### ISSUE THREAD

**Issue by katywings** [GoogleChrome/workbox#1809]
**Library Affected**:
*workbox-webpack-plugin version 3.3.1

**Browser & Platform**:
*node version 10.13.0

**Issue or Feature Request Description**:
*Related issue: #1353 
*I am just wondering from a development side: Why is the glob handling at (globPatterns): https://github.com/GoogleChrome/workbox/blob/912080a1bf3255c61151ca3d0ebd0895aaf377e2/packages/workbox-build/src/lib/get-file-details.js#L45 so strict - is there some risk/danger involved with this option? In my project I had to add an extra glob filter step (https://github.com/witneyjs/witney/commit/34450b41e0078485ac05710a2e10d74f8529701d#diff-9f705cad1d5e127e633dda9ec3641b84R95) as a workaround, just to make sure, that workbox will not throw an error :D. 
If I was guessing, I think every developer using the globPatterns, has to add such a filter logic, because its the nature of globs that they might have an empty result which workbox doesn't accept ;). If there is a hidden reasoning behind this error, I recommend that the reason should be added to the error message, so that developers as I don't just add workarounds to their code :).

P.S. thanks for the awesome work on this project <3!

**Comment by jeffposnick** [comment]
Hello @katywings!

There's a balancing act between being overly aggressive with error condition checking vs. being less aggressive but potentially letting developers end up in a successful build that doesn't actually include the output they expect.

I still have trouble remembering the `glob` syntax and get things wrong all the time, so if there's a pattern in my config that doesn't match anything, I personally find it much more likely that I just got the syntax wrong when adding the pattern—making that a fatal error forces me to address that immediately, instead of "sweeping it under the rug." That's what motivated the original decision.

I can definitely see the other point of view, though. One thing that we have now which we didn't have during the earlier Workbox releases is the concept of non-fatal warning messages that the `workbox-build` tools can return. I'm open to switching that fatal error into a non-fatal warning instead. This runs the risk of folks ignoring the warning, but... like I said, it's a balancing act.

**Comment by katywings** [comment]
Hey @jeffposnick 

Thanks a lot for your openness and the details about the design decision. I absolutely can see your point with the different interest groups / balancing act. 👍 

I am happy that I can keep my workaround without needing to be worried about unknown risks 🍾 :D

**Comment by jeffposnick** [comment]
This is implemented in Workbox v5.
