### ISSUE TITLE
Chinese site

### ISSUE THREAD

**Issue by lecepin** [GoogleChrome/workbox#1810]
I want to write a Chinese document for workbox, how can I join the organization?

thanks~

**Comment by jeffposnick** [comment]
Hello! Thanks for your interest in contributing.

The (English) documentation for Workbox lives in https://github.com/google/WebFundamentals/tree/master/src/content/en/tools/workbox, and is hosted on https://developers.google.com/web/tools/workbox/

There's a process for contributing translated documentation for content that lives on developers.google.com: https://developers.google.com/web/resources/translations

I am not familiar with anyone previously attempting to translate Workbox's documentation, and I'm not 100% sure what the process is beyond what's outlined on that web page, but that would be the place to start.

If you're looking to write your own documentation from scratch rather than translating existing documentation, then I'd recommend just going for it, and hosting it on your own domain. If it's useful, we can help publicize the links to your documentation via our social media accounts.
