### ISSUE TITLE
Specified strategy will always not be used

### ISSUE THREAD

**Issue by lainazy** [GoogleChrome/workbox#1823]
**Library Affected**:
workbox-build (3.6.3)

A problem may have about that the order of workbox.routing.registerRoute and workbox.precaching.precacheAndRoute in sw-template.js file in workbox-build. now workbox.routing.registerRoute function is always called after workbox.precaching.precacheAndRoute, this cause my specified strategy will always not be used if matches precached url. Would you provide a property allowing us specify a url of customed sw-template.js file instead of the default sw-template.js.

```js
// default sw-template.js in workbox-build
...
<% if (Array.isArray(manifestEntries)) {%>
self.__precacheManifest = <%= JSON.stringify(manifestEntries, null, 2) %>.concat(self.__precacheManifest || []);
workbox.precaching.suppressWarnings();
workbox.precaching.precacheAndRoute(self.__precacheManifest, <%= precacheOptionsString %>);
<% } else { %>
if (Array.isArray(self.__precacheManifest)) {
  workbox.precaching.suppressWarnings();
  workbox.precaching.precacheAndRoute(self.__precacheManifest, <%= precacheOptionsString %>);
}
<% } %>
<% if (navigateFallback) { %>workbox.routing.registerNavigationRoute(<%= JSON.stringify(navigateFallback) %><% if (navigateFallbackWhitelist || navigateFallbackBlacklist) { %>, {
  <% if (navigateFallbackWhitelist) { %>whitelist: [<%= navigateFallbackWhitelist %>],<% } %>
  <% if (navigateFallbackBlacklist) { %>blacklist: [<%= navigateFallbackBlacklist %>],<% } %>
}<% } %>);<% } %>

<% if (runtimeCaching) { runtimeCaching.forEach(runtimeCachingString => {%><%= runtimeCachingString %><% });} %>
...
```

**Comment by jeffposnick** [comment]
This is deliberate.

If you want to use a strategy other than cache-first for those URLs, then you can exclude them from the precache manifest and [set up a route and runtime caching strategy](https://developers.google.com/web/tools/workbox/guides/route-requests#handling_a_route_with_a_workbox_strategy) to match those requests.

If you want to "warm" that runtime cache so that the URLs are available prior to the first time they're requested from your web app, you can [follow this recipe](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#warm_the_runtime_cache).

Longer term, we may allow developers to override the cache-first behavior of precached URLs, but that's difficult to do in a way that prevents inadvertently leading to cache inconsistencies. This is tracked at https://github.com/GoogleChrome/workbox/issues/1767, and I'm closing this issue in favor of that.
