### ISSUE TITLE
Single failed fetch during precache fails whole precaching.

### ISSUE THREAD

**Issue by troglotit** [GoogleChrome/workbox#1832]
**Library Affected**:
*workbox-sw, workbox-build*

**Browser & Platform**:
Version 71.0.3578.98 (Official Build) (64-bit)

**Issue or Feature Request Description**:
Single failed fetch during precache fails whole precaching. The question is: Is it by design? 

My uBlock blocked an asset called "googleAd.png", and although I can whitelist it, and also change the name of the asset, other users don't know about my assets, and uBlock can introduce new regexes which will block some of my assets. 

I use workbox-build in my gulpfile.

**Comment by jeffposnick** [comment]
That's intentional, and is unlikely to change. We need to guarantee cache consistency once a service worker has installed, and failing installation due to a network error is part of that.

(We've [gone further](https://github.com/GoogleChrome/workbox/pull/1716) in v4, and will fail installation by default when there's no network error, but a response has a non-`200` status.)

**Comment by troglotit** [comment]
Ohh, then assets would be inconsistent between each other. I got it. Thanks!
