### ISSUE TITLE
Workbox putting new items in temp and not removing old cache

### ISSUE THREAD

**Issue by mjgchase** [GoogleChrome/workbox#1853]
**Library Affected**:
"workbox-webpack-plugin": "^3.6.3"

**Browser & Platform**:
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

*See below screenshot of temp cache and original cache*

![image](https://user-images.githubusercontent.com/8114912/51502098-66fe8180-1dcc-11e9-97b8-c7e149ae1967.png)

![image](https://user-images.githubusercontent.com/8114912/51502113-7da4d880-1dcc-11e9-988b-de23bef3a624.png)

Seems temp contains the new cached files but after page refresh it still does not swap the cache, it only seems to apply after a restart of chrome, even then the temp cache remains but empty

**Webpack configuration**

```javascript
new workboxPlugin.GenerateSW({
        swDest: "sw.js",
        templatedUrls: {
          "/human-resources": productionVersion,
          "/": productionVersion,
          "/about-us": productionVersion,
          "/privacy-statement": productionVersion,
          "/web-development": productionVersion
        },
        runtimeCaching: [
          {
            urlPattern: new RegExp("^https://www.fonts.gstatic.com/"),
            handler: "staleWhileRevalidate",
            options: {
              cacheableResponse: {
                statuses: [0, 200]
              }
            }
          }
        ]
      })
```

**Comment by jeffposnick** [comment]
What you're seeing is expected, due to the service worker lifecycle—the new entries don't get moved over from the `temp` cache to the main cache until the new service worker activates (in Workbox v3, at least).

You can read more about this behavior at https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#activate_1. In general, activation will happen automatically once all open tabs that are controlled by the older service worker are closed.

You can accelerate activation by calling `skipWaiting()` from inside your service worker (add `skipWaiting: true` to your `GenerateSW` config). This will cause the new service worker to activate immediately, regardless of whether there are tabs open that are still controlled by the old service worker. Please not that this behavior can cause problems if you lazy-load resources, in that older tabs might try to lazy-load a URL that was present in the old precache, but has since been deleted once the new service worker took over. That's why `skipWaiting` isn't enabled by default. (See https://jeffy.info/2018/10/10/sw-in-c-r-a.html for some thoughts on that.)

**Comment by jeffposnick** [comment]
(You might want to follow https://github.com/GoogleChrome/workbox/issues/1753, as that's the open issue that's most relevant to improving the developer ergonomics of triggering `skipWaiting` via user interaction instead of automatically.)

**Comment by mjgchase** [comment]
Thanks Jeff , appreciate the heads up, thanks
