### ISSUE TITLE
workbox-precaching routes are not compatible with other packages

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#1857]
**Library Affected**:
*workbox-precaching*

The `addRoute()` (and by extension `precacheAndRoute()`) method in `workbox-precaching` adds its own fetch event listener + cache-first response logic rather than depending on the `Router` and `Route` modules from `workbox-routing` and the `CacheFirst` module from `workbox-strategies`.

This is not ideal for a few reasons:

- Code is duplicated and needs to be tested twice
- Logging for precached routes is different from logging for all other routes
- Precache route logic (the [configuration options](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.precaching#.addRoute) that `addRoute()` and `precacheAndRoute()` offer) is not available to runtime routes.
- Precache route handlers are not exposed to the developer, so they can't be reused with `workbox-streams` code (instead, developers have to create their own `CacheFirst` strategy instances anyway).

I'm sure there's historical reasons for (from the sw-precache/sw-toolbox merge), but I think we should explore whether it would be possible to consolidate these features in the future.

IMO, ideally, `workbox-precaching` would depend on `workbox-routing` and `workbox-strategies`, and the configuration options for customizing preaching routes could be added to the `workbox-routing` package and thus available to all routes.

**Comment by jeffposnick** [comment]
Historically, there were members of the core team who felt that minimizing cross-module dependencies was a priority, so that using `workbox-precaching` wouldn't automatically incur the overheard of the module size of `workbox-routing` and `workbox-strategies`.

I am... less concerned about that, and in particular, if we assume that more folks are going to create custom Workbox bundles in the future, evaluating costs based on the full bundle size of a given module isn't necessarily as meaningful.

**Comment by jeffposnick** [comment]
For some more historical context, the v2 codebase had all of this logic inside of the common `workbox-sw` module, kind of mixed together: https://github.com/GoogleChrome/workbox/blob/5b97922f3d4e06561097f02870f20693b79ee738/packages/workbox-sw/src/lib/workbox-sw.js#L131-L146

With v3, we started separating things out into self-contained modules with minimal overlap or cross-module code sharing.

**Comment by divyeshsachan** [comment]
I do vote for @philipwalton for this, since it'll expose all options of workbox-strategies to precache eventually resolving issue #1760. By default it should depend on CacheFirst / CacheFirst strategy.

**Comment by divyeshsachan** [comment]
I do vote for @philipwalton for this, since it'll expose all options of workbox-strategies to precache eventually resolving issue #1760 and add great flexibility. By default it should depend on CacheFirst / CacheFirst strategy.
After this developers can use other strategies for precache like staleWhileRevalidate, etc, refer https://stackoverflow.com/questions/54651722/how-can-i-set-a-default-setcatchhandler-with-google-workbox-v4 and #1897.
