### ISSUE TITLE
Configure navigationPreload via workbox-webpack-plugin

### ISSUE THREAD

**Issue by merrywhether** [GoogleChrome/workbox#1915]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
all browsers (that support navigation preload)

**Issue or Feature Request Description**:
It doesn't appear that `workbox-webpack-plugin` exposes a configuration option to enable `navigationPreload`, forcing a fallback to `importScripts` and `workbox.navigationPreload.enable();`. Did I miss something? And if not, is this something that could be added?

**Comment by merrywhether** [comment]
Does this seem like it would be a relatively easy first contribution by any chance?

**Comment by jeffposnick** [comment]
Sure! If you're up for it, that would be appreciated, and I think it could be a good first contribution. 👍 

You could model the PR on https://github.com/GoogleChrome/workbox/pull/1610, which added support for `offlineGoogleAnalytics`. That PR was a little more involved, because we took in either a `boolean` or a more involved `Object` as the configuration value, and in this case, I think you'd just need a `boolean` to enable navigation preload, defaulting to `false`.

Note that the change should be made in the `workbox-build` package, which is used under the hood by `workbox-cli` and `workbox-webpack-plugin`.

I'm happy to help with any questions if you do decide to implement this and run into issues.

**Comment by merrywhether** [comment]
Cool, got approval to do the work so should be able to start on it relatively soon.

**Comment by merrywhether** [comment]
@jeffposnick PR is up (#1981). Thanks for the roadmap via the other similar PR!
