### ISSUE TITLE
Crash Chrome on Android only if incognito

### ISSUE THREAD

**Issue by peterpeterparker** [GoogleChrome/workbox#1950]
**Library Affected**:

"workbox-webpack-plugin": "^3.6.3"

**Browser & Platform**:

Google Chrome for Android

**Issue or Feature Request Description**:

I'm honestly not sure if it's a support request or an issue but I'm facing a problem with Workbox on Google Chrome for Android but only in **incognito** mode. 

I'm developing a tool to ship presentation as PWA. If I open the presentation and swipe some slides, after a while the all browser crash respectively the Chrome app will crash.

I don't face the problem if I don't use the incognito mode neither I have been able to catch any logs.

If I remove the service worker respectively Workbox, the problem doesn't happen.

**How to I use workbox?**

```
const {GenerateSW} = require('workbox-webpack-plugin');

plugins.push(new GenerateSW({
            ignoreUrlParametersMatching: [/./]
        }));
```

**Reproduce the error**

1. On an Android phone
2. Open Google Chrome
3. Open an **incognito** tab
4. Go to https://deckdeckgo.com
5. Swipe a couple of slides

-> crash

**Source**

https://github.com/deckgo/deckdeckgo-website

**Note**

At first I thought it was linked to some Web Components I use, like gif or charts, but turns out I could reproduce the problem in another presentation too which is way more simple (url: https://studio.deckdeckgo.com, source: https://github.com/deckgo/deckdeckgo-studio-landing)

Thx in advance for any help!

**Comment by jeffposnick** [comment]
Hello!

It's not likely that we can get to the root of this issue from the Workbox side of things, since this sounds like an issue that's best dealt with by the Chrome engineering team.

There are details about automatic crash reporting at https://www.chromium.org/for-testers/bug-reporting-guidelines/reporting-crash-bug

In particular, if you could visit `chrome://crashes` from your Android device after reproducing the crash in Incognito, you should be able to confirm that the crash report is uploaded, and there should also be a link to provide more information (like explaining that it's triggered only in Incognito).

Apologies, but I think taking those steps will be the best way to get to the bottom of things.

**Comment by peterpeterparker** [comment]
@jeffposnick no worries, it sounds like a dead end or at least that I'm not gonna be able to solve the problem soon, but I understand. Thx for the feedback, always appreciated

**Comment by jeffposnick** [comment]
I wouldn't say that it's a dead end—the info from `chrome://crashes` will actually result in meaningful debug data making it to the relevant engineering team, and I'm sure that they would appreciate the bug report.

**Comment by peterpeterparker** [comment]
I like your spirit, finger crossed 🤞

**Comment by peterpeterparker** [comment]
For the record, a couple of months later, can't reproduce it, I guess it has been solved :)
