### ISSUE TITLE
registerNavigationRoute should support NetworkFirst strategy

### ISSUE THREAD

**Issue by Caaalabash** [GoogleChrome/workbox#1988]
**Issue or Feature Request Description**:

`registerNavigationRoute` only support `CacheFirst`  strategy(default), but I want to use  `NetworkFirst` 

````
workbox.routing.registerNavigationRoute('/index.html')
````

For example,  `index.html` contains `app-versionA.js`

For the first time,  `index.hmtl` got cached,

If I rebuilt my app (SPA),  the app.js file will be named `app-versionB.js`. 

It can't get updated immediately. What's worse, if I remove old assets `app-verionA` on my oss,
the app can't get updated forever.

**Comment by jeffposnick** [comment]
`registerNavigationRoute()` was not, in retrospect, the best name for us to choose for this method, since it implies it's the *only* way to route navigation requests. That's not the case.

You can just use a generic `Route` and check for whether it's as a navigation request in the [`matchCallback`](https://developers.google.com/web/tools/workbox/guides/route-requests#matching_a_route_with_a_callback_function), and then use whatever strategy you'd like as the [`handlerCallback`](https://developers.google.com/web/tools/workbox/guides/route-requests#handling_a_route_with_a_workbox_strategy).

So something  like this would give you the behavior you want:

```
workbox.routing.registerRoute(
  // This will return true for navigation requests, causing the route to match.
  ({event}) => event.request.mode === 'navigate',
  // Customize this handler with whatever options you need.
  new workbox.strategies.NetworkFirst()
);
```

Hopefully that works for you! We can reopen if it doesn't.

**Comment by nuragic** [comment]
Hi @jeffposnick, I was about to open a new issue related to this one, but luckily github is really good at proposing similar issues! 😄 

Seems that this is a common thing to want to use a different caching strategy than CacheFirst for a navigation route (i.e. NetworkFirst or StaleWhileRevalidate). Wouldn't be better if this function could provide an easy way to do so, instead of setting up custom code? If that would be possible one could still use the webpack plugin to generate the service worker. Maybe passing a new `strategy` prop via the `options` argument?

```js
workbox.routing.registerNavigationRoute(
  workbox.precaching.getCacheKeyForURL("/myapp/index.html"),
  { strategy: … },
);
```

That would change the behaviour of the actual handler: https://github.com/GoogleChrome/workbox/blob/94d34d687cf4ab68f76cca938dba590ba3d7b630/packages/workbox-routing/registerNavigationRoute.mjs#L59

Do you think it would be possible? Thanks!

**Comment by jeffposnick** [comment]
It's really not a good idea to use one of the `workbox-strategies` along with `workbox-precaching`. Doing so makes it impossible for `workbox-precaching` to serve as the source of truth about the versioning information for precached resource.

If you'd like something other than the behavior you get when using `workbox-precaching`, then I'd suggest not using it at all, and just use a mix of `workbox-routing` and `workbox-strategies` directly to implement your site's strategies.

**Comment by nuragic** [comment]
Yeah, I realized that I don't need precaching at all for this use case. I'm using registerRoute() plus a custom handler with a NetworkFirst strategy i.e. runtime caching. Thanks for clarifying!
