### ISSUE TITLE
BackgroundSync - get queue length (WB-V4)

### ISSUE THREAD

**Issue by bligny** [GoogleChrome/workbox#2011]
We would like to regularly display the number of pending requests that are parked into workbox  queue.

Yes I can use a custom "onSync" function in order to follow the play/replay of the queued items (and thereby increase/decrease an applicative counter), but the problem is that I need to initialize this counter on application/session startup.

I there a "workbox way" to query the workbox queue to get its length ?
(workbox way = not using indexeddb API to access the "request" store of the  storage named "workbox-background-sync").

Thx in advance!

**Comment by philipwalton** [comment]
Thanks @bligny, this is not currently possible with the `workbox-background-sync` module, but it seems like a reasonable feature to add.

**Comment by Fitzchev** [comment]
What about going even further and be able to browse the pending requests to get the details? Something like _myQueue.forEach(...)_. I guess we can use idb to do that (didn't try yet), but it would be cleaner to use the Queue object directly.

Use case:

In our app (used mostly offline) we have a menu entry called "Synchronizing" which display the number of items in queue (using a dedicated counter). It would be nice that a screen could display that list of pending items so that the user will know which one did not reach yet the backend server.

Thansk.
