### ISSUE TITLE
For matching navigation route consider passing `{ignoreSearch}`

### ISSUE THREAD

**Issue by HenrikJoreteg** [GoogleChrome/workbox#2024]
Hello @jeffposnick @addyosmani and co... I ran into something rather confusing that tripped me up.

**Library Affected**:
workbox-sw 4.2.0

**Browser & Platform**:
all

**Issue or Feature Request Description**:

Consider the following SW script, wouldn't you assume that you've successfully registered a working navigation route?

```js
importScripts('/dist/workbox-v4.2.0/workbox-sw.js')

workbox.setConfig({ debug: true })

workbox.precaching.precacheAndRoute([
  {
    "url": "/dist/home-page.7c7d0d90.js",
    "revision": "0e8f0b596f542632e62ceba1d98665ef"
  },
  {
    "url": "/dist/index.html",
    "revision": "e282c147efbd2dc51960ed563977f696"
  },
  {
    "url": "/dist/tachyons.06318282.css",
    "revision": "20d50a501771050ab24d19ee5c03c17d"
  }
])

workbox.routing.registerNavigationRoute('/dist/index.html', {
  whitelist: [/^(?!.*\.\w{1,7}$)/] // this is just to only answer requests without file extensions.
})

// ... other stuff
```

The trouble is.. it won't match. Because inside `registerNavigationRoute` it does this:

```js
const response = await caches.match(cachedAssetUrl, {cacheName});
```

☝️ this won't ever match the navigation route, because workbox stores these precached assets with a revision number in the URL:

<img width="809" alt="Screen Shot 2019-04-09 at 10 45 08 AM" src="https://user-images.githubusercontent.com/67925/55822522-9f048f00-5ab4-11e9-8e35-03fcd4ce2560.png">

To complicate things further... DevTools lists it *without* the search param:

<img width="841" alt="Screen Shot 2019-04-09 at 10 46 56 AM" src="https://user-images.githubusercontent.com/67925/55822606-d3784b00-5ab4-11e9-9874-486fe2748384.png">

Needless to say this is rather confusing as it is quite non-obvious why the navigation route is failing to match. 

I can see it has pre-cached `/dist/index.html` and yet, when I request it while offline... there's no match found.

Let me know what you think, perhaps I'm just missing something obvious. But it seems to me that it may make sense to pass `{ignoreSearch: true}` in addition to the `cacheName` for navigation routes?

**Comment by HenrikJoreteg** [comment]
By the way, I'm happy to send a PR with this tweak, if you folks agree.

**Comment by nhoizey** [comment]
@HenrikJoreteg I think you have to use the `ignoreURLParametersMatching` setting: https://developers.google.com/web/tools/workbox/modules/workbox-precaching#ignore_url_parameters

Or maybe use `workbox.precaching.getCacheKeyForURL(…)`: https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-precaching.PrecacheController#getCacheKeyForURL

**Comment by jeffposnick** [comment]
👋 @HenrikJoreteg 

Regarding the addition of URL query parameters in Workbox v4, the background is explained in [this issue](https://github.com/GoogleChrome/workbox/issues/1793)—I'd recommend looking through that, as moving to this naming conventions for precached URL keys was a disruptive change, but ultimately it's eliminated a potentially serious failure scenario.

As a result of this change, @nhoizey is correct in that you need to explicitly call `workbox.precaching.getCacheKeyForUrl()` to get the correct cache key when using precached URLs "manually"; we [handle that automatically](https://github.com/GoogleChrome/workbox/pull/1874) for you when you use the `generateSW` mode in our build tools.

Using `{ignoreSearch: true}` isn't safe, because we need to make sure that we're serving the correct cache entry corresponding to the currently active service worker; if there's a newly registered service worker in the `waiting` state, we don't want to accidentally use the version of cached HTML associated with it.

The main takeaway that I have from this issue, and it's something that I've mentioned to @philipwalton in the context of breaking changes for the next Workbox release, is that the `workbox.routing.registerNavigationRoute()` method is a) a bit too magic and b) confusing when we also have a [`NavigationRoute` class](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.routing.NavigationRoute) which is used in a fundamentally different manner.

**Comment by HenrikJoreteg** [comment]
Thanks @nhoizey and @jeffposnick. I "fixed" the issue yesterday by basically doing exactly what `workbox.precaching.getCacheKeyForURL` does by just creating the same URL manually at build time and injecting it along with the cache manifest. Just now, I switched it to the helper method which works fine and feels much less hacky, so thanks.

In terms of the bigger picture, I would tend to agree that there's a bit too much magic. One approach would just be to have the `registerNavigationRoute()` call `getCacheKeyForUrl()` on its own as it is non-obvious that it's necessary.

But, bigger problem, in my opinion...  is that Chrome Dev Tools doesn't show query parameters when you're inspecting caches. The fact that you can't programmatically look up a cache item using the key you see in dev tools seems like a bug, no? I only discovered that the `__WB_REVISION__` param was even there when it failed to return anything without query params.

**Comment by jeffposnick** [comment]
I filed https://bugs.chromium.org/p/chromium/issues/detail?id=951414 to track that feedback for the DevTools team. Feel free to star it to follow along. We've had a pretty good track record of shipping improvements to the Applications panel recently, and this seems like a valid request.

**Comment by HenrikJoreteg** [comment]
@jeffposnick excellent, will do.

**Comment by jeffposnick** [comment]
Looping back on this:

- the DevTools UI was changed, as per https://bugs.chromium.org/p/chromium/issues/detail?id=951414
- we're likely going to change `registerNavigationRoute()` in v5, and that's being tracked in https://github.com/GoogleChrome/workbox/issues/2095, so I'm going to close this issue.
