### ISSUE TITLE
Callback match function not waiting for Promise

### ISSUE THREAD

**Issue by Ale763** [GoogleChrome/workbox#2065]
Hi, I'm using Workbox to match an incoming request based on its request and response headers.
For this I not only have to examine the incoming request, but I also have to examine a possible stored response. This means I need to use the Cache API to retrieve the response from cache.
However, the Cache API returns a Promise and the matching callback function does not wait for the Promise to resolve. I have tried using `await` on every function called in the chain, but I think the callback does not take Promises into account, but I'm not sure. As a result, the matching function always accepts the incoming request, because it does not return `false`. I think the pending promise is interpreted as true. 

**Library Affected**:
*workbox-routing*

**Browser & Platform**:
*Only tested on Google Chrome & Chrome Canary on OSX Mojave".*

**Issue or Feature Request Description**:
*Is there a solution to let the matching callback function wait for the Promise to resolve? Is this possible or is this currently not supported yet?*

An example of the code: 
![image](https://user-images.githubusercontent.com/13874391/58690307-8a909480-8389-11e9-9cc4-1f8f9d0eee85.png)

In this code I try to retrieve the response from cache using the `caches.match(request, {cacheName})`, returning a Promise. I need to wait for the response, because I need to examine its headers (not implemented in this piece of code). Based on certain tests the matching callback function should return true or false (as indicated by the documentation). The problem is that the function does not wait for the Promise to resolve. This causes the incoming request always to be accepted even if it shouldn't.

**Comment by jeffposnick** [comment]
Hello @Ale763!

That's working as intended. You're correct that an `async` function always returns a `Promise`, and a `Promise` is always a "truthy" value, so it will always be interpreted as matching the `Route`.

There's a little more detail about this at https://developers.google.com/web/tools/workbox/modules/workbox-routing#matching_and_handling_in_routes:

> The only limitation is that "match" must synchronously return a truthy value, you can’t perform any asynchronous work. The reason for this is that the Router must synchronously respond to the fetch event or allow falling through to other fetch events.

The basic idea is that the way the underlying a `fetch` handler works, you need to synchronously determine whether or not to call `event.respondWith()` and provide a response. If a given `fetch` handler doesn't synchronously call `event.respondWith()`, then the next registered `fetch` handler gets a chance to respond, and if none of them call `event.respondWith()`, then the default browser behavior for that request is used instead of the service worker. This behavior is part of the service worker specification, and is not something that Workbox can control.

The workaround for this sort of thing is to use a handler that unconditionally matches (either via `workbox.routing.setDefaultHandler()`, or via a `matchCallback` that always returns `true`), and then implement your custom logic inside of your handler to accomplish something similar. If your `handlerCallback` returns `(new workbox.strategies.NetworkOnly()).handle({event})` or just `fetch(event)` then you'd get roughly the same default browser behavior as if the route hadn't been triggered at all.
