### ISSUE TITLE
Leverage the persistent storage API

### ISSUE THREAD

**Issue by leolux** [GoogleChrome/workbox#2081]
As far as I have understood the browser policy the storage used by PWAs to cache files for offline usage might be deleted by the browser if the PWA does not call
` navigator.storage.persist()`

Would it be possible to integrate this into workbox?

To read more on the storage specification:  https://storage.spec.whatwg.org/

**Comment by jeffposnick** [comment]
Since it's straightforward to call `navigator.storage.persist()` directly, I'm not sure that Workbox could add a lot of value here by wrapping that function call.

It would also have to be part of `workbox-window`, since `navigator.storage.persist()` doesn't seem to be exposed in the `ServiceWorkerGlobal` scope.

I can leave this open for a bit in case there are any use cases where `workbox-window` could really help, but my inclination would be no.
