### ISSUE TITLE
Main bundle not using Service Worker cache by default? (webpack plugin)

### ISSUE THREAD

**Issue by ernsheong** [GoogleChrome/workbox#2083]
**Library Affected**:
Workbox Webpack Plugin

**Browser & Platform**:
Chrome 75, all browsers?

**Issue or Feature Request Description**:
My main JS bundle file in `index.html` is not used by Service Worker by default. I had to explicitly set it like this:
![image](https://user-images.githubusercontent.com/1343284/59817796-e086a580-9353-11e9-9485-db611becdf43.png)

**Why this is problematic:**
Since it grabs from the network first, my page will eventually become stale an invalid main JS bundle file, because while index.html comes from Service Worker, it tries to grab main bundle from the network by default, resulting in blank page.

**Comment by jeffposnick** [comment]
Can you please try this using `workbox-webpack-plugin@next`?

By default, all assets in your webpack compilation will be precached (though you can change this by using `include`/`exclude` filters as needed.) That should be the case with older versions of the webpack plugin as well, but if we're going to troubleshoot this, it would be easier to start with the latest code.

**Comment by ernsheong** [comment]
I believe the `main.bundle.js` lives in the `index.html` page, and thus will be a runtime dependency that does not hit the pre-cache cache. 

Hence, an explicit "CacheFirst" configuration needs to be set. So perhaps this is a non-issue? Or at least a documentation issue.

**Comment by jeffposnick** [comment]
If your `main.bundle.js` is created as a result of the webpack compilation, you do have an option to allow it to be precached. That's what I'd recommend doing, as it can be kept up-to-date via versioning information that's generated during the build process.

I would not recommend using a cache-first runtime caching strategy with any URL that does not include versioning information, because the service worker will cache it once and then continue loading it from the cache, despite the fact that you might redeploy to the same URL with updates.

If you really want to use runtime caching for some reason, then either use a strategy like stale-while-revalidate that will eventually go against the network to check for updates, or else include a hash in the resource URL, like `main.bundle.[hash].js`.
