### ISSUE TITLE
workbox.expiration.Plugin - maxAgeSeconds - Issue - not working as expected

### ISSUE THREAD

**Issue by vbhandare** [GoogleChrome/workbox#2086]
**Library Affected**:
4.3.1/workbox-sw.js

**Browser & Platform**:
Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Issue or Feature Request Description**:
maxAgeSeconds Setting is not working When it is configured. as per below Code. My intention was to cache Service response for maximum 1min. This behaviour is expected as per configuration but its not working.  workbox does cache the service response but never update it after 1 min. Sometimes I have to wait more than 5 or more min to see new changes.
Let me know if anything wrong in code. I tested with workbox-sw.prod.v2.0.1.js with different code Which is working fine so not sure Issue with version 4.3.1/workbox-sw.js.
With 4.3.1/workbox-sw.js

```
importScripts('https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js');
const wssCacheName = 'api-servr'
workbox.routing.registerRoute(
  new RegExp('https://(.*)wss2(.+)/v3/anything/([a-zA-Z0-9]+)/(stock|detail)'),
  new workbox.strategies.CacheFirst({
    cacheName: wssCacheName,
    plugins: [
      new workbox.expiration.Plugin({
	maxEntries: 200,
        maxAgeSeconds: 60,
      }),
    ],
  })
);
```

With workbox-sw.prod.v2.0.1.js

```
importScripts('https://unpkg.com/workbox-sw@2.0.1/build/importScripts/workbox-sw.prod.v2.0.1.js')
const workboxSW = new self.WorkboxSW({ clientsClaim: true });
workboxSW.precache([])
workboxSW.router.registerRoute(
	'https://(.*)wss2(.+)/v3/anything/([a-zA-Z0-9]+)/(stock|detail)',
	workboxSW.strategies.cacheFirst({
		cacheName: 'api-servr',
		cacheExpiration: {
			maxEntries: 200,
			maxAgeSeconds: 60, 
		},
		cacheableResponse: {statuses: [200]},
	})
);
```

**Comment by jeffposnick** [comment]
Here's an excerpt from [the documentation](https://developers.google.com/web/tools/workbox/modules/workbox-cache-expiration#restrict_the_age_of_cached_entries) that might explain what's going on:

> Because it’s slow to open IndexedDB, expiration won’t occur until after the request is used. This means that an expired request may be used once, but will be expired after that.
> To alleviate this, the plugin will check the "Date" header of the cached response, if one exists and the date can be parsed, it’ll expire based on this as it doesn’t require an IndexedDB lookup.

If you'd like to ensure that your previously cached entries aren't used to fulfill your next request, make sure that the `Date:` response header is set on them. Since it looks like you're fetching the responses from a third-party API server, getting [CORS properly configured](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers) to expose the `Date:` header is required.
