### ISSUE TITLE
Unexpected Token ...

### ISSUE THREAD

**Issue by radiofrequency** [GoogleChrome/workbox#2091]
**Library Affected**:
*workbox-sw, workbox-build, workbox-cli

Node 7

nothing works on node 7..
/workbox-cli/node_modules/@hapi/hoek/lib/deep-equal.js:17
    options = { prototype: true, ...options };
                                 ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/workbox-cli/node_modules/@hapi/hoek/lib/index.js:9:19)
    at Module._compile (module.js:571:32)

**Comment by jeffposnick** [comment]
This sounds similar to https://github.com/GoogleChrome/workbox/issues/2061

The underlying code comes from the dependency on https://github.com/hapijs/hoek, which doesn't list a specific minimum required version of `node`.

That being said, as per https://node.green, that syntax *should* be supported in node 7, so I'm not sure why you're running into issues—can you ensure that you're on the latest node 7.x minor release, or alternatively, try upgrading to a more recent version of node?

**Comment by radiofrequency** [comment]
Don’t think node has full support for the spread operator until v8.  Specifically node 7 doesn’t handle spreading properties of an object.

Can’t upgrade node i’m just trying to upgrade from swPrecache on some legacy apps.

The package.json suggests this project works on node 6+ maybe u should update that if you don’t support / test on those versions.

**Comment by jeffposnick** [comment]
Apologies that you're running into this—I'm thinking it's likely due to https://github.com/GoogleChrome/workbox/issues/2043, which made it into Workbox v4.3.1.

Does switching to Workbox v4.3.0 resolve the issue for you?

Given that Node v8 is the [earliest version](https://nodejs.org/en/about/releases/) that is still in the maintenance window, I believe that we'll be bumping things up to that as the required minimum version that we support when Workbox v5 is released. Switching our Travis CI environment to explicitly test against both the earliest and the latest node releases is a good idea.

**Comment by radiofrequency** [comment]
Nope 4.3.0 didn’t solve it.

Looks like you need to use joi v12 if you want to support node 6+

https://github.com/hapijs/joi/issues/1802

Don’t really understand why a project that basically generates a text file needs to drop support for old node versions.

**Comment by jeffposnick** [comment]
Okay, thanks for digging into things.

https://github.com/GoogleChrome/workbox/pull/1959 was where we upgraded from `joi` v11 (in order to address the security issue reported at https://github.com/GoogleChrome/workbox/issues/1958). I was not able to find anything in the `joi` release notes at the time about changes to the minimum required node version, and apologies for the inconvenience that this has caused. (See https://github.com/GoogleChrome/workbox/issues/2094 for the Workbox v5 plan.)

Workbox v4.1.0 seems to be the one that was cut right before #1959 was merged, so that should still use `joi` v11.

**Comment by radiofrequency** [comment]
appreciate your help on this.  I tried a bunch of different versions and only workbox 3 seems to include joi 11 and works on node 7.

**Comment by zeriss** [comment]
Same problem with 4.1.0. i downgrade to 3.6.3 to make it work, but it seems to break bgsync feature.

**Comment by jeffposnick** [comment]
We're up to Workbox v5 now, which requires node 8 or higher.

I'm closing this issue as it's no longer actionable.
