### ISSUE TITLE
workbox-window method to trigger SW update check

### ISSUE THREAD

**Issue by jaulz** [GoogleChrome/workbox#2130]
**Library Affected**:
workbox-sw, workbox-window

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
If I try to instantiate workbox a second time no events are fired. What I basically want to achieve is that the user presses a button,  the service worker should reload and thus he will check for updates. It seems that currently the service worker can only be instantiated once. Appending a random timestamp in the file name causes the service worker to always download everything again.

There should be a method that just checks for updates of the service worker itself.

```
  const workbox = new Workbox(`/service-worker.js`, {
    scope: '/',
  })
  await workbox.register()
```

**Comment by jeffposnick** [comment]
CC: @philipwalton for his thoughts.

I had thought that `workbox-window` already had a helper for that, but I think you're correct in that there's no clean way of doing it.

You can do it using your own code pretty cleanly via

```js
navigator.serviceWorker.ready.then((registration) => registration.update());
```

That should work fine in the meantime.

I could see the benefit from exposing an `update()` method on the `Workbox` object that provided a wrapper on top of that logic.

**Comment by jaulz** [comment]
@jeffposnick great, thanks! That worked but it does not trigger the workbox events, i.e. I don't have any indication whether there was an update or not. Would in that case the simple `onupdatefound` work?

**Comment by jeffposnick** [comment]
I can't think of why that code snippet _wouldn't_ trigger the relevant events on the `Workbox`object if it does find an update to the service worker script, as it should be equivalent to what would happen if there's an update found following a navigation.

Can you make sure that you're listening to the right events on the `Workbox` object and if you don't see the expected behavior, open a new bug (since this one is now tracking the feature request)?

**Comment by jaulz** [comment]
Ah, I see... "Precaching 3 files. 18 files are already cached." works but it seems that in that case the `externalinstalled ` and `externalwaiting` events are thrown instead of the normal ones and it does not take over control automatically. I will try to track it down and raise an issue if I have structured details 😊 Thanks already!

**Comment by philipwalton** [comment]
@jaulz could you explain your use case a bit more? Why are you needing to manually update?

For context, `workbox-window` was designed to help developers avoid the problem where a user opens another tab to your site when an existing tab has been open for a while. If the service worker has been updated on the server, then loading the site in a new tab will trigger the `updatefound` event on all open tabs.

Since, in this example, the old page may be running code that wasn't designed to work with the files being precached by the new service worker, we fire the `externalinstalled`/`externalwaiting`/etc. event as a warning signal that things may break if not expected.

All this to say, I'd like to understand if there are cases where an update can be found to the service worker that _is expected_ by the code running on the existing page.

**Comment by jeffposnick** [comment]
https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#manual_updates:

> If you expect the user to be using your site for a long time without reloading, you may want to call update() on an interval (such as hourly).

**Comment by jaulz** [comment]
Yep, that's exactly my use case. An app that is most of the time running in the background and it's seldom that a user closes the tab. So I'm looking for a way to check for updates on a regular basis.

**Comment by philipwalton** [comment]
But what do you do if there's an update? Show UI? Update IndexedDB? Anything like that? Do you activate the installing SW immediately?

Also, how do you handle cases where the new SW is incompatible with the page code? E.g. `postMessage()`-ing between the SW and the page where the format of the data has changed, or dynamic imports to JS files whose URLs have changed.

**Comment by jaulz** [comment]
The idea is to offer a dialog asking the user to refresh the page. Basically the same as what I would show when there is an update found during page load. 

In my specific case the service worker will rarely change and thus I could handle type differences with simple checks.

**Comment by philipwalton** [comment]
In that case it sounds like whatever logic you'd use for `externalinstall` should apply here as well, and it would be exactly the same as if another tab were opened and an update found.

So Jeff's suggestion should work. We could also consider adding a `checkForUpdate()` (or whatever) function to the `Workbox` class as well.

**Comment by jeffposnick** [comment]
Since the `Workbox` class doesn't expose a `ServiceWorkerRegistration` anywhere, I think it would be helpful to add the helper method that made use of the internally-maintained `ServiceWorkerRegistration` and called `update()`.

**Comment by CaptainCodeman** [comment]
> "the externalinstalled and externalwaiting events are thrown instead of the normal ones and it does not take over control automatically"

That looks like the same thing I was seeing in #2031 (sorry, got busy with work and never got round to creating an example to reproduce it)

**Comment by jaulz** [comment]
I gave a first try and created a PR which introduces the new `update` method.

By any chance can you tell me how you usually create examples to reproduce cases like these?

**Comment by daffinm** [comment]
It would be really useful, from a UX point of view, if this new ```update()``` method could return, somehow, a flag indicating if an update was found or not. If this update check is initiated by the user, for instance by clicking a 'Check for Updates' button, this would allow them to be informed that 'No updates were found'. Otherwise nothing seems to happen...
