### ISSUE TITLE
Chunk files not showing in Cache Storage

### ISSUE THREAD

**Issue by shennan** [GoogleChrome/workbox#2145]
**Library Affected**:

Workbox Webpack Plugin

**Browser & Platform**:

Chrome

**Issue or Feature Request Description**:

When I use `globDirectory` and `globPatterns` in the Workbox Webpack Plugin, the JS chunks don't appear in Chromes DevTools > Application > Cache Storage. They do get written to a manifest json file and imported through `importScripts()`, but they never show up as precached assets in Cache Storage.

What's strange is that when I remove `globDirectory` and `globPatterns` as options in the plugin, the chunk files show up.

The issue with this is that I have assets outside of the webpack build process that I also want to precache, and (as I understand it) using `glob`s is the only way to do this?

```js
new GenerateSW({
  swDest: '../service-worker.js',
  globDirectory: 'priv/static',
  globPatterns: ['**/*.{js,css,png,svg,jpg,gif,woff2}'],
  ...
```

There's a corresponding [SO question here](https://stackoverflow.com/questions/57062374/workbox-seemingly-not-pre-caching-chunks-from-webpack-build).

**Comment by jeffposnick** [comment]
The UI in Chrome's DevTools unfortunately creates this confusion a lot.

<img width="651" alt="Screen Shot 2019-07-26 at 9 54 49 AM" src="https://user-images.githubusercontent.com/1749548/61956658-9a90b300-af8b-11e9-9e1b-f7f299e60a49.png">

If you look at the upper-left and bottom-left of that screenshot, you'll see the left/right arrows for paging through entries, and the total number of entries.

If the total number happens to be greater than 50, you'll need to use the arrows to page through entries, 50 at a time. Most of the time when folks can't find an entry that they know should be cached, it's because it's not included within the first 50 entries.

Can you confirm that's what's happened to you?

**Comment by shennan** [comment]
🤦‍♂ Major UI fail.

Ok, thanks for the feedback. That was indeed the issue. I'll close up.

I wonder how many people this trips up and how we can reduce the impact?

**Comment by jeffposnick** [comment]
FWIW, I've filed https://bugs.chromium.org/p/chromium/issues/detail?id=988038 to see if we can get this addressed by the team responsible for Chrome's DevTools.

Feel free to Star that issue to follow along.
