### ISSUE TITLE
Failing workbox-window integration test on Safari

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2150]
After upgrading to `selenium-webdriver` v4 and running the Safari (production) test suite locally, I get consistent failures at

```
  1) [workbox-window] Workbox
       "after each" hook for "reports all events for an external SW registration":
     
  NoSuchWindowError
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:560:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:486:26)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jeffposnick** [comment]
Unfortunately, that test is still flakey.

C.f. https://travis-ci.org/GoogleChrome/workbox/builds/574870617 in Safari Stable:

```sh
  1) [workbox-window] Workbox
       register
         reports all events for an external SW registration:
     
  TimeoutError
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:560:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:486:26)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

I'm assuming we see a slightly different error now due to catching the exception, but it's not enough to eliminate the flakiness.

@philipwalton, as the test's author, do you have any idea what might be causing the occasional failures?

**Comment by philipwalton** [comment]
Since creating #2210, this failure has turned from flaky to consistent. (Not sure why, since that PR didn't make any `workbox-window` changes).

After spending a bunch of time trying to narrow down exactly what changed that's making this now happen more frequently, I couldn't identify anything. (It's also really hard because it's also flakey on master, so it's hard to determine if a particular change is making it _more_ flakey.)

At this point, this issue is blocking us from merging #2210, so unless we can figure out why it's failing, I propose we temporarily skip the failing test in Safari until a solution is found.

@jeffposnick what do you think?

**Comment by philipwalton** [comment]
Not sure if this is related, but [this issue](https://github.com/SeleniumHQ/selenium/issues/3796#issuecomment-459928531) suggests the `NoSuchWindowError` error has been fixed in the latest Safari Tech Preview. However, I tried running the tests in STP and still saw the error, so our issue may be different.

**Comment by jeffposnick** [comment]
It unfortunately wouldn't be the first flakey test that we've had to disable, so yes, let's go for it, and leave this open to track an eventual fix.

**Comment by jeffposnick** [comment]
(Closing this in favor of https://github.com/GoogleChrome/workbox/issues/2150, which tracks the same failure across multiple browsers.)
