### ISSUE TITLE
cacheableResponse.Plugin 301 Status Not Caching

### ISSUE THREAD

**Issue by Snugug** [GoogleChrome/workbox#2217]
Welcome! Please use this template for reporting bugs or requesting features. For questions about using Workbox, the best place to ask is Stack Overflow, tagged with `[workbox]`: https://stackoverflow.com/questions/ask?tags=workbox

**Library Affected**:
*workbox-sw v4.3.1*

**Browser & Platform**:
*Google Chrome v76*

**Issue or Feature Request Description**:
I've got a website built using a static site generator and I'd like to be able to cache, and properly serve, the responses from hitting `/foo` and `/foo/`. In browser, if I navigate to `/foo` and there's a `/foo/index.html` on the server, it'll 301 redirect me using a `opaqueredirect` `Response-Type` to `/foo/`. I _can_ cache both of these responses with Workbox by omitting my  `cacheableResponse.Plugin` code below, although then it captures things I don't want cached. When I include the below, `/foo/` gets correctly captured and cached, but the `opaqueredirect` doesn't. Below is my code I'm using:

```js
workbox.routing.registerRoute(
    new RegExp('/(.*)/.+'),
    new workbox.strategies.StaleWhileRevalidate({
      cacheName: 'pages-cache',
      plugins: [
        new workbox.cacheableResponse.Plugin({
          headers: {
            'Content-Type': 'text/html; charset=UTF-8',
          },
          statuses: [200, 301, 404, 0],
        }),
      ],
    }),
  );
```

I'm unsure if this is a bug or if there's a better way to do this kind of caching that I'm just not seeing. I _don't_ want to precache these files as I only want them saved when requested.

**Comment by jeffposnick** [comment]
In general, if you've got two different URLs and you want to treat them as being equivalent for either cache read or write (or both) operations, you can write a [`cacheKeyWillBeUsed` plugin](https://developers.google.com/web/tools/workbox/guides/using-plugins#custom_plugins) that normalizes them:

```js
const cacheKeyNormalizationPlugin = {
  cacheKeyWillBeUsed: async ({request, mode}) => {
    if (request.mode === 'navigate' && !request.url.endsWith('/')) {
      return request.url + '/';
    }
    return request.url;
  },
};
```

The one issue here is that your response might be redirected, and using a cached redirected response to satisfy a navigation request will fail due to [this security restriction](https://bugs.chromium.org/p/chromium/issues/detail?id=669363).

`workbox-precaching` takes care of this for you by automatically creating a "clean" copy of any redirected responses and storing that in the cache, and you could actually use that same code directly now that [this PR](https://github.com/GoogleChrome/workbox/pull/2193) is checked in. But what's probably cleaner instead is just to add in a `requestWillFetch` plugin that rewrote the outgoing request URL to always end with a `/`, and avoid getting a redirected response in the first place.

Putting both of those together, and taking advantage of the fact that both callbacks have roughly the same signature, you'd have something like:

```js
async function normalizeIfNeeded({request}) {
  if (request.mode === 'navigate' && !request.url.endsWith('/')) {
    return new Request(request.url + '/');
  }
  return request;
}

const navigationNormalizationPlugin = {
  cacheKeyWillBeUsed: normalizeIfNeeded,
  requestWillFetch: normalizeIfNeeded,
};
```

And then add `navigationNormalizationPlugin` to your list of `plugins` when you configure your caching strategy.

**Comment by Snugug** [comment]
Not only does that perfectly solve the issue I had, but it actually _improves_ the experience by removing the `index.html` redirect in browser, making even cleaner URLs!
