### ISSUE TITLE
Opaque response caching is causing android to report enormous usage

### ISSUE THREAD

**Issue by SamSaffron** [GoogleChrome/workbox#2226]
We use:

```
workbox.routing.registerRoute(
  new RegExp('.*?'), // Matches all, GET is implicit
  new workbox.strategies.NetworkFirst({ // This will only use the cache when a network request fails
    cacheName: "discourse-1",
    plugins: [
      new workbox.expiration.Plugin({
        maxAgeSeconds: 7* 24 * 60 * 60, // 7 days
        maxEntries: 500,
        purgeOnQuotaError: true, // safe to automatically delete if exceeding the available storage
      }),
    ],
  })
);
```

To cache on Android so Discourse (eg: meta.discourse.org) can work offline. 

Users started reporting that our app is reporting enormous data usage per: 

![image](https://user-images.githubusercontent.com/5213/64941607-817cf200-d8aa-11e9-9f89-f70ac4c0035e.png)
 
Our analysis of such a device is that there is no such storage going on and instead its due to opaque request caching blowing the perceived size. https://developers.google.com/web/tools/chrome-devtools/progressive-web-apps#opaque-responses. For example we have 157 tiny CSS files that are coming in as opaque. 

Can workbox workaround this issue by using some sort of different container for caching? 

Are we misusing workbox? 

Should we report something to android?

**Comment by jeffposnick** [comment]
Hello!

What you're seeing is explained in more detail at https://developers.google.com/web/tools/workbox/guides/storage-quota in general (with advice on things like cache expiration if you happen to be runtime caching *too much*; not sure if that's also an issue for you) and in particular, https://developers.google.com/web/tools/workbox/guides/storage-quota#beware_of_opaque_responses with an explanation of how opaque responses contribute to quota calculations.

Unfortunately, apparent quota bloat due to opaque responses is not something that Workbox has any control over.

The most straightforward solution is for you to avoid opaque response by a) making sure that your CDN/third-party server supports CORS and b) making sure that when the browser makes a request that's handled via runtime caching, the request is made with CORS mode.

For CSS files, in particular, if you're loading them via `<link href="..." rel="stylesheet">`, that will *not* result in a CORS request by default. You need to explicitly opt-in to CORS mode by setting the [`crossorigin` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes), like `<link href="..." rel="stylesheet" crossorigin>`. Adding in that attribute is what I'd recommend doing to avoid the opaque response quota bloat.

**Comment by SamSaffron** [comment]
@jeffposnick what a wonderful reply! thank you so much!

My only feedback here which may possibly help workbox is to allow for a "dev mode" that counts opaque vs non opaque reqs and maybe warns in console if the count gets high?

Perfectly happy for you to close this, your reply was excellent and I feel this is fully resolved for me. 

Thank you!

**Comment by jeffposnick** [comment]
Glad things worked out!

We do have some opaque response-specific dev mode logging, but it's focused on letting developers know when opaque responses aren't getting cached:

https://github.com/GoogleChrome/workbox/blob/481b960e515c25f719b59d223bde658197e3a773/packages/workbox-core/src/_private/cacheWrapper.ts#L258-L261

(This was a major source of confusion in the past.)

Unfortunately, given that the lifetime of a service worker is pretty short (it's repeatedly started and then killed when idle), it's very difficult to implement any functionality that relies on long-lived state info, like keeping a count of opaque responses over time. I don't think it would be straightforward to add in the debugging info that you describe.
