### ISSUE TITLE
manifestTransforms does nothing

### ISSUE THREAD

**Issue by rafzan** [GoogleChrome/workbox#2243]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
*all browsers* (happens on build) 
Node v12.7.0

**Issue or Feature Request Description**:
Not much to add here. `manifestTransforms` does absolutely nothing, not even logs on terminal.

Here's my `InjectManifest`:
```javascript
new WorkboxPlugin.InjectManifest({
            swSrc: "./assets/js/pwa/worker.js",
            swDest: "sw.js",
            precacheManifestFilename: "precache.[manifestHash].js",
            excludeChunks: ["one", "two", "three"],
            include: [
                /(vendor).*\.js(?=\?|$|)/,
                /\.(woff2)(?=\?|$|)/
            ],
            exclude: [
                "avatar_empty.svg",
                "favicon-512x512.png",
                "favicon-192x192.png",
            ],
            manifestTransforms: [
                // Dirty akamai fix: removing __WB_REVISION__ from fetch URLs
                originalManifest => {
                    const result = originalManifest.map(entry => entry.url);
                    return { manifest: result, warnings: [] };
                }
            ]
        })
```

**Comment by jeffposnick** [comment]
Prior to Workbox v5, for legacy compatibility, `manifestTransforms` in the `webpack` plugin would only operate on URLs matched via `glob` patterns—not URLs derived from `webpack` assets. This obviously makes the option much less useful than it could be.

Starting with Workbox v5 (currently in [pre-release](https://github.com/GoogleChrome/workbox/releases)), `manifestTransforms` will operate as you expect (and we've removed the ability to pick up non-`webpack` assets via `glob` patterns).

You can read more about that change in the [pre-release notes](https://github.com/GoogleChrome/workbox/releases/tag/v5.0.0-alpha.0).

I would recommend trying out Workbox v5, as we're getting fairly close to a final release, especially if you need that functionality.

**Comment by rafzan** [comment]
Actually, I'm trying to remove the `?__WB_REVISION__=...` query string from the cached assets requests, and the only way we found was adding this `map` on my `service-worker.js` file:

```javascript
workbox.precaching.precacheAndRoute(
    self.__precacheManifest.map(entry => new Object({ url: entry.url }))
);
```

Very dirty fix. Is there any better way to achieve this?

**Comment by jeffposnick** [comment]
The point of the `?__WB_REVISION=` parameters is to bypass existing cache entries for URLs that Workbox believes do not contain any revision info already.

However, Workbox v4 wasn't always able to automatically detect which URLs originating from `webpack` assets included `[hash]`s as part of their names, leading to false positives.

In Workbox v5, you can use `dontCacheBustURLsMatching: new RegExp(...)` to specifically tell Workbox what your `[hash]`ed filename pattern looks like, so that it knows those URLs include revision info and don't need to be cache-busted. (Once https://github.com/GoogleChrome/workbox/issues/2221 is addressed, Workbox will be able to do this automatically in a reliable way, without any configuration.)

Furthermore, in the latest Workbox v5 pre-release, [we stopped](https://github.com/GoogleChrome/workbox/pull/2176) adding in `?__WB_REVISION=` URL query parameters altogether, even for URLs that need to be cache-busted, in favor of setting the `cache` mode on the outgoing request to indicate that the response shouldn't be returned by any intermediary caches.
