### ISSUE TITLE
PrecacheController helpers for retrieving responses from the cache

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2249]
**Library Affected**:
*workbox-precaching.*

@philipwalton had previously pinged me about wanting this, but I didn't realize how bad the current ergonomics were until I tried doing something similar using TypeScript.

I've ended up writing this a helper function in my own code:

```
async function getPrecachedResponse(url: string) {
  const cacheKey = getCacheKeyForURL(url);
  if (!cacheKey) {
    throw new Error(`${url} is not in the precache manifest.`);
  }

  const cache = await caches.open(cacheNames.precache);
  const cachedResponse = await cache.match(cacheKey);
  if (!cachedResponse) {
    throw new Error(`${url} is not precached.`);
  }

  return cachedResponse;
}
```

It would make sense to add this as `PrecacheController.getPrecachedResponse(url: string)`, though probably returning `null` instead of throwing an error when there's a cache miss would be more in keeping with the behavior of the Cache Storage API in general. (I'm already handling exceptions in my own code.)

We can *probably* keep `PrecacheController.createHandlerForURL(url: string)` as-is, but I would also be open to renaming it. (We need to keep it around under some name, since it's needed for handling navigation routes in App Shell-like scenarios.)

**Comment by philipwalton** [comment]
> We can _probably_ keep `PrecacheController.createHandlerForURL(url: string)` as-is, but I would also be open to renaming it.

What about a name like `bindHandlerToURL()`, which perhaps makes it more clear that the handler created does not accept a URL?

We could also potentially add a method that creates a handler that responds to any precached URL, and then we could have the `bindHandlerToURL()` method actually bind that handler to the specific URL needed for navigation fallbacks. WDYT?

**Comment by jeffposnick** [comment]
Making this slightly more complicated, `createHandlerForURL()` contains logic to fall back to the network if there's a cache miss: https://github.com/GoogleChrome/workbox/blob/9afb722b58bc111a6261117f26bb86d087be0617/packages/workbox-precaching/src/PrecacheController.ts#L360-L361

**Comment by jeffposnick** [comment]
How about these two methods (comments/logging omitted). The first is general-purpose, and then the second uses the first, but is tailored to the navigation handler use case:

```
async function matchPrecache(request: string|Request): Promise<Response|null> {
  const url = request instanceof Request ? request.url : request;
  const cacheKey = getCacheKeyForURL(url);
  if (!cacheKey) {
    return null;
  }

  const cache = await caches.open(this._cacheName);
  const cachedResponse = await cache.match(url);

  return cachedResponse;
}

async function createHandlerBoundToURL(url: string|Request, fallbackToNetwork = false): RouteHandlerCallback {
  return async () => {
    try {
      const response = await this.matchPrecache(url);
      if (response === null) {
        throw new Error(`The cache ${this._cacheName} did not have an entry ` +
          `for ${url}.`);
      }
    } catch (error) {
      if (fallbackToNetwork) {
        return fetch(url);
      }
    }
  };
}
```

**Comment by philipwalton** [comment]
I think my preference would be to define methods that will place nicely with other Workbox APIs (as you know long term I think it'd be great if Precaching could be build on top of the other APIs).

For example, in the context of compatibility with the `workbox-routing` package, your  `matchPrecache()` method contains logic that does both matching and handling, so you couldn't really use it with an existing `Router` object.

Do you have a usage pattern in mind for this method? Here's what I was thinking:

```js
import {registerRoute} from 'workbox-routing';
import {PrecacheController} from 'workbox-precaching';

const pc = new PrecacheController('my-precache');
pc.addToCacheList(/* ... */);

// What should these names be?
registerRoute(pc.getMatchCallbackSomehow(), pc.getHandlerCallbackSomehow());
```

Also, I'm not sure if I like the `string|Request` pattern. I understand that it's supposed to be a convenience, but since we don't do it everywhere requests are accepted, I think it'll cause more doc lookup time than it'll save. (Also, I think we removed the [only other occurrence of that](https://github.com/GoogleChrome/workbox/pull/2123) already as part of the TS migration).

**Comment by jeffposnick** [comment]
The idea behind the `async function matchPrecache(request: string|Request): Promise<Response|null>` signature was to mirror the `cache.match()` signature, so that `matchPrecache()` could be dropped in anywhere `cache.match()` would otherwise be used, except:

- `matchPrecache()` knows the name of the cache to check
- `matchPrecache()` knows how to translate an arbitrary URL into a URL that includes the right versioning parameter

The usage pattern is anywhere that you'd otherwise use `cache.match()`. [One example](https://github.com/jeffposnick/jeffposnick.github.io/blob/158ead410cfcabe463a603541332b18b9be5ac77/src/service-worker.ts#L48-L56) is:

```
let _site: {string: any};
async function getSiteData() {
  if (!_site) {
    const siteDataResponse = await getPrecachedResponse('/_posts/_data/site.json');
    _site = await siteDataResponse.json();
  }

  return _site;
}
```

(with some `null` checks in there, like you'd have to do if you were using `cache.match()` directly).

**Comment by philipwalton** [comment]
> The idea behind the `async function matchPrecache(request: string|Request): Promise<Response|null>` signature was to mirror the `cache.match()` signature, so that `matchPrecache()` could be dropped in anywhere `cache.match()` would otherwise be used

I get that use case, but the downside of doing it that way is then you can't re-use this function with a `Route`/`Router` instance.

If we have two functions—one that does the route matching and then one that does the request handling (e.g. the `caches.match()` logic with network fallback)—then they could still be used to do what you have above, but they could _also_ be passed to a `Route` instance.

In your example above, you don't really need the route-matching bit because you already have a URL that you expect to be precached. But for all other cases you'd definitely want to check that a URL is in the manifest before going to the cache. (I realize that in your code above it returns `null` if `getCacheKeyForURL()` returns null, but again, that doesn't fit with the Route/Router paradigm so it can't be re-used in that context.)

> (The term "matching" is overloaded here, as I'm talking about cache matching which I'm my mind shouldn't be conflated with route matching.)

In terms of naming, I'd lean toward a name that emphasizes this is a "handler" rather than something that mimics `caches.match()` since it deals with network fallback and could in the future be extended to run plugins.

**Comment by jeffposnick** [comment]
> I get that use case, but the downside of doing it that way is then you can't re-use this function with a Route/Router instance.

That's true, but we're talking about different use cases. Creating a publicly exposed interface that provides the `RouteMatchCallback` logic needed to use `workbox-precaching` without its built-in `fetch` handler doesn't address my use case.

(If you *did* want that functionality, you could trivially implement it from the existing public interface as `({request}) => getCacheKeyForUrl(request.url)`.)

> In terms of naming, I'd lean toward a name that emphasizes this is a "handler" rather than something that mimics caches.match() since it deals with network fallback and could in the future be extended to run plugins.

My [modified proposal](https://github.com/GoogleChrome/workbox/issues/2249#issuecomment-539682107) was for two public methods: `matchPrecache()` and `createHandlerBoundToURL()`, and the latter meets that criteria. Maybe I wasn't clear that I was suggesting two distinct methods?

**Comment by jeffposnick** [comment]
After talking about this offline with @philipwalton, the current plan of record is three new functions:

- `async function matchPrecache(request: string|Request): Promise<Response|null>`
- `async function createHandler(fallbackToNetwork = true): RouteHandlerCallback`
- `async function createHandlerBoundToURL(url: string, fallbackToNetwork = true): RouteHandlerCallback`

(where `createHandlerBoundToURL()` calls `createHandler()` under the hood, and is a shortcut useful for App Shell scenarios in which the same precached URL is used for all navigations.)
