### ISSUE TITLE
Poll: Preferences around importing type definitions?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2252]
Hey all—something that we've realized when playing around with TypeScript in the v5 pre-releases is that there are times when you'll need to explicitly (as opposed to implicitly) reference one of Workbox's types. Here's `RouteHandlerCallbackOptions`, for instance: https://github.com/GoogleChrome/workbox/blob/f23924a988a3e321dbcd9e3781f07b1de5dce916/packages/workbox-core/src/types.ts#L39-L44

There are a few different possible approaches to where you'd import that type definition from, and we were curious to hear from the community about what you'd expect/prefer.

Please vote via emoji reactions to this issue, and post comments with links to other projects and what they do, as we're curious about that as well. We'll take both reactions and prior art into consideration when finalizing the v5 interface.

- 👍 `import RouteHandlerCallbackOptions from 'workbox-core/types';`
- ❤️ `import RouteHandlerCallbackOptions from 'workbox-core';`
- 🚀 `import HandlerCallbackOptions from 'workbox-routing/types';`
- 🎉 `import HandlerCallbackOptions from 'workbox-routing';`

The 👍 option, where all types, regardless of which module they're most closely associated with, have to be imported from from `'workbox-core/types'` is what's implemented in the current v5 beta.

`Route` is omitted from the 🚀 and 🎉 names, since we're assuming that it's redundant if you're importing from `workbox-routing`.

**Comment by philipwalton** [comment]
One consideration to point out regarding option 🎉 (4) is that in some cases a particular package will depend on specific types for integration with another package, yet not actually depend on any APIs from that package.

For example, `workbox-strategies` exports classes that are compatible with APIs in `workbox-routing`, and as a result, types are shared between the two package. However, since no APIs are shared, `workbox-strategies` does not add `workbox-routing` as a dependency in its `package.json`.

If we were two switch to using 🚀 (3) or  🎉 (4), then people might end up having to install packages from npm that they're not actually using.

* * *

Also, with regards to option ❤️(2), one concern I have with importing both types and regular JS objects/classes/functions from the same file is it won't be clear in your code which import is a type and which import is a real JS object.

Does that concern anyone else? How do other folks deal with that ambiguity?
