### ISSUE TITLE
Warn when calling precache with a string or without revision property

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2259]
I'm sure that this was discussed during v5 development, but I'm unable to find the historical issues/PRs with comments about it.

A fairly common issue that we see is developers who pass in string URLs, like `'/offline.html'`, that lack versioning info to `workbox-precaching`. This is a problem because those URLs will never be updated after being cached for the first time. (This is fine if those URLs *do* contain versioning info, like `/app.1234abcd.js`, since it's assumed that the contents will never change, so updates aren't necessary.)

This came up most recently when I took a look at https://github.com/GoogleChrome/web.dev/blob/93694df6ec4874a85975127ce4a1856066e76bf5/src/lib/sw.js#L9

I *think* what we ended up deciding on is that all of the build tools will produce `{url: '/app.1234abcd.js'}` manifest entries, and that we'd very explicitly warn folks who passed in strings in v5 that they need to make sure those URL strings included versioning information, or else dire things would happen. (I'd actually be in favor of doing this in production builds, unlike most of our other warnings that only trigger in dev builds.) And then potentially deprecate passing in strings in v6.

But... I can't find any code in [`PrecacheController`](https://github.com/GoogleChrome/workbox/blob/ac28527b25e301e1330c044a59770af80e8c909a/packages/workbox-precaching/src/PrecacheController.ts) that actually does that.

@philipwalton, is my recollection on that decision accurate? If so, I think we just forgot to add in that extra warning message, and we still have time to do that before the final v5 release.

**Comment by philipwalton** [comment]
I'm fine with logging a warning in this case in dev, but I'd prefer we don't warn in production since that'll require pulling in all of the logger module (which currently isn't used in production).

What if we also did a naive regex match to avoid warning in cases where the developer likely has revision information in the URL? It wouldn't be perfect, but it might help avoid a lot of false positives, e.g. `/[\-._][a-f0-9]{4,}/`?

**Comment by jeffposnick** [comment]
I think what we decided is that if a user has revision information in the URL, we tell them in the warning message that they should switch to `{url: '/app.1234abcd.js'}` instead of `'/app.1234abcd.js'`, and we don't display any warnings when that happens. That seems like an easy opt-in way of avoiding the warning. (But again, I'm struggling to find any record of our previous conversation about this, so my recollection might be flawed.)

I'd be in favor of doing a plain `console.warn()` in production, with the actual Workbox logger used in development. This as a recurring anti-pattern that leads to cached responses which never get updated, and that's the worst-case scenario for a service worker.

**Comment by philipwalton** [comment]
I do remember this conversation, and now I think I recall we also discussed requiring an explicit opt out of revisioning. E.g.:

```js
precacheAndRoute([
  {url: '/index-a1b2c3.html', revision: null},
]);
```

Otherwise, in the future, I think it'll be just as likely that someone will do this:

```js
precacheAndRoute([
  {url: '/index.html'},
]);
```

Which I think should also generate a warning (and perhaps error in v6).

**Comment by jeffposnick** [comment]
Ah, so the mention of `revision: null` helped me find where we talked about this previously: https://github.com/GoogleChrome/workbox/pull/2124

That was just in the context of using `additionalManifestEntries` in the build tools, and we did add in a build-time requirement there.

So this issue could track implementing the same check at runtime inside the service worker, to prevent developers from finding the `workbox-precaching` module and using it directly by passing in unversioned URLs.

The runtime check would be log a warning whenever a string or an object without a `revision` property are passed in to `precache()`/`precacheAndRoute()`, and like I mentioned, I think it's a good idea to do that (via `console.warn()`) even in the production builds.

And then in v6, we can deprecate passing in a string or an object without a `revision` property.

**Comment by brettwillis** [comment]
@jeffposnick , I'm using workbox-webpack-plugin@5.0.0-rc.1, I format Webpack chunk filenames with the revision info built in, and use `dontCacheBustURLsMatching` to exclude the revision from the precache manifest.

All is good except I'm gett this warning about unrevisioned files, because the generated service worker manifest doesn't have `{ ... revision: null }` (they only have the `url` property).

I may be wrong, but is it related to the line below? `revision` is deleted rather that being set to `null`.
https://github.com/GoogleChrome/workbox/blob/ef5c2ca8fcbad586eccbaf8ab1df6c90afec7541/packages/workbox-build/src/lib/no-revision-for-urls-matching-transform.js#L23

**Comment by jeffposnick** [comment]
Thanks for pointing that out, @brettwillis! I'll fix that up to switch to `revision: null`.
