### ISSUE TITLE
workbox-webpack-plugin v5: setCacheNameDetails does not set cache names

### ISSUE THREAD

**Issue by parties** [GoogleChrome/workbox#2261]
**Library Affected**:
workbox-webpack-plugin `v5.0.0-rc.0`

**Browser & Platform**:
Tested on Firefox v70.0b13 and Chrome v77.0.3865.120, but could be happening on other browsers.

**Issue Description**:
The `setCacheNameDetails()` function from `workbox-core` does not set the cache names when using `precacheAndRoute` from `workbox-precaching`; Workbox instead uses the default cache name (`workbox-precache-v1-https://localhost:3000`).

I have tested this using `workbox-webpack-plugin` at `4.3.1` and `5.0.0-rc.0`:
* `4.3.1` is working as expected, creating the caches with the custom names
* `5.0.0-rc.0` is not working, using the default cache names

Here is my service worker file:

```js
import * as core from "workbox-core";
import * as precaching from "workbox-precaching";

core.setCacheNameDetails({
    prefix: "app-name",
    suffix: "1.x.x",
    precache: "custom-precache-name",
    runtime: "custom-runtime-name",
});

// this will log the updated cache names provided above
console.log({
    precache: core.cacheNames.precache,
    runtime: core.cacheNames.runtime,
});

self.addEventListener("message", (event) => {
    if (event.data && event.data.type === "SKIP_WAITING") {
        self.skipWaiting();
    }
});

// this does NOT use the updated cache names, it uses the defaults provided by Workbox
precaching.precacheAndRoute(self.__WB_MANIFEST);
```

And my WorkboxWebpackPlugin configuration:
```js
new WorkboxWebpackPlugin.InjectManifest({
    swSrc: paths.serviceWorker,
    include: [
        /\.js$/,
        /\.css$/,
        /\.svg$/,
        /\.jpeg$/,
        /\.gif$/,
        /\.png$/,
        /\.jpg$/,
        /\.ttf$/,
        /\.eot$/,
        /\.woff$/,
        /\.woff2$/,
        /\.html$/,
        /\.ico$/,
    ],
    exclude: [
        /\.json$/
    ],
}),
```

---

Admittedly, this issue is similar to #1402, but while that issue seems to have been resolved I am still seeing an issue in this particular case with v5.

Thank you all in advance 👍

**Comment by jeffposnick** [comment]
Hmm, I can't reproduce that:

<img width="1256" alt="Screen Shot 2019-10-23 at 5 10 16 PM" src="https://user-images.githubusercontent.com/1749548/67434345-05b44a80-f5b8-11e9-80ca-39ab830b9f83.png">

The precache is created with the custom name when I follow the setup you used.

It's weird that you see `workbox-precache-v1-https://localhost:3000` as the name, since there shoul be a `v2` in that default precache name if you're using Workbox v4+.

It sounds like maybe you've got an old service worker that's still active on `http://localhost:3000` and you're seeing the previous caches it created? Can you try this again in a Chrome Incognito window, or with a local webserver on a port other than `3000`, and see if you can reproduce it?

**Comment by parties** [comment]
I did some deeper investigating and found that I two copies of the `workbox-webpack-plugin` in my `node_modules` tree; removing the `4.x` version fixed it 👍 

Thanks for the quick reply and for taking the time to reproduce an example. 🙏
