### ISSUE TITLE
skipWaiting() fails to activate waiting service worker

### ISSUE THREAD

**Issue by similicious** [GoogleChrome/workbox#2302]
**Library Affected**:
workbox-core v4.3.1

**Browser & Platform**:
Windows: Google Chrome 78.0.3904.108, Firefox 71.0 

**Issue Description**:
I've tried to follow the instructions at [the docs](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users) to show a prompt, when an update is available. 

After clicking the button that triggers `wb.messageSW({type: 'SKIP_WAITING'});`, the message is processed in the service worker, and `skipWaiting()` is called. Then, a warning is logged to console in chrome:
`Event handler of 'install' event must be added on the initial evaluation of worker script.`. The service worker

I've also tried to do a minimal reproduction of the bug, but there, it works as intended.
Any idea whats going wrong in my project?

**Comment by jeffposnick** [comment]
As [per the recipe](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users), you need to make sure that your service worker includes

```
addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    // Use this, and not workbox.skipWaiting()
    skipWaiting();
  }
});
```

and not `workbox.skipWaiting()` for that to work. (The `skipWaiting()` in that example is effectively `self.skipWaiting()`, and `self` refers to the `ServiceWorkerGlobalScope`.)

It's a subtle difference, but `workbox.skipWaiting()` wraps the call inside of an `install` handler, and while that's suitable for use outside of a `message` event listener, inside the listener it ends up being executed after the initial evaluation of the worker script.

**Comment by similicious** [comment]
Thanks a lot for your reply. That worked!

I'm bundling my service worker with webpack, importing the functions from workbox-core. Having skipWaiting still in the import statement added to the confusion.

**Comment by CalebKester** [comment]
I was stuck on this too. Just to clarify it for people, removing this `import { skipWaiting } from 'workbox-core';` got it working. You do not want to use that method, instead you will have an undefined function as it's called in the global scope.

```
addEventListener('message', event => {
	if (event.data && event.data.type === 'SKIP_WAITING') {
		console.log('skip waiting');
		// eslint-disable-next-line no-undef
		skipWaiting();
	}
});
```

**Comment by jeffposnick** [comment]
@CalebKester sorry about that confusion. In v6, we've deprecated usage of `skipWaiting()` from `workbox-core` because of that sort of frustration.

https://github.com/GoogleChrome/workbox/blob/6d38919ebbc9664327e19ff00302d805c8166170/packages/workbox-core/src/skipWaiting.ts#L16-L33

**Comment by CalebKester** [comment]
Makes perfect sense once it got me understanding more how it works. Thanks for all the good work you guys do. Can't wait for v6!

**Comment by robbytx** [comment]
Leaving this comment here for my future self and anyone else:

When using Workbox v5 with `inlineWorkboxRuntime: true` and a non-`production` mode, then the `skipWaiting` function from workbox-core is inlined as-is into `sw.js` becoming a global function named `skipWaiting`, thereby shadowing the true [skipWaiting](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/skipWaiting) function. Therefore when the `install` event fires, the listener ends up invoking itself again leading to the warning `Event handler of 'install' event must be added on the initial evaluation of worker script.`
<img width="1048" alt="Screen Shot 2022-10-20 at 10 00 42 AM" src="https://user-images.githubusercontent.com/1022789/196985514-225646ba-b79c-4191-b215-8bc5c85c5d9c.png">

This is not an issue with any of:
 * `inlineWorkboxRuntime: false` because the function is no longer global
 * `mode: production` (the default) because the function is renamed during minification
 * v6+ because https://github.com/GoogleChrome/workbox/commit/3ffee3d78f716b6d9bd33e3170bc7c3c8cfee37b changed the default template to invoke `self.skipWaiting()` directly, thereby eliminating the function from being inlined into sw.js.
