### ISSUE TITLE
Multiple caches issue 

### ISSUE THREAD

**Issue by Ggayane** [GoogleChrome/workbox#2308]
I'm using webpack to build my workbox, and then importing the generated workbox service worker in another service worker (firebase messaging service).

Everything seems okay, except when firebase push scope appears, after which I get the copy of my precache storage (screenshot below).

<img width="828" alt="Screen Shot 2019-12-15 at 2 46 44 PM" src="https://user-images.githubusercontent.com/15812978/70861701-4c387c80-1f4b-11ea-8d63-9676c4ef2781.png">

Is there a way in workbox to check if there's a cache storage registered already?

**Comment by jeffposnick** [comment]
I don't think this is something that it would make sense for Workbox to automatically detect. There are legitimate use cases where multiple service workers are installed under the same origin, each with a different scope, and that's the same scenario that you're running into.

I'd recommend not including the Workbox-created PWA in the Firebase Messaging service worker to work around this. Because the Firebase Messaging service worker uses a "fake" scope that should never match actual pages, it will never end up controlling your web app's pages anyway.

I believe the [`useServiceWorker()`](https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging.html#useserviceworker) method in Firebase Messaging is designed to let you use your own service worker alongside Firebase Messaging without having to bundle things together.

**Comment by Ggayane** [comment]
@jeffposnick thank you so much for your answer.

Actually I've tried `useServiceWorker()` before, but it didn't work well, workbox service worker keeps triggering "redundant" on reload.

Anyway this was a bad thing to do, so I'll go with another solution.
