### ISSUE TITLE
Why does the Service worker use the cached user-agent  in Network First strategy?

### ISSUE THREAD

**Issue by uj121** [GoogleChrome/workbox#2314]
In our PWA, https://bitdroplet.com/app , we used Network First to cache our api responses. Weirdly, if we change the user agent mode, (say from desktop to mobile), the fetch calls from service worker to the network uses the previous ua string in its request header, and thus on the backend side the session gets invalidated. Unfortunately, it still uses the cache's ua while logging in again. Is there a way to prevent the sw to cache the user agent?

## Strategy

`workbox.routing.registerRoute(
			/https:\/\/bitdroplet\.com\/order\/isLoggedIn.*/,
			new workbox.strategies.NetworkFirst({
				cacheName: 'login-cache',
				plugins: [
					new workbox.expiration.Plugin({
						maxAgeSeconds: 24 * 60 * 60, // 1 day
						maxEntries: 1,
					}),
					new workbox.cacheableResponse.Plugin({
						statuses: [200],
					}),
				],
			}),
			'GET'
		);
`
## Network Call

![Screenshot 2020-01-02 at 7 53 54 PM](https://user-images.githubusercontent.com/18045480/71671661-9f0e9280-2d99-11ea-8bee-a53d8f7a2ea1.png)

![Screenshot 2020-01-02 at 7 55 03 PM](https://user-images.githubusercontent.com/18045480/71671725-c9605000-2d99-11ea-8cd7-c6ca38eb9215.png)
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.93 Safari/537.36

![Screenshot 2020-01-02 at 7 55 55 PM](https://user-images.githubusercontent.com/18045480/71671770-e72db500-2d99-11ea-9a37-426ea5a7eb06.png)
user-agent: Mozilla/5.0 (Linux; Android 9; ONEPLUS A5010) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.93 Mobile Safari/537.36

**Comment by jeffposnick** [comment]
In general, using Chrome's DevTools to change the user agent via [device mode](https://developers.google.com/web/tools/chrome-devtools/device-mode) won't end up changing the effective user agent inside of the service worker.

You can confirm this by checking the `navigator.userAgent` value inside of the `window` and service worker global scope before and after enabling device mode emulation.

It kind of makes sense why that wouldn't be the case—device mode emulation applies to a specific client window that's open, and a service worker can control multiple different windows, each of which might have a different device mode setting. It's not clear which window's setting the service worker should inherit in that case, so just always sticking with the original user agent value makes sense to me.

Does that explain the behavior you're seeing? If you're looking for different behavior, then I'm not sure it would be possible, but if it is, it would likely come by engaging with the Chrome DevTools folks rather than via a change to Workbox.

If I'm misinterpreting your problem, apologies, and I'd welcome a clarification about what's actually going wrong.

**Comment by uj121** [comment]
Thanks for the explanation. 👍

**Comment by uj121** [comment]
Thanks for the explanation 👍

**Comment by Deepakkast** [comment]
can someone please explain in detail m also getting issue in android webview 
becasue of service worker webpage taking default user agent and because of this our custom user agent condition goes wrong 
how can i solve this problem 
Thanks in Advance
