### ISSUE TITLE
Investigate alternative export syntax for our index.js entry points

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#232]
We're following the strategy of using a top-level `index.js` entry point in all our packages, and passing that to Rollup to be bundled. The `index.js` is in charge of pulling in the ES modules from local `lib/` directories and exposing everything we want to be public via named exports.

Currently, an `index.js` might look like:

```js
import Route from './lib/route';
import Router from './lib/router';

export {
  Route,
  Router,
};
```

I've noticed that there's another way of accomplishing this, using a series of explicit `export`s instead of a single `export`ed object:

```js
export {default as Route} from './lib/route';
export {default as Router} from './lib/router';
```

It might be that this is just alternative syntaxes that produce equivalent bundles when run through Rollup, in which case there's no reason to switch. But if there's reason to use one syntax vs. the other (maybe tree-shaking is more efficient?), switching would be easy enough.

Unless someone knows the answer off the top of their head, I'll run some experiments and see whether there's a difference in the generated Rollup bundles.

**Comment by addyosmani** [comment]
Fwiw, I've always considered the above two variations to be functionally equivalent and assumed that bundling tools were smart enough to opt for the correct optimization path regardless of which version you used. I wonder if @Rich-Harris might have some insight here :)

**Comment by Rich-Harris** [comment]
They're *almost* functionally equivalent — in this example, because `Route` and `Router` aren't actually used in `index.js` then they behave exactly the same:

* [import then export](http://rollupjs.org/?version=0.41.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBmb28lMjBmcm9tJTIwJy4lMkZmb28uanMnJTNCJTVDbmltcG9ydCUyMGJhciUyMGZyb20lMjAnLiUyRmJhci5qcyclM0IlNUNuJTVDbmV4cG9ydCUyMCU3QiUyMGZvbyUyQyUyMGJhciUyMCU3RCUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwZm9vJTIwKCklMjAlN0IlNUNuJTIwJTIwYWxlcnQoJTIwJ2ZvbyclMjApJTNCJTIwJTVDbiU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiYXIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwYmFyJTIwKCklMjAlN0IlNUNuJTIwJTIwYWxlcnQoJTIwJ2JhciclMjApJTNCJTIwJTVDbiU3RCUyMiU3RCU1RCU3RA==)
* [export from](http://rollupjs.org/?version=0.41.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAlN0IlMjBkZWZhdWx0JTIwYXMlMjBmb28lMjAlN0QlMjBmcm9tJTIwJy4lMkZmb28uanMnJTNCJTVDbmV4cG9ydCUyMCU3QiUyMGRlZmF1bHQlMjBhcyUyMGJhciUyMCU3RCUyMGZyb20lMjAnLiUyRmJhci5qcyclM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMGZvbyUyMCgpJTIwJTdCJTVDbiUyMCUyMGFsZXJ0KCUyMCdmb28nJTIwKSUzQiUyMCU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYmFyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMGJhciUyMCgpJTIwJTdCJTVDbiUyMCUyMGFsZXJ0KCUyMCdiYXInJTIwKSUzQiUyMCU1Q24lN0QlMjIlN0QlNUQlN0Q=)

The only difference is that you can't use re-exported identifiers in the same module — i.e. if you did [this](http://rollupjs.org/?version=0.41.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAlN0IlMjBkZWZhdWx0JTIwYXMlMjBmb28lMjAlN0QlMjBmcm9tJTIwJy4lMkZmb28uanMnJTNCJTVDbmV4cG9ydCUyMCU3QiUyMGRlZmF1bHQlMjBhcyUyMGJhciUyMCU3RCUyMGZyb20lMjAnLiUyRmJhci5qcyclM0IlNUNuJTVDbiUyRiUyRiUyMCU2MGZvbyU2MCUyMGhlcmUlMjBkb2Vzbid0JTIwcmVmZXIlMjB0byUyMHRoZSUyMGRlZmF1bHQlMjBleHBvcnQlMjBmcm9tJTIwZm9vLmpzJTJDJTVDbiUyRiUyRiUyMHNvJTIwUm9sbHVwJTIwYXNzdW1lcyUyMGl0J3MlMjBhJTIwZ2xvYmFsJTIwaW5zdGVhZCU1Q25mb28oKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwZm9vJTIwKCklMjAlN0IlNUNuJTIwJTIwYWxlcnQoJTIwJ2ZvbyclMjApJTNCJTIwJTVDbiU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiYXIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwYmFyJTIwKCklMjAlN0IlNUNuJTIwJTIwYWxlcnQoJTIwJ2JhciclMjApJTNCJTIwJTVDbiU3RCUyMiU3RCU1RCU3RA==), Rollup would assume you were referring to a global.

In this case I'd recommend the `export ... from` syntax.
