### ISSUE TITLE
String substitution in GenerateSW plugin file output, "swDest"

### ISSUE THREAD

**Issue by johnstonmatt** [GoogleChrome/workbox#2327]
**Library Affected**:
workbox-webpack-plugin

**Browser & Platform**:
all browsers

**Feature Request Description**:
My organization and I would benefit greatly from the ability to use webpack's standard string substitution in `swDest` filenames. 
To match the webpack pattern and conventions, this would enable users of the `webpack-workbox-plugin` to have `swDest` configured in the following way:
```
{
  swDest: "./service-workers/service-worker.[hash].js"
}
```
and have webpack inject its build hash in the place of `[hash]`. 
This functionality is used for standard asset output filenames from webpack, and is documented here:
https://webpack.js.org/configuration/output/#outputfilename

This is important because it enables our organization to serve legacy service workers disambiguated by their build hashes.

**Comment by jeffposnick** [comment]
Changing the URL of your service worker script is generally an anti-pattern, for the reasons explained at https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#avoid-url-change

While there might be some use cases that fall outside of the usual best practices, I don't think they're common enough to warrant adding in that feature—especially since supporting it could give the wrong impression about whether they should do it or not.

If you do need that functionality, I'd recommend adding in an additional build step or `webpack` plugin to handle the renaming.
