### ISSUE TITLE
Add a way to ignore routes matching a particular condition

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#2330]
Workbox makes it easy use regular expression to match routes, but when using regular expression it's often cumbersome to ignore things.

For example, if you wanted to create a route that handled anything matching `new RegExp('/\w+$')` with the exception of `/subscribe`, it's a bit awkward—especially if you have lots of expressions that need to ignore things or lots or things you need to ignore.

Even worse is the simplest way to do this in Workbox is actually an anti-pattern that we don't want to promote—using `NetworkOnly` or some other pass-through fetch handler. E.g:

```js
// Bad!
registerRoute('/subscribe', new workbox.strategies.NetworkOnly());
registerRoute(new RegExp('/\w+$'), new workbox.strategies.StaleWhileRevalidate());
```

To make it easier to handle cases like this, what if we added an `ignoreRoute()` method that, once matched, would stop looking for additional route matches and just use the browser's default response mechanisms. Then the above would become this:

```js
ignoreRoute('/subscribe');
registerRoute(new RegExp('/\w+$'), new workbox.strategies.StaleWhileRevalidate());
```

And when using `ignoreRoute()`, order would still matter, allowing you to layer your matches in whatever way made the logic cleanest.

@jeffposnick WDYT?

(cc: @robdodson as this came up in discussions with him around web.dev SW config)

**Comment by jeffposnick** [comment]
Sure, that sounds like a good idea.

There's currently a decent amount of "magic" overloading w.r.t. the first parameter you pass to the standalone `registerRoute()` helper function:

https://github.com/GoogleChrome/workbox/blob/f2cf7f6723fbeb57b3e9f28c1aa8d98da586cb2d/packages/workbox-routing/src/registerRoute.ts#L38-L41

The main question I have is whether a corresponding `ignoreRoute()` helper function should match that same behavior, or whether we'd limit things so that you'd have to pass in an actual `Route` object.

Assuming we did match that behavior, we should abstract away the logic for converting the mishmash of `RegExp | string | MatchCallback` parameter types into a `Route` (and potentially think about exposing that logic as a public method).

**Comment by robdodson** [comment]
> Even worse is the simplest way to do this in Workbox is actually an anti-pattern that we don't want to promote—using NetworkOnly or some other pass-through fetch handler. 

Can y'all explain why this is an anti pattern?

**Comment by jeffposnick** [comment]
...I don't think it's always an anti-pattern, since handling navigations using the `NetworkOnly` strategy is part of our guidance around using navigation preload.

Not sure exactly what Phil had in mind, but if you're *just* using `NetworkOnly` and navigation preload isn't enabled, then I would imagine it's strictly slower (due to the overhead of running the extra JavaScript) vs. just not calling `respondWith()` and allowing the browser's default behavior to handle things.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
