### ISSUE TITLE
Allow to provide full target path for libraries to copyWorkboxLibraries

### ISSUE THREAD

**Issue by dsebastien** [GoogleChrome/workbox#2331]
Welcome! Please use this template for reporting bugs or requesting features. For questions about using Workbox, the best place to ask is Stack Overflow, tagged with `[workbox]`: https://stackoverflow.com/questions/ask?tags=workbox

**Library Affected**:
workbox-build

**Browser & Platform**:
N/A

**Issue or Feature Request Description**:
It would be nice to be able to completely define the directory in which libraries will be copied when calling copyWorkboxLibraries.

Currently, if I pass a path/directory name, then it only defines the place where the function will create a directory for the libraries before copying them.

The issue for me is that the final folder depends on the workbox version, which forces me to adapt multiple things in my app whenever I switch from one version to another.

By being able to control the target folder, I can simply point all other locations to a stable path.

**Comment by jeffposnick** [comment]
That's intentional, and not likely to change, as using the version of Workbox in the URL that you pass to `importScripts()` ensures that the byte-for-byte SW update check properly deals with imported dependencies in older browsers (pre-Chrome 78): https://developers.google.com/web/updates/2019/09/fresher-sw

In Workbox v5, we expect folks who want a local copy of the Workbox runtime to primarily consume only the pieces of code that they need via our ES modules and produce a final output bundle, as described in https://developers.google.com/web/tools/workbox/guides/using-bundlers

I'd recommend going that route if you want an alternative to the current `copyWorkboxLibraries` behavior.
