### ISSUE TITLE
Idea, add this option appendWorkboxFunctions to workbox-webpack-plugin

### ISSUE THREAD

**Issue by hypernova7** [GoogleChrome/workbox#2337]
It would be a good idea to add an option to add custom functions to the file `sw.js` in the package `workbox-webpack-plugin`

Example:

```javascript
const workbox = require('workbox-webpack-plugin')
module.exports = {
  // ... Other configs,
  plugins: [
    new workbox.GenerateSW({
      // ... Other options config,
      appendWorkboxFunctions: [require('./src/sw-custom-functions.js')]
    })
  ]
}
````
File `sw-custom-functions`
```javascript
self.addEventListener('message', e => {
  // blah blah blah
})
self.addEventListener('push', e => {
  // blah blah blah
})
```

**Comment by jeffposnick** [comment]
There are a few alternatives that will accomplish that in v5 (I'm linking to the JSDocs until we get the generated docs updated on our website):

- Use [`importScripts`](https://github.com/GoogleChrome/workbox/blob/e8136d15f0697cff497891d3728201d59943602a/packages/workbox-webpack-plugin/src/generate-sw.js#L93-L97) and pass in a URL corresponding to wherever your custom JavaScript will be served from (e.g. `importScripts: ['public/sw-custom-functions.js']`). This is the easiest approach, assuming you aren't compiling your custom functions with `webpack`.

- Use [`importScriptsViaChunks`](https://github.com/GoogleChrome/workbox/blob/e8136d15f0697cff497891d3728201d59943602a/packages/workbox-webpack-plugin/src/generate-sw.js#L99-L101) and pass it in the name of a `webpack` chunk that's defined elsewhere in your `webpack` configuration (e.g. `importScriptsViaChunks: ['swCustomFunctions']`). This approach will work if you need to compiled your custom functions.

- Use [`InjectManifest`](https://github.com/GoogleChrome/workbox/blob/e8136d15f0697cff497891d3728201d59943602a/packages/workbox-webpack-plugin/src/inject-manifest.js) mode instead of `GenerateSW`, and you'll have full control over the contents of your service worker, including adding in that extra code in whatever location you want.
