### ISSUE TITLE
How long 'precacheAndRoute' caches for?

### ISSUE THREAD

**Issue by carlinoo** [GoogleChrome/workbox#2338]
Hi there, we used to cache all the routes in our PWA in VueJS but we recently decided that we want the users to have the latest features as soon as they get deployed. We had this line of code which we have just removed:

`// workbox.precaching.precacheAndRoute(self.__precacheManifest, {})`

Now we have the problem that all our users have still the old version with everything cached. How long by default are things cached for? I am asking so that we can expect when users will have our latest version on their phones. 

Thanks :)

**Comment by jeffposnick** [comment]
`workbox.precaching.precacheAndRoute()` (as the name implies) does two things:

- It populates the Cache Storage API ahead of time with all of the entries listed in the precache manifest.
- It sets up a routing rule that will match any request for a URL that is included in the precache manifest, and respond with the cached `Response`.

When you  remove the call to `workbox.precaching.precacheAndRoute()` from your service worker, as you've done, the new service worker will stop responding to requests that would otherwise have matched. Please note that due to the [service worker lifecycle](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#skip_waiting), this new service worker won't go into affect right away; adding in a call to `workbox.core.skipWaiting()` can accelerate when this new service worker activates even if existing clients have other pages on your domain open in other tabs.

Also note that simply remove the call to `precacheAndRoute()` won't clear out previously precached entries. (So data will remain cached on user's devices, but unused.) If you want to clear things out, you have a couple of options, but the cleanest might be to just add in:

```
self.addEventListener('activate', event => {
  event.waitUntil(caches.delete(workbox.core.cacheNames.precache));
});
```

You could alternatively add a call to `workbox.precaching.precache([])` which tells Workbox to use an empty manifest for the precache.
