### ISSUE TITLE
Enable logging for production build v5.0.0

### ISSUE THREAD

**Issue by AlexeyAZ** [GoogleChrome/workbox#2347]
Can i enable logging for production build, when `process.env.NODE_ENV === 'production'`?

**Comment by philipwalton** [comment]
Sorry, we cannot enable logging in production mode because we do not include any of the logging code in our production builds. And the reason we don't include the logging code is because doing so would substantially increase the file size of the Workbox packages.

If you need to have logging in your production application, you could create your own Workbox build [that doesn't exclude dev-only code](https://developers.google.com/web/tools/workbox/guides/using-bundlers#keeping_dev-only_code_out_of_the_bundle), but (again) I'd be very careful to only do so temporarily—to debug an issue. It would not be a good idea to turn on logging permanently for all your users.
