### ISSUE TITLE
Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by keithws** [GoogleChrome/workbox#2363]
**Library Affected**:
*workbox-core*

**Browser & Platform**:
*Google Chrome v80*

**Issue or Feature Request Description**:
*Lighthouse 5.7.0 flags me to Ensure text remains visible during webfont load*

The specific font in question is Lato, as loaded from Google fonts. I do not use Lato, but I see that workbox-core is loading Lato. Can you add the `&display=swap` parameter to the end of your Google Fonts URL when loading Lato?

https://web.dev/font-display/

**Comment by philipwalton** [comment]
Workbox does not load any fonts (or any external assets at all). If you're seeing fonts loaded by your service worker, it's most likely due to:

- A Workbox runtime caching route that's matching more files than you intended it to match.
- A service worker from another project still controlling your origin (this can happen if you have many development projects all sharing the same localhost port).

I'd recommend checking the developer console logs to see which routes are matching the font URLs, and if that doesn't work then clear all your local caches (including unregistering all service workers) for your test origin.

**Comment by keithws** [comment]
Ah... thank you for the quick response. I do not use workbox. It is used by a Wordpress plugin that I use. I will follow up with the plugin author.
