### ISSUE TITLE
additionalManifestEntries any workbox function which helps me create revision for 3rd-party url?

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2418]
Basically ,I got 2 questions @jeffposnick . Would highly appreciate your deepest, well thought answers.

1) The thing is my application needs 3 files in order to work offline. let's call these files `1.js, 2.js, 3.js`. Previously, I had a `registerRoute` function for them but I don't like this because the requests get made for these files before `self.clients.claim()` happen which means that User has to refresh a page 2 times in order to be able to use my website offline.  So, I don't want to make him refresh 2 times in order to work offline. So I might decide to add those files in precache manifest by using `additionalManifestEntries`.  **NOTE** These files are from another project/origin which is also my project.

let's say I added this:

```js
additionalManifestEntries:[
    {
          url: '3rd-party.com/1.js',
         revision: null
    }
]

```

Now, what about revision? any idea on what to put in there? since my `1.js` won't have `hash` in the url.  So what do I put as a revision in there? 

I also understand the risk that this might be bad since if the file is not found (because it's on another origin), service worker installation fails, but everything has ups and downs.

What do you think?

2) This is a really, really interesting thing to decide.

So, let's forget about workbox and think about the pure SW implementation. Let's say I am using Single Page App (`vue.js`).  and I also have dynamic routes (code splitting). Now, Let's say that I am using `window.addEventListener('load')` and in the callback I register my service-worker. Now, let's say that when `load` event got called, I showed the content to the user and the content includes the link `<router-link to="/auth"> Click here </router-link>`. Now, when I show this page to the user, service worker also runs in the background. Let's say SW has to precache 100 items and let's assume we're using 3G slow network. Now, let's say while dowloading/precaching things, user clicks on that `auth` link.  Because that `auth` is `router-link`  and it's dynamic, router-link makes a request for that. But funny thing is because SW started downloading/precaching things before, my clicking on router-link will be delayed until SW is done. Why? because Browser allows 6 maximum requests and because SW downloads more than 6items(we already assumed SW precaches 100 items), it means that request for dynamic `router-link` will be pending until SW is done or until the possiblity of one request out of 6 gets free. and this will be free when SW has downloaded 95 items and has 5 items remaning, which means 6-5=1 and router-link request can go from pending to actually starting.

I wonder, all the examples, all the time I've developed my apps, i have used `window's on load event` after which I run SW.  this means that if user clicks on `router-link` , he has to wait (meaning he can't interact with a page). Is there any solution (i mean good solution or any ideas) how you would approach this? I got some ideas , but wanted to first double check with your mind.

Thanks for all your answers so far <3

**Comment by jeffposnick** [comment]
(In the future, could you please ask general questions on Stack Overflow, [tagged with `workbox`](https://stackoverflow.com/questions/tagged/workbox), and reserve this issue tracker for feature requests and bug reports? Thanks!)

Regarding 1, it's not safe to precache unversioned URLs that you can't generate accurate revision info for as part of your build process. That means it's not safe to precache cross-origin URLs unless you control the deployment of that remote origin (i.e. because it's a CDN that you control, allowing you to change the `revision` field in the precache manifest prior to re-deploying the CDN).

What I'd recommend doing for this scenario is to ["warm" the runtime cache](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#warm_the_runtime_cache), by adding an `install` event handler to your service worker. Then, add in a runtime caching route that uses an appropriate strategy (`StaleWhileRevalidate` most likely, or `NetworkFirst` if you need to prioritize freshness) to serve those URLs. By "warming" the runtime cache in an `install` handler, you ensure that by the time the newly activated service worker takes control of its clients, the cache has been populated (without relying on `workbox-precaching`).

Regarding 2, this recently came up at https://github.com/GoogleChrome/workbox/issues/2382#issuecomment-596465665. I don't have much more to add beyond what's there—in general, bandwidth contention can be a problem, and either precaching less data, showing a "loading" screen while precaching, or delaying service worker registration until much later than the `window`'s `load` event are steps that you could take to work around some of the issues.

**Comment by novaknole** [comment]
So, to sum up, if I use your recommendation about question 1, I don't need `additionalManifestEntries` at all and I don't have to worry about revision or hashes at all. Right?

**Comment by novaknole** [comment]
and by the way, in previous versions, you had 2 precache caches. one for installing and one for the actual one and you'd move assets from one to another.

in V5, as I can see in the code, there's only 1 precache cache.  Am I right?

**Comment by jeffposnick** [comment]
Right, you don't need to use `additionalManifestEntries` or worry about revisions. You just need to use a runtime strategy that ensures an update is made at some point (either `StaleWhileRevalidate` or `NetworkFirst`, depending on how fresh you want the response to be).

You're correct that precaching used to use multiple caches for the `install` and `activate` states, and we moved to a model where a single cache was used instead: https://github.com/GoogleChrome/workbox/pull/1820

**Comment by novaknole** [comment]
One more thing I want to figure out and That's it. Basically, We use revisions if the filename doesn't contain hashes so workbox can figure out if the file changed or not.

Let's call our file `test.js`  As we see there's no hash in the filename and let's say i added it in the manifest without revision. ****Can you just describe the scenario where this would make the app crashable?**** 


Let's say we updated `test.js` and pushed the code. new SW gets installed. So what happens is this. - By looking at the workbox code, `url` and `cacheKey` will be the same. Now,  because our cache already contains `test.js`, it won't add `test.js` to the `toBePrecached` array which means no `fetch` call or `adding thing to the cache` will happen.  In the `activate` listener, workbox  has this code

```js
for (const request of currentlyCachedRequests) {
            if (!expectedCacheKeys.has(request.url)) {
                await cache.delete(request);
                deletedURLs.push(request.url);
            }
        }
``` 

this means that `test.js` won't be deleted from the cache. because of `!` in the if statement. which means that after new worker gets installed/activated, the only thing that's going to be bad because of the abscence of the revision, is that workbox will always return the old version and it will never update the `test.js` unless we have runtime caching for that file too.

**Comment by jeffposnick** [comment]
> this means that test.js won't be deleted from the cache. because of ! in the if statement. which means that after new worker gets installed/activated, the only thing that's going to be bad because of the abscence of the revision, is that workbox will always return the old version and it will never update the test.js unless we have runtime caching for that file too.

Yes, that's the problem. Caching a URL at some point in time and *never* checking that URL for updates is something that I would consider a failure scenario, and we want developers to avoid getting into that state.

You can't "mix and match" precaching with runtime caching. If you have URL in the precache manifest, then `precacheAndRoute()` will end up handling the `fetch` event for that URL, and any runtime caching routes you have set up will never get a chance to fire.

No, you can't use anything like a regexp to warm the runtime cache inside of an `install` handler. You need to pass in actual URLs to `cache.addAll()`. If you don't know those URLs in advance, then you can either just rely on runtime caching to pick up the URLs during the subsequent visit, or alternatively, you can try out the `workbox-window` usage outlined in "[Send the service worker a list of URLs to cache](https://developers.google.com/web/tools/workbox/modules/workbox-window#examples)"

**Comment by novaknole** [comment]
@jeffposnick  there were some bugs about workbox-window . That's why I got the plain sw implementation in the first place.  The bug I mean is that new service worker wouldn't get activated because workbox-window has the old service worker. It sends `skipWaiting` to the old one which results in new service worker never getting activated.  I even remember we got 2 listeners `waiting` and `externalwaiting` . Docs even say nothing about the difference and it just makes it really difficult to debug or follow `workbox-window` package. Any updates on this?

**Comment by jeffposnick** [comment]
1. @philipwalton just updated the [recipe](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users) for using `workbox-window` to show a "reload" message to account for those issues. I'd recommend giving that a try.

2. Service worker precaching happens during the `install` handler. Once the `install` handler completes, the new service worker will either enter the `waiting` state (if there's already an active service worker in control of some page; we covered this elsewhere) or enter the `active` state. If you're talking about the first visit to a site, when there's no previous service worker, you should expect it to transition to the `active` state without going to `waiting`.

You can use the `navigator.serviceWorker.ready` promise to detect when the service worker associated with the current page is activated, which as mentioned, won't happen until after `install` and therefore precaching completes.

So you can write code like

```
navigator.serviceWorker.register('/sw.js');
navigator.serviceWorker.ready.then(() => {
  // This is when you'd show the actual page to the user.
});
```

3. I do answer questions tagged with `workbox` and/or `service-worker` on Stack Overflow, yes, but more to the point, a lot of other folks do as well. These are people who would normally not otherwise see your questions if you just ask them on closed GitHub issues in this repo. That is a much more scalable model for support.

**Comment by daffinm** [comment]
Hey @novaknole. I hit a problem with precaching killing my media app on mobile devices with slow data connections. I have worked out a caching strategy that is a hybrid of precaching and runtime caching that seems to work with all types of file resource. See the following project for details/code etc.
https://github.com/daffinm/audio-cache-test
