### ISSUE TITLE
`mode` isn't supported by workbox-build's injectManifest or getManifest

### ISSUE THREAD

**Issue by Westbrook** [GoogleChrome/workbox#2427]
**Library Affected**:
workbox-build

**Browser & Platform**:
MacOS, but seemingly all.

**Issue or Feature Request Description**:
Currently, both [`generateSW`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.injectManifest) and [`injectManifest`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.injectManifest) API for `workbox-build` support the `mode` option in their configuration. However, it seems that only [`generateSW`](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-build/src/lib/write-sw-using-default-template.js#L12) actually leverages this in its code path.

Is this as expected?

If so, then it seems that `mode` should be removed from the documentation for `injectManifest` so that users relying on a bundler can make more informed decisions as to what sort of interactions they should have with this API.

If it is not expected, could we get this bundle step added to the workflow so that current tools like `rollup-plugin-workbox` will perform more in line with what a user might expect?

**Comment by jeffposnick** [comment]
Thanks for pointing this out—`mode` is in fact an ignored parameter in `workbox-build`'s `injectManifest`, and it ended up being listed as supported by mistake due to some aggressive copy-and-pasting.

I'll update the documentation to make that clear, though I don't think we'll cause the usage of `mode` in `injectManifest` to fail parameter validation in v5, as that would be a breaking change. It's something we can disallow in v6, and warn about in v5.

As for the other question, I am aware that many Rollup users are looking for something similar to `workbox-webpack-plugin`'s `InjectManifest` mode, that will handle bundling and precache manifest injection in a single step. As there are now a few third-party solutions to this that use `workbox-build` "under the hood", I think we're just point folks to those, rather than changing `workbox-build`'s behavior to accommodate this use case.

I'd recommend reaching out to your Workbox Rollup plugin of choice and ask them if they would consider automatically doing the `process.env.NODE_ENV` replacement. (C.f. https://github.com/chromeos/static-site-scaffold-modules/issues/4)

**Comment by kkozlik** [comment]
As the mode is not supported, is there a way to insert non-minified manifest?
