### ISSUE TITLE
workbox-window.update() swallows errors

### ISSUE THREAD

**Issue by daffinm** [GoogleChrome/workbox#2435]
**Library Affected**:
workbox-window 5.1.2

**Browser & Platform**:
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"

**Issue or Feature Request Description**:
workbox-window.update() seems to swallow errors. For instance, if I am offline the catch block below is never executed, nor do I see any error messages in the console.
```javascript
wb.update().then(function () {
   // Do stuff
})
.catch(function (error) {
  // Handle error.
});
```

**Comment by jeffposnick** [comment]
`Workbox.update()` is a very thin wrapper on top of `ServiceWorkerRegistration.update()`, which explicitly kicks off the [service worker update flow](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#updates) (as opposed to waiting for the next implicit update check).

There's nothing in the service worker update flow that involves raising an exception or rejecting a promise if there's a failure when making the request for the new service worker file.

I know that there's another issue open with some feature requests to make `Workbox.update()` more useful, and that may happen in a future release of Workbox. In the meantime, though, the behavior you're seeing here is either expected. It amounts to a feature request, rather than a bug in the current behavior.

**Comment by daffinm** [comment]
> There's nothing in the service worker update flow that involves raising an exception or rejecting a promise if there's a failure when making the request for the new service worker file.

You seem to be right @jeffposnick. The error I was seeing when offline in my vanilla sw code were due to failed `importScripts` in the service worker script. 

I have added a fetch just before the call to `update()` to trigger an error if offline. 

```javascript
await fetch(scriptURL, {method: 'HEAD'}); 
```
Sorry to bother you.
