### ISSUE TITLE
CopyWebpackPlugin files not getting injected in __WB_MANIFEST

### ISSUE THREAD

**Issue by emilmuller** [GoogleChrome/workbox#2449]
Hi. I'm having an issue where the files getting copied to my output directory using CopyWebpackPlugin is not getting injected in the __WB_MANIFEST. My WebPack config is rather large, and there's a lot of things going on there, so I'd rather not paste it here. But please let me know if you need me to create a working example, or if I'm doing something wrong and this is not a bug. Here is an excerpt of my config file:

```
            new CopyWebpackPlugin(...),
            new InjectManifest({
                swSrc: "./src/service-worker.ts",
                dontCacheBustURLsMatching: /\.[0-9a-f]{20}\.(js|css)$/
            })
```

service-worker.ts:

```
import { precacheAndRoute } from 'workbox-precaching/precacheAndRoute';

precacheAndRoute((self as any).__WB_MANIFEST);
```

Using "workbox-webpack-plugin": "^5.1.2"

All other files are injected properly, just not the ones from CopyWebpackPlugin.

Kind regards, Emil Müller

**Comment by jeffposnick** [comment]
Apologies—this is because the literal characters `self.__WB_MANIFEST` are used as the replacement target, and that's not present in your  `src/service-worker.ts` file  (you have `(self as any).__WB_MANIFEST`).

Workbox should handle the necessary TypeScript typing for you via

https://github.com/GoogleChrome/workbox/blob/0f2ffda5537f13b4464ad60fc2a10838b3139f09/packages/workbox-precaching/src/precacheAndRoute.ts#L15-L19

(Or maybe you can get away with just adding `declare let self: ServiceWorkerGlobalScope;` at the top of your file if needed. I'm not 100% sure how TypeScript infers what `self` is.)

**Comment by emilmuller** [comment]
thanks! :)
