### ISSUE TITLE
Caching google fonts/stylesheets sometimes results in a missing font (using a fallback) until clearing my site cache.

### ISSUE THREAD

**Issue by jaunt** [GoogleChrome/workbox#2461]
workbox-sw
Safari Version 13.1 (13609.1.20.111.8) or possibly all browsers

Issue:  Caching google fonts/stylesheets very occasionally results in a user being stuck without the font (using a fallback) until clearing their browser cache for my website.

In my index.html
```
<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
```

In sw.js (using vue/cli 4.3.1 with the PWA plugin 4.3.1, InjectManifest mode)
```
// Cache the Google Fonts stylesheets with a stale-while-revalidate strategy.
workbox.routing.registerRoute(
  /^https:\/\/fonts\.googleapis\.com/,
  new workbox.strategies.StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

// Cache the underlying font files with a cache-first strategy for 1 year.
workbox.routing.registerRoute(
  /^https:\/\/fonts\.gstatic\.com/,
  new workbox.strategies.CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new workbox.cacheableResponse.Plugin({
        statuses: [0, 200],
      }),
      new workbox.expiration.Plugin({
        maxAgeSeconds: 60 * 60 * 24 * 365,
        maxEntries: 30,
      }),
    ],
  })
);
```

I first noticed this problem when also having ?family=Material+Icons in the stylesheet, as a user's browser could occasionally be forever stuck on showing the icon text rather than the icon itself.  Now I use MDI icons only, but I can still get the odd user not having the correct fonts and they have to clear cache.  So far I've only seen this happen on desktop safari but maybe that's just lucky.  And I've verified they are definitely "online" when this occurs.  

Is it possible that if they had bad internet during the first fetch, the problem occurs?  Like if it's too slow and switches to fall-back mode, and then somehow the service worker never tries to fetch again even when internet is better?

**Comment by jeffposnick** [comment]
> Is it possible that if they had bad internet during the first fetch, the problem occurs? Like if it's too slow and switches to fall-back mode, and then somehow the service worker never tries to fetch again even when internet is better?

Yes, that's definitely possible. Because you're opting-in to caching [opaque responses](https://stackoverflow.com/questions/39109789/what-limitations-apply-to-opaque-responses) (those with a status of `0`) in your `CacheFirst` config, you can't be sure that what you add to the cache is actually a valid font file and not some sort of error response. And using a `CacheFirst` strategy means that once the opaque response is added to the cache, it's never updated (until it expires after a year via the `workbox-expiration`).

I don't think you have any way of requesting non-opaque responses from Google Fonts, but you could, e.g., switch from using `CacheFirst` to `StaleWhileRevalidate` in your runtime caching strategy. That would ensure that any error responses that get cached will be "cleaned up" via the revalidation request in a timely manner.
