### ISSUE TITLE
The copyResponse() method should be limited to same-origin requests

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#2468]
The `Response` object in JavaScript has several [built-in security protections](https://bugs.chromium.org/p/chromium/issues/detail?id=669363&desc=2#c1) that we're kinda throwing out the window by exposing our [`copyResponse()`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-core#.copyResponse) helper object.

This method was originally intended to allow Workbox precaching to be able to work with redirected responses, but it probably makes sense to limit this ability to same-origin responses only.

**Comment by jeffposnick** [comment]
Just to elaborate—we specifically added this in to work around redirected responses for HTML documents due to a request for `something/index.html` in your precache manifest resulting in a 301 redirect to `something/`, which is a fairly common web server config.

Since that's a same-origin redirect, that scenario will continue to work.
