### ISSUE TITLE
what about cdn urls in precache? Latest info.

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2469]
**Library Affected**:
*workbox-sw, workbox-build, etc.*

I've seen lots of discussions about adding CDN origin for assets by @jeffposnick . Reading them all will confuse me more. So if it's possible, I will ask what's the final situation about this case in a workbox way?

Q1) I am using `manifestTransforms` and add my functions in it so that I transform urls myself. I add CDN if I want to or not. Is this how you decided to finally solve this problem?

Q2) Really interesting thing is that using CDN for assets might lead to one problem. Even though folks manage `CDN` themselves, it's possible that on `CDN` , one of the file mightn't be present, but it will still be put in our `manifest`. Now, if the urls start with CDN origin, when the service worker install starts, it's gonna fail for that single url which will cause failure of SW installation.  I use `precacheAndRoute`, but as far as I can see, if there's an error related to even file from 100 files, SW doesn't get installed, right?  So this seems a little bit risky for CDN Urls. Is this something you have thought about too and found no other way than just developers deciding to follow that risk or not ?

**Comment by jeffposnick** [comment]
I don't think that there's any difference between the approach here whether the URLs in your precache manifest are served from a CDN or server from your origin server.

The recommended deployment flow, whether you're deploying to a CDN or to an origin server, is to regenerate your service worker's precache manifest as part of your build process, and then push out that latest service worker as part of the same deployment that includes the corresponding updated assets.

One thing specific to a CDN is that you might need to purge your CDN's cache of unversioned URLs, like `service-worker.js`, if your CDN is also responsible for serving them.

Regarding your second question, the idea behind the precache manifest is that _all_ of the URLs listed need to be available and updated to the corresponding versions in order for the new service worker's installation to succeed. You're correct that any missing URLs, even 1 out of 100, will cause the installation to fail and the new service worker will become redundant. Installation will then be re-attempted the next time the service worker update flow happens.

I don't see why failures should be treated differently when the URLs are loaded from a CDN, and if you would prefer that missing URLs don't cause installation failure, you should use runtime rather than precaching for those URLs.

(If there's something unreliable about your CDN deployment process that causes URLs not to be present following a deployment, that sounds like an issue that you should fix regardless of whether you're using a service worker or not.)
