### ISSUE TITLE
is there  a way to precaching the files after install

### ISSUE THREAD

**Issue by closertb** [GoogleChrome/workbox#2471]
**Library Affected**:
*workbox-precaching.*

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
i want to use workbox to speed up the application with prercaching; but my project is a `Micro Front-end`, the sub project are independent, that means I can’t get the manifest json config when i build the project, so in service worker's install period, the precache list is not reachable;  the fileLists come from the perrmission API after user login,  it there a way to solve my situation?
![image](https://user-images.githubusercontent.com/22979584/80327223-f915f500-886d-11ea-8190-f62f24f8c043.png)

**Comment by novaknole** [comment]
You don't like the option of `run-time caching` in this case? it seems to me that those assets getting back from permission API are not precache assets anymore. Is there a specific reason why runtime wouldn't be a solution for you?

**Comment by closertb** [comment]
> You don't like the option of `run-time caching` in this case? it seems to me that those assets getting back from permission API are not precache assets anymore. Is there a specific reason why runtime wouldn't be a solution for you?

runtime cache is like when you went into a shop.. the sales ask what size shoes you wear, and the next time you got in she don't sak；but precache， it a feel like you got into the shop, the sales is already prepare a shoes for you;

am i right to understanding the defference between precache  and runcaching； 

i just want give the user what they want before he ask, because i already know what he want after he login

**Comment by jeffposnick** [comment]
You have a few options.

One would be to call `navigator.serviceWorker.register()` only after the user has logged in. If you delay registration until after whatever conditions are met, then the `install` event will also be delayed, and presumably it will succeed if it takes place after login.

Another option would be to register the service worker immediately, but ensure that the `install` event fails when the user isn't logged in. This might be because you precache a URL that will, e.g., return an HTTP 403 error prior to login. If the `install` event fails, then it will be retried the next time there's a navigation to a new URL under the service worker's scope, and eventually  the  `install` event will succeed (assuming the user logs in).
