### ISSUE TITLE
purgequota

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2473]
**Library Affected**:
*workbox-sw*

There's an `ExpirationPlugin` which we can assign to our routes. I couldn't find in the docs though one thing that clearly states what I need to hear.

 Does this clean up the whole cache for that specific route? if I set this to true for images in the specific cache called `app-images` and let's say quota is exceeded, will this clean up the whole `app-images` cache or some part of it to shrink the size to take it down under the storage limit again?

**Comment by jeffposnick** [comment]
The code will delete everything in the cache, along with any IndexedDB data used by the expiration code:

https://github.com/GoogleChrome/workbox/blob/fe4399505e02c3af6515fc8ffae8c58791f43f3c/packages/workbox-expiration/src/ExpirationPlugin.ts#L262-L289

**Comment by novaknole** [comment]
Yeah, So sorry for another question.

If I use `ExpirationPlugin` for 2 routes, even if those 2 routes have different `cacheName`,  if the storage limit exceeds, is workbox gonna delete everything in both caches? or the one which caused the exceed?

**Comment by jeffposnick** [comment]
It will delete  both of those caches.

The idea is that you want to get well under the quota limit by deleting as much as possible, so it will delete all the caches that you've opted-into deleting.

**Comment by novaknole** [comment]
yeah. I get that. It might be better to only try to delete the one which caused it. maybe it's enough to delete only one cache just to come down the limit ? why both ? That's what i am curious.

**Comment by jeffposnick** [comment]
The goal is to avoid getting the browser close to reaching the limit again for an extended period of time, so deleting as much as the developer has opted-into is the safest default approach.

If you'd prefer to use your own customized approach to recovering from quota errors, instead of setting `purgeOnQuotaError: true` in the `ExpirationPlugin`, you can register your own custom callback with `workbox-core`'s [`registerQuotaErrorCallback()` function](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-core#.registerQuotaErrorCallback).
