### ISSUE TITLE
Prefer matchCallbacks to RegExpRoutes in the docs

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2486]
Pretty much universally throughout our docs and samples, we end up using `RegExp`s for routing.

In retrospect, this ends up being fairly confusing and error prone, especially since we have to explain the nuances around cross-origin `RegExp` routing.

We should audit the current examples in the docs and when it makes sense to switch to a simple `matchCallback`, do so.

E.g.

```
registerRoute(
  /^https:\/\/fonts\.googleapis\.com/,
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);
```

makes much more sense as

```
registerRoute(
  ({url}) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);
```

**Comment by jeffposnick** [comment]
Fixed by https://github.com/google/WebFundamentals/pull/8680

**Comment by dman777** [comment]
I am having a similar issue. 

The front end web app is `https://bar-1.dev.foo.io/` but api calls(which I am trying to cache) are made to `https://bar-api-1.dev.foo.io/v1/bedlist_providers?size=16`. 

The service worker runs with no complaints. It's just not caching the api as it should:

```
registerRoute(
  /v1\/bedlist_providers\?size=/,
  new StaleWhileRevalidate({
    cacheName: 'providers-list'
  }),
);

registerRoute(
  /v1\/providers\/\d*\/bedlist\?size=/,
  new StaleWhileRevalidate({
    cacheName: 'bedlists'
  }),
```

I believe it is because the api route origin is different than what it is registered to. Any ideas what I can do?
