### ISSUE TITLE
Pass a new sameOrigin param to matchCallback

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#2487]
In the course of #2486 I realized there are a lot of places where I end up writing `url.origin === self.location.origin && ...`.

We could simplify this use case by passing in an additional parameter to the `matchCallback` function, `sameOrigin`, that's set to the result of evaluating `url.origin === self.location.origin` inside of the `Router`.

**Comment by dman777** [comment]
I am having a similar issue. 

The front end web app is `https://bar-1.dev.foo.io/` but api calls(which I am trying to cache) are made to `https://bar-api-1.dev.foo.io/v1/bedlist_providers?size=16`. 

The service worker runs with no complaints. It's just not caching the api as it should:

```
registerRoute(
  /v1\/bedlist_providers\?size=/,
  new StaleWhileRevalidate({
    cacheName: 'providers-list'
  }),
);

registerRoute(
  /v1\/providers\/\d*\/bedlist\?size=/,
  new StaleWhileRevalidate({
    cacheName: 'bedlists'
  }),
```

I believe it is because the api route origin is different than what it is registered to. Any ideas what I can do?

**Comment by jeffposnick** [comment]
You can use a [`matchCallback`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-routing#~matchCallback) as the first parameter to `registerRoute()` instead of a RegExp. That would probably end up being a lot cleaner for your use case.

```
registerRoute(
  ({url}) => url.origin === 'https://bar-api-1.dev.foo.io' &&
             url.pathname === '/v1/bedlist_providers',
  new StaleWhileRevalidate({
    cacheName: 'providers-list'
  }),
);
```
