### ISSUE TITLE
Using "Date" header causes issue with expiration plugin and Cloudflare users

### ISSUE THREAD

**Issue by garygreen** [GoogleChrome/workbox#2500]
I know this could be seen as a "issue with Cloudflare"/third party but because that service is so ubiquitous on the internet I think it needs to be a consideration.

When Cloudflare comes back with a response to e.g images it adds a `Date` header which contains the date the server SENT the request - it is NOT the date the image was last modified/updated. This causes issue with not invalidating the cache.

Instead, the `Last-Modified` header contains the actual date the content itself (e.g the image) was last modified.

According to the spec of the [Date](https://tools.ietf.org/html/rfc7231#section-7.1.1.2) header field:

> The "Date" header field represents the date and time at which the message was originated

This sounds somewhat ambigious and so you can see why Cloudflare is possibly using this header correctly or incorrectly.

Suggested fix - maybe we could have a way of using the `Last-Modified` header instead, as an option for the expiration plugin?

**Request for an image on cloudflare as made on 7th May 2020**

![image](https://user-images.githubusercontent.com/1702638/81303686-eec8d780-9073-11ea-80e3-85b75cf9e0a9.png)

As you can see the `Date` header contains essentially todays date, the `Last-Modified` header contains the actual last date the content itself was modified.

**Comment by jeffposnick** [comment]
What you're describing sounds like it's the expected behavior. `workbox-expiration` uses the time that a resource was actually cached by the service worker as the base time when determining what to expire. That would most closely match what the `Date:` header is set to in that example, not the `Last-Modified:` header.

(For situations in which `Date:` isn't available, like for most cross-origin requests, `workbox-expiration` just uses the current `Date.now()` value, which again, is most consistent with `Date:` in your example.)

To give a concrete example, if `workbox-expiration` is applied to an image cached at noon on Monday, with a configured `maxAgeSeconds: 24 * 60 * 60`, then that image wouldn't be a candidate for expiration until noon on Tuesday. If it took `Last-Modified:` into account, and `Last-Modified:` was set to, e.g., noon on the previous Sunday, then the image would effectively be considered expired immediately, since 24 hours had already passed between noon on Sunday and Monday.

**Comment by garygreen** [comment]
@jeffposnick I think your misunderstanding. Cloudflare essentially sets `Date` header to always be `now` which means EVERY time it comes back with a response it's always `now` and isn't reflective of the actual date of the content e.g. image.

> workbox-expiration uses the time that a resource was actually cached by the service worker as the base time when determining what to expire. That would most closely match what the Date: header is set to in that example

As per above, Cloudflare actually keep changing `Date` to match the date of the REQUEST. So it's not working as expected behaviour imo.
