### ISSUE TITLE
Persistent garbage collection/purging in expiration plugin - excessive usage and blocking render

### ISSUE THREAD

**Issue by garygreen** [GoogleChrome/workbox#2501]
We have our app configured to allow a maxium of 200 entries in cache. Once that 200 entries is reached - the next request will persistently add one to the cache, take one out, gargbage collect, .... and repeat:

For example:

1. Request for `image-1.jpg` - checks the cache and sees the cache limit has been reached, open index db, loop through all the entries, etc [....]
2. Request for `image-2.jpg` comes in and again the expiration plugin runs the garbage collection again, open index db, loop through [...]
3. Request for `image-3.jpg` comes in .... I think you can see where I'm going with this
... all of this happens in the space of **1 request** to a page.

This is causing issues in our app because this constant garbage collection is blocking the service worker and preventing our pages from loading.

Is there a more efficient way we can defer this garbage collection to run only *once* and after the browser is *idle*? Maybe in some kind of `requestIdleCallback(() => workbox.expiration.purge())` ?

Also we don't really mind if we exceed our `maxEntries` for one request temporarily, as long as it's cleaned up some time-ish after the request and old entries are purged.

**All in the space of 1 request to a page it's persistently adding one to cache and then removing one**
![image](https://user-images.githubusercontent.com/1702638/81311115-ec1eb000-907c-11ea-8d7e-b88387de8281.png)

**Comment by jeffposnick** [comment]
`workbox-expiration` is limited as to what it could do automatically here by restrictions on how the service worker can run code—only in response to an externally-fired event, like `fetch`—and the fact that when loading a given web page, there's really no concept of "this is going to be the last image request"—at least not in a meaningful way that could be conveyed to the `fetch` handler of a service worker. Running cache expiration logic as part of the promise chain that's passed to `event.waitUntil()` inside of a `fetch` handler seems like the best that's currently possible given what service workers support, but if folks do have ideas for automated alternatives, we're open to them.

If you want to get more manual about the implementation, you can follow the "[Advanced Usage](https://developers.google.com/web/tools/workbox/modules/workbox-expiration#advanced_usage)" section of the `workbox-expiration` docs rather than using the `ExpirationPlugin`. This would give you control over when the expiration checks take place, and you could implement a `message` handler in your service worker that listened for a specific incoming message type, and when it received it, called `expirationManager.expireEntries()`. Your client pages would be  responsible for calling `postMessage()` to your service worker to trigger this `message` handler, and  they could do that, e.g., inside of `requestIdleCallback()`.

Alternatively, you could leave your service worker out of it entirely, and just impose a maximum cache size from within the context of your client page by virtue of the fact that you can access the Cache Storage API via `window.caches`:

```
// Untested... you'd probably want to do something to guard
// against this being run multiple times simultaneously.
const MAX_CACHE_SIZE = 5;
const CACHE_NAME = 'cc-image';

requestIdleCallback(async () => {
  const cache = await window.caches.open(CACHE_NAME);
  const keys = await cache.keys();
  while (keys.length > MAX_CACHE_SIZE) {
    await cache.delete(keys.shift());
  }
});
```

**Comment by garygreen** [comment]
@jeffposnick thanks so much for your comprehensive answer. That section of the docs obviously flew over me - will definitely take a look. Handling of when workbox expires cached entries does seem better done manually. As you say service workers intercept all requests so there isn't always a concept of a "page" request - so way it works out the box is generally a one size fits all, even if it does come at a bit of a cost in garbage collection time.

Did also consider doing this outside the service worker level as have access to cache storage, so thanks for that example code 👍

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
