### ISSUE TITLE
Workaround for background sync for iPad safari

### ISSUE THREAD

**Issue by Kulkanilesh** [GoogleChrome/workbox#2516]
Hi Team,

My application is working fine with PWA and offline functionality on Chrome with windows desktop.
But same application is not working in iPad safari.
Our application is compatible with iPad. We used service worker, index-db to work application seamless in offline mode, but iOS-Safari doesnt support background sync.
Please provide any workaround or solution for same ASAP.
Thanks in advance.

**Comment by jeffposnick** [comment]
[`workbox-background-sync`](https://developers.google.com/web/tools/workbox/modules/workbox-background-sync) detects whether the Background Sync API is supported in the current browser. When it's not (as is the case in Safari), it will attempt to replay any queued requests each time the service worker thread starts up, instead of waiting for the Background Sync event.

That happens automatically, by default, so there's nothing specific that needs to be done.
