### ISSUE TITLE
Functionality missing from PrecacheController class only available in ./utils

### ISSUE THREAD

**Issue by maa105** [GoogleChrome/workbox#2520]
**Library Affected**:
workbox-precache.

**Browser & Platform**:
all browsers.

**Feature Request Description**:
There are functionalities missing from the PrecacheController class only available in the default precacheController. Namely `getCacheKeyForURL` with options (ignoreURLParametersMatching, directoryIndex, cleanURLs, urlManipulation) and `addFetchListener` these are available on the root but sadly if you want more advanced usage by using the PrecacheController you cant use them (there is the `createHandler` but it isn't enough). what I did in [my fork](https://github.com/maa105/workbox) is moved the functionality from the utils to the PrecacheController class without breaking any existing functionality. I did not do any test cases for it  yet. I believe this feature is paramount for advanced usage. Should I issue a pull request? Tell me how you want to proceed. AND 1,000,000 thanks for this useful module.

**Comment by jeffposnick** [comment]
Hello!

Thanks for asking about contributing. @philipwalton is working on a rewrite that touches a lot of the code in `workbox-precaching` targeted for our v6 release. The WIP PR is https://github.com/GoogleChrome/workbox/pull/2459

Given that, I don't think it would make sense for you to contribute that sort of PR until the v6 code stabilizes. Perhaps either the changes that will be introduced in v6 will make it easier to accomplish what you want without having to change anything, or otherwise, you might want to coordinate with @philipwalton on submitted a PR that will work with v6.

**Comment by tropicadri** [comment]
Since v6 `getCacheKeyForUrl` is in PrecacheController and `PrecacheRoute` was added to match incoming requests and handle fetching responses from the precache.

I'm closing this issue if there is still missing functionality we can revisit and reopen.
