### ISSUE TITLE
[Strategy] FreshCache

### ISSUE THREAD

**Issue by jakobrosenberg** [GoogleChrome/workbox#2523]
**Library Affected**:
*workbox-strategies

**Issue or Feature Request Description**:
I'm working on [Routify](https://routify.dev) which aims to provide prefetching of external assets as well as offline availability. 

Prefetching can be handled with CacheFirst and a short expiration, but I'm unable to combine it with a fallback cache for offline use.

Ideally fetching would be handled in the following order:
- If (cached response is fresh) serve from cache
- else if (online) fetch
- else use cache

Would this be doable as a strategy or is there a better approach?

**Comment by jeffposnick** [comment]
That sounds useful. I hope it works out!

https://github.com/GoogleChrome/workbox/pull/2455 in the `v6` branch will make it easier for third parties to create what is otherwise indistinguishable from an "official" `workbox-strategy`.

Pre-`v6`, your best bet is to create a function that uses the [`handlerCallback` interface](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-routing#~handlerCallback), which can then be dropped in to any `Route`.

You can mostly get what you're describing out of the box by using `CacheFirst` + `ExpirationPlugin`, but the one wrinkle is step 3, where you fall back to a cached response that isn't fresh. In order for that to work without the possibility of the `ExpirationPlugin` deleting the stale cached entry first, you need to start you `handlerCallback` by reading from the cache and saving a reference to the cached response, potentially using it later.

(Not that `ExpirationPlugin` needs to read the `Date:` header of a response to figure out if it's "fresh" before using it, and [CORS or opaque responses](https://jeffy.info/2019/07/22/exposing-cors-headers.html) normally won't have that header exposed.)

This is untested, but it should put you in the right direction:

```
import {CacheFirst} from 'workbox-strategies';
import {registerRoute} from 'workbox-routing';
import {ExpirationPlugin} from 'workbox-expiration';

const cacheName = 'my-cache-name';
const maxAgeSeconds = 24 * 60 * 60;

const cacheFirst = new CacheFirst({
  cacheName,
  plugins: [
    new ExpirationPlugin({
      maxAgeSeconds,
    }),
  ],
});

const customHandler = async (params) => {
  let cachedResponse;
  try {
    // Grab cachedResponse before ExpirationPlugin potentially removes it.
    cachedResponse = await caches.match(params.request.url, {
      cacheName,
    });

    // This will throw if there's no response from either the cache or network.
    const response = await cacheFirst.handle(params);
    return response;
  } catch (error) {
    if (cachedResponse) {
      return cachedResponse;
    }

    // If we don't have anything, just return a NetworkError.
    return Response.error();
  }
};

registerRoute(
  // Put your custom routing predicate here.
  // In this case, match all navigation requests.
  ({request}) => request.mode === 'navigate',

  // Provide your custom handlerCallback here.
  customHandler,
);
```

We can reopen this if it doesn't work for you.

**Comment by jakobrosenberg** [comment]
Thanks for the feedback @jeffposnick. Much appreciated!

I wrote a strategy-combo prior to your reply. I hope it doesn't sound off any alarms.

```javascript
/**********
 * ROUTES *
 **********/

// serve local pages from the SPA entry point (__app.html)
registerRoute(isLocalPage, matchPrecache(entrypointUrl))

// serve local assets from cache first
registerRoute(isLocalAsset, new CacheFirst())

// serve external assets from cache if they're fresh
registerRoute(wasRecentlyFetched, new CacheFirst(externalAssetsConfig()))

// serve external pages and assets
setDefaultHandler(new NetworkFirst(externalAssetsConfig()));
```

The function `wasRecentlyFetched` keeps an internal map of request.urls and `validUntil` timestamps. On new requests, invalid request.urls are pruned and new requests are added, if they don't already exists.

This allows me to use request headers such as ``x-prefetch-valid-for`` to set a `validUntil` time.
