### ISSUE TITLE
skipWaiting in message handler doesn't work

### ISSUE THREAD

**Issue by zdila** [GoogleChrome/workbox#2525]
**Library Affected**:
workbox-core

**Browser & Platform**:
"all browsers"

**Issue or Feature Request Description**:

Calling `skipWaiting()` in `message` event handler does nothing. Instead calling `self.skipWaiting()` works. Tested in latest stable Chrome and Firefox.

Application uses webpack an InjectManifest plugin.

```javascript
import { skipWaiting } from 'workbox-core';

addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
   // skipWaiting(); // does nothing
    self.skipWaiting(); // works
  }
});

// ...
```

**Comment by jeffposnick** [comment]
The `skipWaiting` function in `workbox-core` wraps the call to `self.skipWaiting()` inside of an `install` event handler:

https://github.com/GoogleChrome/workbox/blob/8ffe56090f712e9b8bb6cff14e25f7ec090a1ce4/packages/workbox-core/src/skipWaiting.ts#L22-L26

I have wondered how much value is added by `workbox-core`'s `skipWaiting()`, since it should be "safe" to call `self.skipWaiting()` outside of an `install` handler. (The same isn't the case for `self.clients.claim()`, which [throws an exception when called](https://w3c.github.io/ServiceWorker/#dom-clients-claim) unless there's an active service worker.)

I'm in favor making a change in v6 that just makes `workbox-core`'s `skipWaiting()` call `self.skipWaiting()` directly, without the `install` event wrapper, and logs a message in `dev` mode telling folks to migrate to using `self.skipWaiting()` directly. And then maybe we'll remove `skipWaiting()` in v7.
