### ISSUE TITLE
swDest in a subdirectory seems to cause incorrect generated paths

### ISSUE THREAD

**Issue by domenic** [GoogleChrome/workbox#2530]
**Library Affected**: workbox-cli

**Browser & Platform**: all browsers

**Issue or Feature Request Description**:

My workbox configuration file looks like the following:

```js
'use strict';

module.exports = {
  globDirectory: 'www/',
  globPatterns: [
    '**/*.{html,jpg,mjs,css}'
  ],
  swDest: 'www/service-worker/sw.js'
};
```

(This was generated from `npx workbox wizard`, then fixed to make ESLint pass.)

That is, my app is located in `www/`, and I want to generate a service worker in `www/service-worker/sw.js`. (That is, I want the 4 files workbox generates to go into `www/service-worker/`, instead of all over my root `www/`.)

However, the generated files don't seem to account for the service worker being in a subdirectory. They contain lines like

```js
{url:"images/pea-protein.jpg",revision:"b9d1be7cf1fa59d0982288f2149e9167"}
```

which cause the following problem in the JS console

```
WorkboxError.js:28 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"http://localhost:5000/service-worker/images/pea-protein.jpg","status":404}]
    at y.u (http://localhost:5000/service-worker/workbox-1bbb3e0e.js:1:5420)
    at async Promise.all (index 1)
    at async y.install (http://localhost:5000/service-worker/workbox-1bbb3e0e.js:1:4833)
```

i.e. it is looking for `images/pea-protein.jpg` *in the `service-worker/` directory*, not relative to the root.

You can see the full project setup at https://github.com/domenic/remember-to-eat/commit/8166ddcee87c63092618152dc5fd992d335b2151, although I have not deployed that commit to a live URL since it's broken. I'm happy to do so if that would be helpful.

This seems like a bug---especially given that the config file was generated by the wizard---so I'm reporting it here instead of Stack Overflow. But maybe there's a better config file I should be writing...

**Comment by jeffposnick** [comment]
👋 @domenic!

I wanted to cover two points:

First, the `wizard` experience is unfortunately not going to ask about all the [possible options](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.generateSW). (I'm honestly not sure how useful the `wizard` flow is anymore, as the configuration has grown since we originally developed it.) One option that you can add to your configuration, if you need to adjust the URLs that are generated in the manifest, is `modifyURLPrefix`. Something like:

```
module.exports = {
  // ...other options...
  modifyURLPrefix: {
    '': '../',
  },
};
```

would automatically prepend `'../'` to the start of your manifest's URLs. You can get "more fancy", if you need, via the `manifestTransforms` callback as well.

Second, and this gets to the root of why the generated manifest might not meet your expectations, are you sure you want to host your service worker script from the URL `/service-worker/sw.js`? Because of service worker [scoping restrictions](https://stackoverflow.com/a/35415127/385997), that means the only web pages that the service worker can control are pages whose URL prefix is also `/service-worker/`, and I'm assuming that you're not actually using that URL prefix for your HTML.

If you were to use the `Service-Worker-Allowed` response header, you could override that restriction, and using `modifyURLPrefix` would then allow you to "fix" your URLs. But the expectation is that most folks would end up needing to serve their service worker script from their WWW root in order to give their service worker a change to control pages.

**Comment by domenic** [comment]
> Second, and this gets to the root of why the generated manifest might not meet your expectations, are you sure you want to host your service worker script from the URL /service-worker/sw.js? Because of service worker scoping restrictions, that means the only web pages that the service worker can control are pages whose URL prefix is also /service-worker/, and I'm assuming that you're not actually using that URL prefix for your HTML.

Ah, thanks! I guess that is not what I want, after all. And probably adding the `Service-Worker-Allowed` header is not worth it just to keep the 4 generated files quarantined to their own folder. I'll just have to live with a messy root directory.

At this point my issue is solved, but I'll let you decide whether to close this, or use it as a tracker bug to try to give better error messages. (Perhaps `workbox generateSW` could give an error when it generates a service worker with paths, like `service-worker/images/pea-protein.jpg` in my example, that don't exist?)

**Comment by jeffposnick** [comment]
The difficult part of that is that a standalone build tool doesn't know how your web hosting environment is set up. Figuring out whether `service-worker/images/pea-protein.jpg` is a valid URL is doable if we can safely assume that your web server just hosts static documents starting from a given directory as your WWW root, but that assumption falls apart for even moderately complex web servers—which is why we expose `modifyURLPrefix` and `manifestTransforms` to allow folks to adjust their URLs as needed.

(If your overall goal is to have fewer files in your top-level directory, adding `sourcemap: false` and `inlineWorkboxRuntime: true` to your  config will lead to only a single generated file, but you'll lose out on some update optimizations from breaking out the Workbox runtime code from the top-level service worker that contains your precache manifest.)
