### ISSUE TITLE
Use with webpack compression plugin? 

### ISSUE THREAD

**Issue by rossPatton** [GoogleChrome/workbox#2542]
Welcome! Please use this template for reporting bugs or requesting features. For questions about using Workbox, the best place to ask is Stack Overflow, tagged with `[workbox]`: https://stackoverflow.com/questions/ask?tags=workbox

**Library Affected**:
Workbox Webpack Plugin

**Browser & Platform**:
All Browsers

**Issue or Feature Request Description**:
Out of the box use of the plugin caches all assets. I pre-compress my assets on build - so there are 3 versions of every file (uncompressed, gzipped, and brotli). After the initial cache on service worker registration, I get errors when testing with lighthouse. Performance tanks.

The culprit seems to be 'avoid enormous network payloads'. It appears that the service worker doesn't just return the appropriate file (gzipped or brotli) but returns all three, effectively tripling the amount of javascript that has to be downloaded/parsed.

It wasn't clear to me from the documenation how to fine-tune the plugin.

In an related issue, I have static assets that i'm just copying into the dist folder instead of building with webpack, and I would like to be able to serve these with a service worker as well.
 
Following screenshot is in development mode with inline source-maps, hence the large file sizes. But still - it appears as though files are being included more than once?
<img width="722" alt="Screen Shot 2020-06-14 at 1 49 54 AM" src="https://user-images.githubusercontent.com/2379901/84585803-64496580-ade1-11ea-87f9-f9405a7a488a.png">

**Comment by jeffposnick** [comment]
Hello @rossPatton!

You can use `exclude: [/\.br$/, /\.gz$/, /\.map$/]` (tweaked with additional file extensions as needed) to exclude a subset of `webpack`-generated assets from your precache manifest.

My recommendation would be to use the [`CopyWebpackPlugin`](https://webpack.js.org/plugins/copy-webpack-plugin/) instead of a manual process for adding to your `dist` directory, as keeping everything within the `webpack` asset pipeline should make things "just work" with Workbox (and any other plugins you might be using). But if you need to have a separate process for adding to your `dist` folder, *and* you want those URLs precached, you're going to need to have some way of getting a list of each URL and associated hash of its contents in advance, and then use the `additionalManifestEntries` configuration parameter in the Workbox plugin to add those in to your generated precache manifest. You are responsible for ensuring that whenever the contents of one of those URLs changes, the associated `revision` parameter in the precache manifest also changes, or else those URLs won't be properly updated in users' local caches.

The relevant documentation for these configuration options is at https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW
