### ISSUE TITLE
#issue-635754570 seems to be broken if requests happen for the same name

### ISSUE THREAD

**Issue by novaknole** [GoogleChrome/workbox#2555]
Hi @jeffposnick ... I've been trying to get my head around this issue, but with no luck. Hope you can shed some lights.

If you go to this url ( https://github.com/GoogleChrome/workbox/issues/2534#issue-635754570 ) you will notice that's your function written.

It appeared that As you can see on that page, that I've used it and said it works fine. but today, I realized it has a problem.

Let's say that my app makes requests for two files at the same time.

* test.hash123.js

* test.hash456.js

Let's say I am using `CacheFirst`  strategy and using your plugin (`cacheDidUpdate`) from that link

Now, it appears that after making two requests, my cache will end up having no entries instead of having 2 results(test.hash123.js, test.hash456.js`)...

Reason is (At least I think), when these 2 requests get made paralelly, both of them goes into `cacheDidUpdate` when there're already 2 requests cached. and request 1 removes request 2 from cache and request 2 removes request 1 from cache (ending up no results in cache). This might be because of parallelism and threads. Can you confirm that ? This will only happen if filenames are the same, even though hashes will be different..

Don't you agree ? and what workaround can you suggest ? 

Thanks in advance.

**Comment by jeffposnick** [comment]
If both of those requests were made at effectively the same time, then yes, the code as written could end up removing both from the cache.

It's possible to coordinate things so that the SW (which is single-threaded) won't kick off another execution of the asynchronous `cacheDidUpdate` callback until a previously started one completes. I updated the example in https://github.com/GoogleChrome/workbox/issues/2534 to include an `isCurrentlyRunning` flag that should prevent that.

It's really not clear _which_ copy of `test.hash.js` would end up in your cache, though, since either of those two requests might end up being the one that "wins." In general, this model for cache expiration works better if once a given resource has been updated with a new hash, there aren't requests made for the resource with the old hash.

**Comment by novaknole** [comment]
Just to clarify your last comment... This is not about hashes at all. It's about hashes + names. since names are the same, and only hashes are different, that's why it happens that one request removes second, second removes first.

**Comment by novaknole** [comment]
@jeffposnick your solution still doesn't work..

Looks like only one of them ends up in cache... not both of them..   It seems like for those 2 requests, only one of them will get made. other one will just execute `return` statement in `if (hashExpirationPlugin.isCurrentlyRunning) {` . And which of them gets into that function, will remove the other one. That's why only 1 entry will be present in the end..


Seems like I can't find any solutions. starting to believe only choice is to have different filenames for each file + hash.

**Comment by jeffposnick** [comment]
The recipe in https://github.com/GoogleChrome/workbox/issues/2534#issue-635754570 definitely assumes that each unique  subresource is going to have its own "file name" portion (basically, the thing before the hash). If the file names are the same but the hashes are different, then the recipe considers them two versions of the same resource, and will only keep one.

If you're saying that `test.hash123.js` are `test.hash456.js` not two versions of the same subresource, but instead two separate subresources and you _want_ to keep both, then using that expiration recipe isn't appropriate for your use case.

**Comment by novaknole** [comment]
I think I am gonna build these kind of files `test-hash123.hash123.js` and `test-hash456.hash456.js`. Now it will work, but if that file changes, its hash will change, but your function won't delete the old ones.. So I will have cache expiration for these assets as a day. Problem solved... :D Thanks Jeff.
