### ISSUE TITLE
Allow dontCacheBustURLsMatching to accept an array

### ISSUE THREAD

**Issue by joetidee** [GoogleChrome/workbox#2563]
**Library Affected**:
workbox - InjectManifest

**Browser & Platform**:
N/A

**Issue or Feature Request Description**:
Could dontCacheBustURLsMatching please accept an array of regex patterns?

**Comment by jwagner** [comment]
I presume you must have a reason for not wanting to join them into a single expression, [/foo/,/bar/]->/(foo|bar)/ but I can't come up with a case where that would not be possible from the top of my head. Could you share a few more details about your usecase?

**Comment by joetidee** [comment]
I was thinking about our bundles. These are primarily located:

/static/modern/bundles/scenes/checkout/summary/summary.c4485ndf5k9b.js
/static/modern/bundles/scenes/checkout/complete/complete.c4485ndf5k9b.js
/static/modern/bundles/components/common-component.we9n4589c45dffg7.js
/static/modern/bundles/components/map/map.c489fneai8f4gfs.js

So, if we are required to target these bundles, the regex gets fairly busy:

`/^\/static\/modern\/bundles\/(scenes|components)\/([a-z0-9-]+\/)*[a-z0-9-]+\.[a-z0-9]+\.js$/`

... and this is just for bundles.

**Comment by jeffposnick** [comment]
With https://github.com/GoogleChrome/workbox/pull/2673 in place, _most_ of the time you shouldn't need to use `dontCacheBustURLsMatching` with `workbox-webpack-plugin` v6+. So if you're using `webpack`, this shouldn't be as much of an issue.

Assuming you're not using `webpack`, you don't need to match the entire URL in your RegExp. I think you could get away with using `/\.[0-9a-f]{16}\.js$/` as the RegExp for your examples, instead of your more involved RegExp. (That assumes that your hashes are 16 hex characters, surrounded by `.`, and immediately followed by `'js'`.)
