### ISSUE TITLE
index.html appears twice in my precache

### ISSUE THREAD

**Issue by fgruchala** [GoogleChrome/workbox#2578]
**Library Affected**:
*workbox-sw v5.1.2, workbox-cli v4.3.1* 

**Browser & Platform**:
*Google Chrome v83 for Desktop*

**Issue or Feature Request Description**:
*It seems that my precache manage 2 index.html files with two different WB_REVISION (see the screenshot below). Consequently, with chance, I just have to Ctrl+Shift+R to clean the old index.html and see my changes or with less chance, its occurs a blank page due to missing old Javascript scripts referenced by the old index.html.*

![Capture d’écran 2020-07-14 à 16 28 10](https://user-images.githubusercontent.com/12196721/87439067-9ae8ea80-c5f0-11ea-9587-e33dda02e616.png)

*Here is an extract of my service-worker.js*

```
importScripts('https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-sw.js')

if (workbox) {
  // Expiration time
  const oneDay = 24 * 60 * 60
  const oneWeek = oneDay * 7

  workbox.core.setCacheNameDetails({
    prefix: 'lt',
    precache: 'precache'
  })

  // Pre-caching static files
  workbox.precaching.cleanupOutdatedCaches()
  workbox.precaching.precacheAndRoute([])

  // Fallback navigation route
  const handler = workbox.precaching.createHandlerBoundToURL('/index.html')
  const navigationRoute = new workbox.routing.NavigationRoute(handler)
  workbox.routing.registerRoute(navigationRoute)

  ...
```

*And an extract of my workbox.config.js*

```
module.exports = {
  swSrc: 'public/service-worker.js',
  swDest: 'dist/service-worker.js',
  globDirectory: 'dist',
  globPatterns: [
    'index.html',
    'favicon.png',
    'manifest.json',
    '...'
  ]
}
```

*Do you have an idea about what's going on ? This behavior is quite hazardous, it works at times very well and sometimes not.*

**Comment by jeffposnick** [comment]
What you're seeing is two different revisions of your `index.html`, because you previously had an older service worker installed, and then a new one was installed as well (but hasn't yet activated). This new service worker is what's known as the ["waiting" service worker](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#waiting). As soon as the new service worker activates, the older revision of your `index.html` will be cleaned up automatically by `workbox-precaching`.

You could avoid having the newly installed service worker wait by calling `self.skipWaiting()` inside your code, but that has some implications around, e.g., [lazy-loaded URLs](https://pawll.glitch.me/) that the old HTML, which is currently open on the page, might require.
