### ISSUE TITLE
Cache a specific page / Conditional Caching (Next.js)

### ISSUE THREAD

**Issue by beazo** [GoogleChrome/workbox#2634]
**Library Affected**:
workbox-build v4.3.1

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
Using WorkBox, is it possible to only cache a specific page on user action? (i.e button click)

The below config caches everything, but is there any option that will only execute this runtime caching for a specific page? (or better yet, on user action) I don't need any other pages cached.

```
const offlineConfig = {
...
    runtimeCaching: [
      {
        urlPattern: /^https?.*/,
        handler: "NetworkFirst",
        options: {
          cacheName: "everything",
          expiration: {
            maxEntries: 200,
          },
        },
      }
    ],
...
};
```

NOTE: caching a specific page being everything needed for that page to run in offline mode.

**Comment by TheForsakenSpirit** [comment]
@beazo Not shore what you wont to do. But, if you use ganarateSW you can use [this](https://developers.google.com/web/tools/workbox/guides/using-plugins#workbox_plugins) plugin for filter by specific header. Just add header to your`s request. Check [this](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.RuntimeCachingEntry) for configuration this plugin in ganarateSW.

**Comment by Lucide** [comment]
Since you need some custom behaviour, I would suggest moving away from a fully generated SW to a handmade one, you can start from the generated code and customize from there.

Then you could call [`registerRoute()`](https://developers.google.com/web/tools/workbox/guides/route-requests#matching_a_route_with_a_regular_expression) conditionally on a flag stored in the permanent storage (like indexedDB).\
Set that flag at the push of a button and reload the page.

Perhaps, calling `precacheAndRoute()` might be a better choice here, it populates the cache with the files listed in the "precache manifest" immediately, instead of doing it "live" for every request. You'll need to [understand how it works](https://developers.google.com/web/tools/workbox/guides/precache-files) to use it properly. You won't need to reload the page this way. read also [here](https://developers.google.com/web/tools/workbox/modules/workbox-precaching).

**Note** that in any case, the "caching has been enabled" flag will have to be consistent between page reloads, so you'll need to use some permanent storage to store it, perhaps IndexedDB, that Workbox uses too. Client<->Service Worker communication is done through messages.

I've seen you're not using the latest stable Workbox version.

**Comment by jeffposnick** [comment]
There's nothing "built in" to Workbox that would accomplish this. I can suggest something that used a custom [`handlerCallback`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-routing#~handlerCallback), but honestly, unless you want any other additional functionality beyond what you describe, it would probably be easier to do this as a "vanilla" service worker and not use Workbox at all. Here's how.

First, in your web app, call the following function in response to whatever user interaction you'd like, and it will add the current page's HTML and all of the subresources it has loaded to the Cache Storage API (in a cache named `'page-cache'`):

```
async function cacheCurrentPageAndSubresources() {
  const urlsToCache = [
    location.href,
    ...performance.getEntriesByType('resource').map((r) => r.name),
  ];

  const cache = await caches.open('page-cache');
  await cache.addAll(urlsToCache);
}
```

Then, your service worker would just need to be something along the lines of (make sure you use the same `'page-cache'` name):

```
self.addEventListener('fetch', (event) => {
  const networkThenCache = async () => {
    try {
      // Always go to the network first.
      return await fetch(event.request);
    } catch (error) {
      // If there was a network error, attempt to go to the cache.
      // Note that this will never *update* the cache, just read from it.
      const cache = await caches.open('page-cache');
      const cachedResponse = await cache.match(event.request);
      if (cachedResponse) {
        return cachedResponse;
      }

      // If there was a cache miss, we can't do much.
      // Just re-throw the network error.
      throw error;
    }
  };

  event.respondWith(networkThenCache());
});
```

Cache management is up to you—the entries that you added to the cache via the main page will never get purged, or updated automatically. But that's the basic functionality you asked for.

**Comment by beazo** [comment]
Thanks @jeffposnick! 

Sorry for late reply, I'm still working on this but if I find a solution I'll be sure to add it here for any others who are interested in the solution.
