### ISSUE TITLE
create-react-app service worker issue.

### ISSUE THREAD

**Issue by DhilipThangaraj** [GoogleChrome/workbox#2636]
Hey guys,

My project is basically react with redux based application. as we know,react application generally have the service worker enabling/disabling mechanism in src/index.js serviceWorker.register()/serviceWorker.unregister() at the creating time, so that will have the ability to turn our application with PWA support.

Our project came with the approach recently ,we had to control the serviceWorker.register()/serviceWorker.unregister() by some server config property, so when we hit our application at first time we get the server config as pwaEnabled: true that i was keeping in the redux state and trying to control the serviceWorker.register()/serviceWorker.unregister() in index.js.

For some reason, my service worker was not getting registered properly ,i went ahead and kept some console logs statements inside the src/serviceWorker.js then i got to know that window.addEventListener("load", () => {}) somehow was not getting called so only sw registration not happened .whereas if i was not controlling by any conditions serviceWorker.register()/serviceWorker.unregister() in index.js would just works fine and able to get access of PWA..

Here if anybody help on this why am not able to control the serviceworker registration function by condition, that would be great.

Thanks in advance

**Comment by jeffposnick** [comment]
`window.addEventListener("load", () => {})` should cause the callback function to [execute whenever the `window`'s initial resources are ready](https://whistlr.info/2020/understanding-load/). That code really doesn't have anything to do with Workbox or service workers.

If you're not seeing your callback function executed, then it might be because you're adding the `window.addEventListener("load", () => {})` statement dynamically to your web app's code, after the `load` event has already fired? It's hard for me to say.

In any case, it's not clear that this is a question directly related to using Workbox. If you have specific code to share that's related to Workbox which reproduces the issue you're describing, perhaps we'll be able to help and I will reopen this issue.
