### ISSUE TITLE
RegExpRoute not working fine

### ISSUE THREAD

**Issue by MostafaSh** [GoogleChrome/workbox#2658]
**Library Affected**:
*workbox-routing*

**Browser & Platform**:
*Google Chrome Version 86.0.4240.111 (Official Build) (64-bit)*

**Issue or Feature Request Description**:
*RegExpRoute not working fine*
there is no error or any useful info coming out of workbox to mention there, so all i can give you is a description of problem and it's possible cause.

*what is the problem ?*
sometimes, some requests are not handled. while they have a valid route registered in service worker.

*the ways u may be able to produce  the problem ?*
- when I used registerRoute and passed regex as it's first entry
- when I used a custom Router and used RegExpRoute to define route

*how this happens ?*
when 2 or more requests are called with short delay some of them are not detected as a defined route, **no matter wether they are from the same route or not**.

*how I am sure this is a bug ?*
Im not ! but there is a clue leads me to this.

using regex this way solved the problem:
`registerRoute(
({url, request, event}) => {
        return  /PATTERN/g.test(url.href)
    },
 ...`
or
`router.registerRoute(
    new Route(
        ({url, request, event}) => {
            return  /PATTERN/g.test(url.href)
        },
 ...`

**Comment by jeffposnick** [comment]
`RegExpRoute` is a bit picky about how it handles, e.g., full URLs. There are more details at https://developers.google.com/web/tools/workbox/guides/route-requests#matching_a_route_with_a_regular_expression and if you're running the development, rather than production, build of Workbox you may get some helpful console log messages about what's going on.

In general, though, we've been steering developers more in the direction of a [`matchCallback`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-routing#~matchCallback) and away from `RegExpRoute`s recently. That's the working code that you mention at the end.
