### ISSUE TITLE
self.__WB_MANIFEST is replaced only on the first occurrence

### ISSUE THREAD

**Issue by ItalyPaleAle** [GoogleChrome/workbox#2681]
**Library Affected**:

*workbox-webpack-plugin*

**Browser & Platform**:

Webpack 5
Workbox 6.0.0-rc.0

**Issue Description**:

I have this code in my service worker:

```js
if (self.__WB_MANIFEST) {
    console.log('precached', self.__WB_MANIFEST)
    precacheController.addToCacheList(self.__WB_MANIFEST)
}
```

And this in the webpack config:

```js
        new InjectManifest({
            swSrc: './src/sw/sw.js',
            include: undefined,
        }),
```

After building this (without minification), the output files has `self.__WB_MANIFEST` replaced with the manifest only on the first occurrence:

```js
// Manifest omitted
if ([{...}]) {
    console.log('precached', self.__WB_MANIFEST)
    sw_precacheController.addToCacheList(self.__WB_MANIFEST)
}
```

Instead, the manifest should have been replaced in all occurrences.

**Comment by jeffposnick** [comment]
This is a difference in behavior between `workbox-build`'s version of `injectManifest`, and `workbox-webpack-plugin`'s `InjectManifest`. In `workbox-build` we treat multiple instance of `self.__WB_MANIFEST` as a fatal error:

https://github.com/GoogleChrome/workbox/blob/f2ef9126f36cbf1219e9c27997ac0c4d873a0ca8/packages/workbox-build/src/inject-manifest.js#L152-L153

I am going to standardize things so that `workbox-webpack-plugin` does the same instead of just silently replacing the first instance.

The rationale behind this behavior is that the precache manifest might be lengthy, and storing multiple copies of it in the same service worker file is a waste of bytes. You can do the following if you'd like to, e.g., log it and also pass it to `workbox-precaching`:

```
const manifest = self.__WB_MANIFEST;
if (manifest) {
    console.log('precached', manifest);
    precacheController.addToCacheList(manifest);
}
```

**Comment by ItalyPaleAle** [comment]
Thanks. That's what I ended up doing indeed and I understand the rationale.

However, can I recommend showing an error in the console if people try to replace it more than once? Right now, it silently fails and that made me spend quite a bit of time trying to debug this.

**Comment by jeffposnick** [comment]
Yup, I'm going to treat this as a compilation error in v6.

**Comment by tangdexin** [comment]
i have the same error

**Comment by jeffposnick** [comment]
@tangdexin, please only include the symbol `self.__WB_MANIFEST` in your `swSrc` file once. If you need to refer to the manifest multiple times, assign `self.__WB_MANIFEST` to a variable first:

```js
const manifest = self.__WB_MANIFEST;

// Do whatever you want with `manifest`:
if (manifest) {
    console.log('precached', manifest);
    precacheController.addToCacheList(manifest);
}
```

**Comment by tangdexin** [comment]
> 



> @tangdexin, please only include the symbol `self.__WB_MANIFEST` in your `swSrc` file once. If you need to refer to the manifest multiple times, assign `self.__WB_MANIFEST` to a variable first:
> 
> ```js
> const manifest = self.__WB_MANIFEST;
> 
> // Do whatever you want with `manifest`:
> if (manifest) {
>     console.log('precached', manifest);
>     precacheController.addToCacheList(manifest);
> }
> ```

It works , thanks very much

**Comment by Alkaidd** [comment]
version: "workbox-webpack-plugin": "6.6.0"
In this version, i have the same error even if i commented out "self.__WB_MANIFEST" while run dev.
For example:
```javascript
const ignored = self.__WB_MANIFEST;
// precacheAndRoute(self.__WB_MANIFEST)
```
This will cause same error in dev, but work well in build.
After deleting the comment, i run dev successfully.

**Comment by FleetAdmiralJakob** [comment]
Same issue here. Commented out __SW_MANIFEST counts as it is not commented out.
