### ISSUE TITLE
Blank page on redepoly (InjectManifest Mode)

### ISSUE THREAD

**Issue by AlvinTCH** [GoogleChrome/workbox#2707]
Library Affected:
"workbox-webpack-plugi": "^6.0.2",

Browser & Platform:
Chrome, firefox and safari browsers on all platforms

Issue or Feature Request Description:
I bundle my website/PWA using the workbox-webpack-plugin. When I redeploy, there will be a blank screen issue. The error message is usually "Uncaught SyntaxError: Unexpected token '<'" for vendor.****.js. On closer inspection, I could see that the old service worker is running and the new worker is waiting to activate even though I have implemented SkipWaiting using the advanced recipes under https://developers.google.com/web/tools/workbox/guides/advanced-recipes.

I also have referred to and implemented solutions found in https://github.com/GoogleChrome/workbox/issues/2053 and https://github.com/GoogleChrome/workbox/issues/1528. It is not exactly very useful because due to this error, the js files inside the app is not loading.

Attached below are the screenshots with error messages

![skipwaiting fails](https://user-images.githubusercontent.com/48837852/102908905-1b224e80-44b3-11eb-89cc-e849140a2421.PNG)
![skipwaiting fails_2](https://user-images.githubusercontent.com/48837852/102908909-1c537b80-44b3-11eb-8d5f-4259c55505fc.PNG)

Do let me know if there are any workarounds for this as it has been affecting the users on my site after implementing PWA

**Comment by jeffposnick** [comment]
That sounds very much like what you might see if your `vendor.[hash].js` chunk is larger than the maximum size that Workbox is configured to precache by default. (You should see a warning message generated as part of your build letting you know that `vendor.[hash].js` is too big and won't be precached.)

You can adjust the [`maximumFileSizeToCacheInBytes`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.InjectManifest#parameter_1:~:text=maximumFileSizeToCacheInBytes) configuration value, which defaults to 2mb, to something larger if you need to. Alternatively, and this is probably a better idea in general (since large JS chunks can lead to bad performance), you could try to break up the `vendor` chunk into smaller pieces.

**Comment by AlvinTCH** [comment]
Thanks for the quick reply! Increased the maximumFileSizeToCacheInBytes while doing tests on the stability after breaking up the vendor chunks. Seems to be alight so far without seeing the blank pages on subsequent redeploys
