### ISSUE TITLE
How Do I Clear a Specific Cache When a New Record is Created?

### ISSUE THREAD

**Issue by PostAlmostAnything** [GoogleChrome/workbox#2713]
I have a site that users post to frequently and would like to enable caching of pages, but so far my efforts can online limit the amount of time a cache can be kept. This is problematic if a user posts a comment on an article because users that have already been to the article are served the same one when they go back to it. 

Would it be possible to delete the cache just for that article when a new comment is added? 

The method I currently have looks like this

```
workbox.routing.registerRoute(
    new RegExp('https://example.com/posts/(.*)'),
    workbox.strategies.cacheFirst({
        cacheName: 'posts',
        plugins: [
            new workbox.expiration.Plugin({
                maxEntries: 60,
                maxAgeSeconds: 30 * 24 * 60 * 60,
                purgeOnQuotaError: true,
            }),
            new workbox.cacheableResponse.Plugin({
                statuses: [0, 200]
            }),
        ],
    }),
);
```

I was thinking of a couple ways of doing this. The first would be to add an event handler when a new record is submitted and the form submitting the data is valid. Then that script would clear the cache for just that post, but I am new to Workbox and don't really know how to do that. The other would be to redirect users to the post with a query string appended to the URL and writing a script to delete the cache for the post if that string is appended.

**Comment by jeffposnick** [comment]
Hello! Could you provide some more context about a few things?

- In your example, do the `https://example.com/posts/...` URLs correspond to HTML pages, or for an API that returns content?

- When you talk about clearing the cache after a new comment is posted, are you just talking about clearing the cache for the user who actually posted the comment? Because obviously other return visitors to your page won't have their own local caches cleared in that case.

**Comment by jeffposnick** [comment]
I'm closing this for now, but if you have any info to share to address the above questions, please let us know and we can revisit.
