### ISSUE TITLE
registerRoute does not work the first time

### ISSUE THREAD

**Issue by behnam-maqsudi** [GoogleChrome/workbox#2748]
registerRoute does not work the first time.
```import { skipWaiting, clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { NetworkFirst } from 'workbox-strategies';
import { registerRoute } from 'workbox-routing';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

skipWaiting();
clientsClaim();

const WB_MANIFEST = self.__WB_MANIFEST;
self.__WB_DISABLE_DEV_LOGS = true;

precacheAndRoute(WB_MANIFEST);

cleanupOutdatedCaches();

registerRoute(
  /\/localhost:3000/i,
  new NetworkFirst({
    cacheName: 'routes',
  }),
  'GET'
);
```

 But if I refresh the page, the Route will be registered and it will work offline. Where are the problems?
 
 before refresh
 
![image](https://user-images.githubusercontent.com/40948849/107331044-95d91480-6ac7-11eb-9ed5-d744487267b9.png)

after refresh

![image](https://user-images.githubusercontent.com/40948849/107331292-eb152600-6ac7-11eb-8e34-9c77b71ed229.png)

**Comment by jeffposnick** [comment]
Hello @benamm!

The first time you register a service worker, the service worker will install and activate, but it will not take control of any open tabs. (Unless you call `self.clients.claim()` inside of the `activate` handler.) It's not until you navigate to a page under your service worker's scope a second time that the service worker will be in control, and the runtime routes will be in effect.

This is explained in more detail at https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#activate

**Comment by behnam-maqsudi** [comment]
Hello, thank you for answering.
I was not convinced, I thought the user will be able to see the page again
if he refreshes

Please tell me how to fix this problem?

**Comment by behnam-maqsudi** [comment]
i use self.clients.claim()  or clientsClaim() but not register

**Comment by jeffposnick** [comment]
Apologies for missing that you were already claiming your clients.

That being said, if your runtime route only matches your `/` URL, then the cache will only be automatically populated with the entry for `/` the next time a request is made for `/`. That happens when a user refreshes the page and the browser requests `/`.

If you want to populate that cache ahead of time, you should do it explicitly during the `install` event. Assuming you don't want `/` to be precached, you can write your own `install` handler that performs this, using the same cache name as you use when you define your strategy:

```
self.addEventListener('install', (event) => {
  event.waitUntil(caches.open('routes').then((cache) => cache.add('/')));
});
```
