### ISSUE TITLE
Is the revision hash used to check delivered network resources during precaching?

### ISSUE THREAD

**Issue by KolyaKorruptis** [GoogleChrome/workbox#2757]
This just a question I have about precaching: 
When a new SW is activated and populates the cache, it adds the revision hash as a parameter (__WB_REVISION__=XXX) to the network request URL. Presumably to bust CDN caching.

Is the network resource that gets delivered checked against this MD5 hash? 

Background: Due to rolling updates across load balanced servers on our side, a user may receive a new SW but the assets he receives may come from a not yet updated server. I assume the only way to prevent the user caching an old asset until the next SW update is to implement SRI checks. Is this correct?

We're currently using Workbox v4.

**Comment by jeffposnick** [comment]
The precaching network requests vary a bit between v4.x and the current v6.x release.

If I remember correctly, in v4.x, we did use the `__WB_REVISION__` for two purposes: both for providing some measure of avoiding any caches for the network request, and also to allow two responses that would otherwise have the same URL (and therefore the same cache key) when stored in the local Cache Storage API to coexist, in the period of time in between the service worker's `install` and `activate` handlers. (The old response is cleaned up during `activate`.)

(In v6.x, we [rely](https://github.com/GoogleChrome/workbox/blob/3448247a456cd3781d6df8884fd1c2f586c04db4/packages/workbox-precaching/src/PrecacheController.ts#L134-L135) on using a `cache` mode of either `'reload'` or `'default'` to handle bypassing caches on the network, and the `__WB_REVISION__` parameter isn't included in the network requests anymore—it's only used for creating unique cache keys.)

So, yes, regardless of which version of Workbox you're using, I would strongly recommend that you hold off on deploying an update to your service worker file until you're sure that all of the updated resources it references are fully deployed. The `revision` property is not used for any install-time hash comparisons.

If you do want to use subresource integrity on your precached responses, that is supported in Workbox v5.x and later, but you'll need to calculate the `integrity` values yourself, as [described in the documentation](https://developers.google.com/web/tools/workbox/modules/workbox-precaching#using_subresource_integrity).
