### ISSUE TITLE
WorkboxMessageEvent discards event.ports

### ISSUE THREAD

**Issue by StephanBijzitter** [GoogleChrome/workbox#2771]
**Library Affected**:
*workbox-window*

**Browser & Platform**:
*All browsers that support service workers and message channels*

**Issue or Feature Request Description**:
When sending a message from the service worker to all clients (in the case of testing, only one client), the client does not receive the message port with which to respond. This happens when adding the message event listener through workbox, but not when adding the listener through `navigator.serviceWorker`.

Maybe this is by design, but it caught me off-guard.

Given service worker code:
```ts
    const clients = await self.clients.matchAll();
    const channel = new MessageChannel();
    const {port1, port2} = channel;

    return new Promise<R>((resolve, reject) => {
        port1.onmessage = ({data}) => {
            port1.close();

            if (data.error) {
                reject(data.error);
            } else {
                resolve(data.result);
            }
        };

        clients.forEach((client) => client.postMessage({
            meta,
            type,
            payload
        }, [port2]));
    });
```

And client code:
```ts
workbox.addEventListener('message', (event: WorkboxMessageEvent) => {
    console.log((event as any).ports); // always undefined
});

navigator.serviceWorker.addEventListener('message', (event: MessageEvent) => {
    console.log(event.ports); // defined
});
```

**Comment by jeffposnick** [comment]
You should be able to get this from the [`originalEvent` property](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-window.Workbox#:~:text=event.-,originalEvent,-Event) in the `WorkboxMessageEvent` object:

```
workbox.addEventListener('message', (event: WorkboxMessageEvent) => {
  console.log(event.originalEvent.ports);
});
```

That being said, it sounds reasonable to extend the code so that `ports` is mirrored as a property on `WorkboxMessageEvent` directly:

https://github.com/GoogleChrome/workbox/blob/a2f373ece2bf5c72a7177e2e461368acbb7df361/packages/workbox-window/src/Workbox.ts#L536-L541

**Comment by jeffposnick** [comment]
The feature is now deployed in a pre-release of Workbox v6.2.0: https://github.com/GoogleChrome/workbox/releases/tag/v6.2.0-alpha.0

**Comment by StephanBijzitter** [comment]
Ah `originalEvent` makes sense, can't believe I read over that.
Either way, love this little change with 6.2.0, thanks!
