### ISSUE TITLE
Content-Length 0

### ISSUE THREAD

**Issue by steveoh** [GoogleChrome/workbox#2778]
**Library Affected**:
*workbox-build*

**Browser & Platform**:
*Google Chrome v89.0.4389.82 on MacOS*

**Issue or Feature Request Description**:
I've got a lot of precache items displaying 0 content-length. Which is fouling up my app when it loses service. This does not seem to be the case with firefox. 

![image](https://user-images.githubusercontent.com/325813/110890769-e356c600-82ad-11eb-9f7d-1096b4795e79.png)
![image](https://user-images.githubusercontent.com/325813/110890831-04b7b200-82ae-11eb-9ffc-f160815b54d5.png)

**Comment by jeffposnick** [comment]
Can you share a link to a public URL at which this can be reproduced?

**Comment by steveoh** [comment]
This website is password protected but I can certainly spend some time with a repro.

**Comment by jeffposnick** [comment]
You can DM https://twitter.com/jeffposnick if you feel comfortable sharing it privately, and I'll take a look.

**Comment by steveoh** [comment]
I should have said it's protected data for law enforcement.

**Comment by jeffposnick** [comment]
Gotcha 😄 

I wonder whether you might be running into issues due to precaching running before you've got a valid auth credentials, in that case? Perhaps your web server is configured to respond with an empty HTTP response when that happens.

`workbox-precaching` [sets](https://fetch.spec.whatwg.org/#concept-request-credentials-mode) `credentials: 'same-origin'` on the requests that it uses to populate the cache, but that only helps if the credentials are actually available at the time the service worker is first registered.

https://github.com/GoogleChrome/workbox/blob/69aade8b1466a52017994d6b29630565430356b5/packages/workbox-precaching/src/PrecacheController.ts#L194-L198

**Comment by steveoh** [comment]
The network pane screenshot shows the file being successfully requested with content and then when offline the failure. I wouldn't think that would be an issue since the service worker is served over the same secure connection as the items it's trying to precache.

**Comment by jeffposnick** [comment]
If possible, providing a reproduction without sensitive data that I could access would help debug this more quickly.

Absent that, what happens if you start from scratch (say, in an Incognito window) and go through the initial precaching flow, and take a look at the entries in the Network panel corresponding to the precaching requests? They should have little ⚙️  icons next to them. Does anything look amiss about the responses to those precaching requests? Presumably they'll also have a `Content-Length: 0`, but perhaps the Network panel entry for them will include some more context explaining why?

**Comment by steveoh** [comment]
Maybe this is a devtools bug?

content-length is 0 but the cache has data...

![image](https://user-images.githubusercontent.com/325813/111368880-0261a900-865c-11eb-94e8-f357ba2026af.png)

**Comment by jeffposnick** [comment]
Perhaps if there's a chunked transfer encoding used for the response, and there's no `Content-Length` header, then that's what you end up seeing in DevTools?

The actual response should be valid, though. You mentioned that it wasn't worked as expected?

**Comment by steveoh** [comment]
I updated from the cra pwa template 5.1.4 version of workbox to 6.1.1 or whatever is current and I think that problem has fixed itself. 

That is interesting tht the dev tools only show the header value. I could technically make those values whatever i wanted? I assumed that cache would calculate those for it's own size limitation logic

**Comment by jeffposnick** [comment]
I don't know a ton about how DevTools calculates those values, but based on the work a colleague recently did related to something similar (https://bugs.chromium.org/p/chromium/issues/detail?id=1186049) I think it just reads whatever is stored as part of the serialized response headers. That just affects the DevTools UI, not any "real" functionality.

In any case, it sounds like this is resolved? I'll reopen if not.
