### ISSUE TITLE
I'm trying to add the Statoscope webpack plugin for analyzing the service worker bundle, but to no effect

### ISSUE THREAD

**Issue by budarin** [GoogleChrome/workbox#2785]
**Library Affected**:
*any*

**Browser & Platform**:
*any*

**Issue or Feature Request Description**:
I want to analyze service worker bundle with [Statoscope](https://github.com/smelukov/statoscope).

Configuring the plugin:
```js
const StatoscopeWebpackPlugin = require('@statoscope/ui-webpack');

...
const confiig = {
   ...
   plugins = [
    new InjectManifest({
            swSrc: './src/sw/sw.js',
            swDest: 'sw.js',
            webpackCompilationPlugins: [
                new StatoscopeWebpackPlugin({
                    name: 'ServiceWorker',
                    saveTo: path.resolve(`./dist/sw-statoscope.html`),
                    open: 'file',
                }),
            ],
        }),
        ...
```
but there is no any effect - the plugin doesn't work

Note: for the app bundle, this plugin is triggered

**Comment by jeffposnick** [comment]
Hello @budarin.

I'm not familiar with Statoscope, so I can't give a definitive answer without doing some more investigation.I read up a little bit about what it does, and it sounds like it only works if the webpack compilation has full stats enabled, correct?

The `InjectManifest` plugin works by creating a `webpack` child compilation, and running that separately from the main `webpack` compilation. The child compilation is supposed to inherit many of the settings from the parent compilation, including (I think?) the `stats` setting. Since you say that the Statoscope plugin works when run against the app bundle, I'm assuming that means that the `stats` are properly configured there, but perhaps `webpack` doesn't actually pass that `stats` setting through to the child compilation.

Alternatively, there might be something about how `StatoscopeWebpackPlugin` that would make it incompatible with child compilations.

**Comment by budarin** [comment]
Thanks for the reply.
I'll try to ask the Statoscope contributer about it

**Comment by budarin** [comment]
we found out that at the moment Statoscope does not support child compilation, but in the next release it will support
