### ISSUE TITLE
Need to have an ability to log bad-precaching-response errors

### ISSUE THREAD

**Issue by budarin** [GoogleChrome/workbox#2794]
**Library Affected**:
*workbox-precaching*

**Browser & Platform**:
*any*

**Issue or Feature Request Description**:
In some situations some resources could be lost in k8 infrastructure
We need to have an ability to log such errors and react on them

**Comment by jeffposnick** [comment]
You can do this by adding in a plugin implementing the [`handlerDidError` callback](https://developers.google.com/web/tools/workbox/guides/using-plugins) to the underlying `PrecacheStrategy` that `workbox-precaching` uses. There's a helper method, `addPlugins()`, that you can call to add it (since most developers won't instantiate the `PrecacheStrategy` directly).

```js
import {addPlugins, precacheAndRoute} from 'workbox-routing';

addPlugins([{
  handlerDidError: async ({request, event, error, state}) => {
    // Swap this for you custom logging function:
    console.log(`Precaching request for ${request.url} failed: ${error.message}`);

    // Explicitly return null, as we're not providing a fallback response.
    return null;
  }
}]);

precacheAndRoute(self.__WB_MANIFEST);
```

**Comment by budarin** [comment]
thanks!
