### ISSUE TITLE
setCatchHandler not being triggered on cache miss

### ISSUE THREAD

**Issue by rupertdance** [GoogleChrome/workbox#2800]
**Library Affected**:
workbox 5.1.4

**Browser & Platform**:
Chrome desktop, et al

**Issue **:
In order to check a number of dynamically named caches (ie. page-cache-123 where 123 is the ID of an edition of content) I have added a caches.match into a fetch event listener. I did this because I couldn't figure a way to make workbox NavigationRoutes find caches inside my differently named caches. This works in that does load up that cache when the user is offline. However if I then visit any other page that isn't cached, I get a 'This site can't be reached' error, instead of the serviceworker using my setCatchHandler() to show my offline page. Is there a way I am meant to manually trigger the setCatchHandler() from the below fetch listener? 

Or, better yet, how can i make a NetworkFirst navigation route that will actually search every cache no matter the cacheName?

I'm doing this so i can namespace caches so that the user can add + remove them for offline use. I'm using 5.1.4 as its part of a module working inside my CMS Drupal. I'm sure I'm missing a trick here...

Thanks!

```
 if (event.request.headers.get('accept').indexOf('text/html') !== -1 && event.request.mode === 'navigate') {
            event.respondWith((async () => {
            // Try to get the response from a cache.
            const cachedResponse = await caches.match(event.request, {ignoreSearch: true});
            // Return it if we found one.
            if (cachedResponse){
                return cachedResponse;
            } 
            return fetch(event.request).catch(e => {
                console.log(e);
                // setCatchHandler(event); // how to fire this? 
            });
        })());
      }
```

I think the relevant error from console is:
```
The FetchEvent for "https://staging.thesaturdaypaper.com.au/thebriefing" resulted in a network error response: an object that was not a Response was passed to respondWith().
```

You can see a staging version of the site running here: https://staging.thesaturdaypaper.com.au/

**Comment by jeffposnick** [comment]
Hello @rupertdance!

One fundamental issue that would need to be sorted out first is that [`workbox-routing`](https://developers.google.com/web/tools/workbox/modules/workbox-routing), and the various methods it exposes (like `setCatchHandler()`), work by registering their own `fetch` event listener, which then uses the routing information you configure to determine whether or not to respond to a given `fetch` event.

You can use other pieces of Workbox, like `workbox-strategies`, from inside your own `fetch` event listeners, without using `workbox-routing`. But if you _do_ want to use `workbox-routing`, don't attempt to call its methods from inside your own `fetch` event listener.

Going back to your original question, about not being able to find a way to match navigation requests against different caches, I'd say that in this particular case it would be best to use `workbox-routing` but not use `workbox-strategies`, like so:

```js
workbox.routing.registerRoute(
  ({request}) => request.mode === 'navigate',
  async ({request}) => {
    const cachedResponse = await caches.match(request, {
      ignoreSearch: true,
    });

    if (cachedResponse){
      return cachedResponse;
    }

    try {
      return await fetch(request);
    } catch (error) {
      console.log(error);
      // Replace with whatever fallback logic you want:
      return await caches.match('/fallback.html');
    }
  }
```

If you were using Workbox v6, where there's a [clean way](https://web.dev/extending-workbox/) of defining your own custom `Strategy` subclasses, I'd say that would be a good, reusable option, as you could define a strategy that just checked every cache instead of one specific cache.

Hopefully that helps!

**Comment by rupertdance** [comment]
Thanks so much Jeff, great explanation and very helpful there!  If you'd indulge a follow up question it'd really help me out! I'm attempting to cache selected pages before returning the `return await fetch(request);` but having some trouble, perhaps as the documents are using then() and its conflicting with the `await`? Is there a clean way to cache the pages as do the return there?

**Comment by jeffposnick** [comment]
If you're using `Promise`-based APIs, it's technically possible to mix `.then()` and `await`, and every once in a while there is actually a good reason to do so. But in general, you'll find it much easier to write your code if you exclusive use `await` (or if you exclusively use `.then()`).

Guides [like this one](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await) have advice for converting from `.then()` to `await`, along with any gotchas that you need to pay attention to.
