### ISSUE TITLE
Multiple controlling events

### ISSUE THREAD

**Issue by joshkel** [GoogleChrome/workbox#2817]
**Library Affected**: workbox-window

**Browser & Platform**: Tested on Chrome 89.0.4389.114 for Mac

**Issue or Feature Request Description**:

I'm having trouble getting the Workbox class's `controlling` event to work like I expect - or maybe I'm misunderstanding how it's expected to work.

Scenario: I want my page to reload on update, [like in the recipe](https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users):

```js
wb.addEventListener('controlling', (event) => {
  window.location.reload();
});
```

However, unlike the recipe, I want my page to reload even if the update was confirmed in the UI in another browser tab. So I set up this event handler at application start, instead of in response to a `waiting` event. (That was working even prior to #2786 and Workbox 6.1.5, so I may be misunderstanding #2786.)

Then I noticed that my page would reload when it was first loaded (because the newly installed service worker takes control via `clientsClaim`). That seems unnecessary, so I added a check for that:

```js
wb.addEventListener('controlling', (event) => {
  if (!event.isUpdate) {
    window.location.reload();
  }
});
```

However, I then discovered that the `controlling` event [can only fire once](https://github.com/GoogleChrome/workbox/blob/ef225a97db24eaf29d9e320f52286408669c7a7e/packages/workbox-window/src/Workbox.ts#L192): a newly loaded page gets the `controlling` event for the initial load, so it then no longer gets events notifying of future updates.

This seems like a bug, but I could easily be misunderstanding something. Is this the desired behavior?

**Comment by jeffposnick** [comment]
Thanks for catching that, @joshkel. My supposition is that

https://github.com/GoogleChrome/workbox/blob/ef225a97db24eaf29d9e320f52286408669c7a7e/packages/workbox-window/src/Workbox.ts#L191-L192

was written with `{once:true}` originally, as an optimizing for when there was no concept of "external" `controlling` events in `workbox-window`, and that we should have removed the `{once: true}` when we added support for all types of `controlling` events, regardless of whether they originated from the page's original service worker, or a new service worker on a different page.

I think you're already familiar with our codebase, so if you want to take on removing that `{once: true}`, you are encouraged to! Otherwise, we can.

**Comment by jeffposnick** [comment]
The fix is now deployed in a pre-release of Workbox v6.2.0: https://github.com/GoogleChrome/workbox/releases/tag/v6.2.0-alpha.0
