### ISSUE TITLE
Precache event

### ISSUE THREAD

**Issue by raftx24** [GoogleChrome/workbox#2825]
Welcome! Please use this template for reporting bugs or requesting features. For questions about using Workbox, the best place to ask is Stack Overflow, tagged with `[workbox]`: https://stackoverflow.com/questions/ask?tags=workbox

**Library Affected**:
*workbox*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
*Feature Request*

I need an event for precaching loaded status. we have some logs in development for indicating the number of new precache files but we don't have an event for it.   
We need it because we want to send an event to the user for the new version and we want to load service-worker and when precache files are finished and there is a new precache file we will notify the user.

**Comment by jeffposnick** [comment]
I'm not sure that I understand that use case.

Normally, a developer would detect that precaching has fully completed because the service worker would progress from the `installing` stage to either `waiting` or `activating`.

If you wanted to detect when individual responses are added to the cache, you can do that via adding a `cacheDidUpdate` plugin, e.g. https://github.com/GoogleChrome/workbox/issues/2498 or https://stackoverflow.com/questions/56906249/workbox-get-event-when-files-are-in-cache

Do those approaches satisfy your use case, or are you trying to do something different?

**Comment by raftx24** [comment]
@jeffposnick thanks they are enough.
