### ISSUE TITLE
Script errors when using reciepes

### ISSUE THREAD

**Issue by developdeez** [GoogleChrome/workbox#2841]
Hi Im using Workbox by simply adding the reciepes from the docs to my src folder. It seems to cause an error in scripts:
![image](https://user-images.githubusercontent.com/13059525/117905407-f83cdf00-b287-11eb-8eff-215a1c3002d2.png)

Any ideas?

**Comment by jeffposnick** [comment]
If you're seeing that error, it's because your `/service-worker.js` file is not being served with the appropriate `application/javascript` `Content-Type`, and instead is using a `text/html`.

That's probably because your web server responds to any top-level URL with the HTML for your single-page app. You need to configure your web server to properly serve the top-level service worker JavaScript file instead.
