### ISSUE TITLE
Audio Not Getting Cached When Using Audio API

### ISSUE THREAD

**Issue by Debdut** [GoogleChrome/workbox#2849]
**Library Affected**:
*workbox-strategies* *workbox-range-requests* *workbox-cacheable-response*

**Browser & Platform**:
"all browsers"

**Issue or Feature Request Description**:

I'm loading the audio using Audio API in the `main.js`
```js
const audio = new Audio('/music/sample.mp3')
```

The `service-worker.js` CacheFirst strategy with RangeRequests Plugin
```js
import { registerRoute } from 'workbox-routing'
import { CacheFirst } from 'workbox-strategies'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { RangeRequestsPlugin } from 'workbox-range-requests'

registerRoute(
  ({ request }) =>  request.destination === 'audio',
  new CacheFirst({
    cacheName: 'audio-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [ 200 ] }),
      new RangeRequestsPlugin(),
    ],
  }),
)
```

Every file expect the audio files are getting cached, but the `audio-cache` as per above code is always empty although I can see them loading in Network Requests.

I also tried a simpler version for audio caching, but it also doesn't work
```js

registerRoute(
  ({ request }) =>  request.destination === 'audio',
  new CacheFirst({
    cacheName: 'audio-cache',
  }),
)
```

Note
 - The audio files are around ~2-5 Mb
 - The Audio Requests also have the property `request.destination` set to `audio`; I have tested using `console.log`
 - [Audio API Docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio)
 - The code is taken from official Google docs; visit [Advanced Recipes | Workbox](https://developers.google.com/web/tools/workbox/guides/advanced-recipes) and look at the last code

**Comment by jeffposnick** [comment]
Hello @Debdut!

I believe the issue is that when Chrome (and maybe other browsers; I tested in Chrome) executes `new Audio('/music/sample.mp3')`, that ends up firing off a `Range: bytes=0-`  request for the MP3, and the response is an HTTP 206. A 206 (i.e. partial response) can't be directly added to the Cache Storage API.

You can see more detail about what's going on if you use Workbox's development bundles:

<img width="778" alt="Screen Shot 2021-05-24 at 5 40 41 PM" src="https://user-images.githubusercontent.com/1749548/119411145-ee6ba080-bcb7-11eb-9369-8938b0371970.png">

The workaround is to explicitly cache the entirety of the MP3 first, possible during the service worker's installation. Then, when you actually attempt to load it via `new Audio()`, Workbox can serve the response from the cache, including honoring the `Range:` header, since you're using that plugin.

The [`warmStrategyCache()` method](https://developers.google.com/web/tools/workbox/modules/workbox-recipes#warm_strategy_cache) in the new `workbox-recipes` package makes it easy to cache that URL at `install` time. Here's an example of the full logic:

```js
import { registerRoute } from 'workbox-routing'
import { CacheFirst } from 'workbox-strategies'
import { RangeRequestsPlugin } from 'workbox-range-requests'
import { warmStrategyCache } from 'workbox-recipes';

const audioStrategy = CacheFirst({
  cacheName: 'audio-cache',
  plugins: [
    new RangeRequestsPlugin(),
  ],
});

warmStrategyCache({
  strategy: audioStrategy,
  urls: ['/music/sample.mp3'],
});

registerRoute(
  ({request}) =>  request.destination === 'audio',
  audioStrategy
);
```

**Comment by 56789a1987** [comment]
Is it posible to use this in the generate SW build tools?
