### ISSUE TITLE
Typescript confusion

### ISSUE THREAD

**Issue by ivandotv** [GoogleChrome/workbox#2860]
**Library Affected**:
workbox-window
**Browser & Platform**:
"all browsers".*

**Issue or Feature Request Description**:
I'm trying to use `workbox-window` in Typescript however,  the package doesn't export any event type declarations?

```ts
wb.addEventListener('waiting', (evt: WorkboxLifecycleWaitingEvent) => {})  // error
```
`WorkboxLifecycleWaitingEvent` is not exported from `workbox-window`

**Comment by jeffposnick** [comment]
Hello!

While it's true that `WorkboxLifecycleWaitingEvent` is not explicitly exported, that's because you should never need to instantiate an instance from your own code. You're passed an instance of `WorkboxLifecycleWaitingEvent` via the `waiting` callback as the first parameter, and there's no need to explicitly state its type like you're doing in the code snippet—TypeScript knows that it's a `WorkboxLifecycleWaitingEvent` automatically:

![Screen Shot 2021-06-10 at 6 56 26 PM](https://user-images.githubusercontent.com/1749548/121612498-855e8980-ca28-11eb-9a5a-cd5ee9f2080b.png)

I *think* that that's the standard way for library authors to deal with this sort of thing, and is therefore not something that we have plans to change. If I'm misunderstanding a use case, or if this breaks something for you, please let me know and we can reevaluate.

**Comment by ivandotv** [comment]
That is true, only if you create the function inline.
```ts
wb.addEventListener('waiting', handleWaiting)  // error
wb.addEventListener('waiting', myClassInstance.handleWaiting)  // error
```
The first case is very common.
Also , ESLint can give you an error there, depending on your configuration. 

This is very limiting

**Comment by jeffposnick** [comment]
Fair enough! We can get those event definitions exported as part of an upcoming Workbox v6 release.

**Comment by jeffposnick** [comment]
The fix is now deployed in a pre-release of Workbox v6.2.0: https://github.com/GoogleChrome/workbox/releases/tag/v6.2.0-alpha.0
