### ISSUE TITLE
StaleWhileRevalidate ignores ETag and Last-Modified

### ISSUE THREAD

**Issue by EtienneBruines** [GoogleChrome/workbox#2862]
**Library Affected**:
`workbox-strategies:6.1.5`

https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-strategies.StaleWhileRevalidate

**Browser & Platform**:
Probably all browsers, but tested on Chrome 93.

**Issue or Feature Request Description**:
The cached response sent from the service worker to the browser is correct. But, when the service worker then tries to revalidate that resource, the `ETag` HTTP header is omitted. This makes the revalidate quite expensive to do, as the server now cannot simply reply with a `304 Not Modified`. 

The same holds true for the `Last-Modified` HTTP header. This could/should also be used, to revalidate the resource. Revalidate should not mean "redownload", but just checking with the server for updates. We should enable the server (using HTTP headers) to respond with `304 Not Modified` where applicable.

**Comment by jeffposnick** [comment]
Hello @EtienneBruines—I'm surprised to hear that, as it's not the expected behavior.

I just want to clarify—both [`ETag`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) and [`Last-Modified`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) are HTTP response headers, not request headers, so I would not expect them to be present on any outgoing requests. Are you instead referred to the [`If-Match`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Match) and [`If-Modified-Since`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since) request headers?

Assuming that's what you mean,are you using any [plugins](https://developers.google.com/web/tools/workbox/guides/using-plugins) with your `StaleWhileRevalidate` strategy?

**Comment by EtienneBruines** [comment]
@jeffposnick Thank you for your reply.

You are correct, I meant that no `If-Match` or `If-Modified-Since` request headers were present, even though possible values for such headers were provided through the `ETag` and `Last-Modified`http response headers of previous requests. 

No plugins were used.

**Comment by EtienneBruines** [comment]
Apparently, this was due to a browser bug. Updating the browser seemed to fix the issue.

Sorry for taking up your time! :see_no_evil: @jeffposnick
