### ISSUE TITLE
'onSync' property type must be object.

### ISSUE THREAD

**Issue by migueldevpt** [GoogleChrome/workbox#2910]
**Library Affected**:
*workbox-cli, workbox-webpack-plugin*

**Browser & Platform**:
Ubuntu 20.04.2 LTS using zsh with Node Version 16.6.1 also tried in Node 15.14.0. Error happens in cli so it doesn't reach the browser

**Issue or Feature Request Description**:
Hello I have found a possible breaking change that i think hasn't been documented on the release notes of V6 or in the [workbox docs](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-background-sync.Queue) .

While using the workbox-cli or workbox-webpack-plugin in the runtime caching the onSync option for the background sync gives out the following error

![image](https://user-images.githubusercontent.com/27964123/129018629-19807f71-cb07-4b74-890c-401835ed71fe.png)

Saying that it must be an object even though the [docs say that it must be a function](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-background-sync.Queue)

Here is a small repo to reproduce the error on the workbox-cli

https://github.com/migueldamaso/workbox-onsync

If you set the workbox version to V5 the error will not show up

Thank you all for your time

**Comment by jeffposnick** [comment]
Apologies that you're running into this, and thanks for reporting it.

I _think_ #2911 will catch the remaining cases where this might crop up. We'll cut a new release with those changes.

(For those playing along at home, we tested these changes out during the v6.2.0 alpha releases, then ran into what amounted to https://github.com/eslint/eslint/issues/11018#issuecomment-433248374 when using `ajv-keywords` to handle validation of options that could be set to `function`, and now we have to manually override the relevant bits of the generated schema in order to work around that.)

**Comment by jeffposnick** [comment]
This should be fixed now: https://github.com/GoogleChrome/workbox/releases/tag/v6.2.4
