### ISSUE TITLE
Surface fetch errors caused by integrity hash verification failures

### ISSUE THREAD

**Issue by thexeos** [GoogleChrome/workbox#2970]
**Library Affected**:
_workbox-precache_

**Browser & Platform**:
_all browsers_

**Issue or Feature Request Description**:
Right now, this is what the log looks like when one of the pages (index page) has been altered by the local VPN:

![image](https://user-images.githubusercontent.com/2260539/139364761-3ca221ab-bfb3-4f8a-aba5-35f77fdc854b.png)

Unless I'm doing something wrong, I'm not getting any callbacks about this. It just silently fails after `updatefound`. If we could receive this error in the client, we could inform the user about "corrupted" content and provide some troubleshooting steps.

**Comment by jeffposnick** [comment]
Hello @thexeos—there are a few ways you could approach this.

### Exclude integrity

You could leave out the `integrity` field in the precache manifest for `index.html` if you _wanted_ to allow that HTML to be precached despite the VPN manipulation. I'm going to assume that you do actually want to include `integrity` and prevent the wrong HTML from being precached, though.

### Detect redundant service worker from the window context

When a promise passed to `installEvent.waitUntil()` rejects, the service worker that was previously installing becomes redundant, which is a final error state for a given service worker instance. You can listen for this transition from within the `window` context, in your web app. It's a bit [easier to do this using `workbox-window`](https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-window.Workbox#event:redundant), but you could do it using the vanilla service worker APIs, too:

```js
// From inside app.js:

import {Workbox} from 'workbox-window';

const wb = new Workbox('/sw.js');

wb.addEventListener('redundant', () => {
  // Do something in your web app to handle this state, like warn the user.
});

wb.register();
```

### Detect the failure via a plugin

Using a [custom plugin](https://developers.google.com/web/tools/workbox/guides/using-plugins) during precaching would be appropriate if you need a little more control for some reason, and want to identify exactly which request failed, rather than just detecting the overall service worker redundant state change.

```js
// From inside sw.js:

import {addPlugins, precacheAndRoute} from 'workbox-precaching';

const detectFailedFetch = {
  fetchDidFail: ({originalRequest, error}) => {
    // Do something with originalRequest.url and error, like postMessage() to
    // clients letting them know about the failure.
  },
};

addPlugins([detectFailedFetch]);
precacheAndRoute(self.__WB_MANIFEST);
```

You should note in this approach, the `fetchDidFail` callback would be invoked whenever there's an exception thrown by the underlying `fetch()`. This might be because the network is unavailable, it might be because of a content blocker, it might be because of a SRI check, or it might be any other reason. I'm not 100% sure how much insight into the underlying problem will end up being passed in as the `error` parameter—many of those root causes might end up resulting in the same exception, and the specifics might vary from browser to browser.
