### ISSUE TITLE
Overly aggressive default caching of workbox.recipes might be problematic

### ISSUE THREAD

**Issue by chrisbennett-Bene** [GoogleChrome/workbox#2983]
**Library Affected**:
workbox-sw, workbox.recipes

**Browser & Platform**:
Chrome, Edge, Brave etc. Can't easily tell with Firefox

**Issue or Feature Request Description**:
Over aggressive default caching of workbox.recipes can quickly consume large amounts of storage space

Love the continued good work on workbox.

I noticed that the default workbox.recipes are very aggressively caching results, which may be of some concern.
For example, testing on Chrome, Edge, Brave, with a very simple sw using only:
```
importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.2.0/workbox-sw.js');
workbox.recipes.pageCache();
workbox.recipes.imageCache();
workbox.recipes.staticResourceCache();
workbox.recipes.googleFontsCache();
```
Will initially start with:
33.2 kB used out of 254991 MB storage quota
Click on same link with network cache and update on refresh both disabled and the same page reports:
3.3 MB used out of 254991 MB storage quota
Click on same link, again:
9.8 MB used out of 254991 MB storage quota

Same page, somehow adding weight. Whole site is way, way less than 9.8MB, bar third party Google Analytics, Maps API and workbox. 

It *seems* like perhaps precache is being used, despite not being requested explicitly.
This doesn't seem to match the patterns from https://developers.google.com/web/tools/workbox/modules/workbox-recipes, but workbox-precaching.prod.js is indeed being called.

More to the point, none of the created caches display exactly whatever is making up this total. 
The only possibility seems like analytics.js.
I have no idea where that total is going, or being read from, or if it is disposed of when the service worker is cleared or deleted.

**It gets much worse though.**
If your visitor chooses to take a look at your Google map, you get a sudden quarter of a gig hit:
**284 MB** used out of 254991 MB storage quota

I get how it could definitely be useful to opt in to caching google maps in case people go offline, 

That said, if a simple visit to a google map on a single site is actually taking up 284 MB of space then people's devices could quickly slow down for no reason. If the storage figure is accurate (same on Chrome, Edge, Brave) then default recipes on 4 sites with 1 google map =  1+ gig. 

I'm guessing workers or some hidden stuff is included somewhere because transfer from a clear cache is only: 578 kB / 578 kB transferred 1.3 MB / 1.3 MB resources. I just don't know where the huge numbers are coming from 

Visit 20 sites with the google map api and you'd store a hefty 5.5+ gigabytes.
Would very quickly add up and be invisible bloat to a lot of users.

Naturally, we can pass info to the recipes, but if the defaults are unintentionally chunky then that can't be great.

Below is what I use instead of the defaults, because while I'm happy to test stuff I couldn't in good conscience take up so much space.
```
workbox.recipes.pageCache({ cacheName:'Pages', matchCallback: ({ request }) => request.destination === 'document', networkTimeoutSeconds: 2 });
workbox.recipes.imageCache({ cacheName:'Images', matchCallback: /\.(?:png|gif|jpg|jpeg|webp|svg|avif)$/, maxEntries: 120, maxAgeSeconds: 60 * 60 * 24 * 30 });
workbox.recipes.staticResourceCache({ cacheName:'Static', matchCallback: /\.(?:js|css|webmanifest)$/ });
```
While it won't cache Analytics or Google Maps, if it's a trade-off I'm willing to make to save 280+mb of storage.

**Comment by jeffposnick** [comment]
There's more information about how [opaque responses](https://stackoverflow.com/questions/39109789/what-limitations-apply-to-opaque-responses) can cause inflated storage quota usage at https://developers.google.com/web/tools/workbox/guides/storage-quota#beware_of_opaque_responses

My assumption is that most of the automatic caching you're seeing of the Google Maps tiles are for opaque responses, and does not translate into actual bytes on disk.

There are a _lot_ of ways to use Workbox (manually writing your code, using `generateSW` mode in the build tools, using `workbox-recipes` to wrap the underlying module calls, etc.) and they each fall on different ends of the spectrum from needing to configure everything to using as many reasonable defaults as possible. For `workbox-recipes`, the decision was made to cache opaque responses by default, since it could be overly confusing to add an `imageCache` recipe that didn't actually cache all the images requested by your web app.

I can leave this issue open to track the idea of adding a `dontCacheOpaqueResponses` option to those recipes, which would in turn control whether the `status` of `0` were added to the `CacheableResponsePlugin` used under the hood: https://github.com/GoogleChrome/workbox/blob/cdfc4cbc5d16f076d6ad51a49f19ad961c0c7482/packages/workbox-recipes/src/imageCache.ts#L53-L55

CC: @tropicadri in case she has any thoughts on that.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
