### ISSUE TITLE
Make `revision` optional when `integrity` is set in precache manifest

### ISSUE THREAD

**Issue by RandomEngy** [GoogleChrome/workbox#2993]
**Library Affected**:
workbox-build, v6.4.1

**Browser & Platform**:
All browsers

**Issue or Feature Request Description**:
The precache manifest that's injected has entries that look like this:
```
{"revision":null,"url":"/bundles/v1/myScript.f3e2692d7ee7e59d5def.js"}
```

If you set revision to undefined instead of null, it would be left out of the JSON entirely and make a smaller bundle.

```
export declare interface PrecacheEntry {
    integrity?: string;
    url: string;
    revision?: string | null;
}
```

Might be better as
```
revision?: string | undefined;
```

**Comment by jeffposnick** [comment]
At some point this might change, but for the time being, we want an explicit `null` there as a signal that the `revision` field has been deliberately set, rather than someone manually creating a precache manifest entry without taking verisoning into account at all.

(This is obviously not foolproof, but it's part of a best-effort to prevent developers from mistakenly, e.g., adding `{url: '/index.html'}` to their precache manifest and then getting very confused when they make changes to `index.html`, but caches are never updated.)

In Workbox v7, I anticipate we're going to start generating `integrity` properties (for [subresource integrity](https://developers.google.com/web/tools/workbox/modules/workbox-precaching#using_subresource_integrity)) via the build tools. If we see that `integrity` is set, a missing `revision` would probably be fine.

**Comment by RandomEngy** [comment]
Makes sense, thanks for the explanation.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
