### ISSUE TITLE
[feature] Allow passing a Response instead of a string to any of offlineFallback() recipe options

### ISSUE THREAD

**Issue by nhoizey** [GoogleChrome/workbox#2994]
**Library Affected**:

`workbox-recipes`

**Browser & Platform**:

all browsers

**Feature Request Description**:

I would like to be able to use a Response instead of a string with the name of a ressource in the cache, in the `offlineFallback() recipe options`.

For example, for the image:

```javascript
offlineFallback({
  imageFallback: new Response(
    '<svg role="img" aria-labelledby="offline-title" viewBox="0 0 400 225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice"><title id="offline-title">Offline</title><path fill="rgba(145,145,145,0.5)" d="M0 0h400v225H0z" /><text fill="rgba(0,0,0,0.33)" font-family="Georgia,serif" font-size="27" text-anchor="middle" x="200" y="113" dominant-baseline="central">offline</text></svg>',
    { headers: { "Content-Type": "image/svg+xml" } }
  )
});
```

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team

**Comment by nhoizey** [comment]
@tomayac should I open a new issue then, with the same content, if the feature I suggested is still relevant?

**Comment by tomayac** [comment]
I think in this case the feature request, while useful, goes a bit against the [spirit of the recipe](https://developer.chrome.com/docs/workbox/modules/workbox-recipes#type-OfflineFallbackOptions:~:text=A%20number%20of%20common%20patters%2C%20especially%20around%20routing%20and%20caching%2C%20are%20common%20enough%20that%20they%20can%20be%20standardized%20into%20reusable%20recipes.%20workbox%2Drecipes%20makes%20these%20available%20in%20an%20easy%2Dto%2Dconsume%20package%2C%20allowing%20you%20to%20get%20up%2Dand%2Drunning%20with%20a%20highly%20functional%20service%20worker%20quickly.). Since there are other means to get the desired behavior, I think it doesn't make sense to make a simple recipe more complex.

**Comment by nhoizey** [comment]
@tomayac ok, I understand the spirit! 👍

**Comment by nhoizey** [comment]
@tomayac BTW, I guess a “n” is missing in “A number of common patters”.

I opened an issue: https://issuetracker.google.com/issues/336832620

I thought I would be able to provide a PR, but couldn't find how.
