### ISSUE TITLE
question: changing the sw internal behavior

### ISSUE THREAD

**Issue by userquin** [GoogleChrome/workbox#3029]
**Library Affected**:
`workbox-window` + `workbox-build`

**Browser & Platform**:
Google Chrome v98.0.4758.82 for Windows, not yet tested on other browsers and SO.

**Issue or Feature Request Description**:
It is a problem about changing the `workbox-*` internals when using `workbox-build::generateSW` (should have the same problem using a custom sw and `workbox-build:injectManifest`): from auto update to prompt strategy.

The current sw is using:
```ts
self.skipWaiting();
workbox.clientsClaim();
```
and we change it to use:
```ts
 self.addEventListener('message', event => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
      self.skipWaiting();
    }
  });
```

The browser will keep the new sw in `skip waiting` state: see https://github.com/antfu/vite-plugin-pwa/issues/228#issuecomment-1037545037

You can clone the `vite-plugin-pwa` repo, then execute `pnpm install + pnpm run build` (`pnpm` installed globally and node 14+), then `pnpm run examples`, then follow the cli using:

![imagen](https://user-images.githubusercontent.com/6311119/153731767-24c65fde-f14d-4b52-a760-6686e81ebc2b.png)

Open the browser and enter `https://localhost`, wait to `App ready to work offline` toast/dialog message, the sw will be installed with previous `self.skipWaiting` and `workbox.clientsClaim` (you can see opening `workbox-**.js` on source tab, `sw.js/localhost` folder).

Stop the server, but keep the page in the browser, run again `pnpm run examples` then follow cli options but now change `Select a behavior` with `Prompt for Update` instead `Auto Update`:

![imagen](https://user-images.githubusercontent.com/6311119/153731684-0907547c-dc6d-4ea3-a5b7-d71d92de4953.png)

Refresh the browser page and you'll see the sw is on `skip waiting` state. The only way to make it work is closing all browser windows and reopen the url again.

**Comment by jeffposnick** [comment]
I'd recommend reading through https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#updates, which describes what happens when there's an updated service worker.

To summarize, if an updated service worker [enters the `waiting` state](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#waiting), it will remain in that state until either a) all of the open client pages controlled by the currently active service worker are closed or b) the update service worker calls `skipWaiting()`.

So what you're seeing is the expected behavior, based on the service worker specification. Workbox will attempt to help by automatically adding that `message` handler to the service worker it generates when configured with `skipWaiting: false`, so that there's a standard way of triggering `skipWaiting()` from any client page.
