### ISSUE TITLE
Provide out of the box solution equivalent to Cache-Control: max-age=n, stale-while-revalidate=n

### ISSUE THREAD

**Issue by ZYinMD** [GoogleChrome/workbox#3069]
**Library Affected**:
workbox-strategies

**Browser & Platform**:
all browsers

**Feature Request Description**:
In http cache, `Cache-Control: max-age=100, stale-while-revalidate=100` means "CacheFirst if cache is fresher than 100, StaleWhileRevalidate if 100 < cache age < 200, NetworkOnly if cache is older than 200".

This is such a natural way of thinking and using cache. I'm surprised there's no way to do it in workbox (unless I write a custom strategy). 

I propose adding a way to support this. There are multiple ways to do it, one is to add an option to the StaleWhileRevalidate strategy:
```ts
new StaleWhileRevalidate({
  skipRevalidationIfFresherThan?: number,
})
```
Or, a more powerful version could be:
```ts
new StaleWhileRevalidate({
  cacheFirstBeforeSeconds?: number,
  networkFirstAfterSeconds?: number,
  networkOnlyAfterSeconds?: number, // same as maxAgeSeconds in ExpirationPlugin
})
```
Or, provide a brand new strategy:
```ts
new Combined({
  cacheName?: string,
  plugins?: Plugin[],
  breakpoints: [number, number, number] // serve from cache < number1 < serve from cache but revalidate < number2 < go to network but fallback to cache < number3 < network only
})


```

**Comment by jeffposnick** [comment]
If you're willing to implement a custom strategy, following the information available at https://web.dev/extending-workbox/, I think that's the best path forward. We designed `workbox-strategies` in v6 to provide a set of foundational wrappers for interacting with the network and cache, along with an abstract `Strategy` class you could extend to implement your own logic, while still being compatible with any Workbox plugins.

The `StaleWhileRevalidate` strategy that's shipped in Workbox v6 does just that: https://github.com/GoogleChrome/workbox/blob/5530e0b5d0b8d4da9f23747ecac665950a26bd51/packages/workbox-strategies/src/StaleWhileRevalidate.ts#L40

I don't want to dismiss your suggestion as not being useful, but we are a bit hesitant to make fundamental changes to the built-in strategies at this point, since there's a path forward for the community to build their own drop-in replacements.

**Comment by shadow-light** [comment]
It would be nice to have something like `skipRevalidationIfFresherThan` built in (acknowledging that there can't be an option for every situation).

There's a lot of cases where you'll want to periodically check if an asset has been updated, but currently can only either check every single time or never check, or expire the cache and hope the user isn't offline!

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
