### ISSUE TITLE
handlerWillRespond callback never invoked for failures

### ISSUE THREAD

**Issue by pavlexander** [GoogleChrome/workbox#3073]
**Library Affected**:
"workbox-background-sync": "^6.5.3",
"workbox-core": "^6.5.3",
"workbox-precaching": "^6.5.3",
"workbox-window": "^6.5.3"

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
According to this page: https://developer.chrome.com/docs/workbox/using-plugins/#methods-for-custom-plugins

> [handlerWillRespond](https://developer.chrome.com/docs/workbox/reference/workbox-core/#method-HandlerWillRespondCallback): Called before the strategy's [handle() method](https://developer.chrome.com/docs/workbox/reference/workbox-strategies/#method-CacheFirst-handle) returns a response, which is helpful if you need to modify a response before returning it to a [RouteHandler](https://developer.chrome.com/docs/workbox/reference/workbox-core/#type-RouteHandler) or other custom logic.

So I have set the following configuration:

`sw.js`

```
import {
  precacheAndRoute,
  cleanupOutdatedCaches,
  createHandlerBoundToURL,
} from "workbox-precaching";
import { NavigationRoute, registerRoute } from "workbox-routing";
import { Queue } from "workbox-background-sync";
import { NetworkOnly } from "workbox-strategies";

const queue = new Queue("myQueueName", {
  onSync: async ({ queue }) => {
    let entry;
    while ((entry = await queue.shiftRequest())) {
      try {
        await fetch(entry.request.clone());
      } catch (error) {
        await queue.unshiftRequest(entry);
        throw error;
      }
    }
  },
});

precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();
registerRoute(new NavigationRoute(createHandlerBoundToURL("index.html")));

const statusPlugin = {
  handlerWillRespond: async ({ request, response, event, state }) => {
    console.log("handlerWillRespond");
    return response;
  },
  fetchDidFail: async ({ originalRequest, request, error, event }) => {
    console.log("fetchDidFail");
    queue.pushRequest({ request: originalRequest });
  },
  fetchDidSucceed: ({ response }) => {
    console.log("fetchDidSucceed");
    return response;
  },
};

registerRoute(
  new RegExp(".*/Exercises/.*"),
  new NetworkOnly({
    plugins: [statusPlugin],
  }),
  "POST"
);
```

On the **client** using `axios`:

```
    const axiosInstance = axios.create({
      timeout: 2000,
      withCredentials: true,
    });

    const add = async () => {
      try {
        console.log("Client makes a request");
        var response = await axiosInstance.post("Exercises/Create", { name: 'test' });
        console.log("Client sees OK");
      } catch (error) {
        console.log("Client sees an error");
      }
    };
```

For error response the order of output is:

1. Client makes a request
2. Client sees an error
3. `fetchDidFail`

The `handlerWillRespond` callback is never invoked. I expect the following output:

1. Client makes a request
3. `handlerWillRespond` <------
2. Client sees an error
3. `fetchDidFail`

For successful responses order is:

1. Client makes a request
2. `fetchDidSucceed`
3. `handlerWillRespond`
4. Client sees OK

If `handlerWillRespond` (regardless if it's a bug or not) is not meant to be used for this use-case and is not meant to be invoked before client sees the error response - could you show an approach that allows to override the response before the client sees it? Basically I want to override the `fetch` false-positive results

**Comment by jeffposnick** [comment]
I believe that what you're seeing is the expected behavior.

`handlerWillRespond` will only be invoked if there's a valid `Response` generated by the strategy, and it gives you a chance to modify that `Response` object prior to passing it along to the client page. If you're using a `NetworkOnly` strategy and the network is unavailable, then `handlerWillRespond` will not be called.

If you want to provide a fallback/"fake" `Response` via a plugin, as an alternative to returning a network error, then you have two options:

`fetchDidFail` can be used to return a fallback response when the network portion of a strategy fails to returns a `Response`. (As you'd assume, in `NetworkOnly`, there's only a network portion.)

`handlerDidError` can be used to return a fallback response when _all_ portions of a strategy fail to return a `Response`—i.e., both the network and any cache-based portion of a strategy fail to generate anything.

So, it sounds like using one of either `fetchDidFail` or `handlerDidError` will give you want you want.
