### ISSUE TITLE
Workbox should ideally use the same accept header as the browser when fetching resources

### ISSUE THREAD

**Issue by cramforce** [GoogleChrome/workbox#3130]
**Library Affected**: workbox-sw

**Browser & Platform**: All

**Issue or Feature Request Description**:

We noticed that workbox, when prefetching HTML documents, for example for the start-page it is using the accept header `*/*` instead of the browser default for documents (e.g. `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9` for current Chrome)

We are shipping a product which filters whether to do server-side transformations based on the accept header. While this is not an incredibly common use case, it is definitely something that people do :)

I'm happy to send a PR if I can get a quick pointer as to where the relevant fetch actions are performed.

**Comment by jeffposnick** [comment]
👋 @cramforce and CC: @tropicadri for visibility.

(With the caveat that I'm no longer working on Workbox,) Assuming that by "prefetching" you're referring to requests originating from the manifest passed to `workbox-precaching`, from a high-ish level, the request originates at https://github.com/GoogleChrome/workbox/blob/95f97a207fd51efb3f8a653f6e3e58224183a778/packages/workbox-precaching/src/PrecacheStrategy.ts#L213

If you wanted to customize that `handler.fetch()` behavior, the cleanest approach would be to create a suitable [`requestWillFetch` plugin](https://developer.chrome.com/docs/workbox/using-plugins/), and then passing it to the [`addPlugins()`](https://developer.chrome.com/docs/workbox/reference/workbox-precaching/#method-addPlugins) method exported by `workbox-precaching`.

**Comment by cramforce** [comment]
@jeffposnick Clarifying: I'd like to fix this in workbox rather than just for my own project.

**Comment by jeffposnick** [comment]
I was curious, so I just wanted to share what I found when I looked into the current behavior. You might be familiar with this already, @cramforce, but it might help @tropicadri & co. determine how to proceed.

As per the [Fetch spec](https://fetch.spec.whatwg.org/#:~:text=If%20request%E2%80%99s%20header%20list%20does%20not%20contain%20%60Accept%60%2C%20then%3A), when `fetch()`ing a request that doesn't not contain a preconfigured `Accept:` header, a default value of `*/*` should be used, unless the underlying request also has a `destination` property set. If `destination` is set to one of a few specific values, including `'document'`, then there's a different default that _should_ be used. `'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'` is what's given in the spec, but since it's a _should_, I guess Chrome has leeway to use something different.

(It's not possible to explicitly [construct a `Request` object](https://fetch.spec.whatwg.org/#requestinit) with a specific `destination` property, like `'document'`. And the `destination` is [read-only](https://fetch.spec.whatwg.org/#request-class) after construction, so you can't set it from JavaScript, either. Only the browser can create a `Request` with a specific `destination`.)

When Workbox creates a new `Request` that ends up being `fetch()`ed during precaching, it's hard to know whether it's a request for a document, or stylesheet, or anything else. You could try to infer it based on the URL's extension, but I've seen folks with precache manifest URLs like `/appshell`, which don't include an extension at all.

My feeling is that it would be difficult to safely change `workbox-precaching` to intelligently override the `Accept: */*` default for arbitrary URLs that appear in the precache manifest. There's a reason that's the generic default in the Fetch spec.

Doing this via a plugin, which you could add to your own service worker without changing the behavior for others, seems like a safer approach. You presumably have control over what type of URLs end up in your precache manifest, and could make an informed decision about which URL requests should have their `Accept:` header set to a specific value.

**Comment by jeffposnick** [comment]
With that all said, to give some more context to your original question, the code that actual constructs the `Request` that ends up `fetch()`ed when precaching is at https://github.com/GoogleChrome/workbox/blob/95f97a207fd51efb3f8a653f6e3e58224183a778/packages/workbox-precaching/src/PrecacheController.ts#L208-L225

We added in support for supplying an optional `integrity` field in the precache manifest entries a while back, which gets fed into the `Request` constructor. One could imagine adding in a new field in the precache manifest called `headers` which was then used in a similar way. Making it opt-in behavior which is triggered by explicitly setting `headers` values in precache manifest entries would make this a backwards-compatible change.

**Comment by tomayac** [comment]
Hi there,

Workbox is [moving to a new engineering team within Google](https://github.com/GoogleChrome/workbox?tab=readme-ov-file#maintenance-update:~:text=Maintenance%20update,owners%20of%20Workbox.). As part of this move, we're declaring a partial bug bankruptcy to allow the new team to start fresh. We realize this isn't optimal, but realistically, this is the only way we see it working. For transparency, here're the criteria we applied:

- For PRs, we closed [everything that doesn't target the current `v7` branch](https://github.com/GoogleChrome/workbox/pulls?q=is%3Apr+is%3Aclosed+-base%3Av7).
- For Issues, we closed [everything that was created before 2024](https://github.com/GoogleChrome/workbox/issues?q=is%3Aissue+is%3Aclosed+created%3A%3C2024-01-01+). 

Thanks, and we hope for your understanding!
The Workbox team
