### ISSUE TITLE
What caching strategy does cacheRevisionedAssets use?

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/workbox#365]
**Library Affected**:
sw-lib

**Browser & Platform**:
all

**Issue or Feature Request Description**:
The docs for [cacheOnly()](https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.13/module-sw-lib.SWLib.html#cacheOnly), `cacheFirst()`, etc. are straightforward in terms of which caching strategy they use. Those map to Jake's offline cookbook.

But the doc for [cacheRevisionedAssets()](https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.13/module-sw-lib.SWLib.html#cacheRevisionedAssets) is unclear.

From what I understand, when I use `sw-build.generateSW()`, `sw-build` detects when any of the files specified in `globPatterns` change. It then automatically increments the `revision` number for those files in the generated service worker. Something Jeff said led me to believe that the generated SW will use `cacheRevisionedAssets()` in this scenario

But what caching strategy does the SW use to download these updated files?

**Comment by patrickhulce** [comment]
Also unclear if cacheRevisionedAssets actually installs the `fetch` handler at all or if it just does the `install` fetching to store into cache. The [sw-precaching](https://googlechrome.github.io/sw-helpers/reference-docs/stable/v0.0.13/module-sw-precaching.html#main) page example looks like it doesn't have any fetch handler which didn't help

**Comment by gauntface** [comment]
@patrickhulce @kaycebasques super curious what you think is the appropriate behavior here.

To answer the questions:
cacheRevisionedAssets() downloads the files from the network - but only the files that have revisions that have changed and then it will add a route for these entries to be served with the CacheOnly strategy.

We've had other bugs raised around this being too magically / unclear.

Is this just a docs issue or should we add a more explicit API that means the developer adds a route to the router for these cached assets?

**Comment by patrickhulce** [comment]
It's definitely magic, but I think that's the value :)

I'd personally be happier having two calls (1 for inserting into cache, 1 for setting up routes with an explicit mention of cache strategy) just so that it's made explicit what happens where. `fetchChangedAssets(manifest)` and `registerVersionedAssetRoutes(manifest)` or something?

CacheOnly makes sense given these files are revisioned and should never change until the next service worker is pushed, but it's probably worth extra highlighting that fact. Especially since so many people try to construct the manifest themselves. Is the situation handled, btw, if the files get evicted from the cache somehow, but the strategy is cache only?

**Comment by kaycebasques** [comment]
@gauntface does this still hold? Specifically that the default configuration is to use `CacheOnly` and re-download the resource when the revision changes?

**Comment by jeffposnick** [comment]
@kaycebasques—Yes, that's the case.

**Comment by gauntface** [comment]
@patrickhulce @kaycebasques do you think it's worth changing this? (I don't think the linked PR should have closed this issue without further discussion).

I'm not against having the methods `precacheChangedAssets(manifest)` and `addPrecacheRouteHandler()` but since release no-one else has expressed concerns over this, although the precaching is largely a build step and fairly magical.

**Comment by gauntface** [comment]
In v3 we are seperating the precaching of assets and the fetch handling, so this should be clearer to developers.
