### ISSUE TITLE
Router.unregisterRoutes() method?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#390]
**Library Affected**:
`sw-routing`

Not necessarily something we need to add, but it came up in another context, and we can at least consider creating a `Router#unregisterRoutes()` method that would remove one or more `Route` objects from the list of routes that are used in the `fetch` handler.

The tricky bit being that you'd have to save a reference to the original `Route` that was registered and then pass that same reference in when unregistering, since we'd presumably need to check for object equality to figure out which `Route` to unregister.

**Comment by addyosmani** [comment]
Just to confirm: the suggestion here is allowing a `Route` instance to be removed from the list of routes used in the `fetch` handler rather than something that would take one or more static route paths and remove any/all routes associated with them found in the handler?

> The tricky bit being that you'd have to save a reference to the original Route that was registered and then pass that same reference in when unregistering, since we'd presumably need to check for object equality to figure out which Route to unregister.

This caveat seems fair to me. I think we would need to do an amount of equality checking to determine what Route object needs to be removed.

**Comment by jeffposnick** [comment]
Right, I think you'd have to implement this by passing in one or more `Route`s rather than allowing folks to pass in arbitrary paths.

**Comment by gauntface** [comment]
Could we return the Route instances that we generate in workbox-sw and that way most dev's will simply ignore them, but those wishing to unregister can do so with the returned Route.
