### ISSUE TITLE
Improve speed of builds

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/workbox#404]
**Library Affected**:
*sw-appcache-behavior, sw-offline-google-analytics, etc.*

A full build currently takes between 10-30 minutes to complete on Travis:

![image](https://cloud.githubusercontent.com/assets/110953/24618878/40c3077e-184d-11e7-9241-6ab754d90d24.png)

On AppVeyor/Windows, we're looking at it taking multiple minutes too. 
![image](https://cloud.githubusercontent.com/assets/110953/24619000/8e39f4ae-184d-11e7-8889-3f98efc4dfcf.png)

For smaller PRs, this introduces a bit of a bottleneck for folks that are trying to land incremental work at a decent pace. 

* sw-precaching
* sw-background-sync-queue

appear to take a while. 

Some areas for exploration:

* Could we speed up the build by reducing our reliance on babel? drop async/await
* Are we holding RollUp wrong? We might be able to squeeze some wins out by disabling features like tree-shaking
* Downloading browsers (although I believe cached..) appears to take 500+ms per package:

![image](https://cloud.githubusercontent.com/assets/110953/24619270/4b40198e-184e-11e7-9732-09126aae45f7.png)

**Comment by jeffposnick** [comment]
FWIW, a unscientific experiment on 4 year old Mac shows that removing async/await transpilation takes the `sw-lib` build time from 17s down to 15s, and shaves ~1.1kb from the final output size of the minified `umd` bundle.

Removing `babili` minification (which I'm not suggesting we remove) takes the build time from 17s down to 13s.

`sw-background-sync-queue` is a bit of an extreme case, since it requires [bundling a whole bunch of individual modules](https://github.com/GoogleChrome/sw-helpers/blob/master/packages/sw-background-sync-queue/build.js#L38) for testing purposes during the build. Perhaps @prateekbh could provide some context as to whether that's really necessary, and if not, it could be rewritten to follow the patterns used by the other modules?

**Comment by jeffposnick** [comment]
https://github.com/GoogleChrome/sw-helpers/pull/485 should have helped, particular with the speed of `sw-offline-google-analytics` and `sw-background-sync-queue` builds.

A lot of the latency in those screenshots has to do with running code in a throttled CI build environment, as you can see total build times vary by up to an hour depending on what the Travis infrastructure is up to: https://travis-ci.org/GoogleChrome/sw-helpers/builds

**Comment by prateekbh** [comment]
@jeffposnick as of now I can see some really super fast builds on my local. I'll see if I can work with a single build itself

**Comment by gauntface** [comment]
I'm going to close this, I think between my testing re-write and Jeffs build tidy up, the builds are more bearable.

**Comment by jeffposnick** [comment]
💨
