### ISSUE TITLE
Request Wrapper + Handlers + Plugins

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#497]
This has been something that I've been struggling to wrap my head around for some time and this is just me spit balling, so not necessarily thought through 100%, but curious of others points of view.

At the moment this is the "vague" flow we have when a fetch request is made:

*fetch event* > Router > Route > Handler > RequestWrapper[Wrapper calls plugins it has from constructor]

I'm been struggling with the flow between the handler, request wrapper and plugins because the plugins feel misplaced in a request wrapper and it feels unexpected to give every handler a unique request wrapper.

There are scenarios where a developer may want global logic across their service worker, for example:

1. Ignore specific, or all, url search parameters.
2. Use a specific cache by default.
3. Ensure all cache events broadcast a channel update.
4. Define a specific cache expiration for all requests and caches unless specified.

This is fiddly to do in the above flow because the plugins and variables that support these behaviors are added to the request wrapper, this means that each handler needs to have it's own request wrapper with these plugins configured (i.e. it's not global, it's duplicated for each handler).

An alternative would be to make the handlers have the plugins and have an API agreement between the handler and request wrapper (This gives us the same behavior as before):

*fetch event* > Router > Route > Handler[Uses plugins when request wrapper calls] > RequestWrapper[Wrapper calls handler throughout]

The benefit here is that the RequestWrapper can now be a singleton. Handlers are responsible for the extra specifics on behavior (This doesn't solve the global desires outlined above). But, by following this pattern, we can add global behaviors to the RequestWrapper singleton (i.e. the developer could have do something like `self.requestWrapper.addPlugin({cacheWillUpdate: () => {}});`). This would then apply to all requests. 

The complication of this is that we'd need to consider the order the plugins are called. Should the Handler's plugins be called before or after the RequestWrappers plugins. My thought here is that we could decide on a precedent (i.e. globals in RequestWrapper first) or add some notion of priority to plugins.

@jeffposnick @addyosmani @jpmedley thoughts on this?

**Comment by addyosmani** [comment]
Let's chat about the current state of discussion around this at the next team API design sync.

**Comment by jeffposnick** [comment]
For the most part, those scenarios are all reasonable things that a developer might want to do which are either complicated or impossible to accomplish using the current `workbox-sw` interfaces. So yes, let's clean it up!

The use of global state in `sw-toolbox` left a bad taste in my mouth, and I wanted to move away from it with Workbox.

Rather than make `RequestWrapper` a singleton, and then asking developers to configure the default behaviors via `self.requestWrapper.*`, what if we addressed the use case via getters and setters exposed under `WorkboxSW#defaults.*`? (I.e. each instance of `WorkboxSW` has its own `defaults`.)

This has the benefit of hiding the whole concept of `RequestWrappers` from most folks who consume the library. It's an implementation detail that we've mostly papered over already, via the `Handler` factories exposed under `WorkboxSW#strategies`.

It also has the benefit of not shoehorning logic into the `RequestWrapper` that might make more sense if it lived elsewhere. For instance, one of your scenarios is "Ignore specific, or all, url search parameters." I'd argue that this is routing configuration, rather than `Handler` or `RequestWrapper` configuration. Exposing the setting outside the context of `RequestWrapper`s gives us the flexibility to use the setting from our router.

We currently have a number of default values assumed throughout `WorkboxSW`, some of which we exposed via one-off getters, like [`runtimeCacheName`](https://github.com/GoogleChrome/workbox/blob/2469f962a7f8d2bcf665aa32610b16c5b5ccb186/packages/workbox-sw/src/lib/workbox-sw.js#L238). If all those defaults were getters and setters under `WorkboxSW#defaults.*`, we'd end up with a consistent API.

(The question of plugin priority is still equally unanswered in my proposal, but we could deal with that as part of a follow-up discussion.)

**Comment by gauntface** [comment]
I guess what I'm trying to achieve is an API where instead of:

```javascript
const requestWrapper = new workbox.runtimeCaching.RequestWrapper({
  cacheName: 'example-cache-name',
  cacheId: 'cache-id',
  plugins: [],
  fetchOptions: {
    body: 'hello'
  },
  matchOptions: {
    ignoreSearch: true,
  }
});

const cacheFirst = new workbox.runtimeCaching.CacheFirst({
  requestWrapper
});

const requestWrapper = new workbox.runtimeCaching.RequestWrapper({
  cacheName: 'example-cache-name',
  cacheId: 'cache-id',
  plugins: [],
  fetchOptions: {
    body: 'goodbye'
  },
  matchOptions: {
    ignoreSearch: true,
  }
});

const networkFirst = new workbox.runtimeCaching.NetworkFirst({
  requestWrapper
});
```

We achieve the same with:

```javascript
const cacheFirst = new workbox.runtimeCaching.CacheFirst({
  cacheName: 'example-cache-name',
  cacheId: 'cache-id',
  plugins: [],
  fetchOptions: {
    body: 'hello'
  },
  matchOptions: {
    ignoreSearch: true,
  }
});

const networkFirst = new workbox.runtimeCaching.NetworkFirst({
  cacheName: 'example-cache-name',
  cacheId: 'cache-id',
  plugins: [],
  fetchOptions: {
    body: 'goodbye'
  },
  matchOptions: {
    ignoreSearch: true,
  }
});
```

This is a minor API change on the surface, but I think it's more in tune with the expectation of how plugins affect behavior and we can pull some logic out of RequestWrapper into the Handlers (like the  [effective cachaeble response plugin](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-runtime-caching/src/lib/request-wrapper.js#L298) could be defined by the Handler base class) and we can make the reasoning of behaviors easier to follow as a result. Ultimately the RequestWrapper can be stateless,  follow a specific set of steps and push behavior alterations and features into plugins. This will also give us a concise extension story for developers as well.

The only thing that this loses is the "default" configuration for a given RequestWrapper. We can add some of this back in by utilising a "workbox-core" style module where the configuration for defaults can be stored, then either Handlers or the RequestWrapper can use them.

**Comment by jeffposnick** [comment]
I'm supportive of letting developers to configure a `RequestWrapper` via parameters passed to the base `Handler` constructor. It would ideally share a lot with (or be completely identical to) the configuration currently supported by the `WorkboxSW.strategies.*` factory methods. So 👍  there.

> Ultimately the RequestWrapper can be stateless, follow a specific set of steps and push behavior alterations and features into plugins. This will also give us a concise extension story for developers as well.

I still am 👎  on this. There's no technical reason why we couldn't adopt this, but I'm in favor a the model where the low-level foundation used inside of `Handler`s is a `RequestWrapper` instance that has been properly configured ahead of time, rather having `Handler`s call static `RequestWrapper` methods with options/plugins that were configured ahead of time.

`RequestWrappers` haven't (yet) seen adoption as a low-level primitive used outside of Workbox, but they *could*. My feeling is that treating them as self-contained objects, an instances of which fully define the state of network/cache behavior, makes it more likely that they'll eventually find use from developers who don't necessarily want to adopt our `Handler` classes, but do want to adopt our approach to network/cache customization..

**Comment by gauntface** [comment]
@jeffposnick developers will still be able to use RequestWrappers, the class can still be exposed and instantiated on it's own, I just believe that plugins don't need to exist in the RequestWrapper, but instead be passed in. Main difference is we aren't creating lots of instances of a class when the behavior isn't going to change.

**Comment by jeffposnick** [comment]
I'm not worried about creating multiple instances of a class if it means that each instance is self-contained and encapsulates a specific network/cache behavior. That model makes much more sense to me.

We could compromise on a hybrid approach, in which you could still instantiate a new `RequestWrapper` instance and provide plugins/config via the constructor, but also support passing in plugins/config directly as parameters to `fetchAndCache()`, `fetch()`, and `match()`. Then there could just be one "psuedo-static" instance of `RequestWrapper` that was used internally by `workbox-sw`.

This sends a mixed-message about the intended use case to developers who might read the `RequestWrapper` docs because they want to use it correctly, but we see confusion or developers clearly opting for one approach vs. the other, effectively deprecate the alternative approach in a future major release.

**Comment by gauntface** [comment]
We could also do a slightly twist on the above.

We could have static functions that implement `fetch()` and `fetchAndCache()` logic which the RequestWrapper utilises and the core and expose the fetch and fetchAndCache methods as statically accessible methods.

**Comment by jeffposnick** [comment]
Yup, we could. So do we have consensus on:

- Support both the static and instance use cases in the v3 refactoring, using whatever seems the cleanest "under the hood" inside of `workbox-sw`.
- Evaluate deprecation of one of those approaches depending on whether or not we hear from confused developers.

**Comment by gauntface** [comment]
@jeffposnick I think we are in agreement. I'll touch on it early on in V3 and we can discuss further on that if that's ok with you?

**Comment by jeffposnick** [comment]
👍

**Comment by gauntface** [comment]
@jeffposnick I haven't heard anything negative about the current approach in V3, would you be happy to close this?

**Comment by jeffposnick** [comment]
👍
