### ISSUE TITLE
Is there a no-cors option in the caching strategies?

### ISSUE THREAD

**Issue by nasearle** [GoogleChrome/workbox#586]
**Library Affected**:
workbox-sw, workbox-runtime-caching

**Issue or Feature Request Description**:
@gauntface @jeffposnick I'm trying to use the cacheFirst strategy to cache a font from fonts.googleapis.com, but for some reason Workbox isn't caching it. I think the font is opaque/no-cors because when I cache it manually there's no 200 code in the cache in DevTools (but there IS a 200 response when I fetch the font from the console so idk). I can cache this same font with sw-toolbox like this:
```
  global.toolbox.router.get('/(.*)', global.toolbox.cacheFirst, {
    cache: {
      name: 'googleapis',
      maxEntries: 20,
    },
    origin: /\.googleapis\.com$/
  });
```
But when I try to cache it with the following code using workbox, the "googleapis" cache is empty:
```
workboxSW.router.registerRoute('https://fonts.googleapis.com/(.*)',
  workboxSW.strategies.cacheFirst({
    cacheName: 'googleapis',
    cacheExpiration: {
      maxEntries: 20
    }
  })
);
```
Maybe I'm missing a new option in the workbox caching strategies that allows caching opaque responses (if that is actually the issue)?

**Comment by jeffposnick** [comment]
Yes, you have to explicitly opt-in to caching opaque responses when you're using a `cacheFirst` strategy. (Opaque responses are allowed by default when using `networkFirst` and `staleWhileRevalidate`, since even if an error response is cached, it will be replaced in the near future.)

Ideally, there should have been a message to that effect logged in the DevTools JS console explaining what was going on, but that's only helpful if you know where to look.

You can see an example configuration for opting-in to caching opaque responses with `cacheFirst` at the end of https://workboxjs.org/examples/workbox-sw/#explore-the-code:

```js
workboxSW.router.registerRoute(
  'https://httpbin.org/image/(.*)',
  workboxSW.strategies.cacheFirst({
    cacheName: 'images',
    cacheExpiration: {
      maxEntries: 2,
      maxAgeSeconds: 7 * 24 * 60 * 60,
    },
    cacheableResponse: {statuses: [0, 200]},
  })
);
```

And there's some standalone docs at https://workboxjs.org/reference-docs/latest/module-workbox-cacheable-response.html
