### ISSUE TITLE
Add Log to Highlight When a Caching Header if used for a service-worker js file

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#620]
> This is, in my opinion, the issue most likely to cause developer frustration and confusion.
>
> It's very easy to unknowingly cache your service-worker.js file for even a short period of time (e.g. by deploying to GitHub pages, which caches everything for 10 minutes). This cache reuse has an upper bound of 24 hours, so it won't stretch on indefinitely, but during the window when the cache is in effect, the potential for developer (and operations) pain is very high.

We could request the service worker, check for cache headers and log a message to highlight when it's not zero. This could be part of a larger logging / welcome message.

**Comment by gauntface** [comment]
Just had a developer hit this problem.

I think a small check list for these kind of problems, similar style to the welcome message would be extremely helpful.

**Comment by jeffposnick** [comment]
This should no longer be a problem in FF57+, but using a cached version of the `sw.js` is still an issue in Chrome.

My thoughts on this approach is that it's clever, but it's probably not something we'd want to do in the production build. And doing it just in the development build might not be as useful, since it's common to use a different server config with different caching headers for `localhost` vs. a production environment.

So... good idea, but potentially difficult to do in a meaningful way without extra traffic in prod.

**Comment by MattiJarvinen-BA** [comment]
What about simple HEAD request? Traffic but not too heavy.

**Comment by gauntface** [comment]
We can do this in dev and not in prod - so it shouldn't be a concern.

If anyone is will to try and PR this into workbox-core in the v3 branch I'd be more than happy to review it.

**Comment by jeffposnick** [comment]
This is a big pain point, so sure, anything we could do to point folks in the right direction would help.

I'll just reiterate that the logging might be vulnerable to false positives and negatives since the the `localhost` serving environment isn't always going to match the production serving environment.

It would also need to deal with the fact that there are a [bunch of different `Cache-Control` header combinations](https://jakearchibald.com/2016/caching-best-practices/) that would effectively disable reusing cached entries without revalidation. E.g. either `max-age: 0;` or `no-cache` should be considered "correct".

**Comment by gauntface** [comment]
I will be happy with an attempt to help here - regardless of only catching certain headers / combinations and only catching some scenarios on locahost and not on dev.

There is only so much we can do, but something is better than nothing.

Once we have something - it should be easier for people to iterate on it and provide extra checks.

**Comment by gauntface** [comment]
I would still like this for V3 given how many people this still trips up - so will assign to myself and have a stab at it.
