### ISSUE TITLE
Ensure that the sourcemap is automatically copied alongside the production bundle

### ISSUE THREAD

**Issue by ssatz** [GoogleChrome/workbox#625]
**Library Affected**
webpack workbox plugin 

**Browser & Platform**:
Google Chrome v58

**Issue or Feature Request Description**:
DevTools failed to parse SourceMap: http://localhost/workbox-sw.prod.v1.0.1.js.map

Source map file not generated.

**Comment by jeffposnick** [comment]
The sourcemap is generated and published along with the production bundle; I just checked the 1.0.1 release that's currently on `npm` and it's there:

```sh
$ npm install workbox-sw && ls node_modules/workbox-sw/build/importScripts/

workbox-sw.dev.v1.0.1.js        workbox-sw.dev.v1.0.1.js.map    workbox-sw.prod.v1.0.1.js       workbox-sw.prod.v1.0.1.js.map
```

In order for DevTools to parse the `workbox-sw.prod.v1.0.1.js.map` file, it needs to be exposed by your web server in the same directory that your source file is in. Since your source is `http://localhost/workbox-sw.prod.v1.0.1.js`, the sourcemap should be in `http://localhost/workbox-sw.prod.v1.0.1.js.map`.

It sounds like you're using the auto-generated SW file from the `workbox-webpack-plugin`. I believe that takes care of copying over the `workbox-sw.prod.v1.0.1.js` file along with the generated SW, but maybe it's not copying the sourcemap as well. Does that match your experience?

If so, we can repurpose this bug to reflect the fact that we need to automatically copy over the sourcemap file, too.

**Comment by ssatz** [comment]
Yes I am using auto generated SW file and sourcemap file is not  copying with .js file. It should automatically copy.

**Comment by kaycebasques** [comment]
I'm getting this, too. Using gulp.

**Comment by kaycebasques** [comment]
This is pretty much how I'm building. I stripped off some workbox flags that it seemed like I didn't need (but maybe I do), so it could be pilot error on my part.

```
const gulp = require('gulp'),
    child = require('child_process'),
    gutil = require('gulp-util'),
    wb = require('workbox-build');

function buildSw() {
  return wb.generateSW({
    globDirectory: './_site/',
    swDest: './_site/sw.js',
    staticFileGlobs: ['**\/*'],
  }).then(() => {
    gutil.log('Service worker generated.');
  }).catch((err) => {
    gutil.log('[ERROR] This happened: ' + err);
  });
}

gulp.task('build', () => {
  const jekyll = child.spawn('bundle',
      ['exec', 'jekyll', 'build']);
  const logger = (buffer) => {
    buffer.toString()
        .split(/\n/)
        .forEach((message) => gutil.log(message));
  };
  jekyll.stdout.on('data', logger);
  jekyll.stderr.on('data', logger);
  buildSw();
});
```
