### ISSUE TITLE
Use babel to transpile the workbox-build codebase?

### ISSUE THREAD

**Issue by MaxLeiter** [GoogleChrome/workbox#669]
**Library Affected**:
*workbox-build*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
Currently making a PR, should be as easy as throwing in a 'use strict';

Ref: https://travis-ci.org/thelounge/lounge/jobs/251861458
and thelounge/lounge#1317

**Comment by jeffposnick** [comment]
Thanks for pointing that out! The intention is to get support node 4 for `workbox-build`, though we obviously haven't done a great job of testing that.

While we could approach this via adding in `'use strict';'` throughout the individual modules, I wanted to see how @gauntface & co. felt about running the `workbox-build` project through babel with [`babel-present-env`](https://github.com/babel/babel-preset-env) set up for node 4.

There are a number of times that I've wanted to use, e.g., `async`/`await` or spread operators when working on the `workbox-build` codebase, but didn't, because of legacy node support.

**Comment by MaxLeiter** [comment]
Sounds good to me.

**Comment by gauntface** [comment]
Personally I hate having to transpile anything just to run in a baseline environment so I'd rather just accept use strict.

There is a bigger question of what our support matrix should be. Should it be current stable and latest version? or should be follow the same as node's schedule where node 4 is in maintanence? https://github.com/nodejs/LTS

**Comment by jeffposnick** [comment]
The initial impetus behind a minimum of node 4 was to match what `create-react-app` required, on the assumption that we will try to integrate with them at some point. It turns out `c-r-a` has since switched to requiring node 6: https://github.com/facebookincubator/create-react-app/pull/1897

That being said, since we can easily resolve node 4 support with minimal extra effort, I'm fine with keeping 4 as a minimum, at least until April 2018.

We're going to need `use strict` throughout `workbox-build` and `workbox-cli`, in that case.

**Comment by MaxLeiter** [comment]
`use strict` is already present throughout workbox-cli

**Comment by MaxLeiter** [comment]
Fixed as of #670
