### ISSUE TITLE
📣 Proposal for Future of Workbox

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#699]
I've been fiddling some possible architectural changes that I think would benefit the project and solve some of the most common pain points developers are facing with Workbox at the moment. I would 💗 comments and feedback on on the proposed changes here:

https://docs.google.com/document/d/1GYKyBNpICwirWTxSeOvYd2YZeS5xwpeC3rU5wzEQ4YU/edit?usp=sharing

![giphy-downsized 1](https://user-images.githubusercontent.com/139760/28539906-3319a1e6-7068-11e7-8aa7-4470ef71d791.gif)

**Comment by QES** [comment]
Hi,

Your plan seems very sensible and mimics a lot of the issues I have had, the idea of WorkBox is brilliant but it could be optimized and could be more user friendly.

One of the things I love about AMP is that it takes the complexities away and gives the user a very controlled set of rules - only load the JS modules you use (for example).

It strikes me that a starting point for PWA development should be something that simple.  

A series of JS elements loaded from a CDN and a JSON file that contains a set of rules relevant to the web site being built.  The files to be cached (and the cache rules) - the ampproject CDN files; the image files from the image CDN; the sites HTML pages; the fallback offline page.

Then add further modules and capabilities simply as you need them (offline analytics for example)

At that point you have something that almost anyone who can build an AMP site can deploy and get working and take advantage of a PWA.  It is a starting point for people who want to do this kind of thing.

For me building a content focused we site the goal of PWA is to:

1) Cache the fixed objects - ampproject.org / images 
2) Cache home page and visited pages
3) Cache the top stories in a controlled way so that you could configure pages to be downloaded before your commute while connected to WiFi.

WorkBox seems to be a starting point for the first two, and I haven't worked out the third (as yet)

**Comment by addyosmani** [comment]
@gauntface Now that a few rounds of feedback have been shared against your 👌 proposal, does it make sense to distill it down into a set of issues we can track? e.g once #719 lands it would be good to get a sense for the rest of the work that needs to be done.

**Comment by gauntface** [comment]
@addyosmani agreed, would a single umbrella bug with checklists added to top level goals make sense?

**Comment by gauntface** [comment]
Been a while on this so going to close this Issue as we now have a V3 tracking bug and as issues come up we can discuss from there.
