### ISSUE TITLE
I wish modules would be self-contained

### ISSUE THREAD

**Issue by surma** [GoogleChrome/workbox#700]
I was looking to use `workbox-google-analytics` but it seems I can’t without a good amount of buy-in and manual fiddling. This seems to apply to a lot of the modules, but I’ll use `workbox-google-analytics` as an example:

### What I expected

- I can get a minified/bundled version of just the `workbox-google-analytics` code and put it in my project
- The module provides 2 functions.
  - The first function tells me if a `Request` should be handled by this module
  - The second function handles the request (it’s basically an `fetch` event handler)

### What I got

- A module that depends on other modules outside it’s scope (`log-helper` and `idb-helper`)
- No (obvious) way to build just this module as a self-contained package
- Code that - as a side-effect - registers a top-level `fetch` handler. I need to manually figure out _which_ requests are being handled by the module and not handle those requests in _my_ code.

**Comment by gauntface** [comment]
@surma agreed that this isn't good and @philipwalton had the same problems. Could you do me a HUGE favor and look at the doc referenced in #699 which outlines a rethink of our current module setup.

**Comment by surma** [comment]
On it!

**Comment by surma** [comment]
Left a few comments, my point from this issue wasn‘t quite covered, so I started a discussion. Might be worth continuing it here if y’all like, because the GDocs comments can get quite crammed. LMK ;)

**Comment by addyosmani** [comment]
@surma It's totally valid feedback that we don't provide self-contained builds that are easy to just drop-in for offline-analytics. We should fix that bug. Our npm packages could include this, but it still wouldn't address this piece of feedback:

> Code that - as a side-effect - registers a top-level fetch handler. I need to manually figure out which requests are being handled by the module and not handle those requests in my code.

Did you find that our current DEV/debugging story helped understand what requests were handled by the module? Would better docs or logging have helped here vs. the "The module provides 2 functions." part of your feedback?

**Comment by surma** [comment]
No, this is def. not a docs problem. The analytics module code is actually pretty simple to read, but I’d have to duplicate [some code](https://github.com/GoogleChrome/workbox/blob/3cdc1458b1d911aa584f49cb55183901569ff2ae/packages/workbox-google-analytics/src/index.js#L96-L118) to make sure my code doesn’t handle requests that are already handled by the analytics module.

Explicitly having the developer dispatching events to the module (and providing a function to determine whether an even _should_ be dispatched to the module) seems both more readable and most importantly scalable to me.

**Comment by philipwalton** [comment]
@surma, re: this comment:

> I need to manually figure out which requests are being handled by the module and not handle those requests in my code.

Is this not a docs issue? If a service worker is already handling the fetch event for a particular route, subsequent fetch handlers won't event see that event, so they won't have to handle it or write code to ignore it.

The only issue I see with this is not knowing whether a particular module is already handling a fetch event, and that can be solved by both better docs as well as better logging.

FWIW, once we update the GA module to work with the existing router and background sync modules, you'll get the latter for free.

<img width="1425" alt="screen shot 2017-07-31 at 8 27 47 am" src="https://user-images.githubusercontent.com/326742/28785109-3eea9978-75ca-11e7-8662-4c36532f2390.png">

The updated (WIP) code for this can be found here:
https://github.com/GoogleChrome/workbox/blob/offline-analytics-sync/packages/workbox-google-analytics/src/index.js#L64-L163

Re: all your other comments about modularity, I agree 100% and have expressed this concern to the rest of the team many times. I think the v3 proposal addresses all of these issues.

**Comment by surma** [comment]
>  If a service worker is already handling the fetch event for a particular route, subsequent fetch handlers won't event see that event

Currently, the analytics module [adds it’s own `fetch` event handler](https://github.com/GoogleChrome/workbox/blob/3cdc1458b1d911aa584f49cb55183901569ff2ae/packages/workbox-google-analytics/src/index.js#L92), no? So both the module’s handler _and_ my handler would be called. Or am I misunderstanding the code? 

This seems to be addressed in the new code, although looking at the code: Analytics uses `Router` and `Router` attaches itself to the `fetch` event globally, which is the same issue just in another module.

**Comment by philipwalton** [comment]
> > If a service worker is already handling the fetch event for a particular route, subsequent fetch handlers won't event see that event

Sorry, I said this wrong.

> Currently, the analytics module adds it’s own fetch event handler, no? So both the module’s handler and my handler would be called. Or am I misunderstanding the code?

Yes, they would both receive the fetch event. What I was trying to say (poorly) is if one of them responded with its own `fetch()` call, the other one wouldn't receive notification of that happening. Is that your concern?

If not, I guess I'm not sure what the concern is.

**Comment by gauntface** [comment]
Can we not make use to stopPropagation() or whatever the method is to capture analytics events and then let other requests fall through?

I did this in FCM and it worked a treat.

**Comment by jeffposnick** [comment]
The model used for multiple `fetch` handlers in that they're called one at a time, in the order in which they're registered via `addEventListener()`, and the first one the synchronously call `event.respondWith()` "wins".

So `stopPropagation()` in your example with notifications is roughly equivalent to calling `event.respondWith()`, and the fall-through to the next `fetch` handler happens whenever `event.respondWith()` isn't called by the previous `fetch` handler.

(I wrote up a longer explanation of how this works for an unrelated question: https://stackoverflow.com/questions/45257602/sharing-fetch-handler-logic-defined-across-multiple-service-workers/45285119#45285119)

**Comment by surma** [comment]
> and the first one the synchronously call event.respondWith() "wins".

I did _not_ know that. That changes the situation a little bit, but it feels like something very brittle to rely on. 

I guess this reduces my complaint to: I’d strongly prefer to have this explicit rather than implicit (because to what extent can we make _sure_ that workbox’ `fetch` handler is before the user’s code?)

**Comment by jeffposnick** [comment]
> (because to what extent can we make sure that workbox’ fetch handler is before the user’s code?)

You can't make sure of that. The best you can do probably is to include examples that encourage initializing the library very early on in the process.

Or if you had a guarantee that the rest of the user's code also used Workbox, you could bake in some coordination in the underlying `workbox-routing` level, where special routes that had higher priorities were always given precedence, regardless of which order in which they were registered.

That would break down if developers just called `self.addEventListener('fetch', () => {})`, though.

**Comment by surma** [comment]
> The best you can do probably is to include examples

What about the option that I suggested? Don’t do any implicit, side-effecty handler registrations and move that responsibility to the developer. Maybe we can embrace a pattern similar to this:

```js
// my-service-worker.js
import wbAnalytics from 'workbox-google-analytics.min.js'

/* ... */
addEventListener('fetch', event => {
  // Handler returns true if it handled the event.
  if(wbAnalytics.handler(event)) return;
  // user code
})
```

**Comment by jeffposnick** [comment]
A developer who's writing their own `fetch` handler can just as easily respond by accident to a Google Analytics request before Workbox got a chance to create a response. You can't force developers to call the Workbox code at the start of their own `fetch` event handler.

```js
// my-service-worker.js
import wbAnalytics from 'workbox-google-analytics.min.js';

addEventListener('fetch', event => {
  // Oops, the user's accidentally written code that executes before the Workbox code...
  if (event.request.mode === 'POST') {
    event.respondWith(/* my custom POST logic */);
  }

  if(wbAnalytics.handler(event)) return;
  // User code *ideally* would go here in your suggestion,
  // but there's no guarantee that it actually will...
});
```

> I did not know that. That changes the situation a little bit, but it feels like something very brittle to rely on.

Coming back to this: I don't see how using multiple `fetch` handlers is more (or less) brittle than what you're suggesting. In both cases, the order in which code is run matters, and examples and documentation is needed to ensure that developers get that order right.

**Comment by philipwalton** [comment]
> The model used for multiple fetch handlers in that they're called one at a time, in the order in which they're registered via addEventListener(), and the first one the synchronously call event.respondWith() "wins".

Thanks Jeff. This what I was trying to say above, but then when I tested multiple fetch handlers they were all called, so I was second-guessing what I thought I knew and [why we were recommending putting the GA code first](https://github.com/GoogleChrome/workbox/blob/v1.2.0/packages/workbox-google-analytics/src/index.js#L30-L31).

Now I see that multiple fetches were running in my tests because none of them were calling `event.respondWith()`.

**Comment by surma** [comment]
> You can't force developers to call the Workbox code at the start of their own fetch event handler.

This is a feature. The developer can opt out of workbox handling the request on a per-request basis. With the implicit register, I have no way to do that.

**Comment by jakearchibald** [comment]
I kinda hoped that this would operate a bit like express middleware, eg:

```js
import Workbox from 'workbox';
import { networkFirst } from 'workbox/strategies';
import analytics from 'workbox-analytics';

const router = new Workbox();

router.use(analytics());
router.get('/schedule', networkFirst);

addEventListener('fetch', router.fetchHandler);
```

But a more advanced user could do:

```js
import Workbox from 'workbox';
import { networkFirst } from 'workbox/strategies';
import analytics from 'workbox-analytics';

const router = new Workbox();

router.use(analytics());
router.get('/schedule', networkFirst);

addEventListener('fetch', event => {
  event.respondWith(async function() {
    // Maybe respond if I know I don't need workbox here, else:
    const workboxResponse = await router.handle(event);
    // Now I can do stuff with workboxResponse before returning it.
  }());
});
```

**Comment by jeffposnick** [comment]
I can see why someone familiar with Express might want Workbox to match that syntax, but that's not the interface we went for.

> This is a feature. The developer can opt out of workbox handling the request on a per-request basis. With the implicit register, I have no way to do that.

So I'm a bit lost—the way you opt out of Workbox handling Google Analytics requests is to not use the library. The current implicit code is opaque, yes, but it doesn't impact non-Google Analytics requests. What's the use case for using the library, but having the library ignore some Google Analytics requests? (I'm not being facetious—I'd like to know!)

There's nothing stopping us from exporting various internal bits—both the [Handler](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-runtime-caching/src/lib/handler.js) and the [Route](https://github.com/GoogleChrome/workbox/blob/master/packages/workbox-routing/src/lib/route.js)—that are used implicitly by the library so that they could be used explicitly by developers who don't want Workbox doing too much under the hood. It adds noise to the public interface, but that's not the end of the world. (You're still going to end up pulling in the weight of some of the libraries we're using, like the IDB wrapper and soon the Background Sync library, because they play a critical role with the core `Handler` code.)

But, other than empowering developers to continue using their own `fetch` handlers, I'm trying to understand if there's an overlooked use case that this would enable. Because if there is, we should focus on solving that use case for everyone who's using the library, perhaps through additional configuration.

**Comment by surma** [comment]
> So I'm a bit lost—the way you opt out of Workbox handling Google Analytics requests is to not use the library.

That’s an all-or-nothing approach. I’m looking for a dynamic escape hatch. Maybe I want only _some_ requests to be handled by Workbox (this goes beyond the Analytics example). Another thing that I have done is to mangle/augment request data (mostly headers or CORS modes) before handing it off to a module. 

Additionally, with the “auto-register” approach, Workbox will _always_ be the top-level library. If I am already using some other, 3rd party SW library that approach will most likely make it impossible to use both. If we keep dispatch and invocation explicit, I can compose multiple libraries.

For me, this is not really about the syntax (although I do like Jake’s example code), but about the fact that he explicitly invokes the router in his own fetch handler, allowing him add pre- or post-processing. 

I am not arguing against a “Get Workbox running quickly” API, but I strongly recommend adding an escape hatch that allows me to have the full functionality but with more manual control (see Jake’s “Beginner” vs “Advanced”).

**Comment by jeffposnick** [comment]
> That’s an all-or-nothing approach. I’m looking for a dynamic escape hatch. Maybe I want only some requests to be handled by Workbox (this goes beyond the Analytics example).

The Google Analytics library, if you choose to use it, registers a `fetch` handler that will only respond to Google Analytics-related requests.

If you're using `workbox-sw`, then there's another instance where there's not-entirely-obvious registration of a `fetch` handler—when you call `precache()`, requests made for any of precached URLs will be handled using a cache-only strategy. There's some background on the `precache()` naming choice at https://github.com/GoogleChrome/workbox/issues/370, including a rejected possibility of naming it `precacheAndRoute()` to make that implicit route clearer.

> Additionally, with the “auto-register” approach, Workbox will always be the top-level library. If I am already using some other, 3rd party SW library that approach will most likely make it impossible to use both. If we keep dispatch and invocation explicit, I can compose multiple libraries.

In both of the exceptional cases mentioned above, the developer has actively opted-in to doing something that causes Workbox to respond to **a subset of** `fetch` events. Even if you use Google Analytics or `precache()`, other `fetch` events are yours to respond to, either by explicitly using Workbox's routing + handling code, your own `fetch` handler logic, another SW library's logic, or just not respond at all and let the network handle it.

The rules about the order in which `fetch` event handlers are called, and the first-to-call-`respondWith()`-wins nature of them means that in order to opt-in to using certain behavior, you do need to make sure that they get registered before other `fetch` handlers which might otherwise respond to them.

I'm open to suggestions about renaming the Google Analytics initialization method, or `precache()`, to make it clearer that there's implicit `fetch` event registration going on that needs to take place before your own `fetch` handlers that respond to everything is called. We could use this issue to track that if that sounds like a reasonable outcome.

The other concerns that you bring up, about opting-in to using some parts of Workbox meaning that you lose control over **all** of your `fetch` handling, requiring an escape hatch, doesn't match the reality of what Workbox is doing. I'm not sure what the takeaway is there.

**Comment by gauntface** [comment]
Would be good to circle back to this once V3 is released as this makes big steps forward in this direction.

**Comment by gauntface** [comment]
Workbox Modules are actually in a much better state for V3.

Workbox-sw now actually used the modules global namespace and demos are self contained as much as possible. See: https://workbox-demos.firebaseapp.com/

We've also created a policy that event listeners will only be added for the default exports meaning if you use the classes directly - you get full control.

I think there will be more to do here but will need actual library usage to call out specific uses, so going to close and will nag for v3 feedback once it's out.
