### ISSUE TITLE
workbox-background-sync tests are not consistent with all other packages

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#705]
All packages in this monorepo follow a similar BDD style for mocha tests, with the exception of workbox-background-sync (as discussed in #690). Here are the differences I think should be fixed for the sake of consistency:

- We should use `expect()` instead of `chai.assert()` everywhere.
- We should follow the convention of starting `it()` blocks with a description that reads logically (e.g. `it('should push entries onto the queue')` rather than `it('test push')`.

**Comment by jeffposnick** [comment]
+1. I've also started nesting `describe()` blocks for some new tests I'm writing, with a top-level `describe()` for the overall class/package, and then a sub-`describe()` for each method/function. That leads to `it()` descriptions that can be more concise, since you don't have to repeat the method/function name while still being unambiguous.

**Comment by addyosmani** [comment]
We've discussed this in person and I fully agree the bgsync tests should be rewritten to follow the same BDD style as other tests.

**Comment by prateekbh** [comment]
Have opened a PR for the same that's WIP #707
