### ISSUE TITLE
trouble with precaching when supplying `cacheId`

### ISSUE THREAD

**Issue by HenrikJoreteg** [GoogleChrome/workbox#714]
**Library Affected**:
workbox-precache

**Browser & Platform**:
Build related issue

**Issue or Feature Request Description**:
It's not entirely clear how this is happening, but when i supply a `cacheId` i'm ending up with a second misnamed cache being created, that never gets populated.

On initial load everything seems fine:
<img width="1044" alt="screen shot 2017-08-02 at 2 42 39 pm" src="https://user-images.githubusercontent.com/67925/28896413-396f487c-7791-11e7-96da-272a3809213f.png">

When I refresh, a second, misnamed/empty cache gets created:
<img width="1034" alt="screen shot 2017-08-02 at 2 42 58 pm" src="https://user-images.githubusercontent.com/67925/28896435-4ce5d920-7791-11e7-9b81-889ff2e1696e.png">

The trouble is, this second cache gets referenced when you go offline, and so it thinks it has these assets but seemingly looks for them in the wrong cache, causing complete failure to load.

This seems like a pretty major issue so I wanted to raise it, I was hoping to do a PR rather than file a vague bug, but didn't have the time right now, so I figured it was better to file something. 

To be clear the exact same SW works perfect if I just remove the cacheId.

**Comment by liuruoran88** [comment]
the same trouble, and when I set `cacheId`， the precache update will be not effective.
![image](https://user-images.githubusercontent.com/8220802/28910534-d8097524-785f-11e7-8367-0109a23ab27c.png)

**Comment by jeffposnick** [comment]
Thanks for reporting—we'll take a look.

**Comment by jeffposnick** [comment]
There's a few different approaches that we could take to fix this.

I'm inclined to go something along the lines of https://github.com/GoogleChrome/workbox/compare/fix-multiple-cache-id?expand=1, which will explicitly prevent the `cacheId` prefix from being considered when generating the internal `CacheFirst` strategy that's used for precached URLs, since we're already passing in a `cacheName` that we know will include `cacheId`.

We could otherwise address it by trying to get cute inside of the `RequestWrapper` constructor and refusing to prepend the `cacheId` when the source `cacheName` already includes it, but then you prevent someone from deliberately setting `cacheId` and `cacheName` to the same value.

I need to write a few more tests before I'm ready to file a PR, and that's blocked on #716, but that's the general idea.

**Comment by addyosmani** [comment]
> I'm inclined to go something along the lines of https://github.com/GoogleChrome/workbox/compare/fix-multiple-cache-id?expand=1, which will explicitly prevent the cacheId prefix from being considered when generating the internal CacheFirst strategy that's used for precached URLs, since we're already passing in a cacheName that we know will include cacheId.

I'm supportive of preventing the prefix from being used during internal generation of this strategy. Deferring to @HenrikJoreteg on whether he has preferences for this from his end given the options you outlined.

**Comment by HenrikJoreteg** [comment]
@addyosmani @jeffposnick I don't have strong opinions on the mechanism by which this is prevented. 

If it were my lib I'd probably end up writing a simple little helper function along the lines of `ensurePrefix` that simply prepended it whenever it wasn't already there. 

/me shrugs
