### ISSUE TITLE
Need more clarity around when response.status is 0 

### ISSUE THREAD

**Issue by tomayac** [GoogleChrome/workbox#745]
**Library Affected**:
workbox-sw

**Issue or Feature Request Description**:
Need more documentation around when ```response.status``` is ```0```, this [hit us](https://github.com/emojityper/emojityper/pull/29) in @samthor's [EmojiTyper](https://emojityper.com/), where https://fonts.googleapis.com/css?family=Lato:400,700\|Lobster wasn't being cached.

**Comment by jeffposnick** [comment]
There's a lot of background in https://github.com/GoogleChrome/workbox/issues/78

From what I understand, the information provided in the development bundle's logging was sufficient to diagnose what was going on, but that info isn't logged in the production bundle.

So one takeaway would be to change the log level of [that failure](https://github.com/GoogleChrome/workbox/issues/78) from `debug` to something more serious, so that it's not filtered out in production. This comes at the expense of being "spammy" in production, especially if there are a lot of requests being made that result in opaque responses.

A slightly different takeaway would be to do a better job of steering people towards the development bundle when they're on `localhost`, so that this sort of failure could theoretically be identified there, prior to deployment. I think we used to detect `localhost` + production bundle, or at least talked about doing it, and decided not to log anything in that scenario. Maybe we should revisit that?

**Comment by jeffposnick** [comment]
I'm going to close this in favor of #749, which tracks adding in explicit, non-`debug` logging when this happens.

I just helped someone with this issue on Stack Overflow and it's clear that it's a) common and b) not something that developers end up catching with the `debug` logs.
