### ISSUE TITLE
re-introduce warmRuntimeCache

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#773]
Just hit this form the instructor lead training course and recently asked about this from gtech team.

They wanted to "precache" an external asset and the solution is pretty weak in terms of using cache.addAll during install.

I removed because the use of it seemed to confuse and the use case wasn't clear, but adding third party assets to warm the run time cache as well as warm for assets served from a CDN seem like a good use case.

Possible solutions:

1. Re-add warmRuntimeCache() back into workbox-precaching
2. Create a new module just for adding to warmRuntimeCache()

**Comment by DavidScales** [comment]
I think this would be very useful. Like you've said the current solution for precaching external assets is not ideal, and this will be a very common scenario if developers are following the "app shell" model that is suggested (everyone's app shell is going to have an external font, framework, etc.).

**Comment by jeffposnick** [comment]
The previous discussion was at https://github.com/GoogleChrome/workbox/issues/370, if you want some context as to why it was removed, @DavidScales. I'd be hesitant to just add it back without taking that original feedback into account.

Is there anything we could do to make using `cache.addAll()` during install a more viable approach? Is the biggest blocker having to write your own `install` handler, finding the name of the default runtime cache, or something else?

Alternatively, we could approach this from the context of https://github.com/GoogleChrome/workbox/issues/368, with a library that runs in the `window` context and automates adding the resources currently in use into a runtime cache.

**Comment by gauntface** [comment]
Could we move it out of precaching into another module or a seperate module?

Compared the code you call out #370, my work was overkill.

But I think asking developers to suddenly dip in event handlers etc is pretty OTT given the work this library does.

This request has come up a few times, enough that I think we should bring it back, but I also agree that it needs to be down with more consideration that previously (i.e. avoid developer confusion).

Off the top of my head, we could create a module along the lines of `workbox-cacher` and have a single method:

```javascript
import cacher from 'workbox-cacher';

cacher.addOnInstall([...]);

// Option to cache into a specific cacheName
cacher.addOnInstall([...], {cacheName: '....'});
```

It's at least seperate from precaching. It can be down played in terms of use, but would just be friendly for those that need it.

**Comment by jeffposnick** [comment]
I'm still against it, and feel like the work you're doing to make the default cache names more visible will make it even more straightforward for folks who do need this functionality to write it by hand.

I don't have other arguments to offer against it other than what I've already brought up. If the consensus from other folks is that Workbox should be doing this, then I can certainly be outvoted.

**Comment by gauntface** [comment]
It's ultimately boiling down to:

```javascript
self.addEventListener('install', (event) => {
  const urls = [/* ... */];
  const cacheName = swLib.runtimeCacheName; // Or use your own name.
  event.waitUntil(caches.open(cacheName).then((cache) => cache.addAll(urls)));
});
```

vs

```javascript
const urls = [/* ... */];
workbox.cacher.addOnInstall(urls);
```

**Comment by DavidScales** [comment]
@gauntface @jeffposnick @nasearle

Ah yeah looking at #370 it looks like I am proposing something that you've already tried.

Right now it looks like this in my head:

1. Use `precache()` to precache static 1st party assets - this sets up a `cacheFirst` route (invalidating other routes), and enables cache management (updating cache on activation), and allows glob pattern matching in the build process.
2. If you want to precache 1st party assets that don't use the `cacheFirst` strategy, or you want to precache 3rd party assets (that may or may not use the `cacheFirst` strategy) then write your own install handler.

I think the main issue for me is that its confusing to have a library precaching step and a vanilla precaching step. Particularly because the precache method implements a specific pattern (albeit a common one) that sets up a route and manages the cache - which was not initially obvious to me. Intuitively I would think that there would be a generic precache method (that doesn't set up routes or follow a specific pattern) and a shorthand method for caching static assets. But that looks a lot like what you originally had. 

Some other minor issues to consider with the current implementation:

a. glob pattern matching & cache managment is lost for 1st party assets if you write your own handler
b. dev has to reference the appropriate cache name (which isn't too bad if it's exposed)

I would personally vote for something similar to the original pattern (with perhaps `precache` named `precacheAndRoute` to help clarify that a route is being set up), but I have not had the feedback from developers that you guys have so I can't argue with too much confidence.

**Comment by jeffposnick** [comment]
> If you want to precache 1st party assets that don't use the cacheFirst strategy, or you want to precache 3rd party assets (that may or may not use the cacheFirst strategy) then write your own install handler.

While the best we are currently offering is "write your own install handler", we could better accommodate this use case via code that runs in the `window` context, described in #368.

Re-adding a method to `workbox-sw` to simplify cache-on-install of arbitrary URLs doesn't fully address the common use case. There needs to be a way of automatically detecting what the actual third-party resource URLs are (i.e. you might know about a hardcoded Google Fonts CSS URL, but you don't know about the underlying `.woff2` URL that it references), and that's what #368 could help with.

**Comment by DavidScales** [comment]
That's a good point. Thinking about it more, #368 would be super useful (assuming the issues you've referenced with it could be solved).

I don't know if it would be quite the same as something like `warmRuntimeCache`, since #368 is only warming the runtime cache for the initial page (e.g., you wouldn't be able to precache the top 5 articles in a media site or something). But I think it would go a long way in making it easy for developers to address the most common use case of offlining the app shell.

**Comment by jeffposnick** [comment]
I think the idea is that once your service worker is installed, the routes + runtime caching handlers that you've (hopefully) configured will take care of maintaining the caches of third-party assets.

There's a gap between the initial navigation and when the service worker finishes installation, and nothing loaded during that gap would be picked up by runtime caching. #368 would address that.

**Comment by gauntface** [comment]
@jeffposnick #368 feels too magical to me and we would have to consider how we load code in window vs service worker.

Agree with @DavidScales on stripping back the magic of precache() function (there have been a few issues raised about this) and I agree it's weird having one way using library and one way using normal JS.

**Comment by gauntface** [comment]
I'm going to close this issue in favor of an "advanced recipes" guide: https://docs.google.com/document/d/1s-Ym4tNrs22EwmgPC0wA4I0-bA5GPwODzUgKwZ0k8VU/edit?usp=sharing
