### ISSUE TITLE
Routing in workbox (.get(), .post(), .all(), ....)

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#778]
Jake had a proposal for express style routing (which would be similar to sw-toolbox).

The idea being you include the method of the request on the router:

```javascript
router.get(
    new Route({...})
)
router.post(
  new Route({...})
)
```

This is alternative to:

```javascript
router.registerRoute(
    new Route({..., method: 'get'})
);
router.registerRoute(
    new Route({..., method: 'post'})
);
```

Personally, I'm fine with either, slightly leaning on `registerRoute` as I think it reads a little better. I would like our `method: '...'` to be something that could be handled in the match function rather than like this so that a developer could match a Route against either 'get' or 'post' requests.

@jeffposnick @deanhume @addyosmani @jeffposnick @philipwalton @prateekbh @kaycebasques @jakearchibald @surma  for their thoughts on this.

**Comment by prateekbh** [comment]
QQ: Will method 1 produce a comparable smaller bundle size?

Also I somehow feel method 1 to be intuitive and this might be the case with a lot of other devs who have ever worked with express ever, and are touching workbox for the first time.

**Comment by deanhume** [comment]
I have to agree with @prateekbh - I love the idea of including the method of the request! 

The only thing is will it need to include all of the HTTP verbs eg get, post, put, head, delete, options....?

**Comment by gauntface** [comment]
@deanhume agreed (only did some above).

@prateekbh I'm not too fussed regarding file size if it means a better API surface. The difference should be negligible

**Comment by jakearchibald** [comment]
Here's the docs for what I played around with https://github.com/jakearchibald/sw-routes/blob/master/README.md

The idea is:

```js
router.get(fromNetwork());
```

Is shorthand for:

```js
router.all(ifMethod('GET'), fromNetwork());
```

Although the latter supports any method name.

**Comment by gauntface** [comment]
@jakearchibald yeah I'm generally trying to break up that approach into smaller chunks just to compare each piece (as annoying as that may be).

**Comment by jeffposnick** [comment]
At this point, it's unlikely that we're going to change `workbox-routing` significantly.

I understand the difference of preferences, and my hope is that folks who would rather go with an alternative approach to routing can do so and just call the `workbox-strategies` classes directly inside of their custom routes. Our response strategies aren't tied to `workbox-routing`. 

If we need to polyfill https://github.com/w3c/ServiceWorker/issues/1373 then I could see this proposal being revisited as a standalone, alternative module to `workbox-routing` rather than changing `workbox-routing`'s interface.
