### ISSUE TITLE
how to cooperate with pre-render paths?

### ISSUE THREAD

**Issue by bornkiller** [GoogleChrome/workbox#781]
**Library Affected**:
*workbox-sw, workbox-routing.*

**Browser & Platform**:
*OSX - Google Chrome Canary*

**Question**
In personal react project, I have several static route, and use `webpack-spa-plugin` to pre-render related paths.

static paths:

+ /search 
+ /review 
+ /gallery

pre-render files:

+ /search/index.html
+ /review/index.html
+ /gallery/index.html

I want to register navigate route, when match static path, use pre-render html file directly, for example: when request `/search`, respond with `/search/index.html`. otherwise, fallback into `/index.html`.

I can't find solution with `swWorkBox.router.registerNavigationRoute`, I register another route:

```javascript
// Register special strategy
const PreRenderPaths = ['/search', '/review', '/gallery'];
const PreRenderRoute = {
  match: ({ url, event }) => {
    return event.request.mode === 'navigate' && PreRenderPaths.includes(url.pathname);
  },
  handler: ({ event }) => {
    const target = event.request.url + '/index.html';

    return fetch(target).catch(() => caches.match(target));
  }
};

swWorkBox.router.registerRoute(PreRenderRoute.match, PreRenderRoute.handler);
swWorkBox.router.registerNavigationRoute('/index.html', {
  blacklist: [ /\/(search|review|gallery)/]
});
```

It works, but I have to implement another complete cache strategy, not a good solution. 

The question: how to solve the problem?

**Comment by jeffposnick** [comment]
I'm assuming that you're using the Workbox Webpack plugin for generating your service worker file? If so, I'd recommend using the `templatedUrls` [configuration option](https://workboxjs.org/reference-docs/latest/module-workbox-build.html#.Configuration):

```js
templatedUrls: {
  '/search': ['path/to/local/search.html'],
  '/review': ['path/to/local/review.html'],
  // etc.
}
```

If `/search`, etc. URLs depend on some additional files other than the underlying HTML (like, if there's some JS or CSS that are inlined as part of your overall build process), then list those dependencies in the array for each URL as well.

This configuration will ensure that the URLs `/search`, etc. get precached when the SW is installed, and that anytime the underlying dependencies change during your build process, they're automatically kept up to date.

You shouldn't have to include those URLs in the navigation route `blacklist` anymore, since they'll exist in the SW cache.

**Comment by bornkiller** [comment]
thanks a lot, it works :grinning::grinning:.  but the blacklist is still required, which is not a problem.
