### ISSUE TITLE
Explore adding closure to Workbox V3

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#786]
@philipwalton you mentioned you'd be interested in this. I'd like to get this in ASAP if you have time just so that as we add more modules we can be closure compliant (hopefully).

If it's not feasible / not worth the effort, that would still be useful to know.

Let me know if you aren't able to explore this.

**Comment by philipwalton** [comment]
I spent some time playing with this today, and I have some issues / questions that I want to discuss before going further.

**Issues:**

Closure compiler needs to know about *everything* in the code's API structure in order to work. At the moment, this is very incompatible with how we're building our bundles (e.g. separating them out into files that assume a global loader), so it's going to be tricky/hacky to get around this.

The usual way closure handles external dependencies is via [externs](https://developers.google.com/closure/compiler/docs/api-tutorial3#externs), so if we want to support this in workbox, we'll have to create extern files for each package covering the entire public API space. This is problematic, though, as then we're testing the accuracy of our extern files rather than the accuracy of our code.

Another solution (just for testing, it won't work for bundling) is to include the list of workbox dependencies in the source we send to closure compiler. In my testing, this works (and I already discovered a few errors), but it's only helpful for error detection since it'll include that code in the produced bundle.

Another issue I've discovered is closure compiler [currently errors](https://github.com/google/closure-compiler-js/issues/77) when trying to output ES2015+ code. This is presumably a temporary thing that'll get fixed soon, but it means at the moment we wouldn't want to use closure compiler to generate our production builds.

**Questions:**

So I guess the question is: what's the ultimate goal with adding closure compiler support?

_Is it to generate our production code?_ If so then we'll have to wait until proper ES2015+ support.

_Is it to make it compatible with internal Google tools?_ Is so, I don't think that'll work unless we maintain our own list of externs, which will be a fair amount of work and will require extra double-checking to make sure our externs exactly match our API.

_Is it just for type-checking our code?_ If so, I think it'll be manageable, and this is how I could see it working:

1. For each package we look up that package's workbox dependencies
2. For each workbox dependency we prepend the dependency's dev build to the packages dev build
3. We run the result of this through closure compiler and fail if there are errors or warnings

Note that we have to use the dev build to get the jsdoc comments, and this depends on us not minifying dev builds (as we resolved to do in the last slack meeting).

/cc @jeffposnick @addyosmani for their thoughts

**Comment by jeffposnick** [comment]
My somewhat uninformed opinion is that given those findings, adopting TypeScript sounds like a better way to accomplish similar goals.

I'm not necessarily saying that we *should* do either, especially not in the V3 timeframe, just that it sounds more pleasant than some of what Phil describes regarding out-of-band dependencies/types.

**Comment by gauntface** [comment]
Thanks for exploring this @philipwalton.

I was largely interested in this to see if we could get it to be friendly to Google tools. Realistically, if we could just generate externs files for closure that would be enough, so perhaps we need someone who wants this enough, to find a way to make and validate this.
