### ISSUE TITLE
V3 Workbox-build

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/workbox#803]
## workbox-build

- [x] Switch to CDN by default
- [x] Include option to not use CDN
- [x] Add function to copy workbox-build files over
- [x] Consider adding a customised Inject Manifest
- [ ] Consider user journeys and how they can  / should use Workbox-build
    - [ ] "I would like to manipulate the generate precache entries before precaching is done"
    - [ ] "I would like to create two sets of precache entries (one for es2015 modules, one for non-es2015 modules)"
    - [ ] "I would like to generate a service worker with just precaching"
    - [ ] "I would like to generate a service worker with runtime routes"
    - [ ] "I would like to create a manifest of entries"
    - [ ] "I would like to get an Array of entries"
- [ ] Write up docs on workbox-build user journeys.
- [x] Return the files and sizes included in the precache list
- [ ] Check APIs for WebPack works
- [x] Re-organize the codebase. Clear what the public interface is vs internal as helpers.
- [x] Create a base class for our shared options that are valid for all cases, and then subclasses for specific use cases where additional options can be used.
- [x] Move option validation (via joi, most likely).
- [x] Move warnings about unused/unsupported options to the class constructors, instead of spreading out validation across the codebase.

**Comment by jeffposnick** [comment]
Just an update: I'm going to start by getting `workbox-build` moved over with more or less the same functionality, to unblock #808. The main work there seems to be to get the tests happy, as this is the first Node module that's being tested in the new infrastructure.

Substantive changes outlined above will follow once that is done.

**Comment by jeffposnick** [comment]
Some additional goals I'm tracking for v3:

- Re-organize the codebase so that it's clear which modules are "entry points" as part of our public interface, and which are used internally as helpers.
- Create a base `class` for our shared options that are valid for all cases, and then subclasses for specific use cases where additional options can be used. Move option validation (via [`joi`](https://www.npmjs.com/package/joi), most likely) and warnings about unused/unsupported options to the `class` constructors, instead of spreading out validation across the codebase.

**Comment by jeffposnick** [comment]
Here's the current state of things, with #833 merged in the `v3` branch, with special emphasis on changes for @goldhand's use case:

- There's a new [`generateSWString()`](https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-build/src/entry-points/generate-sw-string.js) top-level export, which is intended to be the interface that the Webpack plugin would use. (The supported options are [here](https://github.com/GoogleChrome/workbox/blob/v3/packages/workbox-build/src/entry-points/options/generate-sw-no-fs-options.js), in lieu of full JSDocs.)
- The template is now implemented as string exported by a [CJS module](`self.__precacheManifest` ), rather than a file that needs to be read from the filesystem, which should play nicer with Webpack.
- The `importScripts` option should make it easy to include references to external scripts, such as those generated by Webpack, without having to customize the template.
- The code in the template will now read in the precache manifest from `self.__precacheManifest` (in addition to accepting the manifest as a context variable), and that `self.__precacheManifest` value can be set in one of the imported scripts.

### Still Pending
- JSDoc updates.
- E2E tests for `entry-points/generate-sw.js`.
- Refactoring the way our `joi` validation rules are defined to make it possible to have multiple levels of "cascading"/inherited rules.

**Comment by jeffposnick** [comment]
### Still Pending
- Takeaways from Matt in https://github.com/GoogleChrome/workbox/pull/887 about changes to `workbox-sw` methods/interface. 
- JSDocs scrub, especially for the complete set of options.

**Comment by gauntface** [comment]
I think this is generally done. Docs need writing which is covered in the v3 tracking issue.
