### ISSUE TITLE
Service worker missing workbox-sw.prod.v2.0.1.js

### ISSUE THREAD

**Issue by samirotiv** [GoogleChrome/workbox#809]
Welcome! Please use this template for reporting bugs or requesting features. For questions about using Workbox, the best place to ask is Stack Overflow, tagged with `[workbox]`: https://stackoverflow.com/questions/ask?tags=workbox

**Library Affected**:
*workbox-build*

**Browser & Platform**:
*All browsers*

**Issue or Feature Request Description**:
workbox-build fails to include the workbox-sw.prod.v2.0.1.js file in the manifest. Because of this, the service worker fails to work. On loading the page offline, it fails to fetch workbox-sw.prod.v2.0.1.js, and throws dirty errors. 

I manually renamed workbox-sw.prod.v2.0.1.js to workbox.js, generated the service worker so workbox.js was in the manifest, and then renamed the importScript argument to "workbox.js" - this made it work perfectly. This proves that this is the problem, unless I am missing something. 

Also tried the same with workbox-cli, and from the / root url, both not working. Am I missing something?

I just installed the latest version of workbox-cli and ran `workbox generate:sw`. The sw.js file was missing workbox-sw.prod.v2.0.1.js.

**Comment by jeffposnick** [comment]
Hello @samirotiv!

What you describe is expected. If you go through the `workbox generate:sw` flow, you'll end up with a generated `sw.js` file that includes the statement `importScripts('workbox-sw.prod.v2.0.1.js');`, but will not include a reference to `workbox-sw.prod.v2.0.1.js` in the precache manifest.

The reason for this is that JavaScript [included in a service worked via `importScripts`](https://w3c.github.io/ServiceWorker/#importscripts) are automatically cached by the browser, and in most browsers today, will never be checked for updates as long as their URL doesn't change. So it's not necessary to include a reference to `workbox-sw.prod.v2.0.1.js` in the precache manifest. Additionally, it's actually dangerous to rename `workbox-sw.prod.v2.0.1.js` to `workbox.js`, since without the versioning string in the filename, the service worker will never know to update the file included via `importScripts`.

(There's some more information on how `importScripts` work at https://stackoverflow.com/a/45285119/385997 if you're curious.)

So if your service worker is registering but you're not seeing the expected behavior while offline, I think you have a different root cause. Can you provide some more details about "...and throws dirty errors"? What are you seeing logged? Are you testing going offline after navigating to the page once to register the service worker, and then navigating back again?

**Comment by jeffposnick** [comment]
Closing this for now—@samirotiv, if you can still reproduce and have some details to offer about the errors you're seeing, please let us know and we'll reopen.
