### ISSUE TITLE
Web based configuration wizard?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox#822]
A significant portion of the `workbox-cli` codebase supports the "wizard" feature, which examines the local filesystem and asks a few questions, and then generates a configuration file based on those responses.

Before I start porting `workbox-cli` to v3, I wanted to get opinions on whether this wizard functionality should move over as-is, or whether we should explore other options for providing similar functionality.

One of the things that I had in mind in terms of alternatives is a hosted web app that would ask a similar series of questions, as well as asking whether the developer planned on using Webpack, the CLI, or the Node module directly. The last state of this web app could produce a similar configuration to what you previous got from the `workbox-cli` wizard, ready to be either copy-and-pasted or downloaded.

The advantages are that it could serve as a nice onboarding experience for developers regardless of which build environment they're in. It could also serve as an example PWA that uses Workbox under the hood. The disadvantages are that we'd lose some context about the local filesystem (knowing the names of the directories, knowing the file types that are in the source directory, etc.)

**Comment by prateekbh** [comment]
😍 😍 😍 😍  for web based wizard, it'd serve as a perfect thing to onboard people starting to use `workbox`.
Also it might be too much, but may be saving the final settings as a template/json so that it can be shared would be 💯 (e.g. here's the configuration for company X/project Y's service worker generation).

**Comment by jeffposnick** [comment]
Consensus seems to be:
- Carry over the `workbox-cli` wizard as-is for v3.
- The web app idea has value, but not something that would take priority for anyone currently tasked with v3 work.

**Comment by addyosmani** [comment]
The web based builder idea reminded me of http://www.manifoldjs.com/generator, which exposes a UI for generating SW (in addition to manifests). For Workbox, I think there's value in thinking about this problem space and whether there's a particular _type_ of user we think is going to benefit from this (prototypers? beginners?) before we build it. This might make for a good Q4 or Q1 exercise.

**Comment by jadjoubran** [comment]
Hey @jeffposnick 
I recently stumbled upon this issue while building [webdash.xyz](https://webdash.xyz)
Do you think it makes sense for me to build an open source plugin for webdash that's a UI on top of `workbox wizard`?

here's some technical analysis:
* webdash-workbox would have workbox as a dev dependency
* you'll be presented with a `start wizard` button that spawns `npx workbox wizard` in the end-user's project directory
* the choices that you'd typically see in the console, will be displayed in webdash dashboard, as paper-checkbox or paper-radio-button
* this means we don't lose context about the filesystem since the wizard is running in the end-user directory
* after the workbox-config has been initialized, the plugin will serve as `stats` for your generated `service-worker`: for example, latest version of service worker (cache name), version of workbox running, and the ability to re-run the wizard and override the configuration

If you'd like a quick demo of how webdash works, you can checkout [demo.webdash.xyz](https://demo.webdash.xyz) (P.S.: it's slow as it's hosted on a free EC2 machine and it's not on HTTPS due to some complications with cloudflare + EC2)

**Comment by jeffposnick** [comment]
That certainly sounds like it could be useful if you've got the appetite to build it!

I'd say that you wouldn't have to limit yourself to what the current `workbox wizard` behavior is, since that's tailored to the `workbox-cli` use case. If you could infer from the existing project whether they're already using `webpack` or a node-based build script, then producing a configuration that will work for the `workbox-webpack-plugin` or `workbox-build` as a final output could be really useful.

**Comment by jadjoubran** [comment]
Sounds great!
Webdash doesn't have any additional insights out of the box, I feel like if something was missing, it probably makes sense to include it as part of `workbox wizard` for all users to enjoy

I'll take a look soon at the source code for `wizard` and will ping you as soon as I have a working prototype

**Comment by jadjoubran** [comment]
I think these are the approaches that will possibly work:

The main problem is that there's no `api` for workbox-cli's wizard

### 1. Build my own wizard (as you suggested)
However this sounds like I'll be reinventing most of the logic that you already have in `runWizard` and what ever fixes I merge, won't benefit workbox-cli (and vice versa)

### 2. Mock inquirer

```javascript
const runWizard = require('./node_modules/workbox-cli/build/lib/run-wizard');

const mockInquirer = require('mock-inquirer')

mockInquirer([{
  swSrc: './src/',
  globPattern: '*.js',
  //...
}]);

runWizard();
```

with this approach I'll need to pass in all the answers before running runWizard (which seems to be working).
Do you think that's a good idea?
If yes, can I send a PR to add a `main` file for workbox-wizard, in order to `require` it properly?

### 3. Make it possible to use the code behind Workbox wizard as a node API
This will probably take a lot of time (even if I sent PRs) and would probably require waiting for the next major release

I'm personally included towards approach number 2, but would love to have your opinion as well
Thanks!

**Comment by jadjoubran** [comment]
Quick update: I just published v1, and I'd love to get your feedback on it (what needs to be fixed/changed, ideas for the future, etc..), you can open issues on the plugin [repo](https://github.com/jadjoubran/webdash-workbox) if you want
Here are some [screenshots](https://twitter.com/JoubranJad/status/983283199169228800)
I'll record a proper video soon and upload it on webdash.xyz

it can be tested by simply installing webdash & webdash-workbox:

```
npm install webdash webdash-workbox --save-dev
npx webdash
```

Thanks!

**Comment by jeffposnick** [comment]
Great work, @jadjoubran!

(And `webdash` seems like a useful project in general!)

**Comment by jeffposnick** [comment]
With https://github.com/jadjoubran/webdash-workbox out there, I don't think that we need to take this on as part of the formal Workbox project. Thanks again!
