### ISSUE TITLE
Support navigationPreload in WorkboxSW 

### ISSUE THREAD

**Issue by adityapunjani** [GoogleChrome/workbox#835]
**Library Affected**:
workbox-sw

**Browser & Platform**:
Google Chrome v62 and above

**Feature Request Description**:
Navigation preload for service workers is going to be enabled by default in Chrome 62 stable. I think workbox should provide support for enabling it through WorkboxSW class API. Thoughts?

Workbox runtime strategies that should use preloaded responses. 
CacheFirst (if not in cache)
NetworkFirst
NetworkOnly
StaleWhileRevalidate

**Comment by adityapunjani** [comment]
cc @jeffposnick

**Comment by gauntface** [comment]
Note: *Not supported in Firefox at the moment.

**Comment by roastlechon** [comment]
We would like to use this feature as well!

**Comment by roastlechon** [comment]
Related document https://developers.google.com/web/updates/2017/02/navigation-preload

**Comment by jeffposnick** [comment]
I'm thinking a bit about what this interface would look like. Initial thoughts:

## Updates to `workbox-core`

We currently use `workbox-core` to expose all of the shared functionality that's used across multiple modules, including a wrapper on top of `fetch()` that can be used within `workbox-strategies`, and which exposes various [lifecycle callbacks](https://developers.google.com/web/tools/workbox/guides/using-plugins#custom_plugins) for manipulating the requests and responses.

### requestWillFetch() lifecycle callback

This is currently fired prior to calling the native `fetch()`, and gives a plugin the chance to update the `Request` that will be used for that `fetch()`, by, for example, rewriting the URL.

Right now it's defined as

```
requestWillFetch: async ({request}) => {
  const newRequest = ...;
  return newRequest;
}
```

I think we can update that definition so that it looks like:

```
requestWillFetch: async ({request, event}) => {
  // event might be null

  // return either a Request or a Response
}
```

Inside our[`fetchWrapper`](https://github.com/GoogleChrome/workbox/blob/0cd76a883877250c4a645b4e9dcb7104fef09391/packages/workbox-core/_private/fetchWrapper.mjs#L63-L67), if we detect that a `requestWillFetch()` lifecycle callback resolves with a `Response`, rather than a `Request`, we'll immediately short-circuit and return that `Response`, bypassing the `fetch()` entirely.

This has a whiff of "magic" and would require some updates to the docs, but it could be done in a backwards-compatible way that wouldn't necessitate changing the way any of the existing `requestWillFetch()` implementations work—they can continue returning a `Request`.

## New top-level `workbox-navigation-preload` module
This would be exposed via `workbox-sw` as `workbox.navigationPreload.*`, but, like the other parts of Workbox, would also expose a standalone ES2015 module interface.

### Methods

#### Static `isSupported()`

Helper method that amounts to:

```js
function isSupported() {
  return self.registration && self.registration.navigationPreload;
}
```

#### Static `enable(headerValue)`

Would add an `activate` event handler to the current service worker global scope consisting of:

```js
self.addEventListener('activate', (event) => {
  if (self.registration && self.registration.navigationPreload) {
    event.waitUntil(
      self.registration.navigationPreload.enable().then(() => {
        // Defaults to Service-Worker-Navigation-Preload: true if not set.
        if (headerValue) {
          self.registration.navigationPreload.setHeaderValue(headerValue);
        }
      })
    );
  }
});
```

#### `Plugin` class

Would implement the `requestWillFetch` lifecycle callback, and inside of the function, check `event.preloadResponse` to see if that resolves with a `Response` or `undefined`. If it resolves with a `Response`, then return that response. If it resolves with `undefined`, then return the original `Request`.

## Complete usage example

With the changes described above, using navigation preloads with Workbox could end up looking like:

```js
workbox.navigationPreload.enable();

// Swap in networkOnly, cacheFirst, staleWhileRevalidate as needed.
const strategy = workbox.strategies.networkFirst({
  cacheName: 'cached-navigations',
  plugins: [
    // Any other plugins, like workbox.expiration, etc.
    workbox.navigationPreload.Plugin(),
  ],
});

const navigationRoute = new workbox.routing.NavigationRoute(strategy, {
  // Optionally, provide a white/blacklist of RegExps to determine
  // which paths will match this route.
  whitelist: [],
  blacklist: [],
});

workbox.routing.registerRoute(navigationRoute);
```

**Comment by ithinkihaveacat** [comment]
Perhaps change the signature of `requestWillFetch` from `({request, event})` to `({request, preloadResponse})` and just pass it `event.preloadResponse` if available. Giving it the whole `event` object gives it access to things like `event.waitUntil()` which the callback probably shouldn't be messing with.

**Comment by gauntface** [comment]
Is the plugin necessary? It feels a bit verbose / clunky given that it's been "enabled" in a previous method call.

**Comment by jeffposnick** [comment]
Re: @gauntface, I was thinking that it would give folks more of an opt-in method of using the preloaded response—but it's an anti-pattern to enable navigation preload and then *not* use it, so perhaps opting-in isn't the right approach.

If we *didn't* need a plugin, then we could potentially ditch the standalone module entirely, and just expose `workbox.core.enablenavigationPreload()` along with the changes to the `fetchWrapper`, and assume that any time `preloadResponse` is set, our `fetchWrapper` will always use it.

Let me take a look at what the size cost of adding that code in to `workbox-core` would be, vs. shipping it standalone in its own namespace.
