### ISSUE TITLE
WorkboxSW doesn't work unless instantiated on the workbox namespace

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/workbox#940]
The loader mechanism we have in `WorkboxSW` currently loads `workbox-core` when instantiated, and then it loads any other packages on demand when the namespace is requested.

For most packages this works fine, but it fails if the requested package depends on other workbox packages (that aren't `workbox-core`).

For example, the following code fails to load and run `workbox-google-analytics`:

```js
importScripts('path/to/workbox-sw.prod.js');

const workboxSW = new WorkboxSW();
workboxSW.googleAnalytics.initialize();
```

<img width="1440" alt="screen shot 2017-10-22 at 3 37 39 pm" src="https://user-images.githubusercontent.com/326742/31903980-c13c9088-b7de-11e7-92f3-83c988e35752.png">

But this works:

```js
importScripts('path/to/workbox-sw.prod.js');

self.workbox = new WorkboxSW();
workboxSW.googleAnalytics.initialize();
```

<img width="1440" alt="screen shot 2017-10-22 at 3 37 00 pm" src="https://user-images.githubusercontent.com/326742/31903991-c9d6c268-b7de-11e7-8a94-97260755a165.png">

The reason is the generated `workbox-google-analytics` bundle looks like this:

```js
this.workbox = this.workbox || {};
this.workbox.googleAnalytics = (function (
  exports,
  workboxBackgroundSync,
  workboxCore,
  workboxRouting,
  workboxRuntimeCaching) {
  // ...
}(
  {},
  workbox.backgroundSync,
  workbox.core,
  workbox.routing,
  workbox.strategies
));
//# sourceMappingURL=workbox-google-analytics.dev.js.map
```

As you can see towards the bottom, when this code is run it expects `workbox.backgroundSync`, `workbox.routing`, and `workbox.strategies` to already be populated, and unless these namespaces can *also* be loaded on demand (i.e. via a `WorkboxSW` instance on `self.workbox`) it errors.

Since the generated code for these bundles only uses the namespace `workbox.*` and since `importScripts` doesn't return a module (it just runs the code), I don't see any solution other than making `self.workbox` *be* the loader.

**Comment by philipwalton** [comment]
#941 is a possible solution to this issue.

**Comment by gauntface** [comment]
I'm pretty confused at how you landed on all of the above.

The problem is that routing, background-sync and runtime-strategies aren't loaded when you try to use google analytics.

Current solution you can do manually (NOT the final solution I'd like to go with), is to load the modules explicitly:

```javascript
const workboxSW = new WorkboxSW();

workboxSW.loadModule('workbox-routing');
workboxSW.loadModule('workbox-runtime-strategies');
workboxSW.loadModule('workbox-background-sync');

workboxSW.googleAnalytics.initialize();
```

But it may be a good solution to add a dependency tree to make this work.

The solution you've proposed will cause some weird problems as classes will get lost from workbox-core since the flow will be:

1. Construct the WorkboxSW instance
1. Load the workbox core module on the workbox namespace
1. Replace the workbox namespace with the WorkboxSW instance

**Comment by philipwalton** [comment]
Fixed via https://github.com/GoogleChrome/workbox/pull/941.
