### ISSUE TITLE
Errors in lines like: for(const d of   ...

### ISSUE THREAD

**Issue by AleCaste** [GoogleChrome/workbox#955]
Hello, in ```workbox-sw.prod.v2.1.0``` there is a line that says:
```for(const d of c){```
... should be rewritten to...
```for(var d of c){```
... since ```d``` will change within the loop.
Otherwise some browsers like old versions of Firefox will throw the error: ```SyntaxError: missing = in const declaration```

**Comment by gauntface** [comment]
@AleCaste do you know what versions of Firefox will throw this issue? At the moment I think our plan would be current browsers - 2 versions.

**Comment by AleCaste** [comment]
Hi!
I am trying to run the app on Firefox v46.
According to caniuse.com that version supports service workers:
http://caniuse.com/#search=serviceworker
I can understand if those old versions are not targeted anyway.
My question is whether that line is actually correct or not... My common sense tells me ```var``` should be used there instead of ```const``` but I might be wrong.

**Comment by jeffposnick** [comment]
`const` is syntactically valid there. Each time through the `for` block, it will re-initialize a new `const` variable with the value from the iterator. Using `const` instead of `var` ensures that the variable is only written to once, at the beginning of the block.

Here's an example of what I mean: https://jsbin.com/koyayev/2/edit?js,console

I haven't heard other report incompatibilities with that usage in older versions of Firefox, and I don't have access to Firefox 46 at the moment. If you view that JSBin in your copy of Firefox 46, does the first example (using `const i`) give you an error as well?

**Comment by AleCaste** [comment]
Hello!
Ah ok I understand what you mean.
The problem is that some old browsers may not internally work as you describe.
I ran the jsbin example you put in place and indeed I get an error on Firefox v46:

![screenshot000](https://user-images.githubusercontent.com/6316907/32244562-ef2f426a-be46-11e7-948f-e703a04050e9.jpg)

I get a ```SyntaxError: missing = in const declaration``` error as you can see.

**Comment by jeffposnick** [comment]
As @gauntface points out, our current support plan is for the current + 2 previous major revisions of browsers (including Samsung's Chromium-based browser). We're ensuring this in the v3 branch by explicitly transpiling against the required target platforms using `@babel/preset-env`.

Changes to the v2 branch to support functionality that's been working in major revisions of Firefox for some time now is not likely to happen.

If you have a specific requirements to support users that are stuck on Firefox 46, I'd recommend that you explicitly run the `workbow-sw.prod.2.1.0.js` script through https://github.com/babel/babel/tree/master/experimental/babel-preset-env with the desired configuration, and then use that modified version.
